### PR TITLE
[4.1.0][Refactor] Eliminate BackpackUser model

### LINKED ISSUE #2120: [5.0][Refactor] Remove BackpackUser in favour of User
Upon installing Backpack\Base, Backpack publishes our own model for the admin, ```BackpackUser```. This was done in order to:
1) make the installation as smooth as possible (before this we were asking the developer to add traits to their User model);
2) possibly allow the developer to add methods/attributes only to the admin;

It seems to me like (2) is rarely used, so it doesn't justify the added complexity for everybody. 
And (1) can be done in a different way:
- upon installation, look for ```App\User.php``` or ```App\Models\User.php``` - if it exists, use that; if not, ask the developer to punch in his custom user model;
- ask the developer if we can add a few traits to his User model (```CrudTrait``` and a trait that fixes the password reset for admins); if so - add those traits; if not, ask the developer to do it manually;

This breaking change should:
- make it _a little_ more difficult to install Backpack (reply y/n to prompt in most cases);
- make it easier to use packages like PermissionManager (see https://github.com/Laravel-Backpack/PermissionManager/issues/183);

Thoughts anyone?

### PR DESCRIPTION
**Pull request by tabacitu**
Fixes #2120

```App\Models\BackpackUser``` has only one reason to exist - to be able to send the "password reset" notifications with correct links, that point to ```/admin```. That's it.

Instead of having the notifications triggered from the ```BackpackUser``` model, this PR creates a custom ```PasswordBroker``` and ```PasswordBrokerManager```. This allows us to do the send the exact same notification (```Backpack\CRUD\app\Notifications\ResetPasswordNotification```), but instead of triggering it from the model, we trigger it from the ```PasswordBroker```.

This means:
- we can remove ```BackpackUser``` entirely;
- a lot of problems with ```PermissionManager``` are automatically solved, by use ```App\User``` instead;
- we can remove ```app/Models/Traits/InheritsRelationsFromParentModel.php``` since this is the only place it was used;

Todo:
- [x] Documentation
- [x] Upgrade Guide

### CODE REVIEW

**Comment by AurelDragut** [comment]
Hello, any news on that? I updated backpack crud to 4.1.x to get an error which says that the InheritsRelationsFromParentModel trait is missing and it's called in the BackpackUser model.

**Comment by tabacitu** [comment]
Hi @AurelDragut - indeed the BackpackUser model was removed. Along with it that trait. 

Are you sure you’ve done Step 9 in the upgrade guide? https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-9

**Comment by AurelDragut** [comment]
> Hi @AurelDragut - indeed the BackpackUser model was removed. Along with it that trait.
> 
> Are you sure you’ve done Step 9 in the upgrade guide? https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-9

No, I missed that... Good to know!

**Comment by quannetwork** [comment]
Finally, amazing <3

**Pull request merged**
