### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by promatik**
@tabacitu as we discussed, this is and update for the missing packages in need for update.

Note for you, as you've requested;
- Run the `npm run prod` to publish the assets 😅

---
datatables.net-responsive-bs4 introduced a BC, it removed the `[role="row"]` attribute on datatable rows, so I changed the `list.css` file to support that.

This is not a breaking change for us, because those who are having this new assets, will either publish everything once again, publishing `list.css` also, or are installing backpack and creating a new project.

This fixes; https://github.com/Laravel-Backpack/CRUD/issues/3539

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @promatik 

Ok I get it. I just could not reproduce the BC you mentioned. I think they just don't use `[role=row]` as a selector, but my table still uses them with the new files.

image

Anyway, thanks for fixing 😃 

Best,
Pedro

**Comment by promatik** [comment]
@pxpm can you test with a full `npm run prod` on your side?
I've just updated this branch to make sure it has the latest changes from @dependabot.

Because I think this BC is not introduced only by `datatables.net-fixedheader-bs4` but also by `datatables.net-responsive`, previously updated but nor compiled with mix.

You can see here; https://github.com/Laravel-Backpack/CRUD/pull/3589/files
They no longer use `[role=row]`.

**Comment by pxpm** [comment]
Hello @promatik I did not updated all dependencies, just the responsive ones.

When updating all dependencies I don't get `role=row` like you said. 

Everything seems to work after `npm run prod`

Best,
Pedro

**Review by tabacitu — APPROVED** [review]
Tested, works great. Ran `npm run prod` inside this same branch and merging today 🙏🥳

**Pull request merged**
