### PR TITLE
Remove broken functionality - default CSS and JS files for operations

### PR DESCRIPTION
**Pull request by tabacitu**
@pxpm , @promatik , I need your opinion on this. Let me break it down for you, so that all information you need is here.

In Backpack 4.0 we had a few CSS & JS files published automatically:
- `create.css`, `edit.css`, `form.css`, `list.css`, `reorder.css`, `show.css`, `crud.css`
- `create.js`, `edit.js`, `form.js`, `list.js`, `reorder.js`, `show.js`, `crud.js`

These were there because
- some operations indeed needed some extra stuff to be done (some files weren't empty - `form.css` and `list.css`);
- that way devs could easily add CSS or JS to ALL their Create/Update/List Operations ([docs here](https://backpackforlaravel.com/docs/4.1/crud-how-to#customize-css-and-js-for-default-crud-operations)). 

Then in Backpack 4.1 we basically broke that functionality for past project that were using them, by moving all of them from `vendor/backpack/crud/` to `packages/backpack/crud/`. Very few people noticed - there's an issue for it here https://github.com/Laravel-Backpack/CRUD/issues/2923 - so it looks like very few people (if any) were using this feature in 4.0 and upgraded to 4.1.

Then in Backpack 4.2:
- @promatik has **emptied** all those CSS & JS files, for consistency, and moved their contents to the bundle file; see #3933 and https://github.com/DigitallyHappy/BackStrap/pull/99 for details;
- @promatik & I have provided an easy way to add CSS/JS to an operation, from the CrudController/views, by adding two new widgets - `script` and `style` - see PR https://github.com/Laravel-Backpack/CRUD/pull/3912

With those two changes implemented... those files seem like deadweight: 
- very few people are actually using them;
- by default they're all empty now; they'll be loaded onpage for nothing; that's 4-6 HTTP requests for each pageload, which add absolutely no functionality for 99% of all projects;
- they promote a bad practice - editing stuff in the `public/packages` directory; we actually _don't want_ people to do that; because if they never do that, it's always safe to re-publish the Backpack assets; it's _way_ better for custom CSS and JS files should live in a separate directory;
- they add a bit of confusion, because only _default_ operations do that; operations that live outside the main package (for example... Revise) don't offer this functionality (even though a CSS and JS file were there, they were never loaded);

So in this PR **I've decided to remove this functionality altogether, in Backpack 4.2**. I've deleted those CSS & JS files, and the operations no longer load them. Anybody who's using them can reproduce the same functionality (albeit a little more difficult), by either:
- adding a global CSS file in `config/backpack/base.php`, with proper selectors to target only those pages;
- using the new `script` and `style` widgets provided in https://github.com/Laravel-Backpack/CRUD/pull/3912 to add CSS/JS right where they want it (more optimal);

This _kind of_ fixes https://github.com/Laravel-Backpack/CRUD/issues/2923 by... removing the feature altogether 😅

Let me know what you guys think, if you think this is a bad idea.
Cheers!

PS. Added docs for it here - https://github.com/Laravel-Backpack/docs/pull/275

### CODE REVIEW

**Comment by pxpm** [comment]
@tabacitu I totally agree with the reasoning behind removing those files. `public` should contain compiled assets and not editable assets. Also would make "user files" real "user files" and not "backpack provided user files", I think it makes sense.

The provided solutions cover most if not all use cases and the documentation is dead simple. 

I haven't tested this yet, just looked at code and docs, it seems fine, but what about `config('backpack.base.cachebusting_string')` ? Is it still needed ? 

I will have this a go later when I finish working on other stuff. 

Pedro

**Comment by tabacitu** [comment]
@pxpm pfiew 😅 I was worried you wouldn't like it... felt like one of those ideas that can be either _really good_ oooor _really stupid_ 😅 Glad to hear it's the first one. **No need to test this PR**, I'm 100% confident on the implementation, it's an easy one and I've tested it well enough. Just wanted to know your opinion.

**Comment by promatik** [comment]
I totally agree with this 🙌

I just [read the docs](https://github.com/Laravel-Backpack/docs/pull/275/files#) you've added for the Widget, and it's very well explained how to add js/css on all pages or in a specific page, so, I think this is ok ✌

**Comment by tabacitu** [comment]
Wohoo. I've just pushed another minor updates, that replaces the GIF spinner with a SVG spinner, I'm sure you'd appreciate that @promatik 😅 I've done it here because it's moved to the `base` directory, so starting with 4.2 there is not `public/packages/backpack/crud` directory, that's entirely gone 🎉

Merging.

**Comment by promatik** [comment]
I was about to comment on that! 😂

I loved it ❤

**Pull request merged**
