### PR TITLE
Added date and date range pickers to filters

### PR DESCRIPTION
**Pull request by adriancaamano**
I have added datepicker and daterangepicker to my test project.
Two examples:

- Date picker
```
    $this->crud->addFilter([
      'type' => 'date',
      'name' => 'to',
      'label'=> 'Hasta'
    ],
    false,
    function($value) {
      $this->crud->addClause('where', 'created_at', '<', $value);
    });
```

- Date range picker
 ```
   $this->crud->addFilter([
      'type' => 'date_range',
      'name' => 'from_to',
      'label'=> 'Fecha lectura'
    ],
    false,
    function($value) {
      $dates = json_decode($value);
      $this->crud->addClause('where', 'created_at', '>=', $dates->from);
      $this->crud->addClause('where', 'created_at', '<=', $dates->to);
    });
```

### CODE REVIEW

**Comment by automat64** [comment]
Used daterange. Works great, thanx 👍

**Comment by tabacitu** [comment]
Hi @adriancaamano ,

This are great and much-needed, thank you. Finally got around to testing them and they work great! 

I have discovered some untreated use cases though, for both date and date_range filters:
- when a value is present (filter is active) the pickers don't seem to know and prepopulate that value;
- there is no "clear" button for the datepicker, for the user to clear just that one filter;

I'll have to reserve some time to do these things too before merging. Otherwise people will surely complain. If you have already fixed that in the meantime, please push the fixes here too, or share your solutions.

Great work, thank you. 
Cheers!

**Comment by tabacitu** [comment]
Just finished the date picker on this branch - https://github.com/Laravel-Backpack/CRUD/tree/adriancaamano-date-filters

**Comment by tabacitu** [comment]
Update: just finished the daterangepicker issues too, except for this one thing that I spent >2 hours on: I wasn't able to clear the daterangepicker, when clicking the clear button (x). If anyone finds a way, please please tell me, this really got to me :-)

Cheers!

**Pull request merged**
