### PR TITLE
[Bug] Dependencies in repeatable containers

### PR DESCRIPTION
**Pull request by pxpm**
### BEFORE - What was wrong? What was happening before this PR?

As reported in https://github.com/Laravel-Backpack/CRUD/discussions/4097 I forgot to refactor the `backpack_form_input()` thus it would not work with new arrayable repeatable field names. **EDIT: technically I didn't forget, I was just waiting for us to have the `toggable` feature that would incorporate this one ... but since this one is broken atm, better fix it.**

### AFTER - What is happening after this PR?

They work.

### How did you achieve that, in technical terms?

I refactored the function to account for arrayed names `something[0][whatever]`. 
Also there is a pending PR in `pro` repository that is needed to work in conjunction with this one.

### Is it a breaking change or non-breaking change?

non I guess, It was not working previously.

### How can we test the before & after?

use this field in monster:

```php
$this->crud->addField([
            'name' => 'vendors',
            'type' => 'repeatable',
            'subfields' => [
                [
                    'name' => 'something',
                    'type' => 'text',
                ],
                [
                    'name' => 'type',
                    'type' => 'select2',
                    'model' => 'App\Models\Product',
                    'attribute' => 'name',
                ],
                [ // select2_from_ajax: 1-n relationship
                    'label'                => 'Select2_from_ajax'.backpack_pro_badge(), // Table column heading
                    'type'                 => 'select2_from_ajax',
                    'name'                 => 'select2_from_ajax', // the column that contains the ID of that connected entity;
                    'entity'               => 'article', // the method that defines the relationship in your Model
                    'attribute'            => 'title', // foreign key attribute that is shown to user
                    'model'                => "Backpack\NewsCRUD\app\Models\Article", // foreign key model
                    'data_source'          => url('api/article'), // url to controller search function (with /{id} should return model)
                    'placeholder'          => 'Select an article', // placeholder for the select
                    'minimum_input_length' => 2, // minimum characters to type before querying results
                    'tab'                  => 'Selects',
                    'wrapperAttributes'    => ['class' => 'form-group col-md-4'],
                    'include_all_form_fields' => true, //sends the other form fields along with the request so it can be filtered.
    
                    'dependencies'         => ['type'],
                ],
            ]
        ]);
```

Check `backpack_form_input()` before and after in the `api/article` endpoint.

Don't forget about the PR in pro! 👍

### CODE REVIEW

**Comment by tabacitu** [comment]
@pxpm please remember to ALWAYS answer to the person that reported it too, so they know we're working on it. I see #4097 is without an answer.

Please help me understand:
- What happens if someone gets this update, without the PRO PR? 
- What happens if someone gets the PRO PR, without this one?
- What happens if someone is using the old repeatable field inside v5?

**Comment by pxpm** [comment]
Hey @tabacitu 

Sorry, it slipped me, I saw it but I moved my focus to other conversation I had in mind:

image

I recall having some discussion and implementation details of the dependant selects in repeatable with @prodixx and recall him talking about, and basically that was what drived me to fix this. 

- **What happens if someone gets this update, without the PRO PR?**

The input will be correctly parsed but they will not have access to what row and what input triggered the request. (it will not be sent along).

- **What happens if someone gets the PRO PR, without this one??**

The input will not be correctly parsed but will contain the row and the element that triggered it in the request.

- **What happens if someone is using the old repeatable field inside v5??**

If you have the PRO pr we will send the trigger along with request. 

In case of input parsing, nothing happens, this was not working before, PR was closed before merging: https://github.com/Laravel-Backpack/CRUD/pull/3439 so **what worked before works now**, the regular fields not the repeatable ones. 

NOTE:
> I think the first two questions is something that we should not be testing for. We could have matching/working versions enforcing it in composer.json ? Like minimum pro version for crud 5.0.5 is pro 1.0.4 and the other way around to, so if you update one it will force you to update both, because they are needed together ? Or is it too restrictive ? Why wouldn't you want to update to a version that the only change it has it's the same crud had ? If you think 4.1, this would go  as a single change, now it's two separate changes, but for the same thing. 

The third question ... Well, I did it:  
image

I get Backpack is all-in for flexibility, but man ... v4 inside v5 is something I would like to not have to think about. 

Let me know.

**Comment by tabacitu** [comment]
Awesome, thank you 🙏 Unit test please?

**Comment by pxpm** [comment]
added unit tests for `backpack_form_input()` @tabacitu

**Pull request merged**
