### PR TITLE
[4.1.x] date_range filter - allow passing custom options to JS plugin

### PR DESCRIPTION
**Pull request by tabacitu**
Build upon https://github.com/Laravel-Backpack/CRUD/pull/2489

Similar to how the ```date_range``` FIELD type works, it allows the developer to specify ```date_range_options``` on the filter, and those options overwrite the default ones.

### CODE REVIEW

**Comment by tabacitu** [comment]
@pxpm I've just created this as an example.

**Comment by zachweix** [comment]
Thank you so much for adding these features!

**Comment by tabacitu** [comment]
@zachweix glad to help 😄  It might take quite a while to merge this, since it has to be merged inside https://github.com/Laravel-Backpack/CRUD/pull/2253 basically.

But until then, you can safely download the file from this branch, and use it in your project. [Publish the filter](https://backpackforlaravel.com/docs/4.0/crud-how-to#publish-a-column-field-filter-button-to-modify), then copy-paste the modified code here, and it should work like a charm! When we release it, you can just delete that one file, and Backpack will pick up the one from the package.

**Comment by pxpm** [comment]
Hello everyone!

I'v just merged this solution along with some other improvements in #2253 

Let's close this in favor of the other PR. Thanks guys for the time spent on this issue!

Best,
Pedro

**Pull request closed without merging**
