### PR TITLE
Use Js::from() to create proper JavaScript var

### LINKED ISSUE #4278: [Bug] Invalid JSON in the alerts.blade.php
# Bug report

### What I did

```php
try {
    // throw an exception here
}
catch (\Exception $exception) {
    Alert::error($exception->getMessage())->flash();
    return redirect(route('order.edit.view', ['id' => $id]));
}
```

### What I expected to happen

Show an alert message

### What happened

Becuase the error message contained a ```"``` a JS parse error happened.

### What I've already tried to fix it

Replacing the 
```var $alerts_from_php = JSON.parse('@json(\Alert::getMessages())');```

with ``` var $alerts_from_php =   {{Js::from(\Alert::getMessages())}};```

in ```src/resources/views/base/inc/alerts.blade.php``` fixed the issue
### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

Laravel 9

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.0.7 (cli) (built: Jun 16 2021 00:42:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.7, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v9.4.1@29f0aaade82eadd20ef881b4efb88b0dad4e9a5b

### BACKPACK VERSION:
5.0.10@f0c0c45914c39a9083e19f0c5c3d10ef0e142565


```

### PR DESCRIPTION
**Pull request by olipayne**
Fixes #4278

### CODE REVIEW

**Comment by pxpm** [comment]
Hey @olipayne .

Thanks for the PR. 

Do you happen to get to reproduce the error ?

Using the current master branch with the "old" code seems to work fine when using `"" or ''` in the exception:
image

I tried some variants of the following script to try to reproduce, but was unable to. The messages always displayed properly. 

```php
try {
      throw new \Exception("Division by zero. some wird 'hey'");
  }catch(Exception $e) {
      Alert::info($e->getMessage())->flash();
  }
```

I've tested this PR and it works in the same scenarios as the previous code, so dunno what we are really we fixing here. Maybe @mrbig00 can shed some ligth on how we can reproduce the error ? 

Thanks again

**Comment by mrbig00** [comment]
Hi @pxpm ,

try it with ```Alert::error('"')->flash();```, 
the generated js will be: ``` var $alerts_from_php = JSON.parse('{"error":["\u0022"]}'); ``` 

which trows the following console error in chrome: 
```
VM984:1 Uncaught SyntaxError: Unexpected string in JSON at position 12
    at JSON.parse (<anonymous>)
    at HTMLDocument.document.onreadystatechange (edit:1139:41)
```

**Comment by pxpm** [comment]
Hello @mrbig00 ! 

Thank you very much for the example, unfortunatelly I am not able to reproduce it: 

```php
try {
                throw new \Exception("Division by zero. some wird 'hey'");
            }catch(Exception $e) {
                Alert::error('"')->flash();
            }
```

image

I got the alert with no errors. 

Maybe it's some encoding in browser or something ? I am also using chrome v. 100.0.4896.60

This works with or without this branch. Maybe you are using an overrided version of `alerts.blade.php` that have the error ? 
Can you check if you are overriding this file in your `resources/views/vendor/backpack/base/inc/alerts.blade.php` ? If not can you paste here the contents of that file in the vendor folder ? `vendor/backpack/crud/src/resources/views/base/inc/alerts.blade.php` ?

Thanks

**Comment by olipayne** [comment]
Hmm, this is weird! When I submitted the PR this was definitely fixing a bug, but I can't reproduce it anymore.

image

Weird, but I also can no longer

**Comment by pxpm** [comment]
@mrbig00 I agree with you, not only it could be a performance improvement and it's also more readable, but since an error is reported, for me, it's important to understand why we are doing this change, is it to fix an error, or are we refactoring code readability ? 

I tried now in PHP 8.1 as I only had it tested in 8.0, who knows, some internal in PHP could have changed and was making some function we use have a different behaviour. Everything seems to be working fine, so I still don't know if this is a bug fixing or a refactor. 

Can you post me the string output of your `$exception->getMessage()` that triggers the error ? Maybe it's some other character in the string that is breaking it and not the `"` that we are testing ? 

I know we will probably do this change in the end, but for me, it would be important to reproduce the error before fixing it. Thanks for your help @mrbig00 and @olipayne 🙏

**Comment by mrbig00** [comment]
As I said before, adding the following alert triggers the error: ```Alert::error('"')->flash();```, in fact any message that has double quotation mark. I can do a screen cast later if you want

**Comment by pxpm** [comment]
No need for a screen @mrbig00 . Just wondering why you have it and me and @olipayne can't reproduce it.
 We didn't change nothing in code lastly regarding this feature, but if you have it means that in certain circumstances it can happen, anyway I still think this is a nice improvement, and as I said, it worked the same way as the current code. 👍

**Comment by tabacitu** [comment]
I also couldn't reproduce this in v5... with or without this PR, the output is ok for me. 
But hey, since it's the same thing... let's just trust @mrbig00 here, and merge it.

Thanks guys!

**Pull request merged**
