### PR TITLE
[4.0][Improvement][Needs feedback] Optimize reorder for speed (use DB instead of Eloquent)

### PR DESCRIPTION
**Pull request by marconett**
reorder was extremely slow (~15s) with big datasets (~200 entries) because it created a lot of db queries. this brings it down to <100ms with just one db query.

### CODE REVIEW

**Comment by tabacitu** [comment]
Wow - this is great @marconett . Thanks a lot! 

I have only one concern - that it's using the ```DB```  facade, transactions, commit - all of them SQL concepts. Which makes total sense - that's actually the solution (using DB instead of Eloquent, one transaction to rule them all). But will this still be working for developers who use MongoDB or other no-SQL dbs? We've been providing "unofficial" MongoDB support for a while, but I'm not very familiar with MongoDB myself.

@vesper8, @andrycs , @echol - I know you guys are using Backpack+MongoDB. **What do you think, will this make Reorder stop working for your MongoDB projects?**

**Comment by tabacitu** [comment]
Hi @marconett ,

Thanks again for the PR. I checked and double-checked and it looks like your PR still doesn't make all the updates to one query. It:
- bundles them into a transaction, which should be faster;
- reduces the number of queries (by 50% !!) because it doesn't ```find()``` the items before it updates them;

But in my tests, for 140 entries, it still made 142 db queries. Apparently, Laravel can't do mass updates. Not with DB. Not with Eloquent. It runs them one by one.

But still. Half the number of queries is a huge improvement. So I merged your PR to bundle them into a transaction, but kept using Eloquent instead of DB. This reduces the number of queries (by half) and keeps support for other DBMS like SQLite, PosgreSQL, MongoDB. Best of both worlds, I think.

Thanks again for the PR! I've just merged it into ```v4``` - it'll be available as beta next week.

Cheers!

**Comment by marconett** [comment]
Huh. I didn't actually check the number of queries, just assumed that's how the DB facade works.

I'll test your changes later this week. Thanks for the merge.

FYI, don't forget to remove the DB calls `beginTransaction` and `commit` (lines 25 and 38).

**Comment by tabacitu** [comment]
Actually I've ended up keeping ```DB::beginTransaction()``` and ```DB::commit()``` - see the end result here https://github.com/Laravel-Backpack/CRUD/pull/1935/files#diff-b7e88b81e4bd839520d5c7f5f071bd18 . I think it was a good idea for the entire operation to happen within a transaction:
- it's marginally faster (not in number of queries, but in time to execute)
- if anything fails, the entire transaction will be rolled back, so there were no changes to the db

Let me know what you think.
Cheers!

**Comment by marconett** [comment]
I wasn't aware that you can put Eloquent queries into a DB transaction. I though you could only use DB transactions with DB updates. Good to know.

I tested the `updateTreeOrder` function of the current v4-Branch with my code and it works quite well.👍️

**Pull request merged**
