### PR TITLE
Update crud.php

### PR DESCRIPTION
**Pull request by olipayne**
English fixes

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @olipayne 

I'v run this sentence against two different grammar checks and they don't seem to complain. 

From my understanding both of the forms are correct? https://www.grammar-monster.com/lessons/his_her_their_they_singular_plural.htm

Disclaimer: I am not a native english speaker!

Best,
Pedro

**Comment by olipayne** [comment]
Hi @pxpm,

Thanks for the feedback! As a native English speaker, the use of 'his' assumes that the gender of the user is already known. 

Using 'they' is also a much more socially correct gender-neutral singular pronoun, as 'they' has a better chance of being an acceptable pronoun for the reader vs. 'his' or 'her'.

For your reading pleasure: https://www.americandialect.org/2015-word-of-the-year-is-singular-they

If you accept this I'll happily ```grep``` through the rest of the documentation to ensure any other references or his/him are addressed in the same manner with a separate PR for consistency.

Cheers!

**Comment by pxpm** [comment]
Thanks for the deep explanation. 

I can't argue as I lack the required skills, from the discussion we had it seems you are correct. 

If this is the correct wording, we should make sure to apply it whenever we got it wrong (it would probably be in lots of places).

Thanks for raising this issue @olipayne 

Best,
Pedro

**Comment by tabacitu** [comment]
Totally, we want to be as inclusive and inoffensive as possible. Thanks @olipayne - I imagine it's like that in a lot of places, further PRs about this would be super-helpful.

**Pull request merged**
