### PR TITLE
[Feature][3.4][Ready] Stats

### PR DESCRIPTION
**Pull request by tabacitu**
Send a few stats to the backpack website, to track unlicensed usage and general usage stats.

Right now this PR only puts together the stats, it doesn't send them anywhere. Haven't decided if we should send them using Guzzle (in PHP) or using jQuery (in JS).

### CODE REVIEW

**Comment by AbbyJanke** [comment]
I am going to suggest we do it via Guzzle, its unnecessary to add additional data on page load and assuming we do themes it likely would be left out of most.

I also want to make a point of saying i don’t think we should do this every load/app run. In my opinion maybe once an hour or maybe once a day to lower additional page load and transfer data for those who have limited bandwidth etc.

**Comment by tabacitu** [comment]
@AbbyJanke I think so to. Just pushed an update which adds a Guzzle request. If the request fails... nothing happens, the page loads normally.

Once a day would be more than enough. But doing it once every x would mean _storing the fact that it has been done_. And... that leaves room for hacking/manipulation, and it also pollutes that storage (be it cookie/session/db/file). I don't know... would rather avoid storing the fact that the request has been done for today...

Right now I was thinking a request would be sent every ~100 pageloads. That's what the current code does. What do you think?

**Comment by AbbyJanke** [comment]
I guess i can work with that. Also a thought I was thinking about, what if we expand on what is being reported and including any packages that has `backpack` added to the `keywords` section within composer? That could help in the future for when you have a "plugin marketplace" type thing showing like whats popular, and you can see what are popular features people typically add into backpack.

**Comment by tabacitu** [comment]
Uuuu. I love that! Definitely could use that!

**Comment by AbbyJanke** [comment]
@athuli7, when we add themes you can not add the script to a give themes requires sending it every page load.. seems pointless and slower load for the end user..

**Comment by tabacitu** [comment]
@Athuli7 all valid concerns, thank you. 

A little background on @AbbyJanke 's comment you might not be aware of:
- we plan on making ```Backpack\Base``` and all official Backpack packages except CRUD _fully_ open-source, under MIT license; the only "dual-license" package from Backpack will be CRUD;
- we plan on having "themes" for Backpack, so that people could use something else than AdminLTE;
- those themes will be mostly developed by third-parties; some will have jQuery, some may not (full Vue.js / Angular / what-not);
- so we'd have to ask developers to include the jQuery stats request;
- plus, people could easily delete the jQuery call from their blade files;
- it will be very difficult for us to push updates to it - if the blade/js file is published, we can't;

So jQuery isn't the better option, I'm afraid... 

> There is very little that can be done to stop people from using this without paying and all of them involve locking the source in some weird way. Which I don't think is you are after.

Totally agree with that:
- Trust me, I know there's little that can be done :-) I've been yanking my brain for years, trying to find a good technical solution that's also _reasonable_ and _ethical_; I _think_ I found one, but it's very elaborate and it will probably take ~6-12 months to develop; so it'll most likely be a separate product, which Backpack will use after it's stable & proven; long way to go; Backpack should't wait on that "_perfect_" solution, I think;
- We don't plan on locking the source. A lot of features and improvements have been implemented _because_ the source is open, by our wonderful community. Locking the source would make that go away. Horrible :-) Never.


> 1. Till a timeout is hit, it will wait.
> 2. The latency of the API could affect sites.
> 3. What about geographically distant servers?

All valid. But:
- only for 1% of the requests; which we _could_ further drop down to 0.1%, in time;
- we never run the request in console / cron / api; only web views; so APIs, where performance in milliseconds is important, is not affected by this;
- I've added a 0.5 seconds timeout, so that's the biggest negative impact it can have on that one pageload out of 100;
- we will of course work on having the API as fast and globally-available as possible; this would actually be pretty fun to do :-)

Considering the above (not doing it for apis, the timeout capped at 0.5 seconds), I don't think it's _that_ big of a problem. But it _could be_, for some. So I rolled up my sleeves and I think I've got it: we don't _need_ the response. Guzzle waits for the response, hence the slightly increased pageload. But we don't _need it_. We don't plan on stopping people from using Backpack without a license. Sure, we will show the usual annoying bubble notification, which can be easily hacked, but we won't make their app die. We just want to know when they're using it illegally, so we can email them and ask to purchase a license.

**Since we don't _need_ the response, we can make a "_fire and forget_" request.** But that's tricky in PHP. I tried all viable solutions and... we've got a winner :-) It won't work on all machines, since it requires uses ```exec()``` and ```CURL``` (and not all servers will have them), but it will work on MOST. And for the ones that don't, we can fall back on Guzzle.

Now:
- if ```exec()``` and CURL are available, the request is sent using CURL in a separate process; so almost ZERO impact on pageload;
- if not, the usual Guzzle request is sent, with the timeout and mentions above (minimal impact);

screen shot 2018-07-19 at 11 28 52

My tests show this is waaaay faster, so thanks a lot for bringing this up @Athuli7  :-) 
**Now, on most production environments, this stats request will have ZERO impact on pageload.**

What do you think? Anything I've missed?

**Comment by AbbyJanke** [comment]
@tabacitu in regards to making sure things are licensed when paying etc, without not making it open source is something I've been looking into for my project as well and I took a hint from Blesta billing platform (blesta.com) Encrypt only the file that does the licensing check, in my case and so far seems like is the same case for Backpack, the Service Provider. While yes it does hide some of the code, there really isn't much in there. and we could easily document the main functions of what is added into there. I see no reason or even really why the service provider would be overwritten so that seems like a safest place in my opinion.

**Comment by tabacitu** [comment]
Hmmm... agreed, encrypting that trait should be taken into consideration, thank you @AbbyJanke .

**Pull request merged**
