### PR TITLE
[4.0][Improvement] Setup a front-end scripts flow and started pulling the scripts out of the blade templates

### PR DESCRIPTION
**Pull request by SabatinoMasala**
Setup a webpack flow for the scripts associated with the fields and pulled out the scripts from the blade templates.

**Setting the flow up**
run `npm install` (this will install all dependencies. See `package.json`)

**Running webpack in development mode**
run `npm run dev` (this will execute webpack with the `--watch` flag in development mode)

**Running webpack in production mode**
run `npm run prod` (this will execute webpack with in production mode)

Webpack will take the 'frontend_src' folder into consideration when making bundles. The bundle is located at `src/public/crud/bundle.js` and `form_content.blade.php` loads it up.

I tested all the fields I converted and they all behave the same.

There are some TODO's left:
- Load up styles asynchronously (for example in the iconpicker component)
- Make separate bundles instead of just 1 and load everything up as we go

### CODE REVIEW

**Comment by tabacitu** [comment]
Wooow. This is HUGE :-) I'll take a look at it in the next few days, pretty busy with a project. 

Cheers!

**Comment by SabatinoMasala** [comment]
@tabacitu, did you get a chance to check this out?

**Comment by tabacitu** [comment]
Hi @SabatinoMasala ,

Sorry for not replying sooner - it's been a hell of a week here and I'm now trying to catch-up on all the Backpack action.

This looks like an awesome improvement for those who already use Webpack, but I have to be honest to you - I'm really scared to introduce a new technology dependency for everyone. That's why I didn't take a definitive action on my first reply, I wanted to sleep on it a bit. My train of thought is this:
- according to my last and only survey (Sep 2016), **61.2% of all Backpack developers are "_Just starting_", "_Beginner_" or "_Intermmediate_" in building web apps with Laravel**;
- Laravel is not very easy to learn and love, though it might be a lot better now with [Laracasts](https://laracasts.com/), then when I did;
- **Backpack's learning curve for beginners is quite steep** right now, because:
   - the documentation is subpar 
   - we still lack learning material (videos, tutorials)
   - Backpack assumes you already know how to use Laravel;

**I'm afraid that introducing another technology in the project would make for a steeper learning curve, more github issues and a lot more support questions.** And I'm thinking about this in a general way - others have proposed using Angular or Vue.js and my thoughts are the same regarding that - that maybe we can find a way to keep the core as basic as possible, but somehow introduce more technologies for the users that are already familiar with them. Because it really is a shame for all the work you've put in for this PR and for all the improvements that new technologies could bring.

I **think** we can do that using feature branches or forks. Right? If someone really wants a certain technology-fork-backpack (ex: you), I think the best course of action would be:
- create a branch for that technology (or a fork, if the documentation/installation/usage would be different);
- create a team inside the Backpack organisation for that technology and give that user the reigns for that branch (push, pull, everything);

I think that would:
- keep Backpack accessible for the 61.2%;
- keep Backpack outside the emerging technology wars (Webpack vs Browserify, Angular vs Vue, etc);
- allow the ones that prefer a certain technology to still use Backpack AND be able to easily merge updates from the master branch;

It does, however, assume:
- the one that forks from the mother project (let's lovingly call him a _mother forker_) is willing to take on the responsibilities of maintaining an open-source project (which is _a lot_ of work - I found out the hard way);
- others in the Backpack community agree with this solution;

1) What do you think? Good solution to a complicated problem? Would you like to be the first _mother forker_? :-)
2) Do you think a branch or fork would be better? 
3) Do you foresee any issues I've missed with this plan?

@OwenMelbz , @fede91it , @Ghitu , @cristiantone  - what do you guys think?

Cheers!

**Comment by SabatinoMasala** [comment]
Hey @tabacitu,

Thanks for giving this so much thought, I appreciate it!

It is quite the complicated problem, but I feel like adding a dependency like Webpack (or Gulp, ...) will improve the **development** experience for **maintainers** of Backpack, without impeding those who don't understand (or don't care) and just want a package for easily creating an admin panel.

I'd like to point to a major repositories like Bootstrap. The maintainers use a very nice development flow for creating a distribution version which is situated in the **dist/css** and **dist/js** folder (included in the repository).

If you want to use bootstrap, you have the choice, you either:
- Understand & care about the development flow, and use the sass files to compile Bootstrap yourself (using their gulp flow - or even your own)
- Don't understand or don't care about this flow and use the pre-built production files

Out-of-the-box, people who use the Backpack package wouldn't have to worry about Webpack, because the compiled files would be provided for them in the repository. When they want to get their hands dirty & create custom fields for example, only then they have to worry about the dependency.

Splitting the Javascript from the views allows for much greater flexibility. I'm thinking Ajax reloading parts & creating models in modals, which is simply not possible (or at least very hard) at this moment without making a big mess.

That being said, I totally understand your concerns about introducing Webpack, and I'd love to help you out by maintaining parts where I can and adding features (like the Ajax loading / model creation).

My biggest concern however is that the Webpack feature branch and the Master branch would drift apart quite fast, since fields are going to have to be created twice (the 'webpack way' and 'the regular way').

Maybe a fork would be the better solution here.

**Comment by OwenMelbz** [comment]
Just a thought on this, would it not make more sense just to add something like "backpack.js" which includes the fields into the existing laravel elixr workflow, as it seems that some of this is reinventing the wheel? We could put the core fields into it, which would still allow users to write their own inline javascript? And probably not worth converting it to ES2015 to save people who are not experienced with it having extra hassle

**Comment by lloy0076** [comment]
@SabatinoMasala @tabacitu 

1. This will **need** to be updated to be compatible with the version of webpack that Laravel 5.4 uses, if not also Laravel 5;
2. Whilst I'm all for using ES2015 I'm with @OwenMelbz here and wondering if it adds even *more* complexity than needed;
3. I'm not certain whether I want to support an automated JS build system both for Laravel < 5.4 and >= 5.4 (the transition to webpack was, imho, extremely bumpy).

Introducing another "mother fork" will just make **everyone** confused. Plus it will make the product leaders' job a lot more confusing (i.e. the job of @Tabacitu).

And it will make testing an even greater nightmare.

I don't really support forking the project; I do think there may be room to move some of the work out to a JavaScript builder but for parts of the project that are core parts.

**Comment by tabacitu** [comment]
Let's keep this open, Justin :-)

**Comment by tabacitu** [comment]
@SabatinoMasala - there's only one way I can say this - **You were right, I was wrong** 😄 

Thanks again for putting so much time into this - it was very useful. Unfortunately, I did not "see the light" back in 2016 - now I do. The datatables CDNs were down a few weeks ago, and all Backpack admin panels were inaccessible. Which sucked. Regular admins most likely had their assets cached, but I'm sure not everybody did. Yes, CDNs rarely go down, but sometimes they do. So we need local assets. Now I agree.

In your PR you used elixir because that what was available at the time. I've just pushed a PR that uses NPM to install all CRUD assets, and Laravel Mix to copy them to the ```packages``` folder. I've also updated the assets to their latest versions.

Note that Base and CRUD will be merged soon, so there are two PRs for this:
- https://github.com/Laravel-Backpack/Base/pull/402 pulls and publishes the assets using NPM and Laravel Mix;
- https://github.com/Laravel-Backpack/CRUD/pull/1977 changes the paths to the js/css files from CDNs to local files;

Thanks again for taking the time to submit this - I really appreciate it. I admit - sometimes I'm wrong - this was one of those times. 

Let me know if you don't like something in the new implementation.

Cheers!

**Comment by SabatinoMasala** [comment]
Amazing, thanks for the effort! 👌

**Pull request closed without merging**
