### PR TITLE
use onreadystatechange in favor of DOMContentLoad

### PR DESCRIPTION
**Pull request by pxpm**
refs: #3540 

@tabacitu it's working on local, can you please push this to demo so we can test behind cloudflare ?

### CODE REVIEW

**Comment by tabacitu** [comment]
Confirmed and merged! Works like a charm, thanks @pxpm, @promatik and @martijnb92 ! Pfiew - this was an ugly one.

**Comment by tabacitu** [comment]
I'm wondering - would `$(document).ready()` have saved us from all this trouble? Cause it sounds to me like it would have...

**Comment by promatik** [comment]
@tabacitu and @pxpm keep in mind that with this, we no longer can use `document.onreadystatechange` anywhere else 😬

And I'm just wondering, that if developers have use it on their side, on some `admin.js` on userland, this code may get overridden.

Let me know what you think @tabacitu and @pxpm.

**Comment by pxpm** [comment]
I was not aware of that limitation @promatik, would jQuery save us here like @tabacitu pointed out? It might take some time till we completely get rid of it, so in the meanwhile if it's valid and easy fix why not ? 

@tabacitu just FYI I didn't added jQuery there like we are not adding that much as of late, as in the best of the worlds, we would get rid of it in the end. You might be right and that could work.

Just some quick tests, up until jquery 2.x the `readyState` is `interactive` on `ready()`, in jQuery > 3.x it is `complete`, you can test it out here: http://jsfiddle.net/AMByF/1/

Not sure if this makes any difference in the CF perspective of the problem, on the "local" side it should work.

Pedro

**Comment by promatik** [comment]
@pxpm the problem is with assigning to the `document.onreadystatechange` attribute.

That way if any developer do that too, he is going to be replacing our function, and his alerts stop
I searched a bit and it is possible to add the event listener, that solves the problem, a created the PR on demo; https://github.com/Laravel-Backpack/demo/pull/241

If it works on demo, we may do the same here ✌

**Pull request merged**
