### PR TITLE
[Feature/Add-on] Json viewer - A new json viewer column

### PR DESCRIPTION
**Pull request by stephanus-tantiono**
use json viewer by Roman Makudera at json column

### CODE REVIEW

**Comment by ziming** [comment]
Yup tested this on 1 of our production site for many months. It's an improvement over the json column I submitted last time.

**Review by ziming — APPROVED** [review]

**Comment by ziming** [comment]
@tabacitu May want to rename this to json.blade.php (That is, delete the column I contributed last time)

**Comment by pxpm** [comment]
Hello @stephanus-stuff and @ziming.

Thanks for the contribution. 

We will have a look at it when we unfreeze features. 

Cheers

**Comment by tabacitu** [comment]
This sounds great @stephanus-stuff . Thanks for the help! Like @pxpm said we're currently in a feature freeze - the priority is to squash all bugs in 4.1, before we can consider any new features for v4.2 / v12.

I'll take another look at this when that time comes, but my current position is that **I'd rather have the `json_editor` and `json_viewer` fields/columns as add-ons, rather than built-in**. The reason for that being simple - _I really don't want to encourage devs to create admin panels "for devs"_. Backpack was created to easily build admin panels "for normal people". And "normal people" don't know about JSON and can't edit a JSON and still keep it _valid_. 

I think relying on a JSON viewer/editor will probably make the admin panels "_too techy_", and I don't want to make it easy to do that. Sure, in some cases it's perfectly reasonable - if you know your admin is a dev that's perfectly fine - it will give access to the data structure so the possibilities are endless. But in _most cases_ I think that's not the case. I think that's one of the pitfalls that OctoberCMS has fallen into - it was an awesome idea and it's a great project. But you end up building a CMS for devs who can already code - that makes little sense in my opinion. 

I can be convinced otherwise - of course 😄 Please do if you don't agree with me. 

Keep in mind - I use [the `json_editor` field](https://github.com/Laravel-Backpack/CRUD/pull/2406) that @ziming provided too 😆 And I'll probably use this column too - sounds & looks great!

But for the time being, and probably for the future too, I think these two would work AWESOME as an add-on. Maybe even together as an add-on - the `json` field and `json` column. This will:
- prevent from recommending something that could take Backpack in a direction we don't want;
- still allow us to _easily_ use these fields and columns in our projects, if we decide so because we know what we're doing;

What do you think @ziming & @stephanus-stuff , would you like to [create a Backpack add-on](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial) with these two? If so:
- I promise I'll be the no 1 download, I'll use this on backpackforlaravel.com 😄 🥳 
- I'll promote it so more people use it, like on our add-ons page, reddit, blog, etc;

It shouldn't take more than 1h, and it's a good exercise in launching open-source packages I think, because fields/columns like this one will be SUPER-easy to maintain - I think they will rarely (if ever) need updates.

Let me know what you think, if any of you guys wants to build the add-on, happy to help you do it, give feedback, recommend changes, etc. If not, maybe someone else from the community is willing to pick it up - if so please reply.

Cheers!

**Comment by ziming** [comment]
Hmm you already merged my json column many months ago as json.blade.php, this one is just an upgrade of it. So json column is already in backpack.

Both json column and json editor are used in production for our non developer colleagues actually. The reason for using it is because the api calls return too many values for us to format nicely for our colleagues viewing. Hence we got lazy and just nicely display the response json for them. (for json editor, i made it readonly if you are wondering).

When we are free we can see how we can make it an add-on until you need to decide again. Personally I prefer them official so I don't have to maintain them :). But I understand your perspectives too.

**Comment by ziming** [comment]
I think we can close this PR now since it is a 3rd party package now

**Comment by pxpm** [comment]
We have the json column, and the json field that @ziming and other contributed to. https://github.com/ziming/json-field-for-backpack

If we plan to add an column that support editing the json we would do it inside `editable-columns`.

Thank you all for the time spent here.

Cheers

**Comment by tabacitu** [comment]
Actually @pxpm , in the end @stephanus-tantiono was kind enough to create a Backpack addon with this - https://github.com/stephanus-tantiono/json-column-for-backpack 

I discovered two bugs in it, after those are fixed I'd like to promote it and add it to [our addons page](https://backpackforlaravel.com/addons), to have more people use it.

Alternatively, if the column itself doesn't progress, I'm considering bringing the `json` columns and fields into Backpack/PRO (after recompensating @stephanus-tantiono and @ziming , of course). That would solve the maintenance problem (we would do it) and the publicity problem (lots of visibility since it's part of PRO)... Not 100% sure about this, but JSON does seem like a pretty valid use case, one that a lot of developers might use, if they had a built-in way... 🤷‍♂️ What do you think @pxpm / @ziming / @stephanus-tantiono ?

**Comment by ziming** [comment]
Hmm I can't speak fully for stephanus, but if we were to rebuild json column today we would use JsonEditor or CodeMirror with their new readonly mode setting instead of using the css & js snippet from https://www.cssscript.com/minimal-json-data-formatter-jsonviewer/

That will be the more robust solution. I will leave it to @stephanus-tantiono to answer the question if he will update his package to address those bugs. Be it by fixing the existing code snippet or switching to use JsonEditor / CodeMirror in read only mode.

As for my package, I'm fine with it going into backpack in the future. Tho I also like to keep that package public (where i mainly just bump library versions) because I think it is what allow me to continue to use github co-pilot for free (my other packages aren't as popular).  I hope that is fine. But I can add a note on the top saying a more robust version has landed in backpack.

**Comment by pxpm** [comment]
Didn't know about that other package. 

I agree with @ziming that we should probably rely on more robust solutions like `JsonEditor/CodeMirror` that could solve the problem for field/column and allow further developer customization and keep our side of maintenance as low as possible. 

JSON gained alot of traction since it got query support directly on database. I don't use it that much intentionally, but inconsequentially I use repeatables, translatable fields, fakes etc that all work with JSON.

I think Json viewer/editor is a valid use case.

**Comment by tabacitu** [comment]
Hmm... all true. Tricky. Ok this is not urgent. And we have [a feature for it in this poll](https://github.com/Laravel-Backpack/CRUD/discussions/3960#discussioncomment-1704588). So we definitely won't forget. Let's all keep it in the back of our heads, if we find a good solution we can follow up.

Thanks guys. Cheers!

**Pull request closed without merging**
