### PR TITLE
fix shift select bulk actions

### PR DESCRIPTION
**Pull request by pxpm**
### BEFORE - What was wrong? What was happening before this PR?

fixes https://github.com/Laravel-Backpack/CRUD/issues/4117

### Is it a breaking change?
nop

### CODE REVIEW

**Comment by jorgetwgroup** [comment]
Hello @pxpm 

Checking error on main selecting from A -> Z works normal.

screenshot-backpack test-2022 08 03-15_12_47

But selection from Z -> A, look like try to check all rows to do a full circle to go back to A in incremental way.

screenshot-backpack test-2022 08 03-15_13_05

Even i get this error in console.
Screen Shot 2022-08-03 at 15 15 40

Screen Shot 2022-08-03 at 15 14 10

In fix-bulk-actions-shift-selection branch, everything works as expected to both ways.

screenshot-backpack test-2022 08 03-15_17_27

I just have one suggestion about combination of name variable "first" and "end", look more natural "first" and "last" or "start" and "end".

Thats all here.

Cheers.

**Comment by tabacitu** [comment]
@jorgetwgroup if Pedro still has to do someting about this, please:
- assign him again, not me;
- move the issue _back_ one column (to "In progress");

**Comment by pxpm** [comment]
Hey @jorgetwgroup thanks for the review.

I agree with you that we should use "conventional" naming. 
I've just updated the PR with changed variable names.

Thanks

**Comment by jorgetwgroup** [comment]
Hi @pxpm works great and now looks beautiful 😄 

screenshot-backpack test-2022 08 09-08_46_37

@tabacitu look ready to merge.

Cheers.

**Comment by tabacitu** [comment]
Tested, works like a charm. Thanks guys!

**Pull request merged**
