### PR TITLE
Related models should have the main entry locale too

### PR DESCRIPTION
**Pull request by pxpm**
### BEFORE - What was wrong? What was happening before this PR?

If you have for example an `HasMany` relation where some fields of the related model are translatable, it will always display the default locale, ignoring the main entry locale. 

- So you are editing the main entry in french, it will save the related fields in the according language, but when displaying the main entry in french, the related fields are displayed in the default language (english). 

### AFTER - What is happening after this PR?

The related fields are edited in the same language as the main entry.

### How did you achieve that, in technical terms?

setup the locale on model when fetching the related models from database.

### Is it a breaking change?

I don't think so, it was not working at all.

### How can we test the before & after?

Having translatable fields inside a relationship, there is nothing like that setup in demo, if you want I can create something there to test this.

### CODE REVIEW

**Comment by guleswine** [comment]
Come on guys, I'm tired of adding this manually with every update, this with every update😀

**Comment by guleswine** [comment]
@pxpm  just in case, I want to check if they forgot about it😀

**Comment by pxpm** [comment]
@guleswine 🙃 🙃 Sorry sorry! I think what's preventing @tabacitu from merging this is that this should be merged with other PR that introduces the `useFallbackLocale`. 

I will remove it from here, since it's not mandatory for this to work, to make this PR more appealing to @tabacitu merging skills 👍 

Give me a sec I will push the change.

**Comment by tabacitu** [comment]
Ahhh... much cleaner! Thank you @pxpm , love it when it's so easy to understand what's wrong and what's the fix. 

@guleswine we've merged it, it'll be available with a `composer update` starting Monday. Thank you for your patience 🙏 And the nudge 😉

**Pull request merged**
