### PR TITLE
use video on readme

### PR DESCRIPTION
**Pull request by tabacitu**
### BEFORE - What was wrong? What was happening before this PR?

We had a GIF on readme.

### AFTER - What is happening after this PR?

We have an MP4 on readme, with a montage.

### CODE REVIEW

**Comment by tabacitu** [comment]
@Laravel-Backpack/maintainers  what do you think? You can see it in action here - https://github.com/Laravel-Backpack/CRUD/tree/use-video-on-readme

**Comment by karandatwani92** [comment]
@tabacitu,
My first thought is.. sound is too loud. We need to work on sound.
Second! what if? we pull the more meaningful content in the beginning; pull the clip(0:44 -1:21) and place it after 0:15(Everything is easy in backpack). Place the rest clip(0.15-0.43) at the end. I mean, swap these two from each other.

**Comment by pxpm** [comment]
image

**Comment by tabacitu** [comment]
I've decided to do this. The way it is. We can change/improve the video when we launch v6, we'll need to re-do it then anyway. Until then, I'd make only ONE change: 
- [ ] add a frame at the beginning, with the Backpack logo and a play button or something, so that when you go on the page it doesn't look broken like this:

CleanShot 2023-03-23 at 12 38 14@2x

Let's see how long it takes us to add this one frame 🤦‍♂️😔

**Pull request merged**
