### PR TITLE
Add new field: select2 from array

### PR DESCRIPTION
**Pull request by njbarrett**
A fairly simple addition that allows you to use the select2 package with options from an array.

### CODE REVIEW

**Comment by Fiftysven** [comment]
Hi njbarraett,
I tried your select2-from-array code and although i'm relative new to Backpack everything worked fine and easy =)The one point i am struggling with is in my edit view, i want to pre-select all options that for example already have an entry in my database. Sadly i have no clue where i can mark a certain option as selected in your select2_from_array.blade.php. Any help would be appreciated.

**Comment by bahman2216** [comment]
Perfect! I just trying to make something like this.
But, possible to filter select2 output from model?

I use **where** condition in model relation:

`return $this->belongsTo('MyModel')->where('user_id', Auth::user()->id);`

Seems not work.

**Comment by tabacitu** [comment]
Merged, thank you! It will be available in the next point release (3.1.58 - released today) and in 3.2.

Cheers!

**Comment by njbarrett** [comment]
@Fiftysven im pretty sure this already handles that on edit

@bahman2216 this PR was for just doing a select2 input from an array not a model

**Pull request merged**
