### PR TITLE
[Bug fix] Filters not clearing properly when a select2_ajax filter is used

### LINKED ISSUE #2645: [4.0.58] select2_ajax filter breaks "Remove filters" button (again)
# Bug report
Previous issue - https://github.com/Laravel-Backpack/CRUD/issues/2135

### What I did
Same as previous issue. 

### What I expected to happen
The filters should be removed.

### What happened
The filter is removed from the interface, but the list return zero results.

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v6.18.3@4e48acfaba87f08320a2764d36c3b6a4a4112ccf

### BACKPACK VERSION:
4.0.58@03432680d8ed839bcbd99ce57aed61bcf7a1b695

### PR DESCRIPTION
**Pull request by tabacitu**
Fixes #2645 and #2653 as far as I can tell.

Please see my detailed description in https://github.com/Laravel-Backpack/CRUD/issues/2645#issuecomment-685692258

@pxpm could you please give it a look/test/review and tell me if I can merge it from your point of view?

Cheers!

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @tabacitu 

Are you sure you are using the last bp version on that testing site ? 

I was not able to reproduce it: https://recordit.co/8TCDiiyWz6

Or I did something wrong ? 

Best,
Pedro

**Comment by tabacitu** [comment]
Yup, I'm sure. Just ran `git pull origin master` to make sure, still happening. Here's my test on the Monsters CRUD:


Notice that after I clear "Remove filters" the search URL in developer tools still has one GET parameter.

Also notice that in your video, after you click "Remove filters" it says:
Screenshot 2020-09-02 at 09 18 45

So it's still a little filtered - 8 entries are missing. It should be the same problem - one leftover GET parameter.

**Comment by pxpm** [comment]
I get it now.

Testing your solution. brb o/

**Review by pxpm — APPROVED** [review]
From the tests I did it works fine and should not have any implications in any other part of the app.

I would just go with `!==` for the string comparison (so we make sure we are comparing against a string) and keep `!=` in null comparison because `!==` would not pick it as null. 

Screenshot_16

Best,
Pedro

**Comment by tabacitu** [comment]
Ok, done, thanks! Merged, will be released in today's patch update.

**Pull request merged**
