### PR TITLE
[4.0][FIX] Column with KEY attribute not working with 'visibleInShow …

### PR DESCRIPTION
**Pull request by pxpm**
…=> false'

There has been an attempt to fix this in #2178 for that i really thanks @fzhantw for taking time to tackle it.

While reviewing the PR i found it indeed **has the partial solution** but not full completed.

Columns are forced to have a `key` in their definition, either by developer or we add it on column creation:

```
 // make sure the column has a key
        if (! array_key_exists('key', $column_with_details)) {
            $column_with_details['key'] = str_replace('.', '__', $column_with_details['name']);
        }
```
So i think we should not call the functions with column name, but with key.

We want to fix all this bugs quickly so i just picked it up and finished it so it can be merged quickly.

Thanks again @fzhantw for bring this issue in, and for taking time to figure out where error is coming from.

Best,
Pedro

### CODE REVIEW

**Comment by tabacitu** [comment]
Thank you @pxpm - totally agree with the solution. Merged, will be available as 4.0.20 later today.

One note for better collaboration - in the future **please try to give unique names to your branches**. Something like ```fix-show-operation-not-using-key``` or even ```fix-issue-2178``` would have been great for this branch, for example, instead of ```pxpm-patch-1```. They can even be super-long, we don't care, as long as they're relatively unique and it makes it easy to understand what that branch does differently from any other branch. 

I've already merged 5-6 branches called ```pxpm-patch-1``` then deleted them, and the git history will get very confusing, very fast. It's a miracle I haven't merged the wrong thing by mistake. Yet! 😆  By contrast, having feature branches makes everything clear, and promotes a best practice for PRs - one feature has one PR.

Thank you for understanding. I'm sure this'll make it a bit easier for us in the future.

**Comment by pxpm** [comment]
Haaaa i see @tabacitu , so sorry about it. 

It happens when it's just one file change i make the change in web UI of github instead of creating a branch and pull/push to github from local.

I will check if it is possible to name the branch in the web UI, maybe creating the branch and then merge to that branch. I will have it a look.

No matter what my next branches will have names. I promisse :heart_decoration: 

Best,
Pedro

**Comment by tabacitu** [comment]
Ah I see 😄 Thank you!

I personally recommend _against_ using the Web UI for anything other than markdown files, because you can't do a "refresh" on a real admin panel (to test you haven't broken anything). So it's easy to push small errors (like a missing ```,````) that break the entire app. I know I've done so quite a few times 😆 

My workflow:
```zsh
cd vendor/backpack/crud
git checkout master
git checkout -b fix-show-operation-not-using-key
# make changes to that file
git commit -am "fixes #2178 show operation not using key for columns"
git push origin fix-show-operation-not-using-key
```

Then when you refresh the repo's Github page (project page, or issues, or PRs) there should be a bubble suggesting to create a PR from that new branch.

Then again, now writing about it I realise this is nowhere near as convenient as using the WebUI - maybe I just got used to it 😄 I've done it so many times that it only takes me a few seconds. I understand if you want to keep using the Web UI, but please make sure you test the branch on a live app too. Otherwise it's easy for you to miss a typo, then me to miss the typo, then take 24 hours to understand we've broken the build and fix it. Every 24 hours means about 600 broken installs - we'd make a lot of people unhappy 😞 And if it's their first time installing Backpack, we've probably lost them for ever.

**Comment by pxpm** [comment]
I get your point. Valid ofcourse. :+1: 

It happened to me also, now CTRL+A ! Copy whole file. 

I use that workflow for some big PR's, not so used to it as you :1st_place_medal: , but eventually web UI might be something to throw in the past. It is indeed more prone to errors and it's easier to get complacent and didn't test the 'real code' that goes to repo. 
Prevention before correction. It should be used far more in our society :evergreen_tree: 

Thanks for the heads up :+1:

**Pull request merged**
