### PR TITLE
[BUG] upload_multiple does not allow to delete and store files in the same request

### PR DESCRIPTION
**Pull request by dejury**
This PR will fix the issue mentioned in #3510.

### CODE REVIEW

**Comment by pxpm** [comment]
Hello again @dejury 

Thanks for spotting one more. I'v just been testing this out and it completely solves our problem. 

I just have one comment though. I think we can avoid introducing another class here by using:

```javascript
$(this).next("input[type=hidden]:not([name='clear_"+fieldName+"[]'])").remove();
``` 

If you agree with me, would you mind doing that change so I can mark the PR as ready for merge ? If not let me know why, maybe I am missing something here. 

Thanks again @dejury , wish you the best man! 👍

**Comment by dejury** [comment]
@pxpm Here you go, good addition to the initial change!

**Comment by pxpm** [comment]
@dejury once again, but don't gets old, thank you so much :)

I will be moving this to ready to merge, it should be merged and tagged by next Monday. 

Wish you the best,
Pedro

**Review by pxpm — APPROVED** [review]
Fixes an issue where you could not delete and add files at the same time.

**Pull request merged**
