### PR TITLE
Fix for select2 to match other inputs height

### PR DESCRIPTION
**Pull request by promatik**
Fix for https://github.com/Laravel-Backpack/CRUD/issues/2655.

As discussed on https://github.com/Laravel-Backpack/CRUD/issues/2655, I added the rules on `form.css`.
Later on, on 4.2 probably, we should move it to backstrap custom rules.

image

### CODE REVIEW

**Comment by pxpm** [comment]
@promatik it it's as expected.

I'v just one question before moving this to ready to merge. Shouldn't we use `em/rem` instead of `px` ? 

I am far from beeing a CSS expert, but I think using those units instead of px gives us better screen responsive behaviour ? 

Let me know what you think,

Pedro

**Comment by promatik** [comment]
@pxpm I did in `px` because the main `select2` css was also using `px`.

It's a problem that `select2` keeps using `px` on their css 🤷‍♂️

In this case if we do the rules using `rem` there will be a mix of `px` and `rem` rules leading to cases like this;

image

If we override the `px` with our `px`s, we get this;

image

It is wrong but at least no overlapped stuff.

---
So, until `select2` migrates to `em`, we should keep using the same unit as they do.

**Comment by pxpm** [comment]
Thank you for the clarification @promatik !

**Review by pxpm — APPROVED** [review]
as previous fixes, this one would only become available for people that re-publish assets and/or install a new instance.

**Pull request merged**
