### PR TITLE
[4.2.x] Fix CSS / JS assets loaded multiple times

### PR DESCRIPTION
**Pull request by tabacitu**
Fixes a very _very_ old Backpack inconvenience (3.x and 4.x):
- If you load 2-3 fields on the same form, but those fields ALL require a certain CSS/JS file (the same file), that file gets loaded 2/3 times. There are no errors or anything, and if any sort of caching is in place, that CSS/JS file will not actually get downloaded a bunch of times. But still... ugly.
- #2283 

--

This PR fixes that, with a pretty simple solution. I've added a few blade directives that we can use to load CSS/JS files only once. If you call the same thing a second time, it will do nothing.

```php
@loadCssOnce('path/to/css/file')
@loadJsOnce('path/to/js/file')
```

Also, I've added a similar blade directive for loading any block of HTML, so that we can do the same for inline scripts and inline styles. In order for it to you, you just have to give it a unique name:
```php
@loadOnce('some_name_you_give_it')
   <!-- any kind of content here; it won't be loaded a second time if the name above was already loaded once -->
@endLoadOnce
```

-- 

Bonus: The blade helpers above also render this block unnecessary, as far as I know:

```php
@if ($crud->fieldTypeNotLoaded($field))
    @php
        $crud->markFieldTypeAsLoaded($field);
    @endphp
```

It doesn't matter if the field type was already loaded or not. The CSS/JS will only be loaded once. Am I correct @pxpm ? If we end up implementing this, we can remove those blocks? They're not used by InlineCreate / Relationship / anything, right?

--

I've used the blade helpers above inside all fields that use Select2 - because that's where the biggest problem was. And it seems to work great 😄 🎉 🎈 

More tests & feedback needed. **How can this bite us in the ass? Anybody?**

Cheers!

### CODE REVIEW

**Comment by pxpm** [comment]
I think this is the best, cleanest and simplest solution. 

We had discussed it, not with specific blade tags, but the concept of having the loaded assests stored somewhere. 

I am not 100% sure about the removal of marking the field type as loaded. When we get the new crud panel for the related entity, if I am correct the already loaded assets are not present anywhere? They belong to parent crud ? Or this helper is something global or ? 

ping @tabacitu

**Comment by tabacitu** [comment]
This is how _this_ works :
- on pageload we register a global variable, ```$already_loaded_assets = [];```
- calls to ```@loadCssOnce()```, ```@loadJsOnce()```, ```@loadOnce()``` are equivalent to 

```php 
if (!in_array($string, $already_loaded_assets) 
{ 
    // actually echo the link/script
    // add the string to $already_loaded_assets
} else {
    // drop it like it's hot; do nothing; say nothing;
}
```

That way, all subsequent calls for the same file will do nothing, since the file is already stored in ```$already_loaded_assets```. All this logic above is inside ```blade_directives.php``` in this PR. 

So it's basically the same thing as before. We check that it's not already loaded, otherwise we load it. The only thing that changes is the level - instead of checking PER FIELD TYPE, we check PER CSS/JS FILE.

Does InlineCreate try to specifically load only fields that have not already been loaded? Does it explicity use that functionality at all? If so, please point me to those lines I want to take a closer look.

**Comment by pxpm** [comment]
In `fields/relationship/inc/field_attributes.blade.php` we encode the parent loaded fields with: 
```php
data-parent-loaded-fields="{{json_encode(array_unique(array_column($crud->fields(),'type')))}}"
```

Then in `fetch_or_create.blade.php` we pass it in the post request that fetches the modal, so in `inline_create_modal.blade.php` we mark them as already loaded:

```
$loadedFields = json_decode($parentLoadedFields);

    //mark parent crud fields as loaded.
    foreach($loadedFields as $loadedField) {
        $crud->markFieldTypeAsLoaded($loadedField);
    }
```

Maybe it's ok if we pass the loaded assets and mark those assets as loaded the same way we did for field types.

**Comment by tabacitu** [comment]
Yup - sounds like that's the way to go. Instead of passing loaded _fields_, we pass loaded _assets_. So that they don't get loaded again.

**Comment by tabacitu** [comment]
@pxpm it's done 😄 I've made all fields use ```@loadCssOnce```, ```@loadJsOnce``` and ```@loadOnce```. It was surprisingly easy 🥳  Can you please take a stab at making the InlineCreate use this array of files, instead of the array of fields?

PS. In the process I've also discovered a downside of this blade directive idea:
- you can do `@loadCssOnce('path/to/file.css')`
- you can do `@loadCssOnce('http://example.com/file.css')`
- you can do `@loadCssOnce('https://example.com/file.css')`
- but you CAN'T do `@loadCssOnce($string)`, because of the Laravel processing order; 😞 so it might not be a solution for charts too... just for fields...

**Comment by tabacitu** [comment]
On second thought... This might not be the solution we're looking for...


It's great that it has a higher granularity. It fixes the problem where (for ex) jquery-ui is loaded by multiple fields. But it doesn't fix the problem for charts, because you can't pass variables to it...

So maybe a better solution, one that would tick both boxes, would be to use not Blade Directives, but [Blade Components](https://laravel.com/docs/7.x/blade#components). Since they support passing variables too, that would actually be a much better solution. One that we can keep for years. But that's only been introduced in Laravel 7...

So I don't think I'm going to merge this into 4.1. I'll postpone it until 4.2, when we can maybe drop support for Laravel 6, and we can use the better solution with blade components.

I can be convinced otherwise, though. Let me know.

I'm especially interested if someone knows a way to fix this PR, so that the blade directive can also accept a variable - might be possible and I'm not aware. In that case we can merge this in 4.1.x

**Comment by pxpm** [comment]
@tabacitu can't we use function($name, ... $args) ? for any undefined amount of args ?

**Comment by tabacitu** [comment]
We can, but the problem isn't the number of arguments. It's that:

```php
// you do
@php
  $string = '/path/to/file.css';
@endphp

@loadCssOnce($string)

// but what you get inside the blade directive function 
// is NOT '/path/to/file.css'
// but instead it's '$string'
// the actual name of the variable, with $ prefixed
```

**Comment by pxpm** [comment]
I think I nailed it @tabacitu .

Give it a look/try and let me know :)

Any doubts just ask, but I think changes are very intuitive. 

I changed the loaded assets to a crud property because if we pass a `$variable` to the directive we must return php that can manipulate it when it renders on page, and we have `$crud` on page. Also helps `crud` being a singleton on app lifecycle. 

Let me know :)

**Comment by tabacitu** [comment]
Great job @pxpm . I'll a look at it AFTER we launch 4.1. This is not going to make the cut. Otherwise we'll surely be delayed by 1-2 more weeks and I don't want that.

At first glance - it looks like an awesome solution. But this shouldn't be inside the CrudPanel object, it probably needs its own object, like ```Assets``` or something. That way developers can also use the same thing for loading CSS, JS once inside Widgets, or even on their front-end.

Again, this needs a longer discussion and consideration. So let's postpone this until AFTER 4.1 is out.

**Comment by ziming** [comment]
Really looking forward to this merged!

**Comment by pxpm** [comment]
Hey @tabacitu 

I gave this one more shot to make it more appealing for merge.

The refactor include removing the assets from the crud panel and creating an Facade `Assets` that access our `AssetsManager` class .  That way people can use it in front end too to manage their assets.

- Moving everything to blade components might take a while, and if we aim for a 4.2 bugless I don't think we are going to provide it right now, maybe in 5.0 orso. 

- Fixing this would allow us to provide the sortable on `repeatable` that works in mobile too #2711 , sortable in `select_and_order` that works in mobile too: #2716 also order for `select2` inputs working in mobile #2541 

Note: We have a workaround to make it work in mobile by making sure that the field that is going to be ordered is the last in crud, because of `jquery ui` loading order you can check it in #2716 

I also pushed the fix needed for inline operation to pick the new way we deal with assets.

I tested with variables and it works. Like:

```php
$path = 'my/custom/path';
@loadJsOnce($path)
```

ping @tabacitu

**Comment by tabacitu** [comment]
Thanks a lot @pxpm . I'll take a look at it in a few week/months - it's premature to work on this right now since we can only push it in September/October. Let's focus on 4.1 bugs first.

Cheers!

**Comment by iMokhles** [comment]
i was thinking about -rtl.css what do you think i already worked on somthing similar to fix some issue, but it hard to maintain

Capture d’écran 2020-11-05 à 06 26 27

before
Capture d’écran 2020-11-05 à 06 29 37

after
Capture d’écran 2020-11-05 à 06 29 47

before
Capture d’écran 2020-11-05 à 06 30 18

after
Capture d’écran 2020-11-05 à 06 30 25

and of course it's a quick preview i didn't finish much changes but i guess through this project i will make really a huge change to make it fully support RTL will let you guys know when i finish other changes.

**Comment by tabacitu** [comment]
@iMokhles let's open a separate issue for RTL support please, so we can talk about it more. 

I _do_ want Backpack to provide RLT support out of the box if it's not too difficult to maintain. CoreUI supports RTL, so I always thought it's just about changing a class on the `body`, which can be done inside `config/backpack/base.php`. Please correct me if I'm wrong (or explain how it needs to be done) @iMokhles - but let's do that in a separate issue 😄

**Review by promatik — CHANGES_REQUESTED** [review]
- [x] Solve https://github.com/Laravel-Backpack/demo/issues/300, when this one is ready ✌

**Comment by tabacitu** [comment]
See https://github.com/DigitallyHappy/assets/issues/6 - this might be the holy graal!

**Comment by tabacitu** [comment]
Done - it's now `@loadOnce()` all the way - good job with the name Pedro.

FYI, this has very VERY small performance benefits. Here's the before & after on Monsters Edit:
Screenshot 2021-11-25 at 01 00 47
Screenshot 2021-11-25 at 00 59 18

But yeah... it _was_ a small inconvenience... and hey, at least it solves https://github.com/Laravel-Backpack/demo/issues/300

**Pull request merged**
