### PR TITLE
[Feature] Input Youtube/Vimeo Field

### PR DESCRIPTION
**Pull request by OwenMelbz**
**summary**
Enables users to save youtube or vimeo videos to fields with useful basic meta data attached

**preview**
backpack- video field type 2

**usage**

database column type should be either json or text

```php
protected $casts = [‘video’ => ‘array’];

$this->crud->addField([
'label' => ‘YouTube / Vimeo video’,
'type' => 'video',
'name' => ‘video’
]);

$this->crud->setColumnDetails(‘video’, ['type' => 'video']);

```

this will return an object similar to

```javascript
$video = {
    id: 234324,
    title: ‘my video title’,
    image: ‘https://provider.com/image.jpg',
    url: ‘http://provider.com/video',
    provider: ‘youtube’
}
```

### CODE REVIEW

**Comment by tabacitu** [comment]
Awesome! Will check and merge this weekend. Great job!

**Comment by tabacitu** [comment]
Tested, it works for both normal URLs and "share this" URLs, which is great. 

Two mentions though:
1. If a user edits an entry, pastes the code and then clicks "Save" (without clicking outside the video input first) the value won't be stored, because there was no time to get the info and place it in the hidden input. We should try parseVideoLink() on paste/keypress/change/something else to avoid this.
2. I think we should put both the input and the preview on one line. Either using a suffix or just side-by-side. That way it takes up less space.

Cheers!

**Comment by OwenMelbz** [comment]
@tabacitu just pushed the above 2 changes, give them a look when you can :)

**Comment by OwenMelbz** [comment]
@tabacitu have updated incase you want to check it out

**Comment by tabacitu** [comment]
Hi @OwenMelbz ,

I think it looks and works great. It's one-line, we can use it with col-md-4 or col-md-6, looks simple and is intuitive. Great work. Also, tried the column - looks and works great. No comments there. Pushed an update to make them both work with and without attribute casting.

...sorry to come back to you with this. But I got this bug that... well, it keeps bugging me :-) It seems to me like the video name shows up for a split second on screen when hovering the screenshot. Might only be happening on Youtube. I used this link: ```https://www.youtube.com/watch?v=sqiyXwFig-8```
backpack video field small bug


Could you take a look when you have the time, maybe you figure it out?

Cheers!

**Comment by OwenMelbz** [comment]
@tabacitu ha wow that's a funky bug!  Wonder how I missed that lol! I'll have to check it next week as away with family this weekend with only my phone!

**Comment by tabacitu** [comment]
Sure, no rush :-) Enjoy family time. I'll keep replying to your emails and issues though - please ignore them until you're back.

**Comment by OwenMelbz** [comment]
Oh the fun is over already haha! Been back at work last 2 days, so back in full swing, will give this a look over tonight hopefuly

**Comment by OwenMelbz** [comment]
@tabacitu i cant actually replicate this, but are you able to pull the branch and see if its still happening please?

thanks

**Comment by tabacitu** [comment]
Yup, it's now fixed, thank you. Merging!

**Pull request merged**
