### PR TITLE
fix: don't use save_and_new action if can't create

### PR DESCRIPTION
**Pull request by alashow**

### CODE REVIEW

**Comment by alashow** [comment]
@tabacitu what's up with this `working on it` label?

**Comment by b8ne** [comment]
Hey @alashow i think this is covered in [#679](https://github.com/Laravel-Backpack/CRUD/pull/679)

**Comment by alashow** [comment]
Yes, seems like it. I will keep this open, in case that PR doesn't get merged.

**Comment by tabacitu** [comment]
Hi @alashow , @b8ne ,

Thank you. This was a problem indeed. I've just merged PR #679 , which is, I believe, a more comprehensive solution for this problem. It'll be available later today with a ```composer update```, after I bundle it with a few more non-breaking changes.

Cheers!

**Pull request closed without merging**
