### PR TITLE
Added Line Awesome icon font to on icon picker field

### PR DESCRIPTION
**Pull request by promatik**
As @mpixelz stated on #3339, since backpack adopted line awesome font on v4, it should be available to be used on icon picker field.

image

### CODE REVIEW

**Comment by mpixelz** [comment]
I just checked this.. even thought it does show the lineawesome icons on the editor but the stored values are still fa and fas not `la`...

**Comment by pxpm** [comment]
Indeed, they would never be stored as `la` icons because `iconpicker` (the jquery plugin) does not support it. 

Even if you set `iconset` to something weird, it will default to fontawesome.

image

image

Supported by theirs website documentation:

> glyphicon|ionicon|fontawesome4|fontawesome5|weathericon|mapicon|octicon|typicon|elusiveicon|flagicon

**Comment by promatik** [comment]
@pxpm I did some changes, so I replace `fa` > `la` before save, and `la` > `fa` before showing the icon on icon picker.
It's now stored as lineawesome.

This is possible because line awesome provides a font with the same naming as font awesome (`fa`).
It's working, is it a desired feature to make up for the extra layer of logic?

**Comment by tabacitu** [comment]
Ugh bot that's just sad 😞😅

Now that I hear about it, it does make perfect sense to have line awesome inside the icon picker - especially if you use the backpack interface for both users and admins...

Any way we can make it a "_supported font_"?
- a) Doesn't iconpicker provide a way to extend it?
- b) If not, how difficult would it be to create a PR to their project for it? And how likely is it that it's get accepted? Better ask first. It's an opportunity to thanks someone whose work we've been using for a while now.

**Comment by promatik** [comment]
@tabacitu it appears we commented at the same time 😅 just check my previous comment if you missed out.

Yesterday I though about pushing a PR to add this font, but the project seems a little idle, the latest commit was 2 years ago and there are some issues and PR open.

**Review by tabacitu — CHANGES_REQUESTED** [review]

**Comment by tabacitu** [comment]
> Yesterday I though about pushing a PR to add this font, but the project seems a little idle, the latest commit was 2 years ago and there are some issues and PR open.

Hmm that's right. I see you've already contributed the project a few years ago 😀 🎉

Let's do this:
- I've submitted an issue about it to the project - see and follow https://github.com/victor-valencia/bootstrap-iconpicker/issues/97
- We wait for Victor's reply. If he doesn't reply in 1 week, we send a quick email, I see it's listed in his profile - https://github.com/victor-valencia
- If another week has passed and no email reply, we regroup and think about what we should do alone 😀

I'm really hoping we can have a "proper" fix for this, not a hack 🤞

**Comment by promatik** [comment]
@tabacitu I agree it's a messy code and we should avoid it. It was kinda a smart move to try to use the flavor of line awesome with the prefix of font awesome, but I forgot the part of saving it 😅
Let's wait for an answer from Victor.

**Comment by promatik** [comment]
Since @pxpm got a better solution for this problem, let's close this PR and move the conversation to: #3345

**Pull request closed without merging**
