### PR TITLE
[4.X][Feature Request] Add a field type that can input multiple tags.

### PR DESCRIPTION
**Pull request by liquid207**
Like this:

Screen Shot 2020-01-03 at 6 11 23 PM

### CODE REVIEW

**Comment by pxpm** [comment]
Hey @liquid207 

Thanks for your contribution. I added my notes on the PR.

I also like the concept of the field, and I think it could be usefull in some scenarios. I didn't know that js lib, but select2 (a plugin we already using) also has that feature [select2 tagging](https://select2.org/tagging) 

We could:

- Add the feature like an option to current select2_multiple fields `allow_creation => true`
- Create a new field type that allows this specifically. It could be like the relationship field but with this feature enabled (relationship field deals with ajax and non ajax)

How about handling the data, developer must intercept the request to handle it. 

This is kinda of on-the-fly fields. (#2302 ) but for simpler scenarios like tags, it makes more sense than opening a dialog to input the tag title.

Best,
Pedro

**Comment by liquid207** [comment]
Hey @pxpm 

Thanks for your advice.

`select2_multiple` fields require `n-n` relationship, it assumes that the selected item already exists in the database before you select it, not applicable to input.

**Comment by pxpm** [comment]
Hey @liquid207 ,

Theoretically you are right, but technicaly wrong! haha Joking with you :)

The thing with the tagging ability of select2 elements resides in the fact that the tag does **not need** to exist in the database, but like I stated it probably need some kind of manual handling of the input.

I like the concept it's very simple, but as is, I don't see any major application for it unless in some niche scenarios. Maybe I am wrong. 

I tagged and labelled, will let this run for a while and listen to others opinions. 

Anyway, thanks for your work wish you the best,
Pedro

**Comment by liquid207** [comment]
Hey @pxpm,

You are right. This field does not have many usage scenarios.

**Comment by pxpm** [comment]
@liquid207 hello \o

You endup with a solution for this ?

We now have an addons repository, where all these `not so common` features that we are not willing to merge in to core live as addons for people that might need it. 

If you would like to share your solution it might be helpful to others.

Best to you,
Pedro

**Comment by tabacitu** [comment]
I think this would work GREAT as an add-on. Thank you for providing your code @liquid207 & for resurfacing this @pxpm . We have a [tutorial for how to create a Backpack add-on](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial), which should come in handy. What do you think @liquid207 - would you like to create the add-on? I'd love to provide feedback and promote it afterwards.

Cheers!

**Pull request closed without merging**
