### PR TITLE
Add filter option to preserve the filter for all operations (#516)

### PR DESCRIPTION
**Pull request by NBZ4live**
#516

### CODE REVIEW

**Comment by NBZ4live** [comment]
@tabacitu if you don't want it, than decline it, but any kind of feedback would be good.

**Comment by scottgrayson** [comment]
@NBZ4live does this work for ajax table too?

**Comment by tabacitu** [comment]
Hi @NBZ4live ,

Sorry for not giving feedback for so long, it's inadmissible, but unfortunately I've only had enough time to handle "must haves". And this did not seem urgent. We're now past that moment and I'll be able to dedicate more time to "could haves".

I tried your solution a few days after you submitted the PR and couldn't get it working. Now I tried it again, given it more though and time, and I still can't figure out a way to make it work: https://cl.ly/0S3p02401x3O . Couldn't get it to work, neither for regular nor ajax datatables.

Here are my filters:
```php

        $this->crud->addFilter([ // add a "simple" filter called Draft
          'type' => 'simple',
          'name' => 'checkbox',
          'label'=> 'Checked',
          'preserve' => true,
        ],
        false, // the simple filter has no values, just the "Draft" label specified above
        function () { // if the filter is active (the GET parameter "draft" exits)
            $this->crud->addClause('where', 'checkbox', '1');
        });

        $this->crud->addFilter([
            'type' => 'text',
            'name' => 'textarea',
            'label'=> 'Textarea',
            'preserve' => true,
        ],
        null,
        function ($value) {
            $this->crud->addClause('where', 'textarea', 'LIKE', "%$value%");
        });
```

Anything I missed? I'm actually not sure how this is meant to be working, because no GET parameters get passed by the Edit, Create, etc buttons. Right?

---

Can you please explain again what this PR is supposed to do? I'm not sure I understand the need for it. Seems simpler to me to just code the thing in your ```setup()``` method, if it's needed all the time. Why include a filter in it?

Thanks, cheers!

**Comment by NBZ4live** [comment]
To be honest I don't even remember what it was. Imho can be closed now=)

**Pull request closed without merging**
