### PR TITLE
[4.0][Feature][WIP] Using SweetAlert2 instead of system alert/confirm/prompt

### PR DESCRIPTION
**Pull request by OliverZiegler**
Added sweetalert2 to assets and replaced all alert and confirm calls with sweetalert

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @OliverZiegler ,

I think this is very cool, I like sweetalert too. But I don't think switching from one alerting system to the other has a big enough benefit from the user, that it makes sense to create a breaking change for the developers... I really wish you waited on this before you created the PR... Of course, I might be wrong, so let's leave the PR open for others to pitch in with their opinion.

In the meantime - I'm very curious how you made it look and feel, but I'm on vacation, so very can't run an instance. If you manage to make a video/gif to show off how it looks, I promise I'll look and get excited :-)

Cheers!

**Comment by OliverZiegler** [comment]
As I only replaced the default javascript function calls I'm not aware of any breaking changes for developers.
Personally I would not change PNotify alerts as they can be styled, but hate the browser dependent appearance of default javascript popups as the can firmly destroy your overall design.

So this PR **only** replaces calls to the javascript API `confirm` `alert` and (if there were some) `prompt`

When you look at the changes I made you will see these are in the script parts for the `delete-button` in `list.blade` and some fields and filters.
If developers use their own implementation here, I don't think there are any inconveniences (except including an unnecessary script).

**Comment by tabacitu** [comment]
Hmm... ok, I think I understand it better now. I'm on holiday right now, but I'll reconsider this when I get back home. Not closing this PR.

Unpolished thoughts for later:
- I did plan to make sort of a "marketplace" or "snippets" area in [backpackforlaravel.com](http://backpackforlaravel.com) for drag&drop alternatives to the default backpack behaviour. That might be a better place for it.
- A possible alternative to include this in the main app would be to create our own JS API for these notifications, so the syntax would stay the same, no matter what notification system you use. Then, if you want to change it to SweetAlert, you'd only need to include a different JS file. If you want to create your own, you'd only need to create a new JS file for the API, with your own implementation;

**Comment by lloy0076** [comment]
@tabacitu @OliverZiegler 

Being the devil's advocate here, why use Sweet Alerts when PNotify is *already* there?

**Comment by OliverZiegler** [comment]
@lloy0076 I see your concerns but in my opinion PNotify is not the best choice for "interrupting" alerts the user hast to react on. It#s nice for notices and stuff butt if you want to present an alert or confirm the user has to click I prefer SweetAlert2

**Comment by lloy0076** [comment]
@OliverZiegler - fair enough - that said I wonder if it would be worth backpack making something like an alert abstraction that would act as a standard alert mechanism for all of the backpack packages so that when SourAlert™ library (which features an animated grumpy cat informing the user of the alert) is developed it can be just as easily dropped in.

**Comment by OliverZiegler** [comment]
@lloy0076 fully support this idea!

We could specify some kind of API here and I would edit my pull request accordingly (and use SweetAlert2 as a default...)

**Comment by tabacitu** [comment]
@OliverZiegler - can I just say this... _you were right, I was wrong_ :-)

I've wasted hours on researching alternatives, trying to use Pnotify's modules to get the same thing. But in the end, your choice was better. SweetAlert hits the sweet spot - good initial design, good API, good feature set.

I'm sure you'll be glad to find that in v4 I've already included SweetAlert by default :-)

Cheers!

**Comment by kiddtang** [comment]
How about sweetalert2 ?
https://sweetalert2.github.io/

Many found the difficulties to add select dropdown in the sweetalert1 (https://sweetalert.js.org/)
it required you to write in React in order to achieve the functionality

https://stackoverflow.com/questions/43266673/missing-select-options-with-sweet-alert

**Pull request closed without merging**
