### PR TITLE
Fix translatable fields saved as null

### PR DESCRIPTION
**Pull request by hocklai8**
A possible fix to issue #1633

### CODE REVIEW

**Comment by OliverZiegler** [comment]
as written in #1633 I'm currently not sure if this really is an issue or just some misconfiguration of @hocklai8 
I also remember having issues with adding `translatables` to the `shouldEncodeFakes` method... 🤔

**Comment by DiyanDesigns** [comment]
Any news on this one? I had the same issue and applying the changes fixed it...

**Comment by tabacitu** [comment]
@DiyanDesigns thank you for resurfacing this. I’ve just [replied in detail here](https://github.com/Laravel-Backpack/CRUD/issues/1633#issuecomment-440286291) - please check it out and let me know if this fixes it for you too.

Cheers!

**Comment by hocklai8** [comment]
@tabacitu Awesome. This fixed the issue too. Thanks. Will close this PR.

**Comment by tabacitu** [comment]
Thanks so much for confirming this so fast, @hocklai8 and @DiyanDesigns . 

@DiyanDesigns actually you didn't miss the big notice - I did :-) I did NOT write that clear enough, my bad. I hope it's clear enough now.

Thanks again. Cheers!

**Pull request closed without merging**
