### PR TITLE
allow user to configure 'drops' attribute

### LINKED ISSUE #3776: [Bug] date_range floats below bottom of page, even when there is lots of space above
# Bug report

### What I did
Opened a ```date_range``` field a the bottom of a page

### What I expected to happen

```date_range``` field to popup on the most user-friendly side (above)

### What happened

```date_range``` field doesn't popup on the most user-friendly side (below)

### What I've already tried to fix it

Sending PR

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PR DESCRIPTION
**Pull request by olipayne**
Better version of #3777, that one is closed in favour of this one. Fixes #3776

### CODE REVIEW

**Comment by olipayne** [comment]
This PR no longer introduces a breaking change, it keeps the default of ```down``` but allows the user to overwrite the value, if they so wish.

**Comment by olipayne** [comment]
So I've just been playing with this. It turns out that it's not strictly needed since the ```array_replace_recursive``` just throws everything in, even if it's not predefined. Nice for verbosity but actually no added benefit, unless Bootstrap Datetime Picker change their default ```drops``` value and we want it to stay consistent for Backpack users

**Comment by pxpm** [comment]
@olipayne Thank you so much for the time spent here.

At the end of the day my understanding is that this PR is not needed, unless in the specific case you said that BDP changes their default and we want it to continue to use `drops => down`. 

I would rather merge https://github.com/Laravel-Backpack/docs/pull/257 since it has all the information needed about this drop stuff!

Let me know if you still think we should merge this PR, otherwise fell free to close it, I will be approving the documentation one. 

Wish you the best,
Pedro

**Comment by olipayne** [comment]
Will close, even though this PR wasn't merged, it was a good chance to get to know BackPack on a deeper level :)

**Pull request closed without merging**
