### PR TITLE
Fix select multiple allows null consistency

### PR DESCRIPTION
**Pull request by promatik**
This is PR to fix the consistency of `allows_null` validation on fields.
It's related with https://github.com/Laravel-Backpack/CRUD/pull/3334, it was a breaking change on 4.1.

### CODE REVIEW

**Comment by pxpm** [comment]
@promatik just to make sure, the only difference between this and #3334 is in `select_multiple` where we couldn't make it in 4.1 without breaking change right ?

**Comment by promatik** [comment]
@pxpm yes, this only fixes the consistency on `select_multiple` field 👌

**Review by pxpm — APPROVED** [review]
@tabacitu this is now even with master, but should not be merged in 4.1.

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/4026 , closing in favour of that one.

**Pull request closed without merging**
