### PR TITLE
Add Conditionable trait to support ->when() and ->unless()

### PR DESCRIPTION
**Pull request by ziming**
### BEFORE - What was wrong? What was happening before this PR?

Nothing

### AFTER - What is happening after this PR?

The Conditionable trait from laravel 8 is added. (Backpack minimum laravel 8 version is higher than when this is added into laravel so it is very safe)

https://www.amitmerchant.com/conditionally-executing-callbacks-conditionable-trait-laravel-8x/

I think this will greatly improve the fluent flexibility and reduce if () clauses as you can chain methods on a conditional basis in a fluent way.

### How did you achieve that, in technical terms?

Add the Conditionable trait

### Is it a breaking change?

No

### How can we test the before & after?

Try chaining ->when() or ->unless() method and inside it call other fluent methods conditionally

Feel free to edit this PR and add the Conditionable trait to other classes too (filters, columns.etc), I can add it too if you all want but tell me which classes

I think this is a small change that is a big improvement to developer DX

### CODE REVIEW

**Comment by ziming** [comment]
The macroable trait can be considered in another PR as well if it isn't done yet.

**Comment by tabacitu** [comment]
> Laravel's Macroable trait can be considered in another PR as well if it isn't done yet.

✅ Already done 😉

**Comment by maurohmartinez** [comment]
This is a great feature!

@tabacitu I propose to add it to:

- `CrudColumn`
- `CrudField` already done on this PR
- `CrudFilter`
- `CrudPanel` to do things like `$this->crud->when($condition, function (CrudPanel $crud) {...}`. I think it's useful since very often we set values for settings conditionally.

Sample of a crud field to use in docs:

```php
// If $condition is met, let's add a field
$this->crud->when($condition, function (CrudPanel $crud) {
    $crud->field('email')
        ->label('Email Address')
        ->type('email')
        // Unless $anotherCondition is met, let's add a hint!
        ->unless($anotherCondition, function (CrudField $field) {
            $field->hint('My hint')
            // When the operation is create, let's move the field after name
            ->when($this->crud->getOperation() === 'create', function (CrudField $field) {
                $field->after('name');
            });
        })
        // Finally, if the operation is update, let's put this field into a tab!
        ->when($this->crud->getOperation() === 'update', function (CrudField $field) {
            $field->tab('My tab');
        });
});
```

How about documenting this here?


Screenshot 2023-04-19 at 10 17 32

**Comment by maurohmartinez** [comment]
Moving this [here](https://github.com/Laravel-Backpack/CRUD/pull/5035) to continue it. Great idea @ziming... thanks!

**Pull request closed without merging**
