### PR TITLE
Refactor page or link field

### PR DESCRIPTION
**Pull request by promatik**
This started as a fix for #3412.
End up refactoring everything since it was harder to get to the desired results with the old code.

Along the way, removed jQuery dependency 🙌

### CODE REVIEW

**Comment by tabacitu** [comment]
I'm considering moving this field to the `MenuCRUD` repo, in Backpack 4.2. Does it really make sense for it to be in the core? Does anybody use it anywhere else?

What do you think @promatik & @pxpm ?

**Comment by pxpm** [comment]
@tabacitu I would 100% agree with that. This field is so tied to the functionality it provides I don't think anybody is using it outside of this specific scenario. I never used, and don't know anyone that did 🙃

**Comment by promatik** [comment]
@tabacitu shouldn't it be on PageManager instead of MenuCrud?
https://github.com/Laravel-Backpack/PageManager/tree/master/src/resources/views/vendor/backpack/crud/fields

I also agree, this field dependes on PageManager 🤷‍♂️

Anyway, besides allowing the selection of a page, it also allows the input of a URL, if a dev doesn't install PageManager he should be able to easly add a URL field, we don't have right now right?
Should we create a field for that?

**Comment by tabacitu** [comment]
Oups - right, in PageManager, not MenuManager. I see we already have an issue for that here - https://github.com/Laravel-Backpack/ideas/issues/21 so we're good.

**Comment by tabacitu** [comment]
I've decided to consider this a MUST, since the refactoring is all done and this field seems like deadweight. 

To get this to a close, let's please:
- [ ] @promatik - merge 4.2 into this branch;
- [ ] @promatik - thoroughly test that everything is working fine; 
- [ ] @promatik - create a PR to PageManager that
    - [ ] adds this field there
    - [ ] modifies PageManagerServiceProvider to provide the views; it would have been a wonderful opportunity to have PageManager also use AutomaticServiceProvider but... I'm afraid that will bring more breaking changes so let's postpone doing that until v5/v12 whatever we call it; let's be as surgical as possible here, small changes only;
    - [ ] uses the view from the PageManager, by specifying the correct namespace;
- [ ] @promatik - create a PR to MenuCRUD to use the field from PageManager instead of assuming it's in Backpack;
- [ ] @promatik - refactor this PR to CRUD to remove the field entirely, instead of rewriting it;
- [ ] @tabacitu - tag new major versions of PageManager and MenuCRUD that support Backpack 4.2 only;
- [ ] @tabacitu - add docs to the 4.2 upgrade guide, for people to change the versions of those packages too, and use the field from the namespace if they're used it anywhere else;

PS. Off-topic but cool - after PR #3905 is merged into 4.2, I think this field will also work inside `repeatable`. Which is... you know... unnecessary, but cool 😀

**Comment by promatik** [comment]
@tabacitu this one is ready ✌
PR on PageManager; https://github.com/Laravel-Backpack/PageManager/pull/120
PR on MenuCRUD; https://github.com/Laravel-Backpack/MenuCRUD/pull/67

I tested the field using it with common db columns, and using fake columns, everything worked as expected 👌

**Pull request merged**
