### PR TITLE
only add a hidden "id" field when such field does not exist

### PR DESCRIPTION
**Pull request by isaackwan**

### CODE REVIEW

**Comment by tabacitu** [comment]
Hmm... I'm curious where this triggered an error/issue for you.

The reason I'm asking is - since this is inside the ```getUpdateFields()``` method, there should _always_ be a hidden ID field. Otherwise the update wouldn't work. Right?

Thank you, cheers!

**Comment by isaackwan** [comment]
Hey Cristian,

I wanted to display the primary key in the edit view and with the original
code, even if I've manually added a field for the ID field, the
configuration is overrided by this code.

But what you have brought up is very right. The field must be kept intact
or otherwise the update won't work. Is there any idiomatic way to achieve
what I wanted to do?

Thanks in advance, and have a happy new year!

**Comment by OwenMelbz** [comment]
You could get the entries if a bunch of ways, probably simplest to do something like

Create a custom field that displays it - the field will have access to both the entity and the URL so you could extract the ID. Make sure you set the "name" param to something like "id_fake"

**Comment by tabacitu** [comment]
Hmm... I think you're right, @isaackwan , your addition makes a lot of sense to me now. And it's a non-breaking change, so I'll go ahead and merge it. Will be released today. Cheers!

**Pull request merged**
