### PR TITLE
Field view upload.blade.php : Fix "Next ErrorException: Undefined index: disk"

### PR DESCRIPTION
**Pull request by reeslo**

### CODE REVIEW

**Comment by israelias94** [comment]
somebody fix the bug?

**Comment by OwenMelbz** [comment]
What exception are you seeing?

**Comment by tabacitu** [comment]
Hi @reeslo ,

Thanks for PR. Just got around to merging it, thanks. It'll be available in the next point update (today).

Cheers!

**Comment by reeslo** [comment]
Nice !

**Pull request merged**
