### PR TITLE
[Feature] allow configure date_range popup open direction

### LINKED ISSUE #3776: [Bug] date_range floats below bottom of page, even when there is lots of space above
# Bug report

### What I did
Opened a ```date_range``` field a the bottom of a page

### What I expected to happen

```date_range``` field to popup on the most user-friendly side (above)

### What happened

```date_range``` field doesn't popup on the most user-friendly side (below)

### What I've already tried to fix it

Sending PR

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PR DESCRIPTION
**Pull request by olipayne**
Fixes #3776

### CODE REVIEW

**Review by pxpm — COMMENTED** [review]
I totally agree with this change, but not sure if this should be considered a breaking change since before it ALWAYS opened the popup below the picker as it is the default option for this datepicker plugin and people might be relying on that. 

image

I don't expect it to be breaking change, but in doubt @tabacitu @promatik what you guys think ?

**Comment by olipayne** [comment]
If that's a problem, I can submit a new PR to still default to ```down```, but passing the configuration on to the field config?

**Comment by pxpm** [comment]
@olipayne that would be the best of both worlds I think. So you can have one picker up and the other down if desired. 

Thanks for the contribution :)

Best,
Pedro

**Comment by tabacitu** [comment]
Hey guys - sounds good, I totally agree to making `auto` the default. I have no idea why that isn't the default in the JS plugin itself, sounds like a no-brainer. But I may have an issue with the implementation. Please let me know if I understand this correctly.

**Wouldn't this be better done in the PHP part, so that it's overridable?** 

To rephrase:
- if we merge this PR as-is, where we do `$configuration.drops = 'auto';` in JavaScript, even if the developer specifies in his `addField()` statement the `date_range_options`, and inside them `drops` would be `up`, it'll still be `auto` because it's basically ignored by the javascript;
- if we define the `drops` option in the PHP at the top of the file, where the rest of the defaults are, the developer would be able to override this however he pleases;
```diff
    // make sure the datepicker configuration has at least these defaults
    $field['date_range_options'] = array_replace_recursive([
        'autoApply' => true,
        'startDate' => $start_default,
        'endDate' => $end_default,
+       'drops' => 'auto',
        'locale' => [
            'firstDay' => 0,
            'format' => config('backpack.base.default_date_format'),
            'applyLabel'=> trans('backpack::crud.apply'),
            'cancelLabel'=> trans('backpack::crud.cancel'),
        ],
    ], $field['date_range_options'] ?? []);
```

What do you guys think? Better in PHP or JS?

Cheers!

**Comment by pxpm** [comment]
100% PHP, I think that's what @olipayne mean when he said `passing the configuration on the field config`!

@olipayne if you don't have time to do it, just let me know and I do it 👍 

Best,
Pedro

**Comment by olipayne** [comment]
Sorry if I wasn't clear, yes I'll be doing it exactly as you guys have described, happy to throw a PR your way later this week.

**Comment by tabacitu** [comment]
Excellent. Thank you @olipayne , much appreciated 🙏 Right now we're putting the finishing touches on a shiny new thing, so if you don't get to it... we'll probably get it done in the next bug fixing cycle in Backpack (a few weeks).

Cheers!

**Comment by olipayne** [comment]
opening a new one with everything in one

**Pull request closed without merging**
