### PR TITLE
[WIP] CRUD 3.3 Upgrade

### PR DESCRIPTION
**Pull request by tabacitu**
Includes all breaking changes for the 3.3 upgrade:

- fields with no tabs specified now show up on top;
- unit tests use PHPUnit 6;
- fixed all ajaxTable issues;
- all tables are now ajaxTables;

### CODE REVIEW

**Comment by tabacitu** [comment]
@tumf87 do you have any idea why the tests are failing now? Looks to me like the test DB configuration no longer works on this environment - but there have been zero changes there...

On local I get this:
screen shot 2017-11-01 at 12 30 42


[On travis we get this](https://travis-ci.org/Laravel-Backpack/CRUD/jobs/295646459):
screen shot 2017-11-01 at 12 30 18

**Comment by tumf87** [comment]
@tabacitu, hmm, I'll look into it

**Comment by tabacitu** [comment]
Guys, I’ve just finished writing the upgrade guide from CRUD 3.2 to 3.3 - [here it is, invisible to the public right now](https://laravel-backpack.readme.io/v3.0/docs/upgrading-crud-32-to-33).

If you guys use it, please let me know if you have any suggestions or encounter any issues. I’ll be upgrading a few more projects myself today, to make sure people don’t flood Gitter and Github with issues while upgrading. Then launch this bad boy :-)

Thanks, cheers!

**Comment by tumf87** [comment]
@tabacitu, I've looked into the failing tests and yeah, some of the changes got lost in the plethora of merges. That plus some of the merges brought in new features that changed the structure of the CRUD fields & columns.

I'm gonna get busy and fix them. Let you know when they're done.

**Comment by tumf87** [comment]
@tabacitu, I've noticed two of the added column attributes don't follow the same casing style: ``table_column` and `searchLogic`. Since this branch already contains breaking changes, can we change it to one or the other?

**Comment by tabacitu** [comment]
@tumf87 - damn, you're right, thank you for noticing. Since another field attribute is ```wrapperAttributes``` and we'll most certainly convert the field into an object at the next update, I say let's go with ```tableColumn```. Already pushed the change, thank you!

**Comment by allam2002** [comment]
@tabacitu, I have tried to upgrade to CRUD 3.3 and i followed the instructions in this Link  [here it is, invisible to the public right now](https://laravel-backpack.readme.io/v3.0/docs/upgrading-crud-32-to-33).
but i got an error :
Problem 1
    - The requested package backpack/base ^0.8.0 could not be found.
  Problem 2
    - The requested package backpack/crud ^3.3.0 could not be found.
  Problem 3
    - backpack/logmanager 2.3.9 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.8 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.7 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.6 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.5 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.3 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.2 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.16 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.15 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.14 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.13 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.12 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.11 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.10 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.1 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.0 requires backpack/base 0.* -> no matching package found.
    - backpack/logmanager 2.3.16 requires backpack/base 0.* -> no matching package found.
    - Installation request for backpack/logmanager ^2.3 -> satisfiable by backpack/logmanager[2.3.0, 2.3.1, 2.3.10, 2.3.11, 2.3.12, 2.3.13, 2.3.14, 2.3.15, 2.3.16, 2.3.2, 2.3.3, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by tabacitu** [comment]
BOOM! Merged and launched. Finally! Thank you guys for your contribution, I know this doesn't _look_ like it but this upgrade has major improvements.

@allam2002 you probably tried to upgrade exactly when we were launching Base and CRUD upgrades :-) Since CRUD 3.3 is now officially launched, please use the upgrade guide here, you should have zero issues: https://laravel-backpack.readme.io/v3.0/docs/upgrading-crud-32-to-33

Cheers!

**Comment by tumf87** [comment]
awesome work from everyone! gonna try this asap.

**Comment by allam2002** [comment]
when i tried to upgrade Again i got that error :
 [ReflectionException]
  Class Backpack\Base\Backpack\Base\app\Console\Commands\Install does not exi
  st


Script php artisan optimize handling the post-update-cmd event returned with an error

**Comment by AurelDragut** [comment]
@allam2002, modify the path to install command in \vendor\backpack\base\src\BaseServiceProvider.php

i did this:
``` 
use Backpack\Base\app\Console\Commands\Install;

class BaseServiceProvider extends ServiceProvider
{
    protected $commands = [
        Install::class,
    ];
```

**Comment by alashow** [comment]
Me trying to update my custom filters, crud core custom branch, L5.5:
all fine

**Comment by tabacitu** [comment]
@alashow , @allam2002 - damn, haven't seen your comments until now. Next time something goes this wrong please open new Github issues or email me so I can "_put out the fire_" :-)

As @AurelDragut said, it's since been fixes, so a ```composer update``` should fix it for you guys.

Thanks, cheers!

**Comment by alashow** [comment]
@tabacitu Actually, It was easier than I thought!

Great work, thanks!

**Pull request merged**
