### PR TITLE
[4.x] fixing table headers when not using responsive table

### PR DESCRIPTION
**Pull request by pxpm**
It's an attempt to fix column headers when responsive table is disabled. 

refs: #3138

### CODE REVIEW

**Comment by tabacitu** [comment]
Hmm @pxpm have you tested this with 
- [ ] bulk buttons
- [ ] details_row
- [ ] both bulk_buttons and details_row
- [ ] neither bulk_buttons nor details_row 

I believe that blank first column is crucial for one of the use cases above.

**Review by alfonsocuccaro — APPROVED** [review]
It fixes the issue fine.
The only little thing I notice is that the checkbox for bulk operations is not centered in the column, but I don't think it is a big deal

image

**Comment by alfonsocuccaro** [comment]
Sorry I haven't noticed that columns are still not well aligned.

See the image

It fixes the issue fine.
The only little thing I notice is that the checkbox for bulk operations is not centered in the column, but I don't think it is a big deal

image

**Comment by pxpm** [comment]
closing this in favor of: #3331

**Pull request closed without merging**
