### PR TITLE
[4.1][BugFix] Fix lang attribute parsing on fetch relationship fields.

### PR DESCRIPTION
**Pull request by pxpm**
refs: #2873

### CODE REVIEW

**Comment by promatik** [comment]
Tested;
image

Using FR translation when available, and EN as a fallback.

When there is no translation, this text appears;
image

Should this be translated? This will ideally never happen, because a field should never have no translations, anyway, what do you think?

**Comment by pxpm** [comment]
Hum, sure we should translate that in crud files. But yeah, that's just here because you have two options, show something, or don't show nothing at all. 

Do you agree that we should show something when there is nothing to show ? Should I add the translation string for this text even if the expectation is to never be used, unless something very strange is happening 👍 

Apart from that, the function is working as expected ? 

Thanks for the feedback @promatik

**Comment by promatik** [comment]
@pxpm yes, it worked as expected 👌 and I think it should show something instead of being empty.

Maybe it should appear with some kind of formatting _`(no translation available)`_, to distinguish from normal results, maybe between parentheses or asterisks. Maybe _`(empty)`_ is enough since it's really empty (no other translation is filled otherwise it would fallback to it), what do you think?

**Comment by promatik** [comment]
@pxpm pinging you to check my last comment https://github.com/Laravel-Backpack/CRUD/pull/3267#issuecomment-719650971

**Review by promatik — CHANGES_REQUESTED** [review]
@pxpm pinging you to check my last comment #3267 (comment)

**Comment by pxpm** [comment]
Just did @promatik thanks for the suggestion.

I made it configurable via lang so we don't enforce any specific placeholder for empty values. By default is `(empty)` like you suggested. 

Also removed this from `relationship_select`, we are not using it there.

**Comment by promatik** [comment]
@pxpm I tested and it's working great, I noticed the code could be improved a lot with nullish coalescing and made this commit https://github.com/Laravel-Backpack/CRUD/commit/f9a44920267928945433200c0828f678cf87dfc9 on the branch [`fix-lang-on-relationship-improvment`](https://github.com/Laravel-Backpack/CRUD/tree/fix-lang-on-relationship-improvment).

Please take a look and let me know what you think.
If you think we shouldn't merge that just move to Ready to merge ✌

**Review by promatik — APPROVED** [review]

**Comment by pxpm** [comment]
closing in favor of #3526

**Pull request closed without merging**
