### PR TITLE
Ignoring the hidden 'current_tab' field on store/update

### PR DESCRIPTION
**Pull request by AbbyJanke**
Fixes breaking issue in `return_current_tab` commit. Basically just adding "current_tab" to the exception list when storing and updating records.

https://github.com/Laravel-Backpack/CRUD/commit/4c8a338f36412ae99a9cb76e5a8bc97086d158d4#commitcomment-29499637

### CODE REVIEW

**Comment by AbbyJanke** [comment]
Appears the reason for it failing in the first place is due to not having strict mode enabled and/or not using $fillable/$protected as when I remove those configs i get this error but to ensure users's experience is the best probably should have it for safety.

**Comment by AbbyJanke** [comment]
We could add in a check within the controller if tabs are enabled to better avoid that but may cause confusion when looking into the controller code later down the road for some people?

**Comment by tabacitu** [comment]
Thank you @AbbyJanke ! Merged!

**Comment by tabacitu** [comment]
Thank you @AbbyJanke and @lloy0076  ! Merged!

**Pull request merged**
