### PR TITLE
[Bug] DataTables resetting to first page on bulk actions

### PR DESCRIPTION
**Pull request by promatik**
As @gthu96 reported on #3524, Data tables are reloading resetting to first page on bulk actions clone/delete.
This PR fix that behavior, keeping the user on the current page.

This fix also validates if while deleting the remaining rows on the last page, data tables would move the previous page.

### CODE REVIEW

**Comment by gthu96** [comment]
Hi @promatik  Thanks for the quick fix.
When can i expect this to be merged ?

**Comment by promatik** [comment]
@gthu96 I hope soon 🙌
Since it's a small change, if @pxpm don't find any problems introduced by this change, it may be merged soon.

**Comment by gthu96** [comment]
Hi @promatik is there any issues with the change or does these things take this long to merge?

**Review by pxpm — APPROVED** [review]
From my tests everything works as expected. 

Sorry for taking so much time to review this.

**Comment by tabacitu** [comment]
Merged. Will be tagged later today and available with a `composer update backpack/crud` starting tomorrow. Thanks everyone!

**Comment by gthu96** [comment]
Thank you so much guys. @promatik

**Pull request merged**
