### PR TITLE
Configurable delay on ajax fields

### PR DESCRIPTION
**Pull request by pxpm**
This is a complement to #3544 making the fix for select2 ajax fields/filter configurable.

Thanks https://github.com/matheusb-comp for the fix and @promatik for the review.

### CODE REVIEW

**Comment by promatik** [comment]
@pxpm agree with the changes 👍

I just think we should make a decision on `quiet_milis` vs `delay` usage.
On `select2_ajax.blade.php` we were using `quiet_milis`, so we keep the support. I think we should either;

1) Add `quiet_milis` to all the fields.
2) Aprove this PR as is, and drop the support for `quiet_milis` on v4.2 and keep `delay` only.

@tabacitu maybe you should give your opinion on this too.
I vote for **2**.

**Comment by pxpm** [comment]
Indeed, I made it thinking on your 2º option. I kept `quiet_milis` so we can merge this in 4.1 without BC, but there is no sense adding `quiet_milis` with it's called `delay`.

**Review by promatik — APPROVED** [review]
Ok, I think @tabacitu will agree with it too.
Let's merge this one as is, and once we clean up fields/columns/filters on v4.2 we deprecate `quiet_milis` 👌

**Comment by tabacitu** [comment]
Great! Thanks guys - please remember to add it to the docs too.

**Pull request merged**
