### PR TITLE
Fix to avoid odd dash (not null entry) on select multiple

### PR DESCRIPTION
**Pull request by promatik**
When clearing a select2 **multiple**, even though it allows nulls, it shouldn't place the empty dash `<option>-</option>`.
It creates a strange behavior:

ezgif-5-880297826b77

With this fix:

ezgif-5-3d63a5b574ad

### CODE REVIEW

**Comment by promatik** [comment]
@pxpm should we do this for `select2_multiple` too?
In that case we would remove the option completely, and allows_null would not make sense 🤔
This changes the current behavior. Anyway I don't think 'allow nulls' makes sense here, or at least if you do not allow nulls, an empty option should not be the fallback.

**Comment by pxpm** [comment]
> @pxpm should we do this for `select2_multiple` too?
> In that case we would remove the option completely, and allows_null would not make sense 🤔
> This changes the current behavior. Anyway I don't think 'allow nulls' makes sense here, or at least if you do not allow nulls, an empty option should not be the fallback.

Indeed @promatik if null is not allowed in field, we should make sure that atleast one option is selected. I think this is a behavior problem of all select2. 

Check for example: #3284

**Comment by promatik** [comment]
Humm, that's arguable 😬 I don't think we should keep an option, even though it is not null ... it may lead the end user to mistakenly assume he added that value, or assume that value is correct without checking other options.

So on an ajax field that depends on another, we should fetch new options just to pick the first one?

If we left it empty, he's going to fill it with a value, or have an error when trying to save it.

**Comment by pxpm** [comment]
> Humm, that's arguable 😬 I don't think we should keep an option, even though it is not null ... it may lead the end user to mistakenly assume he added that value, or assume that value is correct without checking other options.
> 
> So on an ajax field that depends on another, we should fetch new options just to pick the first one?
> 
> If we left it empty, he's going to fill it with a value, or have an error when trying to save it.

Sorry for late reply. 

What I mean by that, is that selecting something when null is not allowed is the default html select input behaviour, so that when you want to allow null you have to add an option like `-` or `N/A` wtv. 

So the debatable thing here is when to show an `empty input/developer default` when `allows_null => true`, I think for consistency we could:

`allows_null => true` = empty input or developer selected 
`allows_null => false` = select first option in select by default / developer selected option

If you want to show an empty input, but the column it's not nullable in database you should set the field to `allows_null => true` and validate in the request to don't throw null values on non-nullable database columns ? 

This is how I perceive the usage, let me know if you have a different view.

Best,
Pedro

**Comment by promatik** [comment]
> selecting something when null is not allowed is the default html select input behaviour

I agree with that for simple selects, because there's not other option, something has to be selected by default;
image

But on `select2_multiple` it's strange;
image

Differently from a normal select, `select2_multiple` doesn't force an option to be selected. It can be empty.
I think it would be better to not have the empty-dash option on this cases.

Also, `select2_from_ajax_multiple` doesn't have the empty dash, since it relies on fetching results, it doesn't make sense to have that empty-dash option.

What if in this cases we forced the the `required` html5 attribute?
So, we let the select2 to be empty, but we check the `required` attribute, if not set, is true.
image

**Comment by promatik** [comment]
Just updated the branch with the previous suggestion.

**Comment by pxpm** [comment]
Hello @promatik what I did in `relationship_select` (it allows multilple/non multiple) was:

```javascript
$(element).on("select2:select", function(e){
            if(typeof element.attr('multiple') !== "undefined") {
                let selected_element = $(e.currentTarget);
                let select_val = selected_element.val();
                let valuesWithoutEmpty = select_val.filter(v =>{
                    return v != "";
                });
                $(this).val(valuesWithoutEmpty).trigger('change');
            }
        });
```

This is pending in #3410 here: https://github.com/Laravel-Backpack/CRUD/blob/b92415dbbfbc784982b2aa33107643c0af318123/src/resources/views/crud/fields/relationship/relationship_select.blade.php#L196

I 100% agree with you that the dash does not make sense in `select multiple fields` so I am willing to remove it. We need to make sure to apply the same behaviour to 3xrelationships fields + select2 regular fields.

We have a known problem with html5 required attribute #2340 , basically if you select a save option from the dropdown it will fail miserably 👍 only work with main form button. That PR fixes that. 

Let me know,
Pedro

**Comment by promatik** [comment]
@pxpm that said, I'll postpone this to v4.2, mainly because of #2340, and also because this isn't super important I think (even though I don't like the dash at all 😅)

### Notes for future us;
- Make sure all the relationship fields are included on this.
- Also remove the JS part to deal with the dash
https://github.com/Laravel-Backpack/CRUD/blob/b92415dbbfbc784982b2aa33107643c0af318123/src/resources/views/crud/fields/relationship/relationship_select.blade.php#L196-L208

**Comment by tabacitu** [comment]
This was fixed in 4.2 - hitting "Clear" will no longer add the dash 🎉 



If I'm wrong, please re-open.

**Pull request closed without merging**
