### PR TITLE
Morph to relations support

### PR DESCRIPTION
**Pull request by pxpm**
### BEFORE - What was wrong? What was happening before this PR?

Working with morphTo relations was impossible in a "core" way. Users needed to manually setup the fields, and be aware that Backpack will think it's a relationship (correct), but Backpack didn't know how to handle it. Yet.

### AFTER - What is happening after this PR?

There is a clear way of using a morphTo relation.

```php
        CRUD::field('commentable')->morphTypeField([
            'label' => 'test',
            'tab' => 'po'
        ])->morphModels(['App\Models\Product' => [
            'attribute' => 'description'
        ], 'App\Models\PetShop\Owner']); 

        // or

        $this->crud->addField([
            'name' => 'commentable',
            'morphModels' => [
                'App\Models\Product' => [
                    'attribute' => 'description'
                ], 
                'App\Models\PetShop\Owner',
            ],
            'morphTypeField' => [
                'label' => 'overriden placeholder',
                'tab' => 'test'
            ]
        ]);
```

### How did you achieve that, in technical terms?

So basically I followed https://github.com/Laravel-Backpack/CRUD/issues/4090 but needed to adapt to circunvent some issues that arised. 

As you can see there is no `morphTo` field, only the `morphTo_select` (with the magical option changing and stuff). 
The reason for it is that we cannot add a `commentable` field, that includes the `morphTo`  field and then that field include two other fields because those "added fields" would be stripped out from the request as they are not "crud" fields. 
The only crud field would be the `commentable` (morphTo).

 There were two ways of going through this that I found:

- changing the morph field names to `commentable[morphable_type]` and `commentable['morphable_id']` so the `commentable` field exists and would let the values go through. Apart from the name changing drawback, we could not use native fields like `select_from_array` or whatever because they don't know how to properly parse those values.

- doing like I did, having a clear morph structure inside Crudpanel so both fields become real "crud fields" and there is nothing much to add.

### Is it a breaking change?

I don't think so.

### How can we test the before & after?

Use the `Comments` on the PetShop demo to test this relation. You can use the code I provided to setup fields.

### CODE REVIEW

**Comment by ziming** [comment]
looking forward to this!

**Comment by tabacitu** [comment]
**Note:**
- morphTo field is in https://github.com/DigitallyHappy/backpack-pro/pull/18 (pending review)
- this also needs a PR to the Demo, with an example (@pxpm clearest example would be in Petshop/Comments)

**Comment by pxpm** [comment]
@tabacitu this is refactored as we talked about. 

there is a linked PR in PRO as you know, also updated.

added the demo https://github.com/Laravel-Backpack/demo/pull/388

Cheers

**Comment by tabacitu** [comment]
Good news @pxpm - I've just asked @maurohmartinez to review this and https://github.com/DigitallyHappy/backpack-pro/pull/18 🎉🎉🎉

Can you please fix the merge conflicts, so he can do that?

**Comment by maurohmartinez** [comment]
Hi @pxpm!
I was trying to check this but for some reason I could not get it to work. Maybe I am missing something? I have checkout in the following branches:
- `morphto` on `backpack-demo`
- `morphTo-relations-support` on `crud`
- `morphTo-relation` on `pro`

When trying to save a new comment, validation fails with `The commentable id field is required`. I am not sure if it is related, but the second select field is created with name `comentable` and not `comentable_id`, so in validation it doesn't exist.

I tried manually renaming it, and while it passed validation, the new record was created with `commentable_id` empty.

Let me know if I need to adjust something in the way I set it up. Also, I can dig deeper and try to figure out, but wanted to first confirm with you.

Thanks!

**Comment by pxpm** [comment]
Hello @maurohmartinez , you were right, in the last refactor I forgot about something very important, **don't overwritte the field name if you want stuff to work**. 🙃 

I've just merged master here fixing the conflicts and fixed the issue you described. 

Can you give this a go ? Please notice that this should also work with Laravel MorphMaps. 

Cheers

PS: also updated the PRO pr.

**Comment by maurohmartinez** [comment]
@pxpm Great!
Tested it also with `MorphMaps` and `enforceMorphMap ` and all works like a charm.
Looks good to me!

**Comment by tabacitu** [comment]
Pedro I see your face is still on this issue, even though Mauro seems to have given his thumbs up. Is this ready for me to review & merge? If so, please slap my face on it 😀

**Comment by tabacitu** [comment]
>  in terms of functionality I think this needs to support ajax too, otherwise it will be unusable with models that have alot of entries, that's why I didn't move to you yet.

Damn... that might be true... Ok let's talk about it next week then, in a meeting. And decide together how we approach it.

**Comment by tabacitu** [comment]
Let's try a different syntax, in a different PR:

```php

        // NON-AJAX
        CRUD::field('commentable')
                ->label('Comment for')
                ->addMorphOption('App\Models\Petshop\Owner', 'Owner')
                ->addMorphOption('App\Models\Petshop\Pet', 'Pet')
                ->addMorphOption('monster', 'Monster');

        // AJAX
        CRUD::field('commentable')
                ->label('Comment for')
                ->addMorphOption('App\Models\Petshop\Owner', 'Owner', [
                    'label'       => "End", // Table column heading
                    'attribute'   => "name",
                    'data_source' => url("api/category"), 
                ])
                ->addMorphOption('App\Models\Petshop\Pet', 'Pet', [
                    'label'       => "End", // Table column heading
                    'attribute'   => "name",
                    'data_source' => url("api/category"), 
                ])
                ->addMorphOption('monster', 'Monster', [
                    'label'       => "End", // Table column heading
                    'attribute'   => "name",
                    'data_source' => url("api/category"), 
                ]);

```

This should solve our complexity problem, letting the developer add a "data_source" to a select, to turn it into an AJAX select (Fetch). Great idea @pxpm 👏👏👏 I'm not 100% on the name `addMorphType()` / `addMorphOption()`, but we can work on its name later...

**Comment by tabacitu** [comment]
Closing in favor of https://github.com/Laravel-Backpack/CRUD/pull/4579 - which also adds AJAX support 🎉

**Pull request closed without merging**
