### PR TITLE
Fixes #259 Allowed for mutating form data so laravel casting can work

### LINKED ISSUE #259: Malformed JSON in "table" field when casting
I have a table as a field type in my model, but when I update the model, the JSON in the database isn't right.  This is what I'm seeing:

`"[{\"form_field_name\":\"name\",\"readable_key\":\"Name\"},{\"form_field_name\":\"email\",\"readable_key\":\"Email\"}]"`

Where it should be 

`[{"form_field_name":"name","readable_key":"Name"},{"form_field_name":"email","readable_key":"Email"}]`

When I turn off auto-casting by commenting out `protected $casts = ['fields'=>'array'];`, the DB column saves properly.  Is this an encoding issue of some kind?

I currently solve this by using an extra accessor for the decoded version of the property.

### PR DESCRIPTION
**Pull request by OwenMelbz**
Enabled automatic mutating of form data without developer interaction, allowing them to use default laravel functionality

### CODE REVIEW

**Comment by OwenMelbz** [comment]
Note: this bug also effects the Video field type

**Comment by OwenMelbz** [comment]
This ticket here explains the actual issue -> https://github.com/Laravel-Backpack/CRUD/issues/259

The problem was, when the forms submit, it sends a json encoded string (NOT JSON) thus when it adds it to the database, it adds a json encoded string. e.g
```
"[{\"form_field_name\":\"name\",\"readable_key\":\"Name\"}]"
```

This means if you try inserting it into a json database field type, or use laravels casting it fails, because its not json, its a json encoded string.

for it to work as expected it would need to be

```
[{"form_field_name":"name","readable_key":"Name"}]
```

So this PR converts json encoded strings that are submitted to the form, into an array, so it can be processed correctly. 

-------

However!!! I do like your suggestion about trying to use the $casts directly from the model!! I shall give this another look to see if it can be simplified!

**Comment by tabacitu** [comment]
Damn... Ok, I get it now, thanks. 

Well then... maybe a more general solution could be: 
```php
// before storing stuff (create/update)
if (we have any attribute casting to json or array)
{
  foreach (attribute that has casting to json or array) {
    if (request value for the casted attribute is a json_encoded string) 
    {
      // json_decode it, so that Laravel attribute casting can do its thing;
    }
  }
}
```

1) This _should_ prevent any field from storing the value json-encoded two times. Right?
2) Would this conflict with anything else, I wonder? Would you ever WANT to store it encode it two times and this will prevent you from doing so?

**Comment by OwenMelbz** [comment]
I've just pushed a small refactor to directly use the models casting.

This means nothing is ever double encoded, or decoded (Except from within our field includes - this is because its just trying to cater for everything)

So when you do something like

```
App\Models\Question::find(1)->question->name;
```

form a structure like (in the database)

```
{"name":"dsf","administrative":"Niedersachsen","city":"Atter","country":"Germany","countryCode":"de","type":"address","latlng":{"lat":52.2948,"lng":7.95582},"postcode":"49076","value":"dsf, Atter, Niedersachsen, Germany"}
```

using 

```
protected $casts = ['question' => 'object'];
```

it will now play nice with laravel.

The bug was just simply the JSON was encoded in the hidden inputs on the form page, using `JSON.stringify()` which makes sure its string safe, but the above PR update should be fine now

**Comment by tabacitu** [comment]
Great. Just rephrased things a bit and added documentation. Tested it, works fine. Then again, it worked fine for me before, too.

Merging it, cheers, thanks!

**Pull request merged**
