### PR TITLE
switch to Illuminate\Http\Request in CrudController

### PR DESCRIPTION
**Pull request by OliverZiegler**
current solution for #1119

### CODE REVIEW

**Comment by OliverZiegler** [comment]
Well... StyleCI "destroyed" the intended order of `use` statements... 🤔

**Comment by OliverZiegler** [comment]
I don’t think so. 
The backpack generated files can stay like they are I think

**Comment by tabacitu** [comment]
Thank you @OliverZiegler ! Finally been able to extensively test and merge this. Imho it's a non-breaking change so it'll be available in a patch update later today.

Cheers! Thanks a lot.

**Comment by tabacitu** [comment]
Also changed the generators to extend the default FormRequest, not CrudRequest, so we can deprecate CrudRequest in the future - https://github.com/Laravel-Backpack/Generators/commit/949e3fc7000392b421f4a71f9a9030212da0795a#diff-918597f9a671132c2ebcee64c0b50c97

**Pull request merged**
