### PR TITLE
added name to fetch route

### PR DESCRIPTION
**Pull request by iMokhles**

### CODE REVIEW

**Comment by tabacitu** [comment]
Thank you @iMokhles - from my point of view this'll work great! 
But I'll let @pxpm have the final word on this one, since `Fetch` was his baby. What do you think @pxpm ?

**Review by pxpm — COMMENTED** [review]
I think this is something we can afford. 

I am ok as from my understanding this will have unique routes (using -fetch- as part of the name) 

It should not conflict with anything, unless I am missing some shady behaviour of setting up route names, i don't think so.

For me this PR is ok to merge. 

The only thing I can think that someone could ask further is that sometimes people (i am one of them)  define the route names with `.` (dot) instead of `-` (dash).

Maybe a config key to configure route name separator for `FetchOperation` ? 
`fetch_route_name_separator => '.'` 

Let me know what you guys think.

**Comment by tabacitu** [comment]
Thanks for the review @pxpm . That's the only thing that stood out to me too. 

But then I thought that maybe @iMokhles used dashes instead of dots for consistency with the InlineCreate operation. But I see InlineCreate is the only thing in Backpack that does that, to my knowledge:
Screenshot 2020-08-20 at 08 22 11

Personally I prefer dots over dashes in route names. Then again, I see:
- [the Laravel best practice for route names is to use dots and snake-case](https://www.laravelbestpractices.com/#routes)
- our Operations usually use dots and camelCase (`product.bulkDelete`)

So... yeah. Not pretty.

I think we should at least _not continue_ this inconsistency, of using dashes. **I propose we make this route name `$segment.'@fetch'.$methodName` (dot notation + camelCase).** This way, the only route name that doesn't respect this convention would be the `InlineCreate` operation. For that, @pxpm can create a PR, and we'll merge it in 4.2 (since I assume it'll be a breaking change).

That means, in 4.2, all our route names use dot + camelCase. Until then, only the InlineCreate uses a different system.

What do you guys think - @iMokhles & @pxpm ?

**Comment by iMokhles** [comment]
i'm okey with that it won't hurt a lot and about the dash it's inspired by inline-create routes as it's related to it.

**Comment by pxpm** [comment]
Indeed, sometimes I feel like ... "Why the hell did I use dashes instead of dots". I really didn't take it into consideration because I never though that people would be calling inline create routes by name, it's a very specific url, for a very specific scenario, but now that we talk about it, it kinda works like an API for creation. 

Please @iMokhles , don't take my words to the hearth, you are totally right here, in first place `InlineCreateOperation` route names  should come with dots and not dashes. That's my fault, so sorry :) 

If you can change your PR to use dots instead of dashes that would be awesome. Like @tabacitu said, we might also change Inline routes to use dots and make it consistent when we can push a breaking change in 4.2.

Wish you the best,
Pedro

**Comment by iMokhles** [comment]
it's okey @pxpm thanks and hope the snake delimiter parameter is okey with you to add dashes with dots as suggested

**Comment by tabacitu** [comment]
Thanks a lot @iMokhles ! Good catch running the `$methodName` through another Str, indeed if we don't its first letter will be capitalized (`product.fetch.FallbackIcon`), which would be ugly.

So your current PR, because of the `.` parameter, would result in: `product.fetch.fallback.icon` which I think is a little bit confusing. The dot is usually there to mark a change to the next parameter, but `fallback` and `icon` are part of a single parameter.

What do you and @pxpm think about doing `Str::snake($methodName)` instead, so that the result is `product.fetch.fallbackIcon`?

Then it would be consistent with `product.bulkDelete` and `product.bulkClone`, in that it's: `crudEntityName.operationName.optionalParameterToTheOperation`. Right?

**Comment by iMokhles** [comment]
so we can make it like that product.fetchFallbackIcon what do you think @tabacitu

**Comment by tabacitu** [comment]
Oh right! 🤣 that's even better. 

`product.fetchFallbackIcon` is even more consistent with `product.bulkDelete` and `product.bulkClone`

**Comment by iMokhles** [comment]
@tabacitu done hope it's better like that

**Comment by tabacitu** [comment]
Merged! Thanks @iMokhles , and sorry for the long back-and-forth. It'll be available later today as 4.1.19 gets tagged.

Cheers!

**Pull request merged**
