### PR TITLE
Retrieve table columns as array of Column objects

### PR DESCRIPTION
**Pull request by jonphipps**
When using the ```Autoset``` trait, the ```getDbColumnTypes()``` method uses many separate queries to get the column type and column default. 

This change retrieves the table columns just once as an array of ```\Doctrine\DBAL\Schema\Column``` and iterates through that array to retrieve the column type and default. This results in a fairly dramatic performance improvement.

### CODE REVIEW

**Comment by jonphipps** [comment]
I should have checked the tests before submitting. The failing tests were because of a case-mismatch on the name of the column and the columntype as explained in the commit message. This caused the tests to fail because they couldn't match the array indexes in the tests to the columns.

Normally I wouldn't think of changing the existing tests or the test database, but the overall functionality hasn't changed and the tests still return the correct data about the columns and related fields once the keys align properly.

Nice tests BTW. Thanks for all of the work on that.

**Comment by lloy0076** [comment]
Is the change in case likely to affect actual users (i.e. is that an externally viewable change)?

**Comment by jonphipps** [comment]
@lloy0076 No. It's only used as an internal mapping from column type to field type. The user would only use and see the field type. 

The only place the 'type' value is used in the field setting is in the ```getFieldTypeFromDbColumnType()``` method of the ```AutoSet``` trait where it's used to set the field type: https://github.com/Laravel-Backpack/CRUD/blob/bd2badc5ae6a47bb31a62b5af28361d890f4ce63/src/PanelTraits/AutoSet.php#L92 

The 'case' values in that method are already lowercase matches to the types returned by ```getDbColumnTypes```. The camelcase mismatch is a testing artifact as far as I can see.

There's a list of the DBAL type's and their names here: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix

**Comment by lloy0076** [comment]
Odd, one would have thought the tests would have failed before...in any case your explanation makes sense.

**Comment by lloy0076** [comment]
I'll take this for a spin on MySQL and Postgres and see if I can get an SQL Server Express to behave itself; it looks good but if we break the auto set we'll have users with forks and knives  🍴  after us.

**Comment by jonphipps** [comment]
Hopefully you won't discover any issues (I only tested on MySQL) and users will be happy.

Blackfire reports for execution time (percentage of total) for ```setFromDb`` and total SQL queries for my test 'list' page...
Before: 986ms (67%) and 238 queries
After: 86ms (10%) and 27 queries

:smile:

**Comment by jonphipps** [comment]
I submitted a revised pull request that doesn't require changes to existing tests. 

I was using the key from the column list (all lower case version of column name) instead of the column 'name' attribute for the column key. 

You were right to be cautious.

**Comment by tabacitu** [comment]
> You were right to be cautious.

Love this.

**Pull request closed without merging**
