### PR TITLE
fix handling translated fake fields

### PR DESCRIPTION
**Pull request by OliverZiegler**
This will fix an issue introduced with  #1488 in PR #1533 found in #1546.

Currently working on some unit tests for `CrudTrait` as we currently only test `CrudPanel`

### CODE REVIEW

**Comment by tabacitu** [comment]
MUCH cleaner than my PR https://github.com/Laravel-Backpack/CRUD/pull/1549!

Thank you @OliverZiegler !

**Comment by OliverZiegler** [comment]
@tabacitu ready and packed with basic tests. 🎉 

In `FakeColumnsModel` some of the `$fillables` are currently not used, but would like to leave them there for later. 
Found some idea for a nice feature here.

**Comment by tabacitu** [comment]
[Travis's unit tests say go](https://travis-ci.org/Laravel-Backpack/CRUD/builds/404532593).
My manual tests say go. 
So this is a go :-) 

Thank you so much @OliverZiegler . Excellent PR. 

Of course, leave them, whatever you need. Curious to hear your new feature idea.

**Comment by OliverZiegler** [comment]
@tabacitu here you are #1552 
could be nice imho 😅

**Comment by hocklai8** [comment]
I think I've come across an issue with translated fake fields where it's saved to the DB correctly but does not decode translated fake fields properly to be displayed in the fake fields during edit. Think the shouldDecodeFake() should also check if the column is translatable?

I've attempted to fix this issue here #1636 (It's a follow up to issue #1633)
Please have a look at the PR

**Pull request merged**
