### PR TITLE
[4.0][Feature] Implement orderButtons

### PR DESCRIPTION
**Pull request by tabacitu**
Local branch for PR https://github.com/Laravel-Backpack/CRUD/pull/2446 so we can add unit tests

### CODE REVIEW

**Comment by tabacitu** [comment]
@pxpm This looks great upon review, but it needs a unit test since it's a new CrudPanel method. So... I think it's a great opportunity for you to get familiar with how unit test are set up in Backpack, I know you haven't contributed with any unit tests so far.

My thinking:
- we'll need to add unit tests to the features for 4.1 you've contributed;
- 

**Can you please do this unit test for me?** Let me know if you need help with anything. 

To set up Backpack for unit testing & run the unit tests:

```bash
cd yourproject
cd vendor/backpack/crud
composer install
composer test
```

Then it should just be a matter of adding the new test method to the right file, in this case ```tests/Unit/CrudPanel/CrudPanelButtonsTest.php```

Let me know if you stumble anywhere - I know this testing part in Backpack isn't documented at all, but my tips above should help.

Cheers!

**Comment by pxpm** [comment]
Hey @tabacitu 

While testing this, I think I found an issue. If I add 3 fields, and reorder only two, the reorder operation will remove the field that I did not order from the buttons array. 

```php
public function testReorderButtons() {
        $this->crudPanel->addButton('line', 'update', 'view', 'crud::buttons.update', 'end');
        $this->crudPanel->addButton('line', 'show', 'view', 'crud::buttons.show', 'end');
        $this->crudPanel->addButton('line', 'test', 'view', 'crud::buttons.update', 'end');

        $this->crudPanel->reorderButtons('line', ['show', 'test']);

        $this->assertEquals(['show', 'test', 'update'], $this->crudPanel->buttons()->pluck('name')->toArray());
    }
```

Is this expected behaviour, or the buttons that are not reordered should be pushed to the end instead of removed ? 

Best,
Pedro

**Comment by tabacitu** [comment]
Wow nice catch @pxpm ! Good question. 

**I think we should do the same thing we do for ```fields``` and ```columns```.** Even if it's a bad behaviour there, at least it should be _consistently bad_ between Fields, Columns and Buttons. Right? 😄 I've tried to see how it works for Fields and Columns, but the docblocks aren't very specific on whether they get pushed at the start/end. 

```php
    /**
     * Order the CRUD fields. If certain fields are missing from the given order array, they will be
     * pushed to the new fields array in the original order.
     *
     * @param array $order An array of field names in the desired order.
     */
    public function orderFields($order)
    {
        $this->transformFields(function ($fields) use ($order) {
            return $this->applyOrderToFields($fields, $order);
        });
    }

    /**
     * Order the CRUD columns. If certain columns are missing from the given order array, they will be pushed to the
     * new columns array in the original order.
     *
     * @param array $order An array of column names in the desired order.
     */
    public function orderColumns($order)
    {
        $orderedColumns = [];
        foreach ($order as $columnName) {
            if (array_key_exists($columnName, $this->columns())) {
                $orderedColumns[$columnName] = $this->columns()[$columnName];
            }
        }

        if (empty($orderedColumns)) {
            return;
        }

        $remaining = array_diff_key($this->columns(), $orderedColumns);
        $this->setOperationSetting('columns', array_merge($orderedColumns, $remaining));
    }
```

To be honest, I have no idea how ```orderFields()``` and ```orderColumns()``` work - I don't think I've _ever_ used them outside of testing.

From my point of view, for this PR to be ready to merge we need to:
- [ ] see what happens when using ```orderFields()``` and ```orderColumns()``` and do the same for ```reorderButtons()```
- [ ] rename ```reorderButtons()``` to ```orderButtons()``` for consistency between Fields, Columns, Buttons;
- [ ] create a unit test that specificly tests this use case you discovered, ```testOrderButtonsTwoOutOfThree()```;
- [ ] if you discover this use case (order 2 out of 3 items) isn't covered by unit tests in Fields or Columns either, please also create ```testOrderFieldsTwoOutOfThree()``` and ```testOrderColumnsTwoOutOfThree()```;

Cheers!

**Comment by pxpm** [comment]
Hey @tabacitu 

Refactored this to behave like fields and columns: 
> If button is not ordered by developer is added at the end of the ordered.

I think this is good, please give it a try.

Best,
Pedro

**Comment by tabacitu** [comment]
Works as expected! Good job @pxpm ! Merging this into ```master```. It'll be available in 4.0 with the next patch release.

**Pull request merged**
