### PR TITLE
Auto-truncate email

### PR DESCRIPTION
**Pull request by AbbyJanke**
Per discussion on over at [Spectrum](https://spectrum.chat/?t=93a11ae9-2b41-42bd-b6d3-c15e31a6fe6) allow truncating an email.

### CODE REVIEW

**Comment by AbbyJanke** [comment]
@OwenMelbz thoughts on if we auto truncate then if the limit is set to ‘null’ we don’t truncate? I feel like more people would want it to be rather then not? But i would maybe leave the final decision to @tabacitu

**Comment by tabacitu** [comment]
Haha quite a dilemma - I get both of you guys. On the one hand, the ```text``` column has a default limit 50, so it'd be intuitive the ```email``` column has a default limit 50 too. All columns actually. But @OwenMelbz makes a good point, pushing a default limit _would_ make this a breaking change. So I think **it's best to push a limit null for now**, and make a note of making all limits 50 in the next version. I'd rather have the limit feature sooner rather than later...

**Comment by tabacitu** [comment]
Apparently you can't pass ```null``` or ```0``` or something like that to limit to cancel it. So I've made the default ```254``` - the maximum length of a full email following standards.

This makes this PR non-breaking, so I'm merging it. Thanks for the collaboration @AbbyJanke  & @OwenMelbz !

**Comment by AbbyJanke** [comment]
Thanks @tabacitu I was planning to get to making the change today but looks like you beat me to the punch :)

**Pull request merged**
