### PR TITLE
Fix table json encryption

### PR DESCRIPTION
**Pull request by ibpavlov**
I had an issue with quotes and JSON.stringify helps me encode the JSON exactly as on specification.

### CODE REVIEW

**Comment by tabacitu** [comment]
Thank you @ibpavlov ! This looks great as far as I can tell. I agree it's probably better to use `JSON.stringify` rather than regex. I just hate regex, so difficult to read.

I believe this is a good solution for #2840 . @pxpm could you please review this? 

Personally - I only have one concern regarding this - since we're using JSON.stringify()... won't we be affected by the JSON order problem? JSON is known not to preserving the order of the items, right? Do you think that will affect us negatively here @pxpm ?

**Comment by pxpm** [comment]
Indeed @tabacitu JSON does not preserve keys, but I think there is not a problem here because we are storing { named_key : value } pairs. 

Just not sure we need all this changes to the file. And it might have some error I already reviewed.

**Comment by tabacitu** [comment]
Thanks again @ibpavlov for submitting this. I've just merged #2960 that fixes the same problem, but with fewer changes, so I'm going to close this PR.

I do appreciate you taking the time to put together the PR though - really! It's just that when testing both PRs, #2960 was working well in all use cases, but this PR made the `Fake Table` field (Monsters CRUD > Miscellaneous tab) stop loading previous entries. **If you're using this solution in your project, please take note - fake table fields might not work properly!** I recommend you scrap this solution and do a `composer update`, the fix will be tagged and released later today.

One thing I did like in this PR, and I'm sad that we're not merging it, is that it cleaned up that method a little bit. I do agree that we're in dire need of a cleanup here - so I propose we revisit this and do the cleanup you did here over the current `master` branch, but without this bug obviously 😆 

Thanks again, cheers!

**Comment by tabacitu** [comment]
We'd love that. Keep 'em coming!

**Pull request closed without merging**
