### PR TITLE
[WIP] Add show view

### PR DESCRIPTION
**Pull request by welcoMattic**
Ref. #226

### CODE REVIEW

**Comment by M0H3N** [comment]
Hi 
can I update the package for this feature ?

**Comment by welcoMattic** [comment]
Hi @M0H3N, it's not released yet. There's a certain amount of work before this feature be stable.

**Comment by tabacitu** [comment]
Agreed, needs some polish from the designer ;-) Will do.

**Comment by tabacitu** [comment]
Just merged @AbbyJanke 's PR into ```dev``` - https://github.com/Laravel-Backpack/CRUD/pull/781, which builds upon this concept - it uses SHOW columns in the PREVIEW action. It's still not foolproof, but I think it's a very good feature to be used by developers, and knowledgeable admins.

So I'll close this issue and let's build upon that one.

@welcoMattic thanks a lot for the contribution. Haven't seen you in a while over here. If you stopped using Backpack, what have you been using in the meantime?

Cheers!

**Pull request closed without merging**
