### PR TITLE
Issue #167 - allow return of created entries for custom use

### PR DESCRIPTION
**Pull request by b8ne**

### CODE REVIEW

**Comment by OwenMelbz** [comment]
@b8ne I'm not sure this will get merged as it is, as for 3.2 release this method will be changed a fair amount so this wont be compatible

**Comment by b8ne** [comment]
Hey @OwenMelbz how far off is 3.2? I just had a look and cant see how it wouldnt be compatible?  As discussed in this issue its needed to be able to perform post processing on the new/updated CRUD rows prior to redirect.
ie. in ModelCrudController
```
public function store(StoreRequest $request)
{
    $new_row = parent::storeCrud();
    /*
        Perform Post Processing on $new_row
    */
     return \Redirect::to($this->crud->route.'/'. $this->crud->entry->getKey().'/edit');
}
```

**Comment by OwenMelbz** [comment]
@b8ne because of the way the latest iteration of `storeCrud` works

```
public function storeCrud(StoreRequest $request = null)
    {
        $this->crud->hasAccessOrFail('create');
        // fallback to global request instance
        if (is_null($request)) {
            $request = \Request::instance();
        }
        // replace empty values with NULL, so that it will work with MySQL strict mode on
        foreach ($request->input() as $key => $value) {
            if (empty($value) && $value !== '0') {
                $request->request->set($key, null);
            }
        }
        // insert item in the db
        $item = $this->crud->create($request->except(['redirect_after_save', '_token', '_method']));
        // show a success message
        \Alert::success(trans('backpack::crud.insert_success'))->flash();
        // save the redirect choice for next time
        $this->setSaveAction();
        return $this->performSaveAction($item->getKey());
    }
```

As you can see the final call is `performSaveAction` and currently this will always redirect, meaning you'll never be able to run anything after you call `parent::storeCrud();`

I can't actually find it now, however I've mentioned in another ticket, about adding hook like functionality into these, so you can do it.

So its not that we cant/wont make this possible, its just you wont be able to do this in 3.2 as it currently stands

**Comment by b8ne** [comment]
@OwenMelbz yep I see, I think i stuffed up above with my use case. Should actually be:
```
public function store(StoreRequest $request)
{
    $response = parent::storeCrud();
    /*
        Perform Post Processing on $this->crud->entry
    */
     return $response;
}
```
So even in 3.2 `$this->performSaveAction()` will return a redirect.  `$response` can then hold the redirect until post processing is done.
Totally agree a hook system would be better, however I still think this is a perfectly fine interim solution.

**Comment by tabacitu** [comment]
Uh... Just pushed an update that does the same thing. Too bad I didn't take a look at this PR first.

Thanks for the PR. I've made the entry available in both ```$this->crud->entry``` and ```$this->data['entry']```.

@OwenMelbz , I think this is a good feature. Quite a few people have requested it, no point in not providing it now. We'll make it work in 3.2 too, I don't think it's that much of a hassle.

Cheers!

**Comment by b8ne** [comment]
Yeww thanks @tabacitu this will make my life easier

**Comment by tabacitu** [comment]
All of ours :-) Thanks for the PR and the suggestion. Cheers!

**Pull request closed without merging**
