### PR TITLE
Make Summernote dropdowns work in Bootstrap 5 & 4

### PR DESCRIPTION
**Pull request by karandatwani92**
## WHY
Solves https://github.com/Laravel-Backpack/community-forum/issues/581
### BEFORE - What was wrong? What was happening before this PR?

Summernote was not Bootstrap 5 compatible. 

### AFTER - What is happening after this PR?

Now it supports Bootstrap 5 & 4(Tested on our three themes)

### What's left

- [ ] Dark Mode support.
I don't know if it will be added inside the field or in the tabler theme. @jorgetwgroup Please guide on this.

### CODE REVIEW

**Comment by karandatwani92** [comment]
A snippet for dark mode support, has not been added yet... this might be useful later
```css
@media (prefers-color-scheme: dark) {
              .note-editor.note-airframe,
            .note-editor.note-frame {
                border: 1px solid #f5f5f5
            }

            .note-editor .note-toolbar .note-style .dropdown-style h1,
            .note-editor .note-toolbar .note-style .dropdown-style h2,
            .note-editor .note-toolbar .note-style .dropdown-style h3,
            .note-editor .note-toolbar .note-style .dropdown-style h4,
            .note-editor .note-toolbar .note-style .dropdown-style h5,
            .note-editor .note-toolbar .note-style .dropdown-style h6,
            .note-editor .note-toolbar .note-style .dropdown-style p,
            .note-popover .popover-content .note-style .dropdown-style h1,
            .note-popover .popover-content .note-style .dropdown-style h2,
            .note-popover .popover-content .note-style .dropdown-style h3,
            .note-popover .popover-content .note-style .dropdown-style h4,
            .note-popover .popover-content .note-style .dropdown-style h5,
            .note-popover .popover-content .note-style .dropdown-style h6,
            .note-popover .popover-content .note-style .dropdown-style p {
                color: #000;
            }

            .note-editable h1,
            .note-editable h2,
            .note-editable h3,
            .note-editable h4,
            .note-editable h5,
            .note-editable h6,
            .note-editable p,
            .note-editable blockquote,
            .note-editable pre {
                color: #fff;
            }
        }
```

**Comment by tabacitu** [comment]
I love the fact that you sepparated this, so we can push this through then spend time on dark mode ❤️ Great thinking @karandatwani92 !

**Comment by pxpm** [comment]
Hey @karandatwani92 thanks for the PR.

When I click the "full screen icon" this is what I get: 
image

I don't recall, but I think in v5 this worked fine ?

**Comment by karandatwani92** [comment]
@pxpm Good you found something and we fixed it.

bs5 is for Bootstrap 5 & bs4 is for Bootstrap 4. and we are using lite, which supports both.

Fullscreen was summernote issue [fixed](https://github.com/summernote/summernote/issues/4401#issuecomment-1356228369) by:
 
```
.note-editor.note-frame.fullscreen {
    background-color: white;
}
```

**Pull request merged**
