### PR TITLE
Better debug error message for backpack_view() function

### PR DESCRIPTION
**Pull request by pxpm**
### BEFORE - What was wrong? What was happening before this PR?

Reported in https://github.com/Laravel-Backpack/CRUD/issues/5167

The error message was not very helpful. 

### AFTER - What is happening after this PR?

image

I also added a check for app in production and debug=true to avoid exposing sensitive information if developer pushed to prod with missing views. 

view name and view path I think it's fine, server path is not ok, but it helps in development.

### CODE REVIEW

**Review by tabacitu — APPROVED** [review]

**Comment by tabacitu** [comment]
Code looks good to me. @jorgetwgroup please test, and if ok give it back to Pedro to merge and tag.

**Comment by pxpm** [comment]
Heads up @jorgetwgroup 

I've modified the code slightly to don't include the debug details when in production or debug is of. 

In production: 
image

In dev:
image

Cheers

**Comment by karandatwani92** [comment]
Hey Master @pxpm
I have a question, why show error details in the production?
Screenshot 2023-07-23 at 6 19 43 PM

**Comment by karandatwani92** [comment]
Hey Master @pxpm 
I have a question.

In **Production** or when `APP_DEBUG=false` . Errors - **view** file, $**errorMessage** is fine.✅ Totally the same as laravel errors in production
image


But in **Dev** or when `APP_DEBUG=true` the **error view** is totally same, the only change is it's appended with $errorDetails.

Where the error view is supposed to be different like this:
image

**Comment by pxpm** [comment]
Thanks for the review @karandatwani92 

The problem here is not the view not found. It's how this particular error is displayed.

We search on multiple namespaces, if we throw the Laravel error it will not say the full namespace where the view was not found, you need to read the php code (hidden inside "vendor frames" tab) to know that we tried 3 different namespaces.

The error you propose is more helpful for "us" (maintainers), but for developers using the package it's very difficult to debug anyway. 

With this you know the same:
- The view was not found
- we tried X namespaces
- if you are not in production or have debug enabled you get the information where that view being called. 

Let me know what you think.

**Comment by karandatwani92** [comment]
@pxpm UNDERSTOOD.

CLEAR✅ READY TO MERGE

**Pull request merged**
