### PR TITLE
[4.0][Feature] Date_range filter - allow for Custom Options, Such as minDate

### PR DESCRIPTION
**Pull request by zachweix**

### CODE REVIEW

**Comment by tabacitu** [comment]
Wow - I think that's a very good way to pass configuration options to filters (through the ```options``` parameter) Great idea @zachweix ! I also agree to make it easy for developers to customize their date_range pickers.

We won't merge this as-is, though, because I think the syntax to do this is a bit off - and it's important to nail the syntax from day 1. Introducing breaking changes can only be done once every 6 months.

Here's what I mean by the that. Right now devs are supposed to do:
```php
// daterange filter
$this->crud->addFilter([
  'type'  => 'date_range',
  'name'  => 'from_to',
  'label' => 'Date range'
],
  [
    'custom' => [
           'key' => 'value',
    ]
  ],
  function ($value) { // if the filter is active, apply these constraints
      // $dates = json_decode($value);
      // $this->crud->addClause('where', 'date', '>=', $dates->from);
      // $this->crud->addClause('where', 'date', '<=', $dates->to . ' 23:59:59');
  });
```

I think:
- [ ] it would be better to use the entire ```options``` parameter for this; no ```custom```; I don't see anything else we'd need to pass as ```options``` to this filter in the future, so let's use the entire parameter; that way, the syntax would be:
```php
// daterange filter
$this->crud->addFilter([
  'type'  => 'date_range',
  'name'  => 'from_to',
  'label' => 'Date range'
],
  [ 'key' => 'value' ],
  function ($value) { // if the filter is active, apply these constraints
      // $dates = json_decode($value);
      // $this->crud->addClause('where', 'date', '>=', $dates->from);
      // $this->crud->addClause('where', 'date', '<=', $dates->to . ' 23:59:59');
  });
```
- [ ] plus - possible problem: in the current implementation I don't think you can push boolean values, because they're echoed within quotes; instead of echoing them using ```{{ $key }}: "{{ $option }}",``` I would probably do something like this at the top of the filter:
```php
  @php
     // make sure the jQuery plugin has the necessary configs to work
     // in case the developer hasn't specified any, use the defaults 
     $filter->options = array_merge([
         'timePicker' => false,
	 'alwaysShowCalendars' => true,
	 'autoUpdateInput' => true,
     ], $filter->options);
  @endphp
```
Then inside the JS:
```diff
		jQuery(document).ready(function($) {
-			var dateRangeInput = $('#daterangepicker-{{ str_slug($filter->name) }}').daterangepicker({
+			var config = {
-				timePicker: false,
		        ranges: {
		            'Today': [moment().startOf('day'), moment().endOf('day')],
		            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
		            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
		            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
		            'This Month': [moment().startOf('month'), moment().endOf('month')],
		            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
		        },
				@if ($filter->currentValue)
		        startDate: moment("{{ $start_date }}"),
		        endDate: moment("{{ $end_date }}"),
				@endif
-				alwaysShowCalendars: true,
-				autoUpdateInput: true
-			});
+			}.concat(@json($field->options));
+			var dateRangeInput = $('#daterangepicker-{{ str_slug($filter->name) }}').daterangepicker(config);
```
Notice that if we do it like this, we can also make a few more default options like ```timePicker```, ```alwaysShowCalendars``` and ```autoUpdateInput``` configurable, with a default. Unfortunately, I don't think we can do this for ```ranges```, ```startDate``` and ```endDate```, since those depend on momentJS... So those will probably remain hardcoded and difficult to overwrite...

Let me know if you'd like to try the changes above yourself @zachweix , and modify your PR, or you'd rather wait for us to do them. It's good for us either way 😄

**Comment by tabacitu** [comment]
Ok so right after I posted the above I noticed something else 😄 
- [ ] if we pass the JS plugin options through the ```options``` parameter, we'd be introducing an inconsistency between how the date_range Filter and date_range Field work; so rather than passing the options through ```options```, I think it would be better to follow the syntax of the date_range Field, and do:

```diff
// daterange filter
$this->crud->addFilter([
  'type'  => 'date_range',
  'name'  => 'from_to',
  'label' => 'Date range',
+ 'date_range_options' => [ 'key' => 'value' ],
],
  false,
  function ($value) { // if the filter is active, apply these constraints
      // $dates = json_decode($value);
      // $this->crud->addClause('where', 'date', '>=', $dates->from);
      // $this->crud->addClause('where', 'date', '<=', $dates->to . ' 23:59:59');
  });
```

It's a worse syntax. Definitely. But it would be consistent between Fields and Filters... which I think would be a good thing...

Eager to see what others think about this though...

**Comment by pxpm** [comment]
just for reference: #2253

**Comment by tabacitu** [comment]
@zachweix thanks again for the PR. I've continued the work with my notes above, and it's now on a new branch here. Check out https://github.com/Laravel-Backpack/CRUD/pull/2500 please.

**Pull request closed without merging**
