### PR TITLE
[Feature][3.5][Ready] Made CrudPanel class Macroable

### PR DESCRIPTION
**Pull request by tabacitu**
I would love it if we could create separate packages for some CRUD Operations. Some common, but... not that common. Say... ```moderate```, or ```simpleReorder```. I think ```revisions``` is a good example for that. I don't think it should live in the main CRUD package. It's just not that important, and most people don't use it.

We _should_ allow developers to build their own Features, and reuse them across different CrudControllers. Let me explain. Say someone wants to add a SimpleReorder OPERATION. A SimpleReorder that doesn't need ```left```, ```right```, ```depth```. No nested set. Just a plain simple ```order``` column in the db. They can:
- create a ```Reorder``` trait for the Operation, and use it on CrudController; that trait would provide the two methods their operation needs, ```showReorderScreen()``` and ```saveReorder()```; 
- but then they notice they're reuseing some of the code; their methods are sloppy; so they end up having new methods inside the ```Reorder``` trait, that don't actually belong there; that only process ```$crud``` stuff; just like we now have ```Backpack\CRUD\PanelTraits\Reorder```;

Previously you couldn't add your own methods to ```$this->crud```. This fixes it. Allows something like this:
```php
class MonsterCrudController extends CrudController 
{
   public function setup() 
   {
       $this->crud->macro('doStuff', function($something) {
            echo '<pre>'; var_dump($something); echo '</pre>';
            dd($this);
        });
       $this->crud->macro('getColumnsInTheFormatIWant', function() {
            $columns = $this->columns;
            // ... do something to $columns;
            return $columns;
        });
       
       // bla-bla-bla the actual setup code
   }
   public function sendEmail() 
   {
      // ...
      $this->crud->doStuff();
      dd($this->crud->getColumnsInTheFormatIWant());
      // ...
   }
   public function markPending() 
   {
      // ...
      $this->crud->doStuff();
      dd($this->crud->getColumnsInTheFormatIWant());
      // ...
   }
}
```

This _is_ a small improvement in my opinion. Think about it this way, if you had do change something that CrudPanel did, where would you put it? On MonsterCrudController most likely, right? So you would have made a class that does something with $crud variables, on the controller. Even though it doesn't have a route. That's not where it belongs... It belongs on CrudPanel if it only manipulates its properties. And this PR allows you to do that.

However. **What happens if we add methods to CrudPanel that users themselves have put in, in their projects?** Well... they'll be using OUR methods when they update, instead of their macro-ed methods. Because macros only apply when that method doesn't exist. So **it's a nice change, but it WOULD make it more difficult for us to push methods inside CrudPanel...**

**But how else can we let developers add features to CrudPanel?**

### CODE REVIEW

**Comment by tswonke** [comment]
@OliverZiegler and I just talked about this. This would be a nice feature for us - makes some things simplier. But we share your concerns.

I think Oli will also comment on this :-)

**Comment by OliverZiegler** [comment]
as @tswonke says here I am :)

First of all, macroable can highly improve how packages can interact with CrudPanel and make many things easier for package developers I think.
So developing a package which provides some crud functionality we can add the methods we need via macro in our package service provider and can access them in every CrudController, in the views where we have `$crud` and so on.

I think your current example above is kind of misleading as macros are better seen as dynamic, app wide class decoration without extending/overriding classes 🤔 

## To your concerns:

To address the issue of "kicking out" macros by defining functions with same name in updates, we could think about overriding the `public static function macro($name, $macro)` of `Macroable` to check whether a function with `$name` already exists. If so we throw an exception and all users will see exceptions after updating as long as they didn't refactor.
In my opinion this is a straight forward way and we can take the inconveniences as breaking changes...

## More Ideas

To make CrudPanel more extendable and also remove the "God class" character I think about the following things (but some need more deeper testing and understanding on my side). This is just kind of a brainstorming 😉 

1. **Provide all functionality of CrudPanel via mixins**
As we (soon) have `Macroable` and require Laravel 5.5 we could also use the `public static function mixin($mixin)` to apply functionality to our CrudPanel. If we "remove" all the traits and add our own functionality via mixins, perhaps we could offer some kind of "namespaces" (e.g Read, Query kind of like the current trait names) and people can then override the mixin.

2. **Inject Interfaces into CrudPanel which can be bound in the Service Container**
Using auto injections for CrudPanel we can rely on the flexibility of the [laravel service container](https://laravel.com/docs/5.6/container). 
We only need to define the base functionalities we currently rely on as Interfaces which get injected into our CrudPanel and refactor the traits to "ServiceClasses" that implement these Interfaces.
Like described in [binding interfaces to implementations](https://laravel.com/docs/5.6/container#binding-interfaces-to-implementations) others can easily "swap out" the default implementation and use their own one or even extend current functionality with the decorator pattern like described [here](https://laravel.com/docs/5.6/container#extending-bindings).
I'm currently not sure what will happen if this gets called at multiple PackageProviders, but I will try to check this out.

3. **Using a Singleton (facade) CrudPanel and Facades for everything else**
Like I already implemented in #826 we could allow access to the CrudPanel via Facade and offer more functionality through other Facades. People can implement more Facades as they wish or extend the provided ones and exchange the binding.

**Comment by OliverZiegler** [comment]
Just for completeness. 
I opened an [issue](https://github.com/laravel/ideas/issues/1255) at laravel/ideas proposing the check for existing functions in `Macroable`.

**Comment by tabacitu** [comment]
Hi @OliverZiegler ,

0. We could totally do that - overwrite the ```macro``` method. Good idea. I'd rather _not_ overwrite Laravel methods unless we _have to_, so let's see what they say - maybe they'll support it out of the box.

1. Mixins would definitely be supported along with macros, but I'm not sure we should rewrite the current traits to mixins since traits are more intuitive, in my opinion. And... do we _really_ want people to be able to _swap_ CrudPanel functionality for something else? :-) I do see this useful for package developers, yes. But I'm afraid of how regular developers might use it to swap core functionality, then complain when we push breaking changes... Then again, we could just push it and not document it. Or create a separate documentation for package developers - so that only people who know what they're doing would be overwriting core functionality... this could be a nifty way to prevent it :-) (brainstorming here too) 

2. I see this as an alternative to rewriting to Mixins above, with the same caveat, same fix for it :-) I do think this is cleaner, though, and it would also allow us to define _properties_ too, not only _methods_. So you'd be able to really add new functionality to the CrudPanel class. For example, say Reorder was a new operation - it would have a Reorder service class that contains all methods it needs, but also the properties ($this->reorder, $this->reorder_label, $this->reorder_max_level). But how would we tell CrudPanel to use this extra Operation on CrudPanel? Cause the right place to mention this would be in the EntityCrudController. And would be able to call this a bunch of times, for Reorder, Clone, etc? I wonder...

3. I think ```CrudPanel::addColumn()``` is a better syntax than ```$this->crud->addColumn()```, even though it hides the actual process a bit... So I'm a little torn. On the one hand ```CrudPanel::``` is prettier, on the other hand what it _actually_ does 99.9% of the times is just ```$this->crud```, so it's just another layer that makes it more difficult to understand how Backpack works (less intuitive), for the sake of convenience. But it _is_ a prettier syntax, and I like it :-)

This is a big decision, on how to do this. Let me think about it some more and get back to you. My thoughts above might seem all over the place right now... and I expect they'll stay so until I actually put some code down for it... Thanks a lot for pitching in with all the options. I'll probably prototype a PR and link to it.

Cheers!

**Comment by tabacitu** [comment]
That's so true. Thank you @OliverZiegler - we CAN overwrite the ```macro()``` method to throw an error to let the user know his macro hasn't been registered :-) Thank you, just pushed this on this same branch.

I'll soon merge this into 3.5 - so CrudPanel will officially be macroable :D

**Comment by tabacitu** [comment]
Let's leave the Singleton / Service Container discussion for the 4.0 version - that's one place the rewrite can really stand out :-)

**Comment by OliverZiegler** [comment]
@tabacitu is there any (convenient) place to gather ideas for the 4.0 rewrite?

**Comment by tabacitu** [comment]
@OliverZiegler - convenient? No :-))

I think Github Issues will do. I’m in a closing spree, and aim to fix, merge, close or tag [3.5] or [4.0] every small issue & PR. So just write ```[4.0]``` in the issue name - that should be good enough :-)

**Pull request merged**
