### PR TITLE
Default user model is now the one in auth (fixes Class 'App\User' not found error when installing on Laravel 8)

### PR DESCRIPTION
**Pull request by tabacitu**
Because in Laravel 8+ the default User model has been moved from `App\User` to `App\Models\User`, by default when you install Backpack 4.1.x on Laravel 8, you won't be able to login - it'll throw a `Class 'App\User' not found` error (see https://flareapp.io/share/w5BBOwD5) 

This is a very bad first experience when installing Backpack. We should make it "_just work_" both on Laravel 6 and 7 (`App\User`) and on Laravel 8 (`App\Models\User`). _One way_ would be to just use the same config value in the `auth.php` file - which is what this change does.

_However_, using a config value in a different config file did not use to work, a while back. I was surprised it does, now that I tried it 😄 🥳 I wonder - what's the order? Maybe now Laravel loads its config files first, then the other ones? I don't know, but this would be a great non-breaking fix for this. Just want a second/third opinion before I merge it, to make sure we're not breaking anything. @pxpm ? @mahasadhu ?

Thanks a lot!

Addresses https://github.com/Laravel-Backpack/docs/pull/186

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @tabacitu 

I'd had some issues with using `config()` inside a config file before. 

From my browser history: https://blog.maqe.com/dont-use-laravel-s-config-inside-config-files-40e2c8207225

It's an old post but I think it still applys because the issue was with OS.

Let me know,
Pedro

**Comment by tabacitu** [comment]
Haha! Answers my question exactly, thank you @pxpm . Sooo.... if Laravel now loads config files by file name... `auth.php` will always be loaded before `base.php`... soo... it should be ok? Maybe?!

**Comment by pxpm** [comment]
Yes, it seems ok now because they sort the files by name. 

https://github.com/laravel/framework/blob/3e4f5f4b771fbdc12a10db1694d55c7c91441161/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L94

I'v checked and atleast since 6.X they do the sorting thing. 

Best,
Pedro

**Comment by tabacitu** [comment]
That's awesome, because that's what we currently support 😆 6.x, 7.x and 8.x

Ok then, merging!

**Comment by mahasadhu** [comment]
Well this is a new thing for me, even though after I checked this is a default behavior since 2017
https://github.com/laravel/framework/pull/21634/files

This could helps me prevent redundant values in my config files 😃 

Thank you @tabacitu @pxpm !

**Pull request merged**
