### PR TITLE
added view input field

### PR DESCRIPTION
**Pull request by nathanielks**
This PR adds a input field of type `view`. The idea here is to be able to add custom form inputs outside of what Backpack provides. The actual use case I am using this for is to add behavior buttons to one of my models. For example:

*resources/views/partials/send-password-reset.blade.php:*
```php
  <a href="{{ url($crud->route, [ $entry->id, 'send-password-reset']) }}" class="btn btn-primary ladda-button">Send Password Reset</a>
```

*app/Http/Controllers/Admin/UserCrudController.php:*
```php
class UserCrudController extends CrudController {

    public function __construct() {
        parent::__construct();

        // ... stuff ...
        $this->crud->addField([
            'name' => 'send-password-reset',
            'type' => 'view',
            'view' => 'partials/send-password-reset'
        ],'update');

       // ... more stuff ...
    }
}
```

Which gives us this!
screen shot 2016-09-09 at 4 55 30 pm

### CODE REVIEW

**Comment by tabacitu** [comment]
This is great, thanks for the work. Will merge as soon as I get to my computer.

Note: there are 2 other ways to do the same thing:

(1) create a view in your ```resources/backpack/crud/fields```; say ```address.blade.php```; that's what I've called a [custom field type](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types); then just use it as you would any other field; backpack loads any fields in that directory first, then if it doesn't find the name you gave it, it will search the same folder in vendor;

(2) use the [custom_html field type](https://laravel-backpack.readme.io/docs/crud-fields#custom_html-v207) and pass the view as a value; I saw someone use this trick, but I can't say I like it very much, I don't know why;

These options are not easy to spot in the documentation, still trying to figure out how to balance giving enough information to get users going _and_ letting them know of niche solutions like this one.

Cheers!

**Comment by guillermohaad** [comment]
hi friend nathanielks 

I am following the foot dela letter and testing your PR but I get this error in the image attached

error_pr

**Comment by tabacitu** [comment]
Thank you! Checked and merged, nice work!

I've also [added it to the documentation](https://laravel-backpack.readme.io/v3.0/docs/crud-fields#view).

Cheers and keep 'em coming :-)

**Comment by tabacitu** [comment]
@guillermohaad after swithing to the PR branch, you should also pull it. That's probably why you were missing the view file. It's definitely working now, run ```composer update``` and get Backpack/CRUD v3.1.3 - it should work. Please tell me if it still doesn't :-)

Cheers!

**Comment by guillermohaad** [comment]
Hi friend @tabacitu , 
update versions and effectively no longer displays errors.
But I must again follow the upgrade steps that made our @nathanielks friend?

So is my front-end atached image:
front-end user

**Comment by tabacitu** [comment]
That's odd - it shows the errors for me:
screen shot 2016-09-12 at 20 16 50

**Does it not show errors only for the User entity or for others as well** (Pages, Menu Items, Tags, etc)?

**Comment by nathanielks** [comment]
@tabacitu thanks man, I appreciate it! The main value for this I see is two-fold:

1. Not needing to add additional views to the vendor directory that Backpack doesn't own.
2. Gaining access to the $entity, $crud, and $field variables.

To my knowledge, the custom_html field didn't allow for #2 and #1is a nicety. Happy to contribute!

**Comment by guillermohaad** [comment]
According to my @nathanielks  friend, as I say, one! delicious contribution.

**Comment by guillermohaad** [comment]
@tabacitu , sorry, my English is not very good and creates confusion.
what I mean is that the button I add my @nathanielks friend does not appear in the user form.

Attached image
button sendpassword

**Comment by tabacitu** [comment]
Hi @guillermohaad ,

That button will only appear if you modify the UserCrudController to include it (add a view with a the button, then add the field to the CRUD). 

To test it works, you can create a new blade file, say ```resources\views\test.blade.php```:
```php
<h4>Testy <small>Test</small></h4>
```

And then in a CrudController add that field:
```php
        $this->crud->addField([
            'name' => 'test',
            'type' => 'view',
            'view' => 'test'
        ]);
```

Then in the CRUD's edit and update forms you should also see that content (Testy test).

Cheers!

**Comment by guillermohaad** [comment]
thanks frien @tabacitu ,  for teaching I'll try.

**Comment by tabacitu** [comment]
You know about [Hacktoberfest](https://hacktoberfest.digitalocean.com/), right? If you're interested, submit a few very small PRs... and get free swag? :-)

**Pull request merged**
