### PR TITLE
Add support for Eloquent Model events to fields

### PR DESCRIPTION
**Pull request by tabacitu**
### BEFORE - What was wrong? What was happening before this PR?

For `upload`, `upload_multiple` and `image` fields, you had to resort to Mutators in order to actually upload stuff to the disk, then save the filename to the database.

### AFTER - What is happening after this PR?

You can define stuff to happen when standard Eloquent Model events are triggered. For example, you can do:

```php
// using the ARRAY SYNTAX, define an array of events and closures
CRUD::addField([
    'name' => 'name',
    'events' => [
        'saving' => function ($entry) {
            $entry->name = strtoupper($entry->name);
        },
    ],
]);

// using the FLUENT SYNTAX, you can define the same array
CRUD::field('name')->events([
    'saving' => function ($entry) {
        $entry->name = strtoupper($entry->name);
    },
]);
// BUT you can also use the convenience method "on" to define just ONE event
CRUD::field('name')->on('saving', function ($entry) {
    $entry->name = strtoupper($entry->name);
});
```

It supports [all Eloquent events](https://laravel.com/docs/master/eloquent#events), but... the ones that make sense are just: ~~`retrieved`~~, `creating`, `created`, `updating`, `updated`, `saving`, `saved`, ~~`deleting`~~, ~~`deleted`~~, ~~`restoring`~~, ~~`restored`~~, and ~~`replicating`~~, because those are the events that actually take place inside the Create or Update operation.

You CANNOT register events that happen OUTSIDE this particular operation. I mean, you can, but they won't be run. For example it's no use doing stuff on the `deleting` event inside `setupCreateOperation()`... because `deleting` will never happen there, it will only happen inside the `Delete` operation.

----

You can, however, do this kind of general stuff inside the `setup()` method, which is run inside all operations. There, you can use standard Laravel syntax, for example:

```php
Monster::deleting(function ($entry) {
    // TODO: delete that entry's files from the disk
});
```

This is also a preferred way of doing stuf before / after an entry has been create/updated. We're going to instruct people to do this, instead of overriding the `store()` or `update()` methods. Either in `setup()` or `setupUpdateOperation()` or `setupCreateOperation()`.

### How did you achieve that, in technical terms?

Before we actually do the creating/updating inside `store()` and `update()`, we go through all fields, see if they have `events` defined and if so, register those events.

For the general way of adding model events, in `setup()`, we did nothing. It was already working, we just didn't think of it.

### Is it a breaking change or non-breaking change?

non-breaking

### How can we test the before & after?

Inside `CategoryCrudController::setupCreateOperation()` for example, you can do this:
```php
CRUD::field('name')->on('saving', function ($entry) {
    $entry->name = strtoupper($entry->name);
});
```

Before, this did nothing, it just added it to the field definition. 
Now, after you create/update the entry, the name should be uppercased.

## WHAT

What needs to be done next?
- [x] decide if we should use `when('saving', $closure)` or `on('saving', $closure)`... or both;
- [x] test & review
- [ ] docs

### CODE REVIEW

**Review by promatik — APPROVED** [review]
This is actually a great feature, this avoids a mutator, it is better to do mutators but sometimes it is unnecessary 🤷‍♂️ it would be nice if we could avoid an accessor too, maybe?

We would need the same closure logic from columns, on fields.

```php
CRUD::field([
    'name' => 'name',
    // accessor
    'value' => function ($value) {
        return preg_replace('/^.*(\w{4})(\w{4})(\w{4})(\w{4})$/', '$1-$2-$3-$4', strtoupper(str_replace('-', '', $value)));
    },
    // mutator
    'events' => [
        'saving' => function ($entry) {
            $entry->name = str_replace('-', '', $entry->name);
        },
    ],
]);
```

Any way, tested this one, all the events, and it's working good 👌

---

> _decide if we should use when('saving', $closure) or on('saving', $closure)... or both;_

I vote for `on` only, but I'm ok with both options too.

**Comment by promatik** [comment]
By the way @tabacitu, I noticed this may happen;

image

This is due to relations, I remember this was discussed before, I though it was solved ... maybe we should avoid triggering all this events?

**Comment by tabacitu** [comment]
1) I agree, we could make `value` a closure, to let devs have "inline accessors" too. Good catch, let's do it in v12.
2) How did you get that `saving/saved` triggered multiple times? Was it for the same Model or for separate models? Cause if it's for separate models... it's normal... right? 👀 or... is it? Please investigate, let's go a bit deeper to understand why/when this happens, and if it's a problem. You might be onto something here!

**Comment by tabacitu** [comment]
Hmmm how did you get that result? Where/when did you `dump()`?

**Comment by promatik** [comment]
@tabacitu you can add the following code on `ProductCrudController` on demo.

```php
CRUD::field('name')
    ->on('saving', function ($entry) {dump('saving');})
    ->on('saved', function ($entry) {dump('saved');})
    ->on('updating', function ($entry) {dump('updating');})
    ->on('updated', function ($entry) {dump('updated');})
    ->on('creating', function ($entry) {dump('creating');})
    ->on('created', function ($entry) {dump('created');});
```

The dumps will flash on screen for a second, prepare your print-screen shortcut 😅

`ProductCrudController` has one relationship, if you try to do this on `MonsterCrusController` you'll get something like this;

image

**Comment by promatik** [comment]
Btw, I'm pretty sure this was fixed on the relationship huge PR.
@pxpm please step by to confirm this ✌

**Comment by tabacitu** [comment]
Right. Just tested this and can confirm events are triggered multiple times for the main model, and this _might_ interfere with this new functionality. Tested after merging 4.2 into this branch so it's not fixed _yet_.

@pxpm did we have plans to fix this multiple-event-triggering now? What will it take?

**Comment by pxpm** [comment]
Hey @promatik and @tabacitu 👋 

I've sent PR #4020 to address the multiple event issue. @promatik was rigth, we had already solved this in that relationship branch. We would eventually get there as I compare that branch with current merged relationships features.

@promatik can you give your tests a re-run with the PR i've sent ? 

Thanks,
Pedro

**Review by promatik — APPROVED** [review]
@tabacitu, this is working flawless now 👌

**Comment by tabacitu** [comment]
Thank you! Added first draft docs here - https://github.com/Laravel-Backpack/docs/commit/ee0cbcb1f9ef7e10bcc3850dd3ab29e39caa6cc6

**Pull request merged**
