### PR TITLE
Non breaking fix for avatar dependency

### PR DESCRIPTION
**Pull request by promatik**
Related with https://github.com/Laravel-Backpack/CRUD/pull/3425.

This is super ugly with all the CSS inline 🙃
Anyway, it works, and I think it's non breaking, am I wrong?

Basically it places a CSS solution below the image, and if the image has any error, it is hidden.

### CODE REVIEW

**Comment by tabacitu** [comment]
It's totally a solution, but I think it only fixes one piece of the problem - if `placehold.it` is down, it'll not look broken. 
But I think we should go a bit further in fixing this - and remove the `placehold.it` dependency entirely. And we can't do that using this technique, we can only do that inside `backpack_avatar_url()` as a non-breaking change.

**Comment by tabacitu** [comment]
Ah ok now I get it. This is to have a fallback image, instead of hosting the images on `backpackforlaravel.com` as I suggested in https://github.com/Laravel-Backpack/CRUD/pull/3425#issuecomment-815531487

Oups - I get it now.

**Comment by promatik** [comment]
Exactly @tabacitu 😅
This a **permanent** solution for 4.1, even if `placehold.it` fails, this will keep the avatar working.

On 4.2 we can remove those dependencies.

Do you think we should merge this on 4.1?

**Comment by tabacitu** [comment]
Oh ok - now I get it. Sure, if it works 🤷‍♂️ It's better to have a failsafe then not to have it right? 😅

**Comment by pxpm** [comment]
@promatik I don't like the inline solution, but I agree with a 100% css solution instead of relying in some external service, be it placehold.it or backpackforlaravel.com to deliver such a tiny functionality.

I don't think this makes sense to merge in 4.2, as in 4.2 we can do BC and decide whatever we want to do, make it 100% CSS (but move it to a proper place) or keep using some external service to generate the message. 

I see this beeing a file that is easily ovewritten by user so our "fail-safe" plan might not be delivered to everyone. 

One thing I notice is that if you setup `placehold` as the user avatar, it will query: `https://placehold.it/160x160/00a65a/ffffff/&text=D`

If you setup `gravatar` as the user avatar, in case the email does not exist (in gravatar) it fallback to `placehold`, but the query url is different:  `https://i1.wp.com/placehold.it/160x160/00a65a/ffffff/&text=D?ssl=1` even if we pass the same placeholdit url in the fallback:

```php
return Gravatar::fallback('https://placehold.it/160x160/00a65a/ffffff/&text='.$firstLetter)->get($user->email);
```

Not sure if `i1.wp.com` is just a redirector. At the moment `placeholdit` still don't have a valid certificate, but the images are showing (as didn't happen before, where a certificate issue was raised).

Maybe they fixed the issue and now it works with/without https ?

**Comment by promatik** [comment]
@pxpm first I though this was an easy fix for 4.1 ONLY, so, by merging this we would provide a solution forever on 4.1.

Now I start to think this should be also provided on 4.2.
This solution should be the default fallback to gravatar, it works everywhere/forever, independently of any CDN or avatar API.

I end up not understanding what you think about it, please let me know 😅

**Review by pxpm — APPROVED** [review]
This works as expected! On image error, the css is loaded instead!

Perfect!

**Pull request merged**
