### PR TITLE
[feature] column "year"

### PR DESCRIPTION
**Pull request by JayAhrDE**
I needed a column to show just the "year" from (year-)mysql-column.

Existing 'date' column just showed the year formatted as '1. January 2016', soooo...

... I created a copy using fixed format 'Y'. No magic at all.

If you want to add, do so. If I just missed the correct way of creating a year column, thanks for pointing out to me! :)

### CODE REVIEW

**Comment by tabacitu** [comment]
Thanks for the contribution, @JayAhrDE. I think including it will be useful for some use cases, yes. 

@OwenMelbz , @MarcosBL  - what's your opinion on this? Corner case or ok to include? Keep in mind if we include it, _we can't take it back_, we'd be breaking people's projects.

Cheers!

**Comment by OwenMelbz** [comment]
Hmm tricky! As sure I can see people might have a need for it, however would having something's that more latavelly be better suited as a whole?

getYearAttribute() not be more universally useful for the application as a whole, if this data is needed then it should be retrievable by a proper method. That way you can just use entry->year to display it? Or does doing this instead have its pit falls?

**Comment by MarcosBL** [comment]
I'm new here, but corner case IMHO

Isn't this what `model_function` is for ?

In Controller

````php
[
   // run a function on the CRUD model and show its return value
   'label' => "Year", // Table column heading
   'type' => "model_function",
   'function_name' => 'getYear', // the method in your Model
],
````
In Model

````php
public function getYear() {
   return \Date::parse($this->yourdate->format('Y');
}
````

Easy peasy!

**Comment by tabacitu** [comment]
See? This is why I asked :-) You guys make a valid point, thanks for pitching in.

@JayAhrDE - these guys have me convinced. Since it's a pretty corner case and there's a more general approach for this, I won't be merging this PR, sorry.

I hope this doesn't discourage you from submitting other PRs and contributing to the project. It's usually better to first propose the PR on a GitHub issue, to talk about it first and make sure the team agrees it's a feature to be included. Then do the work of submitting it, which (I know) can be a pain, at least at first. 

Thanks for submitting your work, see you in the Issues section :-)

Cheers!

**Comment by JayAhrDE** [comment]
No problem, and next time it will be less pain so I'm happy with the extra work. ;)

Me personally will stick to the year column anyway, needing it throughout multiple models. Probably simply a rather different use case.

Thx for all the good work, maybe I can contribute at another point one day! ;)

**Comment by MarcosBL** [comment]
Just a side note, I think it's perfectly normal to include custom columns, I have ~ 20 in my first Backpack project, for example to include info from 3+ fields into a single one and things like that. 

There are a lot of admin packages out there, even some with WYSIWYG definitions, but what I really like of Backpack is the customization it allows, and the fact of **everything** being able to override, cheers for trying a custom solution that works !

**Pull request closed without merging**
