### PR TITLE
Fix for elements on long dropdowns being cut off

### PR DESCRIPTION
**Pull request by promatik**
Possible fix for: https://github.com/Laravel-Backpack/CRUD/issues/2945.

This is a very simple and easy way to fix the problem, I avoided Javascript to solve this since it has the downside of adding an extra layer of logic and another thing to maintain, here is the result;

- CRUD table with one entry _(Column visibility button)_
image

- CRUD table with 10+ entries _(Column visibility button)_
image

- CRUD table with one entry _(Language picker dropdown)_
image

- CRUD table with 10+ entries _(Language picker dropdown)_
image

Since this solution uses no Javascript, it is "dumb", it doesn't know when it could use more space or not. And CSS alone is not enough to solve this, because the max sizes are relative to the table height, not the page height.

@tabacitu and @pxpm, do you think this solution is enough, or should we add the javascript layer to optimize the space usage?

### CODE REVIEW

**Comment by pxpm** [comment]
Is there something we can do to make scrollbars visible in macos by default ?

https://stackoverflow.com/questions/7855590/preventing-scroll-bars-from-being-hidden-for-macos-trackpad-users-in-webkit-blin

**Comment by promatik** [comment]
@pxpm as far as I know, we can override the default scroll bars, give it some style and it would become always visible.

But, you can't style for mac os only, so this styles would become general, and I don't like the idea of changing everyone's scrollbars (windows/linux/?) to a opinionated style, and just for this two components.

Maybe we can use javascript to style it just for mac, does it worth it?

**Comment by pxpm** [comment]
I agree, if there is not easy way to only force visibility for macOS users we should NOT override the the bar for every OS.

I am not sure, and have no way to test it, but from my research I found out that for macOS users, forcing the scrollbar visibility without changing the style is possible if we programmatically `scroll one pixel down and one pixel back up` when we open the dropdown, so it will show the bar by default (like windows/linux users) ?

https://stackoverflow.com/a/14936704

```javascript
var el = document.getElementById('scrollable-section');
el.scrollTop = 1;
el.scrollTop = 0;
```

It's a shame if we can't easily fix it because I think it's unintuitive and unexpected behaviour, but I am not going to hold on this as I think the problem solved by this PR is way bigger/more important than the problem with macOS bar. (technically it still works).

I am also not totally happy with the fact that it's "unresponsive", but that is something I think we can add later.

Best,
Pedro

**Review by pxpm — APPROVED** [review]
I'v added my concerns in a previous comment. 

Non of them are mergin-breakers so I am approving this as is.

**Comment by tabacitu** [comment]
Whoohoo! 🥳 Great then, merging. I agree with you guys - not worth forcing the scrollbar to show on Mac OS. Not only because it's a bit nasty from a developer's perspective, but also because it isn't pretty 😄 And it isn't the default, so it's different from what Mac users are expecting (I think).

I'm glad to have this fixed. Good job @promatik !

**Pull request merged**
