### PR TITLE
[4.0][Feature][Ready] Multi_select field type

### PR DESCRIPTION
**Pull request by AbbyJanke**
Instead of just a dropdown/single column for selecting columns this is a new take on it having multiple columns where you "click" on the option and it transfers it to a second column and vice versa.

- Supports arrays, models, and pivots
- Option for "searching" each list

#### Example:
screen shot 2018-05-13 at 4 52 50 pm

#### Code Example
```
[
   'name' => 'tags',
   'label' => 'Tags',
   'type' => 'select2_cols',
   'model' => 'App\Tag',
   'attribute' => 'name',
   'entity' => 'tags',
   'pivot' => true,
   // 'searchable' => false,
   // 'options' => ['test', 'test2', 'test3'],
]
```

In the end its a basic select2_multiple field just with a fancy look/feel that may better suite some needs.

### CODE REVIEW

**Comment by AbbyJanke** [comment]
There are arguments among myself if it should be called "select2_multiple_cols" or something similar since it only seems useful on multiples and not single selects but in the end chose 'select2_cols' for shortness sake.

**Comment by OwenMelbz** [comment]
😁 does it have anything to do with select2?

If not, I don’t see what’s wrong with just “multi_select” ?

**Comment by tabacitu** [comment]
Hi @AbbyJanke ,

This looks great. 

I agree with @OwenMelbz on this one - since [the JS plugin is called "multi-select"](https://github.com/lou/multi-select), I think we should name the field ```multi_select``` too. More intuitive that way, for people that are already familiar with multi-select. Also, it would be consistent with other field names (select2, ckeditor, tinymce, summernote, etc).

Thanks, cheers!

**Comment by tabacitu** [comment]
Just tested it and pushed a few updates to this PR - just making sure the CSS/JS assets are loaded from the correct location and renaming the file to ```multi_select```.

However, I see that ```searchable``` doesn't work, and there are some small JS errors triggered upon click. I think I'll get to take another looks in a few days.

Thanks again @AbbyJanke ! Cheers!

**Comment by tabacitu** [comment]
Video here: https://cl.ly/3v2h2U1Y0d17

**Comment by AbbyJanke** [comment]
Alrighty, so Issue with the search was that I failed to include the "quicksearch" plugin that is required, added that which solved both the console errors you saw. Renamed the file to multi_select.

Video: https://cl.ly/1a330H2y3F3e

**Comment by AbbyJanke** [comment]
Idea for some better clarification to show which is "selected" and which is not.
 
screen shot 2018-05-14 at 3 27 43 pm

```css

          .ms-container .ms-selectable li.ms-elem-selectable:after,
          .ms-container .ms-selection li.ms-elem-selection:after{
            font-family: FontAwesome;
            font-weight: normal;
            font-size: 1rem;
            font-style: normal;
            padding-top: 2px;
            right: 10px;
            position: absolute;
            text-decoration:none;
          }
          .ms-container .ms-selectable li.ms-elem-selectable:after{
            content: '\f067';
          }
          .ms-container .ms-selection li.ms-elem-selection:after{
            content: '\f068';
            padding-top: 4px;
          }
```

**Comment by tabacitu** [comment]
giphy


Thank you @AbbyJanke . I've just added the :after CSS too - I think it's way more intuitive with +/- icons.

**Also, I've added back the nestedSortable css&js. I see you've removed it - I figured it was by accident. Let me know if it was intentional and I should remove it again.** As far as I know, nestedSortable _is_ used in other places, most importantly in the "reorder" crud functionality.

Thanks, cheers!

PS. Tested and re-tested this field. Works like a charm, so it's ```ready``` to be merged. The only thing I've found that isn't perfect about it: its keyboard shortcuts are not that intuitive. I expected "enter" ("return") to select an item, but it doesn't, "space" does. It's the plugin's fault, so... hey ho.

**Comment by AbbyJanke** [comment]
@tabacitu any thoughts on when we will get this merged in?

**Comment by tabacitu** [comment]
Hmm... no idea why this PR is still open. The feature got merged & launched some time ago, in Backpack 4.0. You can find it in the docs as [the ```select_and_order``` field](https://backpackforlaravel.com/docs/4.0/crud-fields#select_and_order). Closing the PR since it's no longer needed.

Once again - kudos to @AbbyJanke for the PR. Thank you so much!

**Pull request closed without merging**
