### PR TITLE
[Feature][WIP] Layout field type

### LINKED ISSUE #1873: [4.0][Feature] Drag-and-drop page builder field type aka layout field type
It should:
- allow admins to resize columns
- allow admins to add blocks of different types (which could contain multiple fields)
- allow admins to reorder move said blocks
- store contents as JSON in a hidden input
- use a clear and simple hierarchy for the JSON, so that it can be easily converted into HTML blocks, either Bootstrap 4 (provided), 3, Bulma,  Tailwind or whatever’s next

I don’t think it’s important to have the fields visible at all times. I’d rather have them shown in a modal upon block click. That should keep the create/update form clean.

WIP.

### PR DESCRIPTION
**Pull request by tabacitu**
Fixes #1873

### CODE REVIEW

**Comment by tabacitu** [comment]
It should:

- allow admins to resize columns
- allow admins to add blocks of different types (which could contain multiple fields)
- allow admins to reorder move said blocks
- store contents as JSON in a hidden input
- use a clear and simple hierarchy for the JSON, so that it can be easily converted into HTML blocks, either Bootstrap 4 (provided), 3, Bulma, Tailwind or whatever’s next

I don’t think it’s important to have the fields visible at all times. I’d rather have them shown in a modal upon block click. That should keep the create/update form clean.

**Comment by tabacitu** [comment]
Todo:
- [ ] remove blocks from Backpack
- [ ] add docs with how to use
- [ ] add example blocks to gist
- [ ] add example blocks in documentation

**Comment by tabacitu** [comment]
Note: the "multiply" field type has also been included in this PR https://github.com/Laravel-Backpack/CRUD/pull/2266 , renamed as "repeatable". I think that's a better name for it, and I think it's better to release the "repeatable" field first, and then maybe release this "layout" field (still not sure if it should be a separate package or part of the main Backpack repo).

**Comment by oddvalue** [comment]
What's the status of this feature? Is it likely to be added to a release any time soon? We have a project coming up that could **really** benefit from it.

**Comment by tabacitu** [comment]
Sorry @oddvalue but we haven't found the time to polish this and move over to v4.x yet. It shouldn't be too difficult, but currently we're in a feature freeze - we're only fixing bugs for v4.1.x. Only after we're done with that will we be looking to polish/finish/implement new features for v4.2 / v12. So it won't receive any love in the next 1-2 months, sorry.

**Comment by tabacitu** [comment]
Update: it looks like making this work on Backpack v4.x won't only require changing CSS classes from Bootstrap 3 to Bootstrap 4. Mark says:

> One problem I ran into. Every time I add a column with a block the page needs to be saved first. Otherwise CKEditor is nog working. After saving it works fine. Also when I add two columns and I save only one column is saved.

So it looks like part of the functionality is broken. Maybe the difference in classes affects the JS too? Idk. But it's good to keep that in mind.

---

Also, while we're at it. This field type should probably be delivered as a 1stparty addon. So `backpack/layout-field`. Because:
- I expect A LOT of talk around it, so it's best to separate that from the main package.
- Not everyone will need it. In fact, I'd argue most devs won't use it. So it's better to not have it at all.

**Comment by de-raaf-media** [comment]
Hi @tabacitu. Any updates on this?

**Comment by tabacitu** [comment]
Decided we're not gonna do this for now - too much to maintain for now, for too little demand. 
I still want a solution for this, but I don't think this is it.

When we do this, we'll probably do it as an add-on, so I'm going to close this PR.

**Pull request closed without merging**
