### PR TITLE
add base chinese language

### PR DESCRIPTION
**Pull request by lucksevenl7**
add base chinese language translation

### CODE REVIEW

**Comment by lloy0076** [comment]
Thank you for providing this - I'm not able to comment too well on the actual translation(s) themselves as I cannot read Chinese (simplified or otherwise) however translate.google.com seem to indicate that the ones I did check were correct.

There does seem to be the `zh-CN` vs `zh-cn` issue though - @tabacitu.

**Comment by lucksevenl7** [comment]
backpack is good frame to build a adminpanel. about  zh-CN and zh-cn ,i don't kown well,so add all..

**Comment by tabacitu** [comment]
Hi @lucksevenl7 ,

Thanks for the PR, but the ```base``` language file should sit inside the [Backpack\Base package](https://github.com/laravel-backpack/base), not CRUD. I see there are already ```zh-cn``` and ```zh-hant``` translations there. Please submit a PR there if you're unhappy with the translation, and we'll call upon other Chinese speakers to pitch in. Just like @lloy0076 - I don't speak Chinese, so I can't have an opinion on that :-)

Cheers!

**Comment by lucksevenl7** [comment]
hi @tabacitu , thank you , i first time PR.. sorry.  hope this project better.

**Pull request closed without merging**
