### PR TITLE
ensure table column works with associative arrays too

### PR DESCRIPTION
**Pull request by pxpm**
refs: #2635 

Problem: Using table column to display a single array of values.

Solution: As is expected by table column, we ensure to provide a multi-dimensional array when developer provide a single array. 

If I understood code correctly, only when the field is not casted as array we endup with an object as value because of the `json_decode`, forcing `true` as a second parameter we ensure an `array` output instead of `object`. 

So we migth be able to remove the conditional check for `is_object()`.

### CODE REVIEW

**Comment by promatik** [comment]
@pxpm I tested this, and it's braking the current table.
Maybe here it should be a different sign(?) `count($value) !== count($value, COUNT_RECURSIVE)`

Also, can you give me an example where we can use a field to create an associate array so I can test that part?

image

image

**Comment by iMokhles** [comment]
@promatik i tested it and it works

normal table 2 json
Capture d’écran 2020-12-13 à 04 25 28

normal table 1 json
Capture d’écran 2020-12-13 à 04 28 09

associative array
Capture d’écran 2020-12-13 à 04 26 11

how did you save your array and which php version you have !

**Comment by pxpm** [comment]
ping @tabacitu @promatik 

Merged 4.2 here, fixed conflicts. 

This is a NON-BC I think, let me know if I am wrong.

Pedro

**Comment by tabacitu** [comment]
If it's non-BC and a SHOULD (not a MUST) then it's a problem for future us. Moving to 4.2.x. Let's focus on the 4.2 launch please, we have more important things to finish.

**Comment by tabacitu** [comment]
@pxpm this column will soon be moved to `backpack/pro`, so please take another look at this, test it and tell me if this is 100% a non-breaking change and I can merge it. If not, we leave it for future us (after we launch 4.2).

Thanks!

**Comment by pxpm** [comment]
@tabacitu I've done the required changes to make this non-BC and solve the problem we are trying to solve here.

So before table would work if:
- You gave it a json string 
- You gave it a multidimensional associative array

After it works:
- You gave it a json string 
- You gave it a multidimensional associative array
- You gave it a single associative array

I've removed the need to check for `is_object` in html by adding the second parameter to `json_decode($var, true)` that forces to decode nested objects too, and by casting to array `(array) $obj` in case developer passed an object.

AFAIK nothing breaks, a good and easy way to test is by adding the `features` column in `Product` crud, that has a `table` field. 
```php
   CRUD::addColumn([
       'name' => 'features',
       'type' => 'table',
       'columns' => ['name' => 'name', 'desc' => 'desc']
   ]);
```

If you want to test the other scenarios too you can pass them in column `'value' => function($entry) {}`

**Review by promatik — APPROVED** [review]
Tested, everything is working and I think this is a non breaking change 🙌

There was only one situation that was not covered by the validations, it was the case the user sent an array of objects, something like; 

```php
'value' => function ($entry) {
    return [
        (object) ['name' => '1', 'desc' => 'a'],
        (object) ['name' => '2', 'desc' => 'b'],
    ];
},
```

But this can't happen by the normal usage of the field (save/retrieve).

**Pull request merged**
