### PR TITLE
fixes #1488 fakes with casts

### LINKED ISSUE #1488: Errors if cast json field to array as Docs say
I tried to seek help on the gitter chatroom earlier and decide to report this bug

Copy of the chat logs:
Hi, I'm trying to addField (for a json field) and I keep getting:

json_decode() expects parameter 1 to be string, array given

my field is casted as array of course as the docs recommend
Any idea what's wrong?
If I remove the cast to array in my model, it works!
That runs against the docs so I am confused

Z @ziming 00:06
Anyone here?

Abby @AbbyJanke 00:34
@ziming can you post some code either here or to a gist so we can take a look?

Z @ziming 00:54
Thanks Abby. Here you go.
In my model I cast shop_information to array as seen here
https://cl.ly/segJ

Then in my CrudController my addField I have the following fake field
https://cl.ly/seyg

But when I am in list view or edit view, I will get an error
Here is a screenshot of the logs
https://cl.ly/sesx

Abby @AbbyJanke 00:57
what type of field are you looking for? just a plain text?

Z @ziming 00:57
https://cl.ly/sf6r

my shop_information field is a json field
name is 1 of the fields in that json field
**Reading the docs, it says if my json field is not named 'extras' I must cast it as array**
which I already did. All my json fields are cast as array before using backpack
Yet it give me this error
When I remove the cast to array, the error dissapear and everything works fine in backpack but other parts of my codebase requires my json fields to be cast as array.
The backpack docs itself said so too:

https://cl.ly/sdun

Abby @AbbyJanke 01:34
public function getShopInformationAttribute($value) {
      return json_encode($value);
    }
if you add that to your model it will fix it for now.

Z @ziming 01:35
Problem is other parts of my codebase... expect an array back
various other json related packages such as spatie/schemaless also expect json fields to be casted as array

My backpack/crud is "backpack/crud": "^3.4". I only installed backpack today

I have protected $fakeColumns = ['shop_information']; too in my model too

[2018-06-30 17:47:41] local.ERROR: json_decode() expects parameter 1 to be string, array given {"userId":1,"email":"some@example.com","exception":"[object] (ErrorException(code: 0): json_decode() expects parameter 1 to be string, array given at /Users/my-name/php-apps/my-app/vendor/backpack/crud/src/CrudTrait.php:82)

### PR DESCRIPTION
**Pull request by tabacitu**
Fixes #1488 in a different way than #1362

### CODE REVIEW

**Comment by tabacitu** [comment]
There are a bunch of ways to getting an attribute:
```php
$this->getAttribute($column));
$this->attributes[$column]);
$this->{$column});
```

If the attribute (say... ```extras```) is NOT cast as anything, they all output the same thing:
```
string(112) "{"number_with_prefix":null,"number_with_suffix":null,"text_with_both_prefix_and_suffix":"122","fake_table":null}"

string(112) "{"number_with_prefix":null,"number_with_suffix":null,"text_with_both_prefix_and_suffix":"122","fake_table":null}"

string(112) "{"number_with_prefix":null,"number_with_suffix":null,"text_with_both_prefix_and_suffix":"122","fake_table":null}"
```

If the attribute (say... ```extras```) IS cast as array/object, the output is totally different:
```
array(4) {
  ["number_with_prefix"]=>
  NULL
  ["number_with_suffix"]=>
  NULL
  ["text_with_both_prefix_and_suffix"]=>
  string(3) "122"
  ["fake_table"]=>
  NULL
}

string(112) "{"number_with_prefix":null,"number_with_suffix":null,"text_with_both_prefix_and_suffix":"122","fake_table":null}"

array(4) {
  ["number_with_prefix"]=>
  NULL
  ["number_with_suffix"]=>
  NULL
  ["text_with_both_prefix_and_suffix"]=>
  string(3) "122"
  ["fake_table"]=>
  NULL
}
```

In short:
- ```$this->attributes[$column]``` gets the value BEFORE the cast has been applied;
- ```$this->getAttribute($column));``` and ```$this->{column}``` gets the value AFTER the cast has been applied;

In this case, we definitely prefer BEFORE.

**Comment by tabacitu** [comment]
Yeah, no. Remember when I said we don't need to check if the attribute is set? We do. Desperately. Otherwise it will fail when no fake column is present. Good think we have unit tests.

Added on master. Issue is really closed now.

**Comment by OliverZiegler** [comment]
@tabacitu Unfortunately this introduced an issue with translations. see the reference

**Comment by tabacitu** [comment]
Thank you @OliverZiegler ! On it!

**Comment by OliverZiegler** [comment]
@tabacitu I'm currently preparing a PR

Just implementing unit tests for this at the moment ;)
@tswonke and me already have a fix 😊

**Comment by OliverZiegler** [comment]
@tabacitu see #1548 for the fix.

Working on the unit tests to verify every edge case will work 😉

**Pull request merged**
