### PR TITLE
use reflection to work with php enum classes

### PR DESCRIPTION
**Pull request by pxpm**
Make the enum field consistent by always using `ReflectionEnum` on PHP Enums. 

Removes a bit of dead code reported in https://github.com/Laravel-Backpack/CRUD/pull/4735

The code is now more readable and removed the corners in `Backed` vs `Unit` enums.

### CODE REVIEW

**Comment by susanu** [comment]
Can i make a suggestion here?

If this is used inside a ```relationship``` field, then try to guess the enum class from the relationship model, not the base model.

Example:
```
// inside the Person model
public function companies()
{
    return $this->belongsToMany(\App\Models\Company::class)
                ->withPivot('job_title', 'job_description');
}
// Inside PersonCrudController
[
    'name'          => 'companies',
    'type'          => "relationship",
    'subfields'   => [
        [
            'name' => 'job_title',
            'type' => 'enum',
            'wrapper' => [
                'class' => 'form-group col-md-3',
            ],
        ],
        [
            'name' => 'job_description',
            'type' => 'text',
            'wrapper' => [
                'class' => 'form-group col-md-9',
            ],
        ],
    ],
]
```
With the current behavior, the field will try to guess the enum class from the ```Person``` model, not the ```Company``` model.

Proposed code:
```
{{-- enum --}}
@php
    $entity_model = $field['baseModel'] ?? ($field['model'] ?? $crud->model);
    $fieldName = str(square_brackets_to_dots($field['name']))->afterLast('.')->toString();
    $field['value'] = old_empty_or_null($field['name'], '') ??  $field['value'] ?? $field['default'] ?? '';

    $possible_values = (function() use ($entity_model, $field, $fieldName) {
        // if developer provided the options, use them, no ned to guess.
        if(isset($field['options'])) {
            return $field['options'];
        }

        // if we are in a PHP version where PHP enums are not available, it can only be a database enum
        if(! function_exists('enum_exists')) {
            $options = $entity_model::getPossibleEnumValues($fieldName);
            return array_combine($options, $options);
        }

        // developer can provide the enum class so that we extract the available options from it
        $enumClassReflection = isset($field['enum_class']) ? new \ReflectionEnum($field['enum_class']) : false;

        if(! $enumClassReflection) {
            // check for model casting
            $possibleEnumCast = (new $entity_model)->getCasts()[$fieldName] ?? false;
            if($possibleEnumCast && class_exists($possibleEnumCast)) {
                $enumClassReflection = new \ReflectionEnum($possibleEnumCast);
            }
        }
        
        if($enumClassReflection) {
            $options = array_map(function($item) use ($enumClassReflection) {
                return $enumClassReflection->isBacked() ? [$item->getBackingValue() => $item->name] : $item->name;
            },$enumClassReflection->getCases());
            $options = is_multidimensional_array($options) ? array_merge(...$options) : array_combine($options, $options);
        }

        if(isset($field['enum_function']) && isset($options)) {
            $options = array_map(function($item) use ($field, $enumClassReflection) {
                if ($enumClassReflection->hasConstant($item)) {
                    return $enumClassReflection->getConstant($item)->{$field['enum_function']}();
                }
                return $item;
            }, $options);
            return $options;
        }

        // if we have the enum options return them
        if(isset($options)) {
            return $options;
        }

        // no enum options, can only be database enum
        $options = $entity_model::getPossibleEnumValues($fieldName);
        return array_combine($options, $options);
    })();
    

    if(function_exists('enum_exists') && !empty($field['value']) && $field['value'] instanceof \UnitEnum)  {
        $field['value'] = $field['value'] instanceof \BackedEnum ? $field['value']->value : $field['value']->name;
    }
@endphp

@include('crud::fields.inc.wrapper_start')
<label>{!! $field['label'] !!}</label>
@include('crud::fields.inc.translatable_icon')
<select
        name="{{ $field['name'] }}"
        @include('crud::fields.inc.attributes')
>

    @if ($entity_model::isColumnNullable($fieldName))
        <option value="">-</option>
    @endif

    @if (count($possible_values))
        @foreach ($possible_values as $key => $possible_value)
            <option value="{{ $key }}"
                    @if ($field['value']==$key)
                        selected
                    @endif
            >{{ $possible_value }}</option>
        @endforeach
    @endif
</select>

{{-- HINT --}}
@if (isset($field['hint']))
    <p class="help-block">{!! $field['hint'] !!}</p>
@endif
@include('crud::fields.inc.wrapper_end')
```

**Comment by pxpm** [comment]
Hello @susanu thanks for the suggestion.

It's indeed a very good one for a very valid use case. 

I've used the same concept you suggested, but applied it a bit different, otherwise it would fail for nested relationships like `HasOne/MorphOne` where you could define the fields using `dot.notation`.

I've just updated the PR to take into account your suggestions. If you give it a try let me know if you find something broken. 🙏 

Cheers

**Comment by tabacitu** [comment]
@jorgetwgroup could you take a look at this, please? I feel like we need to merge this, it's a bug fix.

**Comment by jorgetwgroup** [comment]
Hi @pxpm this take me long to understand and test.

As you say need to still be working and i see this is working.

I add to Dummy a product relationship with pivot

Screenshot 2022-11-09 at 20 46 16

Add field

Screenshot 2022-11-09 at 20 44 57

And is working normally.

Screenshot 2022-11-09 at 20 44 44

Please let me know if i miss something.

Ready to merge.

Cheers.

**Pull request merged**
