### PR TITLE
make views row class configurable

### PR DESCRIPTION
**Pull request by iMokhles**

### CODE REVIEW

**Comment by iMokhles** [comment]
i really like to center forms 
So by making row class configurable developers will be able to pass at least ( justify-content-center ) or any other classes.

here's my example:
BEFORE:
Capture d’écran 2020-04-21 à 01 46 14
AFTER:
Capture d’écran 2020-04-21 à 01 45 57
hope you find it handy ;)

**Comment by tabacitu** [comment]
Hi @iMokhles ,

Excellent PR - very clean.

I'm wondering - couldn't you have achieved the same thing by putting ```justify-content-center``` on the existing ```contentClass```? [Docs here](https://backpackforlaravel.com/docs/4.0/crud-how-to#change-the-content-class-for-an-operation). As far as I know all operations have only one element inside this wrapper, so I _think_ it was possible before this change too.

**Comment by iMokhles** [comment]
yes i tried to pass justify-content-center to contentClass but it doesn't work :( 
Capture d’écran 2020-04-21 à 16 10 40

**Comment by pxpm** [comment]
Could you try with: `col-offset-md-2 col-md-8`

**Comment by iMokhles** [comment]
it doesn't work :( 
i tried to change it through the crud config file but the changes didn't apply i had to use the manual change
Capture d’écran 2020-04-21 à 19 09 16
i was able to achieve my goal to center the cards by passing justify-content-center with the row class itself
Capture d’écran 2020-04-21 à 19 11 48

**Comment by tabacitu** [comment]
Apparently in Bootstrap 4 it's ```offset-md-2```. I can confirm this works:
Screenshot 2020-04-22 at 08 09 00
Screenshot 2020-04-22 at 08 08 18

So we already have a solution for this, built-in. Thanks for the PR @iMokhles but in this case I'll close the PR without merging it - no point in adding this feature if we can already do it ;-) Sorry for the time you spent putting together the PR - but it's appreciated nonetheless.

Cheers!

**Pull request closed without merging**
