### PR TITLE
Fixes #784 for ajaxtables

### LINKED ISSUE #784: latest update 3.2.13 breaks the model_function column
Just updated to CRUD 3.2.13 and now it requires to have 'name' for column model_function.

This was working fine previously and doc doesn't mention this new requirement.

### PR DESCRIPTION
**Pull request by alashow**
fixes #784, for ajaxtables.

### CODE REVIEW

**Comment by lloy0076** [comment]
Can we do *something* other than *nothing* if we ifnd something that is rejected?

**Comment by alashow** [comment]
@lloy0076 like what?

**Comment by lloy0076** [comment]
Oh, logging at an error or at least info level (`console.info` or `Log::info`) might be appropriate. The worst thing is if something just "doesn't work" and there's no clue as to why.

**Comment by alashow** [comment]
I agree. I had a bad time when I was using `model_function` and the column I set in `name` was null (#758). Had to use copy custom `model_function` so it won't reject it or [this](https://github.com/alashow/CRUD/commit/c1aed23bc7e8bbdb84da6e415aea48a7166e0d88).

**Comment by tabacitu** [comment]
Hi @alashow ,

Thanks a lot for the PR. I can confirm your solution works, but since that whole part has been rewritten in 3.3 on the ```upgrade``` branch, that's no longer an issue, so I can't merge the PR.

I tested and re-tested and you won't have the same issue when we launch the brand-new ajaxdatatables on the ```upgrade``` branch, later this week ;-)

Thanks, cheers!

**Comment by alashow** [comment]
No worries. This works for me now.

Can't wait for that upgrade!
I have made customizations and fixes on my branch. I will need to do some manual merges though...

**Comment by alashow** [comment]
@tabacitu I have a question.

Can you check whether column ordering/sorting works correctly in the rewrite? Because in current version it sorts by next column (i.e if I click sort button on the first column, it will actually sort by the second one).

I kinda remember finding an issue related to this bug before, but I couldn't find it now.

**Comment by tabacitu** [comment]
Yup, fixed that one too! :-)

**Comment by shamatov** [comment]
Hi @tabacitu ,

I am experiencing the same faulty behavior on v3.3.1. The last version that works for me is 3.2.12.
Is the fixed/rewritten section still to be released?

Thanks!

**Comment by tabacitu** [comment]
@shamatov , I'm sorry to hear you're having this problem again. As far as I know this issue has been fixed and confirmed in 3.3.1 - which is currently the latest Backpack version.

How does the issue manifest itself? Do you still have problems if you give a "name" to your model_function column? Feel free to open another issue for this if you're still having it.

Cheers!

**Pull request closed without merging**
