### PR TITLE
removed data tables live control package and fixed the ajax table trait

### PR DESCRIPTION
**Pull request by indra1**
- I removed \LiveControl\EloquentDataTable\DataTable library that was failing for model functions and ordering the table
- created getEntriesWithConditions in the Read trait. The method receives these arguments 
```
$length = null,
$skip = 0,
$orderBy = null,
$orderDirection = 'asc',
$filter = null
```
The function returns the entries with the conditions stated. Any pf them can be skipped

- still working on ordering and searching through entries generated by a model function

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @indra1 ,

It seems there are a lot of unnecessary files in this PR (a total of 7267 files) - have you accidentally included the vendor folder too? Can you take it out?

Cheers!

**Comment by tabacitu** [comment]
Hi @indra1 ,

Any news on bringing this PR up-to-date? Would love to merge it this week.

Cheers!

**Comment by tabacitu** [comment]
Seems to me like the last 3 commits have been pushed by mistake. Right? 

If I remove the last 3 commits, will the AjaxDatatables still work, or have you pushed any fixes along with those 3 commits?

Cheers!

**Comment by indra1** [comment]
Hey,

Yeah, the extra commits where because I needed to use that package in my project to test that all it's fine and I ended up following a semi-bad tutorial and one was a bug fix. I have some time tomorrow so I'll fix everything and let you know.

**Comment by tabacitu** [comment]
Ping :-)

**Comment by indra1** [comment]
Doing it now.

**Comment by tabacitu** [comment]
OMG OMG OMG. Great. I'll leave you be :-)

**Comment by stygiansabyss** [comment]
What is the progress on this?

**Comment by indra1** [comment]
@stygiansabyss , @tabacitu was going to merge the fixes. 
I am now working on making the order by relationship work.
As of now order by date works and model functions don't give errors anymore. 
The next step after ordering by a relationship would be to make order by model function work. That will be the most difficult.

**Comment by tabacitu** [comment]
Hi @indra1 ,

Just fixed the merge conflicts and merged this into a feature branch (found no better way to do it). I started a PR from it to the ```dev``` branch and the plan is to test every little thing that was wrong with ajax data tables on that branch, make sure it works, then merge it into dev.

Let's move the conversation there please: https://github.com/Laravel-Backpack/CRUD/pull/710

Cheers!

**Pull request merged**
