### PR TITLE
pameters not respecting what passed

### PR DESCRIPTION
**Pull request by dilneiss**
only default is accepted

### CODE REVIEW

**Comment by tabacitu** [comment]
Hmm... to be honest I don't think this will do anything @dilneiss - two lines above, in the function definition, there are already default values for those variables. So this fix should not have any effect.

Please explain in more words - what's the problem you discovered? What did you try to do? What did you expect to happen? What happened instead? What's you Backpack version?

Cheers!

**Comment by dilneiss** [comment]
> Hmm... to be honest I don't think this will do anything @dilneiss - two lines above, in the function definition, there are already default values for those variables. So this fix should not have any effect.
> 
> Please explain in more words - what's the problem you discovered? What did you try to do? What did you expect to happen? What happened instead? What's you Backpack version?
> 
> Cheers!

the bug I discovered was that the function is setting the defaults: $ parameters = [], $ secure = null
but if I pass my parameters to this function or secure = true / false, when calling the url function, it is being replaced by $ parameters = [], $ secure = null, so this method will never respect what I pass in parameters or secure because it is replacing the variable, I thought it was kind of obvious, so I didn’t put any more information, sometimes this type of problem goes unnoticed, I believe you didn’t notice it either.

**Comment by tabacitu** [comment]
😆 indeed, it should have been obvious, thanks @dilneiss . In fact, it was so obvious that I read it the other way I around - I thought your PR was to ADD those defaults, instead of removing them. That's why it didn't make any sense 😄 

Obviously it makes zero sense to overwrite the parameter defaults. Dooh. 
Merging now, thank you!

**Comment by tabacitu** [comment]
😆 indeed, it should have been obvious, thanks @dilneiss . In fact, it was so obvious that I read it the other way I around - I thought your PR was to ADD those defaults, instead of removing them. That's why it didn't make any sense 😄 

Obviously it makes zero sense to overwrite the parameter defaults. Dooh. 
Merging in both 4.0 and 4.1. Thank you!

**Pull request merged**
