### PR TITLE
Update delete.blade.php

### PR DESCRIPTION
**Pull request by mgralikowski**
Hide delete button for already deleted (soft).

### CODE REVIEW

**Comment by mgralikowski** [comment]
Ahh.. It causes error for model without softdeleting so better approach is needed.

**Comment by tabacitu** [comment]
Hi @mgralikowski ,

I agree - this will probably fail for non-soft-deletable entities. But why do you need this button? AFAIK trashed items should _not_ be visible anyway - Eloquent won't list them.

**Comment by mgralikowski** [comment]
You are right but we can use filter to show soft deleted and in this case this would be nice to hide button or replace by "Restore".

**Comment by tabacitu** [comment]
Hmm... I agree, it would be nice to show a "Restore" button if the entry is soft deleted. 

I've thought about adding support for this in Backpack before but I think in 99% of use cases you don't even want your admin to know things are soft deleted. Usually I use soft deletes because I don't trust the admin, and want a way back in case he deletes something important. I've dumped my thoughts about it here - https://github.com/Laravel-Backpack/CRUD/issues/1827 let me know what you think about it please.

I think it ok to have this, as it doesn't hurt anyone, I'll merge it now into the 3.6 branch (note I said 3.6 - we've silently upgraded to provide Laravel 5.8 support, I'll send a newsletter in the next few days too).

Thanks, cheers!

**Comment by tabacitu** [comment]
Ouch - on second thought, while merging I saw this change makes the list view error for all non-soft-delete entities :-) Which makes a lot of sense, the ```trashed()``` method only exists if it has the SoftDeletes trait :-)

In this case, rather than having a ```method_exists()``` call and negative conditional on each and every delete button, when this is not actually used 99% of the time, I think we'd rather have a ```soft_delete``` button, which copies ```delete``` and adds this functionality. I think this will keep things snappy and clear for most people, which don't need this soft deletes hiding, but also provide the functionality. Don't know whether to include this in the core, though... maybe better with a different operation like I mentioned here #1827

Sorry, cheers!

**Pull request closed without merging**
