### PR TITLE
Remove overrides for Cviebrock Sluggable

### PR DESCRIPTION
**Pull request by pxpm**
refs #3723 

One more BC from Cviebrock Sluggable.

I don't get why the Observer was overriden, I can't find any specific crud code in there.

I've just removed the overrides but kept the class so we can remove the overrides as NON-BC. 

Let me know @tabacitu

### CODE REVIEW

**Comment by tabacitu** [comment]
Ugh just saw this @pxpm . Totally, thank you! 

Please remember to also assign the 4.1/4.2 project to PRs & issues. Otherwise they'll never get merged, 'cause we'll forget about them. It's a miracle I've stumbled into this 😀 🔆

**Comment by Gaspertrix** [comment]
Hi @tabacitu,

Any news on this?
#3723 still persists because #3625 didn't fix it.

Thanks

**Review by promatik — APPROVED** [review]
I approve this one as it is, but I'd go a little further, I've created https://github.com/Laravel-Backpack/CRUD/pull/3811 that removes even more common stuff, @pxpm can you give it your review?

https://github.com/Laravel-Backpack/CRUD/pull/3811 is pointing to this branch.

**Comment by pxpm** [comment]
Hello @promatik 

I cannot review the PR myself, but consider this comment a review.

I've just tested this branch with your latest changes and everything is working as expected.

I will move this to ready to merge. 

Thanks,
Pedro

**Comment by promatik** [comment]
Perfect 👌
We're now overriding just the stuff we really need to change.

**Comment by pxpm** [comment]
@tabacitu just tested this with:

image

Tested with a translatable slug and still works fine:

```php
public function sluggable(): array
    {
        return [
            'description' => [
                'source' => 'name',
            ],
        ];
    }
```

👍

**Pull request merged**
