### PR TITLE
[Feature][Ready] Phone field type

### LINKED ISSUE #1202: [Feature Request] CRUD field type - phone
Who wants it? Can we have it?

Possible libraries for this feature request.

https://github.com/jackocnr/intl-tel-input
https://github.com/iPublikuj/form-phone

### PR DESCRIPTION
**Pull request by tabacitu**
Merges #1348 
Fixes #1202 
Uses https://github.com/jackocnr/intl-tel-input

Declaration:
```
[
   'name' => 'phone',
   'type' => 'phone',
   'label' => 'Phone Number (international)',
]
```

Merged #1348 and added a few features:
- the number is always stored using the international format (in a hidden input);
- check phone number integrity using utilsScript, loaded from CDN (the only way I could get it to work);
- always show the phone number prefix, next to the country flag;
- pre-populate the country flag based on the user's IP address, if the field is empty (geoIpLookup);
- copy-paste a phone number with prefix will automatically load the country flag;

Removed:
- prefix and suffix field options (not needed; plus it would be confusing since the phone number also has its own prefix);
- html files with intl-tel-input demo

### CODE REVIEW

**Comment by tabacitu** [comment]
PS. The field type seems to be working properly for me, but further testing is recommended.

**Comment by tabacitu** [comment]
@AbbyJanke - what do you think? I feel enabling these advanced features makes the field more intuitive and foolproof.

**Comment by tabacitu** [comment]
@ziming probably by the end of the week, included in the 3.5 release. It’s gonna be a big update - I think you’ll love it :-) Can’t wait to finally put all pieces together.

**Comment by ziming** [comment]
agreed!

**Comment by CyberCr33p** [comment]
Any news about this?

**Comment by martijnb92** [comment]
Paths are still based on backpack v3, uses vendor instead of packages. This needs to be changed before merging.

**Comment by rUriarteDev** [comment]
Hi guys, any news on this?

**Comment by tabacitu** [comment]
Haven't worked on this in a while, @rUriarteDev , no, sorry. I'd still love to have this, it's just never been a priority. The v4 field shouldn't be too different from the v3 code here - only minor changes I think.

**Comment by AfzalSabbir** [comment]
Any update on this?

**Comment by tabacitu** [comment]
No updates yet. But it's on the roadmap, and it'll probably get done in the next 1-2 months.

We should keep in mind that developers could/should also use [Propaganistas/Laravel-Phone](https://github.com/Propaganistas/Laravel-Phone) to validate the phone numbers introduced with any new `phone` field. So the inputs should also match the format that package expects. This adds another layer of complexity to the field...

**Comment by ziming** [comment]
I do use that package. it accepts a wide variety of formats and normalize it to 1E64

so it reduces the complexity in my opinion

**Comment by tabacitu** [comment]
New field checklist:
- [ ] does the value get saved to the database?
- [ ] does the value need to be casted to something in the Model? is it mandatory? should it support both?
- [ ] can the dev increase/decrease the size using Bootstrap classes?
- [ ] does resizing also work with Fluent field syntax? eg. `->size(6)`?
- [ ] does it support `->disabled()` and `->readonly()`
- [ ] does it support `->default()`?
- [ ] has all jQuery been removed in favor of vanilla Javascript?
- [ ] have the CSS and JS dependencies been loaded with @loadOnce?
- [ ] have the CSS and JS dependencies been pushed to proper stacks (`after_scripts` and `after_styles`)
- [ ] on error, does the field properly show the error?
- [ ] does the field support `prefix` and `suffix`?
- [ ] does the field support `hint`?
- [ ] on validation error, does the field properly get the old value?
- [ ] can the dev customize the configuration/parameters from PHP?
- [ ] are you sure there are no visible strings that should be turned into translated strings?
- [ ] does this field work inside the `repeatable` field?
- [ ] does this field work with our `CrudField` JS Library? do all events there work on this field?
- [ ] if the input is first on page, does the focus correctly set on the input?
- [ ] if the input is first in a modal, does the focus correctly set on the input?
- [ ] does the field have documentation? should it say it needs assets to be published to work?
- [ ] does the field have a screenshot?

**Comment by jorgetwgroup** [comment]
This field is done by PR PRO 103

**Comment by tabacitu** [comment]
Closing in favor of #4761 🎉

**Pull request closed without merging**
