### PR TITLE
Date_range filter premade range strings in French Added

### PR DESCRIPTION
**Pull request by mamarmite**
Added strings for the premade ranges (today, last 7 days, etc.)

in 3 files ; fr, fr-CA, fr_CA

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @mamarmite 

Thanks for the PR. 

I will just trust your french here, my `Bonjour` is not enough to doubt your translations are not right 👍 

Best,
Pedro

**Comment by mamarmite** [comment]
I double check my grammar, but in french, everybody got their preference and taste. These could be translated in other ways.
But these I how I would translated the english one :)

**Comment by mamarmite** [comment]
To be transparent, I translated the fr and fr-CA and fr_CA. Even if I'm a french canadian (Québec). So maybe a french backpacker would challenge the translation for fr.
Anyhow, it's not like emails or other tech related neologism, that francophone don't agree on :P

**Comment by pxpm** [comment]
I understand that and this is not a closed book. 

If in future someone has something to suggest we can always do that change. But better french in french than english in french :)

Thanks,
Pedro

**Comment by mamarmite** [comment]
Yes, as always :)
Thank you and the team !

**Review by promatik — APPROVED** [review]

**Pull request merged**
