### PR TITLE
[4.1][Package / Custom Field] Input - Random

### PR DESCRIPTION
**Pull request by OwenMelbz**
**Summary**

Creates a random string based off pre-defined patterns or custom.

**Preview**
random

**Usage**

``` php
//Controller->setUp()
$this->crud->addField([
    'label' => 'Random Alphanumeric',
    'name' => 'name',
    'type' => 'random',
    'random_pattern' => 'alphanumeric', //alpha, alphanumeric, alphanumericsymbols, symbols, custom (optional - defaults to alphanumericsymbols)
    'random_casing' => 'mixed',  //upper, lower (optional - defaults to mixed)
    'random_length' => 32, //(optional - defaults to 16)
]);

$this->crud->addField([
    'label' => 'Random Alphanumeric + Symbols',
    'name' => 'description',
    'type' => 'random',
    'random_pattern' => 'alphanumericsymbols', //alpha, alphanumeric, alphanumericsymbols, symbols, custom (optional - defaults to alphanumericsymbols)
    'random_length' => 20, //(optional - defaults to 16)
]);

$this->crud->addField([
    'label' => 'Random Custom "backpack"',
    'name' => 'points_needed',
    'type' => 'random',
    'random_pattern' => 'backpack', //alpha, alphanumeric, alphanumericsymbols, symbols, custom (optional - defaults to alphanumericsymbols)
]);
```

### CODE REVIEW

**Comment by tabacitu** [comment]
Nice! :-) Will check it out and merge tonight or tomorrow. Cheers!

**Comment by OwenMelbz** [comment]
@tabacitu wonder if this could make its way into 3.2 any time soon? Save us maintaining separate views 😄

**Comment by EmanueleCoppola** [comment]
News on this?

**Comment by tabacitu** [comment]
Hey there,

I've considered this a number of times (without answering here) and decided **this is not something we want inside Backpack's core**. **I see where this might be useful, but for 99% of all admin panels I think this is NOT needed, so we're not going to invest time into polishing and maintaining this.**

However, if anybody [creates a Backpack addon](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial-using-the-addon-skeleton) with a column type that does this... we'll gladly promote it, so more people use it.

Thank you for understanding - and for taking the put together the PR @OwenMelbz , I super-appreciate it 🙏
Cheers!

PS. If you or anybody else stumbles onto this and think I'm wrong and we should reconsider the decision - please reply. We're human, we make mistakes all the time, so we're open to feedback.

**Pull request closed without merging**
