### PR TITLE
Add missing fallback themes config for list operation

### PR DESCRIPTION
**Pull request by karandatwani92**
## Solves 
- https://github.com/Laravel-Backpack/theme-coreuiv4/issues/38
- https://github.com/Laravel-Backpack/CRUD/issues/5184

## How
by adding a fallback theme config to `ui.php` for list operation.

### CODE REVIEW

**Review by pxpm — CHANGES_REQUESTED** [review]
Hey @karandatwani92 thanks for the PR 🙏 

How about the other keys ? I know some of them are exclusive of tabler, so they don't make sense to be in ui. But others like `body` also throw errors on CRUD pages, as reported in https://github.com/Laravel-Backpack/CRUD/issues/5229

Is there any reason to left those keys out that I am missing ?

Cheers

**Comment by karandatwani92** [comment]
> Hey @karandatwani92 thanks for the PR 🙏
> 
> How about the other keys ? I know some of them are exclusive of tabler, so they don't make sense to be in ui. But others like `body` also throw errors on CRUD pages, as reported in #5229
> 
> Is there any reason to left those keys out that I am missing ?
> 
> Cheers

Hey Master @pxpm . I considered them already and found only CRUD's list view requires `classes.___` attribute. Nowhere else CRUD required any attributes like `classes.body`, `classes.sidebar`, `classes.header`, `classes.footer`.

Thus, no need to add them. 😬

**Comment by pxpm** [comment]
Hey @karandatwani92 I found this in theme coreui-v2 https://github.com/search?q=repo%3ALaravel-Backpack%2Ftheme-coreuiv2%20classes.body&type=code

So they may be needed ?

**Comment by karandatwani92** [comment]
@pxpm let me explain
## Why no need for other attributes?
Themes may ask for n number of attributes it could be `body` or `anything`. And theme config should only be responsible for those values which the theme requires. Those values must come up with the theme itself.

### What fallback attributes should be covered in ui.php
Only attributes that are required by CRUD, PRO, Dev Tools or any Backpack package which has `views`, so they could match with the theme's classes by overriding default classes.

Till now I have found, only the CRUD's list operation needs attributes which we are adding here.

**Pull request merged**
