### PR TITLE
Addition of entity gender

### PR DESCRIPTION
**Pull request by KevinLbr**

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @KevinLbr ,

Thanks for the PR. Looks good to me - it would be useful for Romanian too. I would rename ```all_f``` to ```all_feminine``` or something more expressive though :-)

Anybody else has any thoughts on this? Other languages?

**Comment by KevinLbr** [comment]
You're welcome @tabacitu :)

**Comment by AurelDragut** [comment]
@tabacitu, i think we talked about something related some time ago. Great job done here, @KevinLbr! I think that for the Romanian language it will be a little more complicated because of the suffixes of the words (*plural* - all the *plural*+suffix). Pretty sure, @tabacitu knows what i am talking about it, though i am not that sure we can find a proper way to manage that unless we add an optional parameter... like ` $this->crud->setEntityNameStrings($singular, $plural, $articulatedPlural=null, $gender=null); `

**Comment by OliverZiegler** [comment]
This could also improve german translations. We often have issues with the "new" button.

"New entity" sound perfectly fine. But in German depending of gender you need "Neue", "Neues" or "Neuer".

@AurelDragut could you clarify the need of `$articulatedPlural` for  people not knowing Romanian language? 😊

**Comment by tabacitu** [comment]
Hi guys,

Seems like this issue has been solved by another fix. In 3.5 that text (“**All _monsters_ in the database**”) will automatically be replaced by DataTables’ text, as soon as it loads. So instead it will read “**Showing 1 to 10 of 4,845 entries**”.

screenshot 2018-11-20 at 17 26 31

This way, we no longer have to deal with the gender there 😄 

So I’m sorry, @KevinLbr - though I really like and appreciate the PR, and now going through it I think I should have given it higher priority, I don’t think we need this anymore, so I’m going to close it. Thanks again @KevinLbr - I do appreciate it, please ask for a free commercial license at hello@tabacitu.ro when you have personal projects ;-) Please don’t take it personally, your PR is top-notch, I myself have had dozens of PRs closed, and have others pending for years - nothing personal.

Cheers!

**Pull request closed without merging**
