### PR TITLE
Allow for passing additional closures to filtering for when no filter is applied

### PR DESCRIPTION
**Pull request by jsiebach**
I have a use case where I need to be able to apply a query clause when no filter is applied.  Basically, I have a select multiple filter for "Status" which allows users to see entries with a particular status.  But if no status is selected, there are a few statuses I'd like to exclude by default.  This change would be non-breaking and useful, I think.

### CODE REVIEW

**Comment by jsiebach** [comment]
Sorry - first pull request, I don't know what the Style CI test is failing for but I'll be happy to fix it or discuss the PR!

**Comment by shaoshiva** [comment]
Hi,

You can see what fails and a corrected code proposal by clicking the `Details` link for the checks that have not passed.

Here are the contributing rules : https://github.com/Laravel-Backpack/CRUD/blob/master/CONTRIBUTING.md#user-content-idea-for-a-new-feature

**Comment by tabacitu** [comment]
Hi @jsiebach ,

Thanks for the PR. Don't worry to much about StyleCI - it's just code style, after all. I do agree it could be very useful for some use cases. Saves you a conditional and makes the code cleaner. And since it's a non-breaking change, I see now harm in merging it now.

I just made one small change - I renamed ```$default_logic``` into ```$fallback_logic```. It seemed more appropriate this way, since we already had a "default logic" concept in the comments and it's something that happens on the "else" branch of a conditional statement.

I'm sure you'll be ok with that, so I'll go ahead and merge this into ```dev```, so it'll be available to everyone this week.

Thanks, cheers! Keep 'em coming :-)

**Comment by tabacitu** [comment]
@shaoshiva thanks for pitching!

**Pull request merged**
