### PR TITLE
Fix #1370: Multibyte title is lowercase in page title

### LINKED ISSUE #1370: Multibyte title is lowercase in page title
# Bug report
`ucfirst` doesn't work with multibyte strings
### What I did:
I've created CRUD controller and changed entity names:
`$this->crud->setEntityNameStrings( 'книга', 'книги' );`
### What I expected to happen:
Title on list page should be `Книги :: Backpack Admin`
### What happened:
Title is `книги :: Backpack Admin` 
### What I've already tried to fix it:
I have overloaded method `Backpack\CRUD\app\Http\Controllers\CrudController@index`
Line 67 was:
`this->data['title'] = ucfirst($this->crud->entity_name_plural);`
Became: 
`this->data['title'] = mb_convert_case($this->crud->entity_name_plural, MB_CASE_TITLE);`
### Backpack, Laravel, PHP, DB version:
Backpack CRUD 3.4.6
Laravel 5.6.18
PHP 7.2.5 
MySQL 5.7.21

### PR DESCRIPTION
**Pull request by justnero-ru**
Fix #1370

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @justnero-ru ,

Thanks a lot for the PR! Didn't know this was happening, unfortunately I don't get to test much with non-latin alphabets. 

I found a few other places where ```ucfirst()``` is used and I'd like it if we replaced those too, so that non-latin-alphabet developers get a consistently good dev experience. But first, please let me know, **don't we need to specify the third parameter as UTF-8 too?** As in:

```php
-ucfirst($smth);
-mb_convert_case($smth, MB_CASE_TITLE);
+mb_convert_case($smth, MB_CASE_TITLE, 'UTF-8');
```

? Or does Laravel specify  ```mb_internal_encoding('UTF-8');``` itself so it's not needed?

Sorry to back-and-forth on this, it's not my first time running into multibyte issues, but I'm no expert either, so I could use a second opinion on implementing it "_the right way_".

Good round-up of differences here: http://www.brainbell.com/tutorials/php/change-string-case.html

**Comment by justnero-ru** [comment]
Hi @tabacitu,

Thanks for the review! There is **no** need to specify third parameter, Laravel actually does that for us at [`Illuminate\Foundation\Bootstrap\LoadConfiguration@bootstrap`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L51).

About the other places we should implement full-blown `mb_ucfirst` because title-case is *ok* in the title, but it's not for column and field labels. So where would be *"the right place"* for this type of helper function?

**Comment by tabacitu** [comment]
Got it, thank you. Just created a PR replacing all the ```ucfirst()``` I found with our helper, ```mb_ucfirst()```. Please let me know what you think: https://github.com/Laravel-Backpack/CRUD/pull/1390

**Comment by tabacitu** [comment]
(that PR already has your PR merged, thank you very much)

**Pull request closed without merging**
