### PR TITLE
add script and style widgets

### PR DESCRIPTION
**Pull request by tabacitu**
Fixes https://github.com/Laravel-Backpack/ideas/issues/80

This PR adds two new widgets (`script` and `style`), that help you push JS or CSS to a certain Blade stack from the Controller. This is normally frowned upon (handing CSS/JS in Controllers), but... sometimes it can be a whole lot better than overwriting an entire huge blade file and maintaining it.

This is how they can be used:

```php
            // script widget - works the same for both local paths and CDN
            Widget::add()->type('script')->content('assets/js/custom-script.js');            
            Widget::add()->type('script')->content('https://code.jquery.com/ui/1.12.0/jquery-ui.min.js');
            Widget::add()->type('script')
                         ->content('https://code.jquery.com/ui/1.12.0/jquery-ui.min.js')
                         ->integrity('sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk=')
                         ->crossorigin('anonymous');

            // style widget - works the same for both local paths and CDN
            Widget::add()->type('style')->content('assets/css/custom-style.css');
            Widget::add()->type('style')->content('https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.58/dist/themes/light.css');
            Widget::add()->type('style')
                         ->content('https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.58/dist/themes/light.css')
                         ->integrity('sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk=')
                         ->crossorigin('anonymous');
````

Todo:
- [x] test & check we didn't miss something
- [x] PR to docs - done in https://github.com/Laravel-Backpack/docs/pull/276

### CODE REVIEW

**Comment by promatik** [comment]
Hi @tabacitu!
May I completely change your PR? 😅

The issue I see is that there is a lot of attributes, that developers may want to use and may not be able to.

Something like this is not possible;
`<link rel="preload" href="style.css" as="style">`

With the style, there are other tags like `scoped` or `media` and in the case of the script tag there is also the `async` or `defer`.
And there are others, and others may appear in future 🤷‍♂️

In my opinion, the safest thing to do is to iterate over the all the attributes the developer add.

I did it, let me know if we can't for any reason ✌

Also tested and works great, boolean or empty attributes like `async` or `scoped` are rendered without the value as expected.
Let me know if we should proceed to docs or revert this 😅

**Comment by tabacitu** [comment]
Lovely ❤️ Yeah, I knew I was hardcoding what was attributes were necessary _right now_ and we'd have to do this at some point. Better for it to be done now, I agree.

Is this final - tested & working? If so, I agree with the changes, please:
- fix the merge conflicts with 4.2
- tag Pedro to review & double-check so we can merge it into 4.2
- I'll add the docs for it after Pedro gives his thumbs up

**Comment by promatik** [comment]
@tabacitu after this; `changed the base branch from master to 4.2 5 hours ago` this is having conflicts with `bundle.js`.

Any chance you can merge `master` into `4.2` to updated it and avoid this conflicts?

**Comment by promatik** [comment]
From my side, this is ready ✌

**Script**
```php
Widget::add()->type('script')
    ->src('https://code.jquery.com/ui/1.12.0/jquery-ui.min.js')
    ->integrity('sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk=')
    ->async(true)
    ->defer()
    ->crossorigin('anonymous');
```

```js
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
    integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk="
    async
    defer
    crossorigin="anonymous"
  ></script>
```

**Style**
```php
Widget::add()->type('style')
    ->content('https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.58/dist/themes/light.css')
    ->rel('preload')
    ->as('style');
```

```js
<link href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.58/dist/themes/light.css" type="text/css"
    rel="preload"
    as="style"
  />
```

@pxpm please add your review, let me know if you'd change anything.

**Review by promatik — APPROVED** [review]

**Comment by tabacitu** [comment]
Just triple-checked this. It's gold. Merging without @pxpm 's review - @pxpm if you do get the time to take a look at the code and spot anything, let us know.

**Pull request merged**
