### PR TITLE
Allow validation from rules next to custom Request class

### PR DESCRIPTION
**Pull request by sjefmoling**
For me it's annoying - especially in a large project - to write custom FormRequests for the validation of each and every CRUD. Laravel provides already functionality to validate the "default" Request using a set of rules in an array.

This PR adds this functionality to Backpack

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @sjefmoling 

Thanks for raising the issue and providing a PR to it. 

When you say that Laravel provides a way to validate with an array in controller you are talking about: https://laravel.com/docs/8.x/validation#manually-creating-validators ??

If this is the case, why not use the Laravel way? The way I see it, we are just creating an "overlay" over already implemented Laravel features with no actual benefit ? 

Let me know if I missed something here.

Best,
Pedro

**Comment by sjefmoling** [comment]
Although there're many workarounds, I think it will also benefit to keep the code (c)lean and to prevent the nessecity to override the trait store() and update() methods just for validation. Now one needs to add 

`public function update(Request $request)
    {
        $request->validate([ ... ]);

        return $this->traitUpdate( );
    }`

**Comment by tabacitu** [comment]
@sjefmoling I like the idea of moving the validation to the controller (optionally). It'd be one less file to worry about.

I'd rather have the validation rule defined inside the same `addField()` statement though, I think it'd be easier for the dev to write everything in one go. After all, that's when you realise that field is required, when you add it to the form. So I think a cooler way to approach this would be to have the `update()` and `store()` methods check if any of the fields have a `validation` or `rules` attribute (don't know what a good name for this would be). If so, it would validate them.

Of course, both approaches will have a downside (any controller-based validation, really). If you have a complex validation, or custom validators, or you need to specify different messages for the validators... you'd still be better off using a separate Request file...

**Comment by sjefmoling** [comment]
sounds like a workable solution too. Naming remains difficult, but personally I'd choose `rules`

**Comment by tabacitu** [comment]
I think I've figured out how to do this with no downsides:

```php
// so you can still do this
CRUD::setValidation(ArticleRequest::class);
CRUD::setValidation('App\Requests\ArticleRequest');

// but you can also pass a rules array (optional second parameter for messages)
CRUD::setValidation($rules, $messages);
```

To sum up, `setValidation()` would accept three things for the first parameter:
- `string` => it's a FormRequest
- classname => it's a FormRequest
- `array` => [create a `Validator` object](https://laravel.com/docs/8.x/validation#manually-creating-validators) and run it (optional second parameter as messages array)

```php
// I expect most people will just do:
CRUD::setValidation([
    'title' => 'required|unique:posts|max:255',
    'body' => 'required',
]);
```

---

What I _especially_ like about this approach is that the `validationRules` and `validationMessages` are stored in a setting. Which can _also_ be populated by the `addField()` statement, so in the future the dev might also be able to do:

```php
CRUD::field('title')->type('text')->validationRules('required|unique:posts|max:255');
CRUD::field('title')->type('markdown')->validationRules('required');

// during the validation, we'd see that validationRules and/or validationMessages is populated, 
// and we'd create a custom Validator with them and run it; no need to call 
// CRUD::setValidation() anymore if at least one
// CRUD::field()->validationRules() is defined
```

So in total you'd have THREE ways of validating fields:
```php
// Option 1 - pass the FormRequest (it will ignore any defined validationRules)
CRUD::setValidation(ArticleRequest::class);
CRUD::setValidation('App\Requests\ArticleRequest');

// Option 2 - inline validation when defining the field
CRUD::field('title')->type('text')->validationRules('required|unique:posts|max:255');

// Option 3 - define a custom validator (it will override the inline-defined validation rules)
CRUD::setValidation([
    'title' => 'required|unique:posts|max:255',
    'body' => 'required',
]);
```

**Comment by tabacitu** [comment]
Hey @sjefmoling ! I have great news - I've built upon your PR, implemented the ideas above, and...

 

You can now do ALL of the above. I think will be my preferred method will be inside fields - after all that's when I think about what validation rules that field should respect.

Please take a look at https://github.com/Laravel-Backpack/CRUD/pull/4004 , tell me what you think and what _your_ favorite way to do this will be 😀

Thanks again for submitting this 🙏 
This is gold!

**Comment by tabacitu** [comment]
Closing - let's move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/4004 which includes this PR and one more way of doing this.

**Comment by sjefmoling** [comment]
Great sollution! Love what you did with it and love to see it moving to production!

**Pull request closed without merging**
