### PR TITLE
Merge pull request #3 from Laravel-Backpack/master

### PR DESCRIPTION
**Pull request by DelightedD0D**
Merging in the official repo

### CODE REVIEW

**Comment by DelightedD0D** [comment]
Whoops, didnt mean to open this

**Comment by tabacitu** [comment]
I'm curious what you're working with there, @DelightedD0D 😄 I assume you're running a modified version of Backpack, your own repo? Curious what changes you made 😄

**Comment by DelightedD0D** [comment]
@tabacitu Actually I was trying to sync my fork from years ago in order to make and PR a small feature. Syncing forks is a bit convoluted in github so I just deleted my old copy and re-forked. 

Small pull request to follow ;)

**Comment by DelightedD0D** [comment]
@tabacitu So this is something I always add to my apps that run Backpack. I just started a new project and while adding it I thought "I'd be great if this were part of the package"

I'm not sure if you'll agree, but I've found it quite useful.

If you have time, please review the below, if this is something you'd want to see added, I'll test my changes and do a proper pull request here :) 

https://github.com/DelightedD0D/CRUD/pull/1

**Pull request closed without merging**
