### PR TITLE
Address field type - fixes #43

### LINKED ISSUE #43: [FIELDS] New field type: address
Use Algolia Places or Google Maps:

https://github.com/algolia/places

### PR DESCRIPTION
**Pull request by OwenMelbz**
Was a nicety, but a super basic feature that could be added easily. As
it happens in a few weeks we’re starting a new app that will need basic
address lookups!

usage

```php
$this->crud->addField([
            'name' => ‘address’,
            'type' => 'address',
            'label' => 'Address Lookup'
        ]);
```

### CODE REVIEW

**Comment by tabacitu** [comment]
This looks and works great! It's really beautiful field.

One question: does Algolia also provide the GPS coordinates, city name/id, country name/id, postcode, zipcode or other information? I would store everything in the same "address" field, as JSON (with attribute casting to array or object).

My reasoning is this:
- right now, Algolia helps to write the address faster; which is nice;
- but if we also use Algolia to store extra information about that address (lat, lng, postcode, city, country) developers could use one field instead of multiple AND have the coordinates to place pins on a map, if necessary; that would be a huge help in some cases;

**Comment by OwenMelbz** [comment]
I did consider doing this!

Algolia provides back "the data that it has" - from my testing, the data-set is actually inconsistent.

For example when searching some postcodes, it returned no data, but searching the address returned it, some address searches returned back the postcode, some searches didn't return a postcode.

So I was thinking of adding an extra param similar to `address_full` => true/false - which would save the full response back, but the developers need to be aware that the data returned from Algolia wont be 100% reliable.

**Comment by OwenMelbz** [comment]
the GitHub app went weird, showed I was on a different branch but still pushed to this branch! so accidently pushed other changes into this branch, they're reverting now!

**Comment by tabacitu** [comment]
Ok, that sounds good. I've changed the naming to ```store_as_json```, though, so it would be more intuitive. Merging into master! 

Another great work, @OwenMelbz  :-) Thank you!

**Pull request merged**
