### PR TITLE
[4.0][FIX] Fix breadcrumb alignment in rtl html direction.

### PR DESCRIPTION
**Pull request by ahmadmrj**
https://github.com/Laravel-Backpack/CRUD/issues/2684

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @ahmadmrj 

Thank you for submitting you issue and providing a fix for it. 

I would just do some code optimization and instead of that confusing if/else i would go with something like:

```
<ol class="breadcrumb bg-transparent p-0
	  @php(config('backpack.base.html_direction') == 'rtl' ? 'justify-content-start' : 'justify-content-end')
      >
```

Would you mind making that change ?

Best,

**Comment by ahmadmrj** [comment]
Hi Pedro,

Thanks for your refine. Sure, I'll do.

Regards,

**Comment by pxpm** [comment]
Thank you @ahmadmrj 

One good thing (now that your are an active contributor and a rtl user) is that you can give a look at backpack app and check if there are other spots that we missed rtl support.

For me this PR is good, but I think it would be nice if you can keep using Backpack and if you find other glitches with RTL we can fix them at once :)

This problably will be merged in our  MMD - monday merge day (just came up with the name :+1: ) if we find more things to fix we can do it until monday and have a big batch of fixes.

If you can't find any other issue maybe we did a good job before :)

Once again, thank you very much.

Best,

**Comment by tabacitu** [comment]
Thanks @ahmadmrj & @pxpm ! Merged! I only had to do one small change - ```{{ }}``` instead of ```@php()``` - it didn't work that way, I don't think that Blade helper exists, only ```@php @endphp``` I think.

Merged and tagged, it'll be available the latest on Monday, like @pxpm said. I love the name MMD (Monday Merge Day) - let's keep it 🥳

**Comment by ahmadmrj** [comment]
I appreciate your hints @pxpm & @tabacitu, And thank you for your trust. As Pedro mentioned I can help to fix other probable issues of RTL theme.

**Comment by pxpm** [comment]
> Thanks @ahmadmrj & @pxpm ! Merged! I only had to do one small change - `{{ }}` instead of `@php()` - it didn't work that way, I don't think that Blade helper exists, only `@php @endphp` I think.
> 
> Merged and tagged, it'll be available the latest on Monday, like @pxpm said. I love the name MMD (Monday Merge Day) - let's keep it

Just FYI, there is a blade @php() without ending tags, it will evaluate php code inside it and auto-close. 

I also found some scenarios where it would not work, maybe this is one of those, but surely it works, we had it on field wraper before the refactor.  

Anyway, your solution is even cleaner than mine so, we are good :)

Thanks guys!

**Pull request merged**
