### PR TITLE
[4.0][BUGFIX] Elfinder mime type filter.

### PR DESCRIPTION
**Pull request by pxpm**
Reported in: #2480 

It was related with bad parsing of mime types.

We have also #2400 open to fix an issue with file clearing.

ping @tabacitu

### CODE REVIEW

**Comment by tabacitu** [comment]
Great! Thank you @pxpm ! Merged into ```master```. It'll be released shortly.

**Comment by pxpm** [comment]
@tabacitu don't merge this yet.

This needs a fix in: 

```
```

**Comment by tabacitu** [comment]
😆 too late.

Kidding. Ok please change it on the same branch ```fix-browse-multiple-elfinder-mimes``` and let me know when it's ready to merge. It's already merged on ```master``` but it's not tagged yet, so we're good.

**Comment by tabacitu** [comment]
@pxpm done - let me know if we need to do anything more than https://github.com/Laravel-Backpack/CRUD/pull/2510

**Comment by pxpm** [comment]
@tabacitu afaik no. It's all done. Thanks

**Pull request merged**
