### PR TITLE
Catalan translations.

### PR DESCRIPTION
**Pull request by profe-pep**
### BEFORE - What was wrong? What was happening before this PR?

Missing catalan language.

### AFTER - What is happening after this PR?

Catalan localization.

### How did you achieve that, in technical terms?

Adding new language translations.

### Is it a breaking change?

No.

### How can we test the before & after?

Set locale "ca" at config/app.php.

### CODE REVIEW

**Comment by maurohmartinez** [comment]
@tabacitu for some reason I am not able to checkout to `profe-pep:profe-pep-catalan` on CRUD repo. Is it on a different project that I am not seeing? Sorry!

**Comment by tabacitu** [comment]
Hmm what's weird. 

1) What about using [Github CLI](https://cli.github.com/)? Does `gh pr checkout 4508` work?

3) Did you try using SSH too? 
```
git remote add profe-pep git@github.com:profe-pep/CRUD.git
git fetch profe-pep profe-pep-catalan
git switch --track profe-pep/profe-pep-catalan
```

**Comment by maurohmartinez** [comment]
@tabacitu yep, that worked... thanks!

**Review by maurohmartinez — APPROVED** [review]
This PR looks good!
I don't speak catalan, but my nephew does...now he can also use Backpack 😄 🚀 
Well done @profe-pep!

**Pull request merged**
