### PR TITLE
Merge column and field guess functions

### PR DESCRIPTION
**Pull request by pxpm**
#### What was wrong before ? 
Columns were missing some "guessing" that we do on fields, like attribute for example. 
In preparation to have fields/columns used interchangeably we need to make sure both entities are able infer the missing attributes.

#### What's working after?
- Adds the `guessing attribute` functionality to columns via function. (using the same function we use for fields)
- Add the subfield attribute guessing in columns too
- Remove duplicated code.

#### is it a breaking change?
no I don't think so.

#### how can I test the before and after ? 
Add a field that has subfields, and use the same field definition as a column definition.

### CODE REVIEW

**Comment by tabacitu** [comment]
@pxpm I think this needs a more "human" explanation for Mauro to be able to test. Please answer the questions in the [PR template](https://github.com/Laravel-Backpack/CRUD/blob/main/.github/pull_request_template.md) from now on. They're there for a reason, to force us to make it easy for the next guy to do his job:

```
WHY
BEFORE - What was wrong? What was happening before this PR?
??

AFTER - What is happening after this PR?
??

HOW
How did you achieve that, in technical terms?
??

Is it a breaking change?
??

How can we test the before & after?
??
```

**Comment by maurohmartinez** [comment]
Hey @pxpm
I was trying to come up with an example to test this, but I am not able to tell the difference.
Can you give me an example?

Sorry! :)

**Comment by pxpm** [comment]
@maurohmartinez sorry for late reply. 

You should be able to test this by doing:
- Create a new local branch starting from https://github.com/Laravel-Backpack/CRUD/pull/4675
- Checkout https://github.com/Laravel-Backpack/demo/pull/430 on demo and https://github.com/Laravel-Backpack/PRO/pull/91 on PRO

You then go to `Other Entities -> Column Monsters`. 

What we are doing there (ColumnMonstersCrudController) is getting the fields from the `Monsters` crud, and setting them as columns too. Some of those fields have subfields, and we still need to run the guessing functionality on those fields. (this PR)

At first you will get an error, remember that I said for you to create a local branch starting from the other crud PR ? Ok, now merge this branch inside that local branch (started from the branch where this PR points to).  Hopefully everything will work. 

Let me know if I didn't make myself clear enough. 

Cheers

**Comment by maurohmartinez** [comment]
> You then go to `Other Entities -> Column Monsters`.

@pxpm, that was very helpful!
I was able to do that but got an error. This is what I got https://flareapp.io/share/Vme4Ddq5#F57

Is that because I did something wrong?

**Comment by pxpm** [comment]
> > You then go to `Other Entities -> Column Monsters`.
> 
> @pxpm, that was very helpful! I was able to do that but got an error. This is what I got https://flareapp.io/share/Vme4Ddq5#F57
> 
> Is that because I did something wrong?

You did nothing wrong, I guess that's just a bug, not related with this specific PR, but with the columns PR.

Let me have a better look at it .. in the meanwhile, what should be "really tested" in this PR, like I mentioned, are the columns that have subfields and/or are not completely defined and Backpack guesses the attributes. 

You can comment out that line to test the rest of the functionality without worrying about those issues. Focus only on the changes proposed in this PR, the columns PR still a working progress. 👍 

Let me know if I can help you with something else.

**Comment by maurohmartinez** [comment]
@pxpm Ok! This is the settings I am using for a field, and now for a column, and this is the result.

It looks good to me, but I am not sure I get the idea about the attributes you mentioned. Should I inspect that column and look for certain attributes? Or you mean something else? Sorry for so many questions! :)

Screenshot 2022-11-25 at 16 54 50

**Comment by pxpm** [comment]
@maurohmartinez as you can see, if you inspect, let's say the `wish.country` column before and after this PR you will see the main differences. In this PR it will have everything setup (entity, relation type etc etc), while in the main branch it will have nothing of that setup.

**Comment by maurohmartinez** [comment]
> @maurohmartinez as you can see, if you inspect, let's say the `wish.country` column before and after this PR you will see the main differences. In this PR it will have everything setup (entity, relation type etc etc), while in the main branch it will have nothing of that setup.

@pxpm You are right, I can't even see the page without this PR as it shows `Undefined array key "type"`. Cool!

Do you want me to have a look at the code as well? Or just testing it works is enough?

**Comment by pxpm** [comment]
I don't have any particular concern about the code since it's very straightforward 👍 

Thanks for the review, I am merging this in the columns branch so that we can test with only 3 PR's (crud, pro and demo) without creating an adicional test branch!

Thanks!

**Pull request merged**
