### PR TITLE
[4.1-beta] Ignore dep package json

### PR DESCRIPTION
**Pull request by tabacitu**

### CODE REVIEW

**Comment by AbbyJanke** [comment]
I feel like requiring Carbon is important. Based on your comments of previous issues/PRs backpack still supports 5.6. Feels like a safety precaution. Breaking Change?

**Comment by tabacitu** [comment]
Thanks for the heads-up, I appreciate it! 

But this PR points to 4.1, and there we only support Laravel 6 and Laravel 7 - which both require either carbon >2.0 and >2.1 respectively. So it should be fine 🤞 🤣

**Comment by AbbyJanke** [comment]
:) Wasn't 100% sure heh, Was hoping that was the case but it was a comment you had just made was probably just for 4.0. I'm using Laravel 7.9 and 4.1 beta to play with right now so trying to read what I can about it and help where can. Loving it so far, (needs documentation though heh). PHPStorm is being helpful with recommendations.

**Comment by tabacitu** [comment]
Let me know when you find something that isn't properly documented - not easy to see the holes myself.

**Pull request merged**
