### PR TITLE
fix "Argument #1 ($var) must be of type Countable|array, string given"

### PR DESCRIPTION
**Pull request by egyjs**
# error 
```
count(): Argument #1 ($var) must be of type Countable|array, string given
```
image

# fix
> convert value to array if the value is string 
image

### CODE REVIEW

**Comment by pxpm** [comment]
@egyjs 

Thanks for the report. Can you please make sure that you have your field inside the `$casts` property of your model ? 

image
https://backpackforlaravel.com/docs/4.1/crud-fields#upload_multiple

We have a channel in gitter, somewhat active where people usually post this kind of questions or any issues they are having before creating PR's or issues, if you want to join us: https://gitter.im/BackpackForLaravel/Lobby

I might be wrong here, so please if I am stick with me so we can fix this :)

Thanks,
Pedro

**Comment by egyjs** [comment]
Hi @pxpm , how are you doing today..
The reason i made this line Cuz we dont have `browse_multiple` column, and this column is similar to `upload_mulitple` .. so this way we can support both fields/columns

**Comment by pxpm** [comment]
> Hi @pxpm , how are you doing today.. The reason i made this line Cuz we dont have `browse_multiple` column, and this column is similar to `upload_mulitple` .. so this way we can support both fields/columns

Hello @egyjs ! I am fine thanks for asking, and you ? 

Sorry I missed that you were talking about columns, but I think the principle remains, if you add that column to the `casts` property as array it would work. Can you try it ? 

Thanks,
Pedro

**Comment by egyjs** [comment]
Thanks @pxpm  for your quick response ෆ

I already tried , unfortunately its return an error on creating , with `browse_multiple` 

So there is 2 solutions here 
1. Create a `browse_multiple` *column* file
Or 
2. This line should do it for both

**Comment by pxpm** [comment]
Hey @egyjs 

Let's break this down to make sure I don't get lost. 

So you use the same field (let's say `photos`), as a `browse_multiple` field in the create operation, and as an `upload_multiple` column type ? Both need to be casted as array, so you should be fine. 

I've just tested adding a `browse_multiple` field in the create operation, and then the same name as an `upload_multiple` column in List operation and it works fine.

```php
// setupCreateOperation
$this->crud->addField(['name' => 'photos', 'type' => 'browse_multiple', 'upload' => true]);

// setupListOperation
$this->crud->addColumn(['name' => 'photos', 'type' => 'upload_multiple');

// in model I have:

protected $casts = [
    'photos' => 'array'
];
```
So I am not sure but maybe you have some corrupt json in your database or something that causes the field to error ?

Best,
Pedro

**Pull request closed without merging**
