### PR TITLE
[Bug Fix] Use Doctrine to query if column is nullable

### PR DESCRIPTION
**Pull request by just-paja**
This should fix the problem with backpack not working with sqlite.

I must say, I'm really new to Laravel, so please take time to code review the shit out of this - I can't imagine what could this tiny change affect and I can't really see any tests in this repository.

### CODE REVIEW

**Comment by tabacitu** [comment]
Great, thank you. I'll test it thoroughly but really, there are only 2 places where it's used, so it won't be that difficult. Unit tests are of course on the roadmap, but... we're not there yet.

I'll be back after testing.

Cheers, thank you!

**Comment by tabacitu** [comment]
Hmm... I'm afraid this works for aaaalmost all uses cases. 

It doesn't seem to work for ```enum``` column types though, it throws this error in the select2 field type. 
screen shot 2016-10-15 at 13 06 00

Might it be that Doctrine doesn't support the ```enum```  column type?

Cheers!

**Comment by just-paja** [comment]
What about the enum type?

**Comment by tabacitu** [comment]
Found the solution, finally! Check it out [here](https://github.com/Laravel-Backpack/CRUD/commit/f3590249e3b8ef8f270c9c188245e76dd11118de), if you want. I've merged your code and only added a notice for Doctrine to know what "enum" is.

Thank you for the contribution again. Cheers!

**Comment by tabacitu** [comment]
The "enum" field type, created specifically for the MySQL/PosgreSQL "enum" column type, is just like a SELECT, but its gets its values straight from the database schema.

The update broke it. But it's fixed now.

**Comment by just-paja** [comment]
Great, thanks ☺


Pavel Žákhttp://improliga.cz

-------- Původní zpráva --------
Od: Cristian Tabacitu <notifications@github.com> 
Datum: 17.10.2016  18:20  (GMT+01:00) 
Komu: Laravel-Backpack/CRUD <CRUD@noreply.github.com> 
Cc: Pavel Žák <just.paja@gmail.com>, Author <author@noreply.github.com> 
Předmět: Re: [Laravel-Backpack/CRUD] [Bug Fix] Use Doctrine to query if column
  is nullable (#176) 

The "enum" field type, created specifically for the MySQL/PosgreSQL "enum" column type, is just like a SELECT, but its gets its values straight from the database schema.

The update broke it. But it's fixed now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Laravel-Backpack/CRUD","title":"Laravel-Backpack/CRUD","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Laravel-Backpack/CRUD"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tabacitu in #176: The \"enum\" field type, created specifically for the MySQL/PosgreSQL \"enum\" column type, is just like a SELECT, but its gets its values straight from the database schema.\r\n\r\nThe update broke it. But it's fixed now."}],"action":{"name":"View Pull Request","url":"https://github.com/Laravel-Backpack/CRUD/pull/176#issuecomment-254256607"}}}

**Pull request merged**
