### PR TITLE
Hasone tests and improvements

### PR DESCRIPTION
**Pull request by pxpm**
I was working on #3250 and decided to tackle this relation too. 

I'v added tests for HasOne relation and also refactored the relation creation code. 

This is aimed to be merged into #3250 and merge both on master.

### CODE REVIEW

**Comment by tabacitu** [comment]
🥳 confidence++ 😀

**Comment by promatik** [comment]
@pxpm I have being debugging this, and I can't find why it's failing.
It's failing on Demo, when creating a "Monster";

`Create.php:89 associateBelongsToRelations`

```
BadMethodCallException
Call to undefined method App\Models\Monster::address.icon()
```

`Monster::class` `hasOne` `Address::class`, and
`Address::class` `belongsTo` an `Icon::class`.

As far as I understood, it's trying to associate the belongsTo relation first, to a non existing Address.

**Comment by promatik** [comment]
@pxpm I have being debugging this, and I can't find why it's failing.
It's failing on Demo, when creating a "Monster";

`Create.php:89 associateBelongsToRelations`

```
BadMethodCallException
Call to undefined method App\Models\Monster::address.icon()
```

`Monster::class` `hasOne` `Address::class`, and
`Address::class` `belongsTo` an `Icon::class`.

As far as I understood, it's trying to associate the belongsTo relation first, to a non existing Address.

**Review by promatik — CHANGES_REQUESTED** [review]
Left a comment above; https://github.com/Laravel-Backpack/CRUD/pull/3322#issuecomment-731606369

**Comment by pxpm** [comment]
@promatik I found the reported problem. The `address.icon` field is indeed a relationship field, but not a primary one. It's a `BelongsTo` relation in the `Address` model, and not in `Monster`. That was causing conflicts. 

To deal with that I applied the same concept we use for main item `BelongsTo` relations, that is adding them to the `array of values` that will be created as the `HasOne`.

So in your example, when you are creating the address, we will get the BelongsTo relations for `Address` (Icon) and save it along with `Address` itself. 

I added tests for this scenario I am describing to you, I left the `@group failing` so you can go straight to them: `vendor/bin/phpunit --testdox --group=failing`

**Comment by pxpm** [comment]
I probably shouldn't have merged `master` into this branch. 

Now probably better merge to master instead of the intended branch ? 

Help me here @tabacitu when you can :) thanks

**Comment by tabacitu** [comment]
No problem! I've created https://github.com/Laravel-Backpack/CRUD/pull/3383/files that holds all the changes here, and points to `master` - I think this is what you were looking for, right? Here's what I did:

```bash
git fetch
git checkout hasone-tests-and-improvements
git checkout -b hasone-tests-and-improvements-2
git merge master
git push origin hasone-tests-and-improvements-2
# then created a PR for it
```

**Pull request merged**
