### PR TITLE
Allow translatable button texts on custom save actions

### PR DESCRIPTION
**Pull request by jnoordsij**
Allow translatable button texts on custom save actions by looking for the name of the save action in the language files.

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @jnoordsij 

Thanks for submiting a PR for this. 

I wonder if this works for you, because the keys in the translation file does not match what you proposed.

From language file:
```php
'save_action_save_and_new'         => 'Save and new item',
'save_action_save_and_edit'        => 'Save and edit this item',
'save_action_save_and_back'        => 'Save and back',
```

So, they are prefixed with `save_action` before the `$saveAction['name']`.

Would you mind changing your PR to match the current lang files we have ?

So it should be: 

```php
trans('backpack::crud.save_action_' . $saveAction['name']);
```

Thanks again, let me know if you are willing to fix this or want me to deal with it :)

Wish you the best.

**Comment by jnoordsij** [comment]
Actually it does work on my end, because the basic actions are not added with this method, but in a separate function call (see https://github.com/Laravel-Backpack/CRUD/blob/915abdd75ff1d4c900371b65d474ac7e7ca076d9/src/app/Library/CrudPanel/Traits/SaveActions.php#L381). 

I think not adding the prefix is slightly clearer to users, but for consistency it might be better to add it. I'm fine with both options.

**Comment by pxpm** [comment]
Ahhh i see, my bad i misread, so sorry :(

So in that scenario, wouldn't it be better if you provide the translated name to `button_text` from your controller instead of hardcoding `backpack::crud` translation file ? 

I don't think this makes sense, it's like label, you provide the `trans('label')` from controller. 

Let me know.

**Comment by jnoordsij** [comment]
No problem, thanks for your feedback anyways!

I think your suggestion actually might make more sense now. At first I was a little confused when I saw the entries in the lang files, but adding one for my custom button did not work. But the main problem was I didn't see the `button_text` entry at that point.

I'll change https://github.com/Laravel-Backpack/docs/pull/135 to have some instructions on the `button_text` attribute, so it's easier to find, then this one is no longer necessary.

**Pull request closed without merging**
