### PR TITLE
fixed methods beforeColumn and afterColumn

### PR DESCRIPTION
**Pull request by gmedeiros**
array_splice was not receiving a number as the second parameter on these two functions,  it was receiving the name of the column so the order of the columns was not being correctly set when using beforeColumn() or afterColumn(): https://cl.ly/1D0G0H3M193G

`$this->crud->addColumn(['label' => "Name", 'type' => "text", 'name' => 'name'])->beforeColumn('surname');`

With this fix, the offset of the column is sent to the array_splice as the second parameter.

### CODE REVIEW

**Comment by dmagur** [comment]
This PR will not work if you use beforeColumn on previously added column, i.e.
`$this->crud->addColumn('col1');`
`$this->crud->addColumn('col2')->beforeColumn('col1')`

because addColumn method adds elements with 
`array_filter($this->columns[] = $column_with_details);`

so key will be integer and not column name and this
`$offset = array_search($column, array_keys($this->columns));`
will fail

**Comment by tabacitu** [comment]
Hi @gmedeiros ,

Sorry for the long wait - I was unable to get the same error, so did not prioritize this. @dmagur 's note yesterday was very very helpful - turns out you were using ```setFromDb()```, and that's the only time that ever occurs. I never do.

That being said, thanks a lot for the PR, I've fixed the underlining issue and merged your PR, it's now on the ```dev``` branch waiting for others to test and report if anything goes wrong.

Cheers!

**Comment by gmedeiros** [comment]
Hi @tabacitu , thanks for getting back to me! I'm glad my PR helped in any way. I hope I can keep contributing with the project, I really love it :)

Cheers!

**Comment by tabacitu** [comment]
@gmedeiros - definitely keep contributing :-)
I really appreciate it. Cheers!

**Pull request merged**
