### PR TITLE
[Refactor][3.4] Renamed CrudFeatures into Operations

### PR DESCRIPTION
**Pull request by tabacitu**
Since it's a terminology we use, I think that makes more sense to have the same terminology in the namespace / class names. See [my comment here](https://github.com/Laravel-Backpack/CRUD/pull/1350#issuecomment-403205564) for more details. Basically:

- an OPERATION is something big you can do to an Entity; it usually has its own route, controller method, view etc; for example ```Create```, ```Update```, ```List```, ```Preview```, ```Delete```, ```Reorder```; what we used to hold in ```Http\Controllers\CrudFeatures```;
- a FEATURE is some functionality on the Operation; most of the times, the Feature can be enabled/disabled; for example on the ```List``` operation we can have ```export_button```, ```details_row```, things like that;
- the ACTION is just the controller method being called by the route - that's it; so the CREATE operation can call the ```create()``` action and the ```store()``` action, by calling their respective routes;
- a PERMISSION is an entry in the database that helps enable/disable Features; so if you have the ```editor``` role you could have an ```edit_own_entries``` permission, but also an ```edit_all_entries``` permission; in code, if the user has one permission or the other, you can enable/disable Features or entire Operations;

### CODE REVIEW

**Comment by tabacitu** [comment]
Not a breaking change, if we refrain from moving SaveActions into the CrudPanel object.

**Comment by niladam** [comment]
I doubt this is a non-breaking change. After a simple composer update, all my crudcontrollers went nuts. Here's an error:

`Argument 1 passed to Backpack\CRUD\app\Http\Controllers\CrudController::updateCrud() must be an instance of Backpack\CRUD\app\Http\Controllers\Operations\UpdateRequest or null, instance of App\Http\Requests\ProductRequest given
`

Sadly, i'll have to spend some time trying to fix this on my end. You can see how having a large number of crudcontrollers this breaks all of them, right ?

**Comment by niladam** [comment]
I wonder if someone could provide me with some pointers on fixing this ?

**Comment by tabacitu** [comment]
@niladam that's weird... 

1) **What PHP version are you on?**
2) Sounds to me like the problem you're facing might be because Style.CI has removed ```use Illuminate\Http\Request as StoreRequest;``` and ```use Illuminate\Http\Request as UpdateRequest;``` from CrudController. They're no longer used there, since we moved the methods. **Would adding these declarations back fix this problem for you?** Can you try to: 
- add ```use Illuminate\Http\Request as StoreRequest;``` to ```vendor/backpack/crud/src/app/Http/Controllers/Operations/Create.php```, after namespace;
- add ```use Illuminate\Http\Request as UpdateRequest;``` to ```vendor/backpack/crud/src/app/Http/Controllers/Operations/Update.php```, after namespace;

Really curious if this is PHP-version thing, or what. I'm not getting any errors here...

**Comment by niladam** [comment]
@tabacitu I'm on a Mac and i'm using valet. My PHP version:

```
PHP 7.2.7 (cli) (built: Jun 22 2018 06:27:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7, Copyright (c) 1999-2018, by Zend Technologies
```

I will tackle this tomorrow as i've already downgraded my crud installation. I had a struck of imagination and came attempting to fix something. I did, and the rest is for tomorrow -- i'll get back with the news.

**Comment by tabacitu** [comment]
Well that's odd - I'm running on a Mac Valet with PHP 7.2.6 here, and no error...

Ok, no problem!

**Comment by tabacitu** [comment]
@niladam - yup, that was it. I managed to find a controller of mine where the same error happened. Apparently it only happens when the $request is passed as parameter to updateCrud() and storeCrud(). Not all CrudControllers do that.

Anyway - just pushed an update (3.4.20). A ```composer update``` should fix it for you, and let you use all the latest features.

Thanks for revealing this bug so soon after the update!

**Comment by niladam** [comment]
@tabacitu - i can confirm now that everything works 👍  

- Thanks!:)

**Pull request merged**
