### PR TITLE
Fix some bugs I've found

### PR DESCRIPTION
**Pull request by jgrossi**
Hey guys!

I was trying to use the `multilanguage` branch and was getting some exceptions like `Indefined index 'locale'` or even `strip_tags() expects parameter 1 to be string, array given`.

Hope it helps!

Great job, JG.

### CODE REVIEW

**Comment by OwenMelbz** [comment]
I haven't actually looked at this branch yet. And I'm sure eventually a changes like this will be useful.

However by effectively hiding these errors it means it's harder to identify the actual issue.

You might have received this error due to an underlying problem which actually needs addressing.

It would be worth actually back tracing the issue you have to find out why locale was not set?

For example if you've just swapped branches, and not republished views/configs which have new fields in them, that might be the actual issue, rather than the code itself?

If you were able to identify the actual issue that would be more useful than suppressing it, maybe compare your published views/configs against the ones in the vendor folder and see what you find?

**Comment by jgrossi** [comment]
Hey @OwenMelbz I already did that, comparing views and config, and no change comparing to `master`. The issue is more about the code itself like: 
```
$locale = $attributes['locale'] ? $attributes['locale'] : App::getLocale();
```
instead of: 
```
$locale = $attributes['locale'] ?? \App::getLocale(); // \App and not App
```
Or even the `getTranslation()` method from `spatie/laravel-translatable` returning an array instead of a string, just verifying that ;-)

JG

**Comment by tabacitu** [comment]
Hi @jgrossi ,

Merged, thank you, great additions. I'll take a look at your ::find() suggestion shortly.

Cheers!

**Comment by tabacitu** [comment]
@jgrossi , just fixed the find and findOrFail issue (they couldn't be called statically): https://github.com/Laravel-Backpack/CRUD/commit/0e6dec3b89863c4f228fc791b92e43dbd67bd854

Please let me know if you find any more issues with this branch.

Cheers!

**Comment by jgrossi** [comment]
Thanks @tabacitu! I'm gonna take a look and anything I send a new PR :-) Thanks a lot!

**Pull request merged**
