### PR TITLE
[Feature] Index column functionality

### PR DESCRIPTION
**Pull request by promatik**
Fix for #1299 
This enables the installation process on windows.

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @promatik ,

Thanks a lot for the PR. I see the windows installation fix got merged with the "index" column functionality, so I manually merged the windows fix, and will review this separately. I'll rename it so it's appropriate again.

Thanks, be back, cheers!

**Comment by tabacitu** [comment]
Hmm... I see you've also added another feature in the same PR - passing an array to the reorder method. **Question: wouldn't an accessor on the model be another method to solve the same problem?**

**Comment by promatik** [comment]
@tabacitu you are right!
Much more easier **and clean**, to create an accessor! You can ignore the commit about it (https://github.com/Laravel-Backpack/CRUD/pull/1428/commits/312a3a4e1b12c450e7cf99041296f3ee6f28bb45).

**Comment by tabacitu** [comment]
Closing this in favour of https://github.com/Laravel-Backpack/CRUD/pull/1471 which includes your commit for this feature (and that commit alone).

Thanks, cheers!

**Pull request closed without merging**
