### PR TITLE
Fixed removing columns not preserving columns array keys. Deprecated …

### LINKED ISSUE #1002: The removeColumns methods does not preserve columns keys
The CrudPanel `removeColumns` method in the Columns trait does not preserve the fields array keys.

### PR DESCRIPTION
**Pull request by tumf87**
Fixes #1002.

### CODE REVIEW

**Comment by tumf87** [comment]
@tabacitu, please take note that this deprecated the Columns trait `remove` method.

From what I see, it is not used in any other parts of the code but I did not removed it for backwards compatibility purposes.

**Comment by tabacitu** [comment]
@tumf87 I see this has some merge conflicts with dev - I probably used a different merge order than you intended... 

Do you mind merging dev into this branch and fixing the conflicts? You know best what's to keep.

**Comment by tumf87** [comment]
@tabacitu, on it!

**Comment by tumf87** [comment]
@tabacitu, should be good now!

**Comment by tabacitu** [comment]
Awesome. Merged, thanks!

**Pull request merged**
