### PR TITLE
Add .gitattributes file to reduce package size 

### PR DESCRIPTION
**Pull request by lakuapik**
first of all, thanks for the awesome package!

this PR just add `.gitattributes` file to reduce package download size and save approximately ~1.5MB of disk space.
reference: https://php.watch/articles/composer-gitattributes

feel free to add/remove entry from `.gitattributes` file 😇️

PS: if this pr accepted, will open this to other backpack repo too.

### CODE REVIEW

**Comment by pxpm** [comment]
Hey @lakuapik 

Thanks for the contribution. I've read about `.gitattributes` and the benefits and I really think this is a good idea to reduce bundle size. 

Although we need to make sure we don't remove any needed files from the bundle. I've moved this to 4.2 as we still have some work to do in 4.1 and I think this needs some carefull testing. 

Also, there is some "barrier" for some devs when they go to the package folder not beeing aware of this possibility and don't find some files (like tests and stuff) inside the package folder. (it happened to me before, and I was like `wtf is happening here`. )

Anyway, very appreciated your effort, I am sure we will giving a look at it some time soon.

Thanks,
Pedro

**Comment by tabacitu** [comment]
I absolutely freakin' LOVE this! Thanks @lakuapik , I had no idea about `export-ignore`. 

We will DEFINITELY do this. We just need to figure out where to draw the line. Like @pxpm said, it's better to do this in 4.2, since we're currently only merging bug fixes to 4.1. It would make me so-so happy to have 4.2 _smaller_ than 4.1 🤯 I didn't dare to dream about that but now I can 😅

Thanks again @lakuapik !

**Comment by lakuapik** [comment]
@pxpm @tabacitu glad if it helps 😇️

----

i have a question though :D

regarding the package size, i see one thing that makes `backpack/crud` size large is the `src/public/packages` dir, its around **87MB** and taking up  **~94%** of total package size (**92MB**).

in the future, would it be possible to exclude backpack `packages` and only use CDN?
my suggestion on this is the `package:install` command has an option to either use CDN or download packages on the fly,
so no more `packages` dir on the `backpack/crud` and more space for other thing?? :D

i've seen this https://github.com/Laravel-Backpack/CRUD/pull/1007 and yeah i agreed, when the CDN down, the packages cannot be loaded, IMHO  the option to use install with CDN or local packages seems fair for me, as long as user know what they're doing.

if this sound interesting, i would love to make a draft PR.

**Comment by lakuapik** [comment]
@tabacitu, also one thing that comes to mind is just reduce the `packages` size by removing unecessary files
and only include files that backpack really needed (min.css, min.js, LICENSE, etc).
IMHO, this could be the simplest solution to reduce package size right now, just look at 
`packages/summernote/dist/` dir, there are 4 zip files that takes up `~4.3MB` and i believe those are not
necessary to be included.

**Comment by tabacitu** [comment]
> regarding the package size, i see one thing that makes backpack/crud size large is the src/public/packages dir, its around 87MB and taking up ~94% of total package size (92MB).

Yeah I know... it's been bugging us for a while now. Hopefully we'll be able to take care of it once and for all in 4.2 - see https://github.com/Laravel-Backpack/CRUD/pull/2652 for details (hope that's the one). Basically what we intend is to have a Blade helper to load a CDN asset onpage. If that asset is cached on already pulled into the current server, it'll use it from there (swap out the URL). If not, it'll download it and put it in public, so that it'll get used from there next time. There are quite a few kinks to work out in this process though - we want to prototype it first to see if there are bigger issues that we didn't think about. But in theory it should eliminate all our asset-loading problems, and be a joy to work with.

**Comment by tabacitu** [comment]
I've decided rather than shave off a few MB (1-5% of the total size)... we are going to try to shave off 90% of the size, with something like https://github.com/Laravel-Backpack/CRUD/pull/4008

I'm pretty sure this is not going to make it into 4.2, because we're behind the deadline already. But I wanted to thank you @lakuapik for opening my eyes to `export-ignore` - I think it'll be a HUGE boost in v5.

Closing this in favor of https://github.com/Laravel-Backpack/CRUD/pull/4008 

Thanks again @lakuapik !

**Pull request closed without merging**
