### PR TITLE
[4.1][Feature][Ready] Configurable web middleware

### PR DESCRIPTION
**Pull request by tabacitu**
Continued PR https://github.com/Laravel-Backpack/CRUD/pull/2392, which was the same as Laravel-Backpack/Base#413

Makes the "web" middleware configurable. In case the developer has changed his "web" middleware in any way for the front-end of his app, this will make it easier for him to choose a different web middleware.

### CODE REVIEW

**Comment by tabacitu** [comment]
@MartijnvAdrichem & @pxpm there are two more things that I'm wondering before we can merge this.

1) @MartijnvAdrichem if you needed to change this inside the ```routes/backpack/base.php``` file, that means you also needed to change it inside the ```routes/backpack/custom.php``` file. And inside the route files for all Backpack add-ons that you might have installed (like BackupManager, PermissionManager, etc). Right?

2) I did not know that you can "break" Backpack by changing your web middleware for the front-end. Because I rarely (if ever) do that. With this new information, **I'm wondering if it makes more sense, like @pxpm proposed, to not use the default "web" middleware in Backpack, but our own middleware group**. We don't even have to create a middleware group, we can just use an array in the config file (like ```web_middleware``` in this PR). Using our own web middleware would make the Backpack routes&pages more independent from the front-end, which I think is a good thing. Right? Right?! I don't know 😆 It's just a matter of changing the default value in the ```web_middleware``` config we just created. But I'm not sure which way to go. What do you guys think?

Todo:
- [ ] replace ```web``` with ```config('backpack.base.web_middleware')``` in all Backpack add-ons;

**In either case, this PR is ready to be merged.** The problem is - it constitutes a **breaking change** of sorts. Because the route files get published, modifying something inside them means we also need to tell developers to modify this themselves, in their published route files. So it needs to be mentioned in the **upgrade guide**. Fortunately, we're a few weeks away from one. Backpack 4.1 is a good time&place to merge this. 

Labelling it "ready". **Let me know if you think the default for ```web_middleware``` should be the explicit array with all middleware Backpack needs, or just "web".**

Cheers!

**Comment by MartijnvAdrichem** [comment]
Hi @tabacitu 

Thanks for fixing the PR!

Good point that each add-on requires this change! Is that something you can do? 

About point 2 I think it is a good idea, because it will make Backpack work more often out-of-the-box in existing applications. One down side is that a midleware needs to be added in 2 places when the developer wants to add a new middleware in the frontend and Backpack. 

For me this current fix is good enough, so it is up to you decide!

**Comment by tabacitu** [comment]
Thanks for the feedback @MartijnvAdrichem ! 

> Good point that each add-on requires this change! Is that something you can do?

Of course, we have a TODO above, to adopt this new config in all official backpack packages.

> For me this current fix is good enough, so it is up to you decide!

Agreed. I think the config alone is a good step forward for 4.1. Maybe in 4.2 we'll decide to have the web middleware for Backpack completely separate. We'll see. 

For 4.1, this PR is READY TO MERGE imho.

**Comment by tabacitu** [comment]
Merged into ```v4dot1```. This PR will automatically get closed when 4.1 is launched.
Until then, let's leave it open because we have TODOs here:
- [ ] make all first-party Backpack add-ons use this configurable web middleware;
- [ ] add to docs;

**Pull request merged**
