### PR TITLE
Fixed: Reorder with uuid primary key

### PR DESCRIPTION
**Pull request by karandatwani92**
## WHY
Resolving #4961 

### Is it a breaking change?
NO

### CODE REVIEW

**Comment by tabacitu** [comment]
OMFG you managed to fix this without needing to edit the nestedSortable JS? That makes me so happy, thanks @karandatwani92 . Again, if this is ready to review, please un-assign your self and assign @pxpm , he's in charge of reviewing and merging 5.5.x releases.

**Comment by tabacitu** [comment]
PS. Always helpful to be clear that the PR is ready in a message in the thread, for example "_Hey @pxpm this is ready for review. Could you please give it a read and test?_"

**Review by pxpm — CHANGES_REQUESTED** [review]
Hey @karandatwani92 clever solution here 👍  But something hitched me about it ... having other stuff than numerical ids is common these days, and this solution felt more like a workaround for a lot of common scenarios.

I dig a little bit more on the problem (it was easier after you pointed it out 🙏 ) and found that the JS script provides an extra `expression` configuration key that is used in conjunction with `toArray()`. 

From my tests something like `arraied = $('ol.sortable').nestedSortable('toArray', {startDepthCount: 0, expression: /(.+)_(.+)/ });` would work for us. 

Another thing that I noticed, but it's also happening in master so I think was not related with this PR, is that the first element sent in the array always has null `item_id` and `depth = 0`.
image

It seems to don't happen when `startDepthCount: 1`, but I am thinking it may have implications with other plugin configurations ? like when you define root or stuff like that that goes to depth 0 ?? Can you give this an investigation too ? 
If you find something worth fixing, please create a new PR for it to keep this one simple and clean.

Thanks @karandatwani92 🙏

**Comment by karandatwani92** [comment]
@StyleCIBot doesn't want to keep this PR simple and clean. In actual, this PR is a **one line fix**.

**Comment by tabacitu** [comment]
Did you guys just add boobs to the code?! 😅

225375392-8a53d95e-bfb7-413c-9275-6f9254913cb9


I'm not complaining... but just sayin' In fact... maybe that's exactly what Backpack was missing! 😅

**Comment by tabacitu** [comment]
@karandatwani92 try to pull `main` into this branch, then push again. I've forced StyleCI to do the same changes on `main`, so when you do that, it should no longer show them in the diff.

**Comment by pxpm** [comment]
Thank you @karandatwani92 , merged into master 🙏 

Have other stuff to tag too, so I will tag a new version later today!

@tabacitu having a kid that is breastfeed shows you the real power of boobs. Backpack with boobs it's a life insurance 🙏

**Pull request merged**
