### PR TITLE
Fixed issue #616

### PR DESCRIPTION
**Pull request by promatik**
The variable was arriving at `compactFakeFields` as null, so it won't be treated as a fake field, backpack would try to store it on its own column.
By replacing `isset` by `array_key_exists`, the key exists as null, so it's treated as a fake field.

### CODE REVIEW

**Comment by lloy0076** [comment]
I wonder if this "fix" will suddenly break any code that relies on the bug?

**Comment by promatik** [comment]
@lloy0076 I don't believe this fix will break any previous code because the fields, while not null, were being stored in the fake columns (as expected). If the fields were null, this error would happen. Probably, to avoid this error, everyone was adding validation rules to the request, in my case I wanted the field to be nullable.

**Comment by tabacitu** [comment]
This is a great fix, thank you @promatik !

**Comment by tabacitu** [comment]
Merged it into DEV, will be available to everyone shortly.

**Pull request closed without merging**
