### PR TITLE
[Feature] Input - Date Picker

### PR DESCRIPTION
**Pull request by OwenMelbz**
**Summary**

Simple datepicker using bootstrap-datepicker with optional config/lang
support based off http://bootstrap-datepicker.readthedocs.io/en/latest/

**Preview**
backpack - datepicker - edited 1

**Usage**
```php
//Model
protected $dates = ['published_at'];
protected $casts = ['published_at' => 'date'];
```
```php
//Controller->setUp()
$this->crud->addField([
    'name' => 'published_at',
    'label' => 'Date',
    'type' => 'date_picker',
    'date_picker_options' => [
        'todayBtn' => true,
        'format' => 'mm-dd-yyyy',
        'language' => 'fr'
    ]
]);


```

### CODE REVIEW

**Comment by tabacitu** [comment]
Looks grat and the code seems perfect. Will test and merge tomorrow. Thanks, cheers!

**Comment by tabacitu** [comment]
Hi @OwenMelbz ,

Tried it - it doesn't seem to work for me. It throws an "invalid date" javascript error at the big blog of minified code and it doesn't store the info in the database. And because it's minified, I can't debug it :-) I think it's best we keep it unminified. Any reason why we should uglify it?

Cheers!

**Comment by OwenMelbz** [comment]
@tabacitu what database column type you using? And are you casting the fields? And what's your controller setup like?

Might be some configuration conflict

**Comment by tabacitu** [comment]
Well in my model I have:

```php
	protected $fillable = ['name', 'image', 'photos', 'sum', 'agreed', 'status', 'options', 'address', 'video', 'date', 'color', 'datetime'];
	// protected $hidden = [];
    // protected $dates = [];
    protected $casts = [
    	'photos' => 'array',
    	// 'options' => 'object',
        'address' => 'array',
        // 'video' => 'array',
        'date' => 'date',
        'datetime' => 'datetime'
    ];
```

My db column is ```DATE```:
screen shot 2016-10-11 at 16 15 55

My controller just has this inside ```setup()```:
```php
       $this->crud->addField([
           'name' => 'date',
           'type' => 'date_picker',
           'label' => 'Date',
           'date_picker_options' => [
                'todayBtn' => true,
                'format' => 'mm-dd-yyyy',
                'language' => 'fr'
            ],
           'wrapperAttributes' => [
                'class' => 'form-group col-md-6'
           ]
       ]);
```

**Comment by OwenMelbz** [comment]
@tabacitu might have fixed it :) if you're able to test again would be good!

**Comment by MarcosBL** [comment]
Please take into account Date Picker requires jQuery-ui, either add it in a custom template or in your layout

````javascript
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
````

**Pull request merged**
