### PR TITLE
Add export buttons to Model

### PR DESCRIPTION
**Pull request by nathanielks**
Howdy, @tabacitu!

Thanks again for all the work you've done, it's great. A project I'm working on needed the ability to export data, so I went ahead and added these buttons. I figure this will serve as the starting off point for the PR as we work out additional options (like if you want these displayed conditionally, ability to select buttons, etc).

Anywho, here's a screenshot of what it looks like!

screen shot 2016-09-08 at 7 00 45 pm

### CODE REVIEW

**Comment by guillermohaad** [comment]
Friend +nathanielks Congratulations on this magnificent contribution, I works great.

**Comment by tabacitu** [comment]
Oh man. Looks great :-)

I'll get to a computer tomorrow the earliest, check it and merge it.

Cheers, keep up the good work!!

**Comment by tabacitu** [comment]
@nathanielks ,

Again - great work, man. It's awesome. I _have_ made a few small changes before merge, hope they're ok with you:
- made the buttons a little smaller (```.btn-sm```);
- put the buttons in the top-right corner, so that they don't conflict with the pageLength option and are not so center-stage (for most projects they aren't the main attraction of the page);
screen shot 2016-09-12 at 16 49 09

- by default, I did _not_ enable the export buttons functionality, because most entities won't need them; they are easily enabled by calling ```$this->crud->enableExportButtons();```

About your mention about being able to select which buttons to see - I say all buttons are ok for now and we'll make it more customizable when the time comes. I imagine the API could be something like ```$this->crud->removeExportButton('copyHtml5');``` But if we do that, we'll need to split ```list.blade.php``` into a few partials, because it already is a little bloated and has a lot of conditionals. So I say we leave that to CRUD v4, because that would be a breaking change.

What do you think?

Cheers and thanks again for this great contribution!

**Comment by guillermohaad** [comment]
friends I'm aware of this great project and makes a good instanste update and change the buttons, congratulations to my friends and @tabacitu  and @nathanielks 
tried.

**Comment by nathanielks** [comment]
That all sounds great to me @tabacitu!

**Pull request merged**
