### PR TITLE
Update crud.php

### PR DESCRIPTION
**Pull request by petyots**
Add the new save button translations

### CODE REVIEW

**Comment by tabacitu** [comment]
Wow. That was fast. Thank you! :-)

**Comment by petyots** [comment]
As fast as possible :-> I just upgraded from dev-multilanguage btw everything works like a charm, the process was breeze :)

**Comment by tabacitu** [comment]
Pfiew! 

Please let me know if you find any new issues - the first 1-2 days after a release I'm in "_stress testing_" mode :-)

Cheers!

**Comment by petyots** [comment]
Yep, i know what you mean i will help the project as much as I can. BTW i just opened new issue about the backpack:crud-controller

**Pull request merged**
