### PR TITLE
$this->SetUp __construct replacement concept

### PR DESCRIPTION
**Pull request by OwenMelbz**
Concept for easier __construct replacement for laravel 5.3+

### CODE REVIEW

**Comment by tabacitu** [comment]
Yeah, this should work. Question: what's the ```tearDown()``` method for?

**Comment by OwenMelbz** [comment]
ha no idea really, added it because most implementations of setUp also have a tearDown that can be called if the user wants to.

e.g we're using it to delete the entries we've just added if we're running ?tearDown=1 in the URL, to keep the database more clean when running automated tests from browserStack

**Comment by tabacitu** [comment]
Oh, ok... I say let's leave the teardown() for when we write the automated tests, then, if we're not going to use it.

Agreed?

**Comment by tabacitu** [comment]
I've pushed the same things separately, without the teardown() function;

One mention though: I've renamed the ```setUp()``` (verb) method to ```setup()``` (noun) because I could foresee A LOT of issues where people would just write that method name wrong and they'd open github issues. Right? :-)

**Comment by OwenMelbz** [comment]
Woo! very happy for this to be added in! solves many issues and is a backwards compatible change :)

**Comment by tabacitu** [comment]
One question: I keep answering people on Github with [thumbs up reaction] and such, like you do in Facebook Chat. Do you get notifications for this or do people think I'm rude and haven't answered? :-)

**Comment by OwenMelbz** [comment]
Ha personally, I haven't received a single notification about them. I just assumed it was you "reacting" to a message, rather than replying

**Pull request closed without merging**
