### PR TITLE
[4.0][Feature][WIP] Use CoreUI instead of AdminLTE (Bootstrap 4 instead of Bootstrap 3)

### PR DESCRIPTION
**Pull request by tabacitu**
Content is now priority numero uno (sidebar and navbar are a lot lower in the visual hierarchy).
Uses flexbox.
Prettier.

Screenshot 2019-06-21 at 11 31 18
Screenshot 2019-06-21 at 11 31 32
Screenshot 2019-06-21 at 11 31 43
Screenshot 2019-06-21 at 11 32 17

### CODE REVIEW

**Comment by ziming** [comment]
Nice! When will it arrive? :)

**Comment by tabacitu** [comment]
@ziming the design itself is pretty much ready. We have quite a few more CRUD features to polish, though. I expect we'll launch in 1 month or soon after the new Laravel version is out.

**Comment by Jamesking56** [comment]
@tabacitu Anything left to do for this? I am happy to help - Been using CoreUI a bit for private projects and I do think it is a better admin panel than AdminLTE :+1:

**Comment by ziming** [comment]
Just curious what will be used. CoreUI or CoreUI Pro?

**Comment by tabacitu** [comment]
@ziming we're using CoreUI free, not Pro. Because Backpack's source is public, we can't use dependencies whose source is closed-source, unfortunately. A lot more work for us - trust, me I know... 😄 

I'll close this issue since the move to CoreUI is now done, and it's been merged into the ```v4``` branch.

**Comment by ziming** [comment]
Is okay. Yea public is better.

**Pull request closed without merging**
