### PR TITLE
Allow decimals in number.blade.php

### PR DESCRIPTION
**Pull request by MarcosBL**
Previous template couldn't be used with decimals because of HTML5 validation + now label click activates field

### CODE REVIEW

**Comment by oscarmlage** [comment]
Please @tabacitu review the PR asap, it's really easy and it would be nice to be able to put decimals in number.blade.php. Thanks in advance.

**Comment by OwenMelbz** [comment]
I don't think this can be merged in its current state. It needs to be configurable, imagine it was like "how many tickets" and it allows you to enter 5.23

Maybe "allow_decimals" param to enable?

**Comment by tabacitu** [comment]
That was my concern too. Maybe a better idea would be to have multiple numer fields:
- integer
- float
?

And we'd keep number as is for backwards-compatibility (it would be the same as integer).

I think this would satisfy all use cases. Right?

**Comment by MarcosBL** [comment]
I understand the backwards compatibility issue, but I really think it should be a param, not a separate field. Otherwise, if we start with integer, float... we would end up as well with "text", "text-readonly", "text-default-value", etc...

If we don't want to touch the defaults for backwards compatibility, then there is no real need for a custom attribute, as we can just pass it in the attributes field, ["step" => "any"], and this PR makes no sense. My concern was the field not having decimals not so obvious at first sight, but I would feel confortable as user with both situations:

- A custom attribute "decimals" true/false that sets/don't the "step=>any" attribute
- Just leave it as is, and maybe add a comment in the doc /* pass an atribute step => any to enable decimals */

Just let me know if you want me to close this or elaborate something in the PR

**Comment by tabacitu** [comment]
@MarcosBL , true, the could be as simple as commenting this into the documentation. I've already done that:
```php
[   // Number
    'name' => 'number',
    'label' => 'Number',
    'type' => 'number',
    // optionals
    // 'attributes' => ["step" => "any"], // allow decimals
    // 'prefix' => "$",
    // 'suffix' => ".00",
],
```

I'll go ahead and merge the part where it was broken - the label and ID were missing, thanks for the fix.

Cheers!

**Comment by tabacitu** [comment]
Also, on the "too many field types note", maybe check out my question here? https://github.com/Laravel-Backpack/CRUD/issues/603
Eager to hear your guys' opinion.

Cheers!

**Pull request merged**
