### PR TITLE
Allow equal height rows to prevent errors displacing fields

### PR DESCRIPTION
**Pull request by b8ne**
Solution for [#638](https://github.com/Laravel-Backpack/CRUD/issues/638)
This should do the trick.

### CODE REVIEW

**Comment by b8ne** [comment]
Setting as false replicates how the view currently functions.
I thought given that this is a small non-breaking change/feature, it shouldn't influence UI changes if not wanted.

**Comment by tabacitu** [comment]
I love this, @b8ne , thank you! 

Just like @lloy0076, I see this as a non-breaking change too. **@b8ne , @MickaelTH do you see any reason why we shouldn't just pop ```style="display: flex;flex-wrap: wrap;"``` in there, without a config option and conditional?** 

IMHO, no need to insert a config option if it "just works" for everybody. Right now I can't figure out a reason why this would be a breaking change or inconvenience for anyone. Just tried it with a few of my projects and it works wonderfully.

**Comment by b8ne** [comment]
Thanks @tabacitu if you're happy to force it then I don't see any problems. Given this all may change in v4, hard coding it in a `style` tag shouldn't be a problem for now.

**Comment by MickaelTH** [comment]
Perfect thanks

**Comment by tabacitu** [comment]
Excellent then! Thank you guys, I just modified & merged it, it will be available in the next few days, as a patch update. Cheers!

**Comment by tabacitu** [comment]
@b8ne work on v4 hasn't even started yet, and it will be a BIG rewrite. So it might take 5-8 months to launch -  just to set expectations low on a launch date :-)

**Pull request merged**
