### PR TITLE
Allow HTML in fields help block

### PR DESCRIPTION
**Pull request by fede91it**

### CODE REVIEW

**Comment by tabacitu** [comment]
Done, thank you!

**Comment by fede91it** [comment]
To you, for the awesome backpack tools!

**Comment by tabacitu** [comment]
Planning on creating a SublimeText plugin/snippets for CRUD (details in https://github.com/Laravel-Backpack/crud/issues/31). Just curious - what editor/IDE do you use?

**Comment by fede91it** [comment]
The last year I switched from Sublime to phpStorm, that I think is a superior IDE.
I have to do a look to Atom, but not for now. However, is interesting this plugin you have in mind! It's like en Emmet for Backpack

**Pull request merged**
