### PR TITLE
[4.0][Feature] Custom save and back action

### PR DESCRIPTION
**Pull request by mariavilaro**
I did the same that https://github.com/Laravel-Backpack/CRUD/pull/576 but I also allow the return url to be any url, not just the list with filters. Why do I need this? I'm developing a full featured child table (as discussed here https://github.com/Laravel-Backpack/CRUD/issues/463) and I added a edit button next to every row, so I need that the save button in the edit form that opens goes back to the "parent" form, not to the entity list. I'm attaching some screenshots to make it easier to understand. 

formulario_edition_with_child_fields
campo_edit_with_custom_back_url

### CODE REVIEW

**Comment by mariavilaro** [comment]
I detected and fixed some bugs in my second commit

**Comment by amipax** [comment]
i'm trying to implement something similar , like in the [imagen](https://imgur.com/ujnANZ0),
i'm have problems to save data to the intermeditate table in store though

**Comment by mariavilaro** [comment]
@amipax this is what I do, this is a Invoice Model with Invoice Details, when saving I need to save the details and calculate totals https://pastebin.com/R9ztrwN7

I'm working in the child forms in a branch in my fork, but it's not ready to publish
https://github.com/mariavilaro/CRUD/tree/child_forms

**Comment by tabacitu** [comment]
Thank you for working on this @mariavilaro - I'm sorry this did not get merged at the time. 

I think you'll be glad to know we've _finally_ decided to merge a solution for this. We're working on it in #2356 - please follow it there if you're interested. It will have ```add```, ```remove``` and ```replace``` functionality.

Thanks again for taking the time to submit the PR. Even if this one did not get merged, I'm very grateful for it. You were right to propose a solution to this, it _is_ something worth solving.

Thanks again.
Cheers!

**Pull request closed without merging**
