### PR TITLE
Fixed the 419 csrf token mismatch/List CRUD operation

### PR DESCRIPTION
**Pull request by JoacinB**
### BEFORE - What was wrong? What was happening before this PR?

Error 419 - Token Mismatch: search@ListOperation

### AFTER - What is happening after this PR?

CRUDs are now being listed

### How did you achieve that, in technical terms?

Adding csrf_token headers to an ajax post configuration

### Is it a breaking change?

No.

### How can we test the before & after?

New backpack project
php artisan backpack:crud tag
Go to Tags section in dashboard
Before: Error 419
After: Shows Tags information

### CODE REVIEW

**Comment by tabacitu** [comment]
Thanks @JoacinB ! I'll ask @pxpm to give this a look and merge. I know he was working on the same problem and we don't want the solutions to overlap in any way.

**Comment by pxpm** [comment]
Hey @JoacinB thanks for the PR 🙏 Much appreciated. 

Unfortunately I don't think it's necessary. For a long time our ajax calls had been setup in https://github.com/Laravel-Backpack/CRUD/blob/f915dea671825e53840430f3fa279c19b45b68c7/src/resources/assets/js/common.js#L4

If you remove that bit of code everything would still work. That code was a left-over from old days, the metatag is called `csrf-token` not `csrf_token` as you see in the code I posted above. 😞 

Your 419 error was related with `APP_URL` in `.env` file not matching the browser url. 

We had pushed a fix today to bassets to address that issue, so you should be able to get basset 1.0.2 with a composer update. 
Please be aware that there is an issue with `basset:fresh` command that we are currently working on the fix. You should run separately `php artisan basset:clear` and `php artisan basset:internalize` as a workaround until we tag 1.0.3 with the tag fix. 

We can still merge this PR if you remove the unused code. A cleanup still a win right? 🥳 

Cheers

**Comment by chrishentges** [comment]
@pxpm I'm having the same exact issue. 419 on every list page and I've checked to make sure the .env APP_URL matches what's in the browser

**Comment by phpMuhammed** [comment]
Hi @tabacitu tabacitu,
There is same error in editable column package.

**Comment by phpMuhammed** [comment]
> Hi @tabacitu, There is same error in editable column package.

knowing that the i check the .env APP_URL

**Comment by pxpm** [comment]
Closing as this is stalled. 

Merged #5255 to address this.

Thanks for the PR @JoacinB , sorry it didn't get merge. 🙏

**Comment by artanmerko** [comment]
This issue is still happening. I am experiencing a 419 Page Expired error when accessing one of the modules in Backpack CRUD. When I submit a form, I get a CSRF token mismatch error, causing the request to fail.


Here are my session settings:

- APP_URL=http://localhost:8000  
- SESSION_DRIVER=database  
- SESSION_LIFETIME=120  
- SESSION_ENCRYPT=false  
- SESSION_PATH=/  
- SESSION_DOMAIN=null  

The issue persists even though my session is stored in the database. Can this issue be reopened?

**Comment by pxpm** [comment]
@artanmerko it's probable that you have an error in your javascript console, or in the network tab, where `common.js` is failing to load. In there is located the script that injects the CSRF token into requests. 

Please try a `php artisan basset:check` to see if basset is properly working. If so, try a `php artisan basset:clear && php artisan basset:cache`. 

Cheers

**Pull request closed without merging**
