### PR TITLE
date field initializations should not rely on wrapper class

### PR DESCRIPTION
**Pull request by DoDSoftware**
Fix for https://github.com/Laravel-Backpack/CRUD/issues/3308

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @DoDSoftware 

Thank you very much for providing the solution for this problem. 

I'm looking at this now, and it seems that this problem applies also to `date_range` and `datetime_picker`. 

Could you update the PR to include the fix in both those fields too, or want me to do it ? 

Thanks,
Pedro

**Comment by DoDSoftware** [comment]
@pxpm Good catch! I'll update those and repush.

**Comment by DoDSoftware** [comment]
@pxpm Tested and updated. Also did a search in the `fields` folder for `('.form-group')` and didn't find any other instances beyond those.

**Review by pxpm — APPROVED** [review]
Thanks @DoDSoftware

**Review by promatik — APPROVED** [review]

**Comment by tabacitu** [comment]
This. Is freaking. AWESOME. Excellent collaboration here guys! Thanks a lot, I can merge this with so much confidence now! MERGED! 😄 It'll be available on Monday like @pxpm said.

**Pull request merged**
