### PR TITLE
Electric purple color palette by default

### PR DESCRIPTION
**Pull request by tabacitu**
This PR brings the electric-purple color palette to Backpack's default published files.
 
Fixes an inconsistency, where people could see the purple-based color palette in the demo, but then when they actually installed backpack their admins would be blue-based.

It could _technically_ be considered a breaking change. But since 4.1 has been out for so little time, and this is just a color change (and a dependency update change), I think it's ok to merge it to master and launch it as a non-breaking change.

### CODE REVIEW

**Comment by quanengineering** [comment]
@tabacitu Could you show me ways to replace this purple color palette in case I want to change it? Thank you.

**Comment by quanengineering** [comment]
I found it, just clone this repo https://github.com/DigitallyHappy/BackStrap and recompiled the CSSs, then copy into `public/packages/@digitallyhappy/backstrap/css`

**Comment by tabacitu** [comment]
@quanengineering sure - the bundle file is actually created in _this_ package (Backpack/CRUD) using Laravel Mix. Take a look at [webpack.mix.js](https://github.com/Laravel-Backpack/CRUD/blob/master/webpack.mix.js) - that explain what it does exactly. The comment at the top will explain in detail how _we, Backpack maintainers_ use the file to generate `bundle.css` and `bundle.js`. 

If you've created different CSS files for Backstrap (with no electric purple) the easiest change you could do would probably to change the paths of the Backstrap files, to pick up _your_ file, instead of the one fetched using `npm install`. Or modifying the files right then and there in `node_modules` before bundling them - even if that's a bit messy.

So a quick process would probably be:

1. `cd vendor/backpack/crud`
2. `npm install`
3. copy-paste your custom CSS files over the ones at `vendor/backpack/crud/node_modules/@digitallyhappy/backstrap`
4. `npm run prod`

Hope it helps!

**Comment by quanengineering** [comment]
Thanks @tabacitu, I did it 🚀

**Pull request merged**
