### PR TITLE
[4.1][Merged] Remove deprecated helpers and dependency

### LINKED ISSUE #2502: [4.1] Remove laravel/helpers dependency
There's no reason to keep ```laravel/helpers``` as a dependency, since inside our package we can use ```Str::smth()``` and ```Arr::smth()```. I'm now trying to provide Laravel 7 support, and it's very difficult because ```laravel/helpers``` doesn't _officially_ support it yet. 

To do: 
- [x] go through [all helpers in 5.6](https://laravel.com/docs/5.6/helpers), see if we use them in first-party Backpack package, and replace them with their ```Str``` or ```Arr``` equivalent.

Too bad there's no Laravel Shift for this - would buy that in a second.

### PR DESCRIPTION
**Pull request by jasonmccreary**
This is the result of running a custom [Shift](https://laravelshift.com) script to convert the global helper functions to their equivalent `Str` and `Arr` class methods. These helper functions were deprecated in Laravel 5.8 and removed in Laravel 6.

---
Closes #2502

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@tabacitu, here it is. I ran against the `master` branch. However, if you'd rather I run against `4.1` or another more current branch or include other folders, let me know. Only takes a second. 👍

**Comment by ziming** [comment]
Thank you!

**Comment by tabacitu** [comment]
Wow. Just... wow. Thanks a lot @jasonmccreary , this would have been so tedious... I have to tell you, from the outside... this looks like a freakin superpower. Makes me wonder how many _other_ custom shifts you have, lying around. I might actually take you up on the offer - and ask for a second run on ```4.1``` after we've merged the 10+ PRs we have lying around.

Q: **Which one of the standard shifts does this str to Str:: update?**

----

Note to self - 4.1 Upgrade Docs:
- [ ] Backpack 4.1 no longer uses ```laravel/helpers```. So please make sure you've added the ```Str``` and ```Arr``` aliases in your ```config/app.php```, when you've upgraded to Laravel 5.8/6/7:

```php
    'aliases' => [
        'Arr'       => Illuminate\Support\Arr::class,
        'Str'       => Illuminate\Support\Str::class,
    ],
```
- [ ] If you're still using the string&array helpers _in your custom code_ (Controllers, Models, Views, etc), you should do _one_ of the following:
   - (A) install the helpers back in your project, using ```composer require laravel/helpers```;
   - (B) go through your custom code and manually replace things like ```str_slug``` with ```Str::slug``` and ```array_first``` with ```Arr::first()```; you can use the [L5.6 docs for a list of all helpers](https://laravel.com/docs/5.6/helpers), and find-and-replace;
   - (C) Purchase the 5.8/6/7 [Laravel Shift](https://laravelshift.com/shifts) for $9-19 and get an automatic PR with the above, in addition to most other Laravel upgrade steps.

**Comment by tabacitu** [comment]
Update: merged into ```4.1```. This PR will get closed automatically when 4.1 is launched.

**Comment by jasonmccreary** [comment]
@tabacitu no problem. Just mention me on the new PR or issue and let me know what to rerun it against. Feel free to close this one.

Shift treats any deprecation like a removal. So this was done as part of the [Laravel 5.8 Shift](https://laravelshift.com/upgrade-laravel-5.7-to-laravel-5.8). I also repeated it in the [Laravel 6.x Shift](https://laravelshift.com/upgrade-laravel-5.8-to-laravel-6.0) for convenience. And it's part of the [Laravel Fixer](https://laravelshift.com/laravel-code-fixer).

And yes, I have a crapload of custom Shifts. Helping promote the Laravel 7 release this past week has given me some ideas for making them more accessible before Laravel 8.

**Pull request merged**
