### PR TITLE
Fixed icons and alignment on non responsive datatable

### PR DESCRIPTION
**Pull request by promatik**
Fix for https://github.com/Laravel-Backpack/CRUD/issues/4479.

### BEFORE - What was wrong? What was happening before this PR?

Table header was not aligned with the table body.

image

### AFTER - What is happening after this PR?

Everything is aligned.
**AND ALSO**, the sorting arrow icons are fixed on non responsive table 👌

image

### Is it a breaking change?

No, but users must publish assets to get the updated css.

### How can we test the before & after?

View https://demo.backpackforlaravel.com/admin/fluent-monster with the new and the old `bundle.css`.

### CODE REVIEW

**Comment by promatik** [comment]
@tabacitu, in order to fix this issue, I had to manually change the file `node_modules\@digitallyhappy\backstrap\src\scss\_custom.scss`.

Because the published file is not up to date with the repo on github.

Basically, this PR is merged, but not tagged https://github.com/DigitallyHappy/BackStrap/pull/101.

---
I changed the file and compiled these `bundle.css` and `blue-bundle.css`, if you try to build on your side, it will not work because you don't have this file up to date.

**Comment by tabacitu** [comment]
Awesome, thanks @promatik & @maurohmartinez .

@promatik - do me a favor. Can you please run `npm build` on Backstrap, and create a PR with that? I have a `node-gyp` error on my machine (freaking again), spent 30+ min trying to fix it, and I really don't want to spend the rest of my day fixing it. Fucking NPM... After you submit that PR to digitallyhappy/backstrap, I can easily tag 0.4.1.

Thanks!

**Comment by pxpm** [comment]
@mnightingale what is broken ? Can you share a screenshot ?

Cheers

**Comment by mnightingale** [comment]
@pxpm It's the same issue this PR fixed previously, more detail is in #4479 

Basically with non-responsive table; when `CRUD::disableResponsiveTable()` has been called.
The header row doesn't match the data and footer rows, so the columns don't line up.

image

Screenshot is from https://demo.backpackforlaravel.com/admin/fluent-monster

As far as I could tell from testing a bunch of versions I think `5.3.5` is the last release that it worked correctly in, the only thing that jumps out at me is 5.3.6 upgraded npm packages (I had to skip that version because it was a broken release), so maybe there is some competing CSS somewhere, I spent sometime looking at it but I couldn't find what had changed.

Thanks

**Comment by pxpm** [comment]
Thanks for the feedback and for the time spent. 
 I will investigate and get back to you with news.

Cheers

**Comment by tabacitu** [comment]
Ouch! @pxpm please talk to @promatik too - he might know what went wrong.

**Pull request merged**
