### PR TITLE
[5.0][Feature][WIP] Add support for dimsav/translatable

### PR DESCRIPTION
**Pull request by tabacitu**
# WARNING

Not tested. Some things might not work. Huge change. Big improvement. Much wow.

### CODE REVIEW

**Comment by AbbyJanke** [comment]
@tabacitu I wanted to maybe toss the idea of this being apart of backpack v4? Since we are already making some major and likely breaking changes this seems a decent time to add it in. @lloy0076 since you have been working a lot on this, thoughts?

**Comment by tabacitu** [comment]
@AbbyJanke totally agree - let’s move this to 4.0

**Comment by bedoz** [comment]
OMG, it's passed a lot of time since I saw this page, and there's a lot of errors on commits.

Anyway i work hardly on this branch and I need to explain to you what I've done.

I've made a lot of changes not just to have compatibility with dimsav/translatable but also a lot of other improvement.

I can explain with a list:
- Added support to dimsav/translatable
- Added support to sort and search on translatable fields
- Fixed count on pagination with translations
- Added Facebook support to video field
- Added method to add and remove save actions
- Added support for querystring in crud (i use it for filtering content, by relations)
- Added support for multiple sorting in lists
- Fix upload field that has no hidden input so it cannot upload files

Now I have merged every master update to my release so it is updated with today commits.

Now I'm trying to fix error that block merging.

Anyway I have not already tested since 3.5 came out. So be carefull before use my branch on production.
Before 3.5 merge all were working like a charm, but now it must be checked in depth.

Hope to gave to all of you a nice feedback

**Comment by bedoz** [comment]
Maybe someone can help me to solve issue with a test.

Problems seems to be a test with FakeColumnsModel.php that use SpatieTranslatable and that return a null on setTranslation.

Someone can help me? so i can clean brach for a possible merge.

Thank you so much.

**Comment by tabacitu** [comment]
Since few people have actually requested this, and we've already got tons of breaking changes in v4, let's postpone this until v5.

**Comment by bedoz** [comment]
> Since few people have actually requested this, and we've already got tons of breaking changes in v4, let's postpone this until v5.

Hi Cristian,
I'm using my version without any issue and i'm continuing to maintain it often updating my branch every few weeks from master branch and solving issues if something happen.
I had also updated my scripts to use new version of translatable that is not from dimsav anymore (he leave the project) but from astronomic.
I don't understand why I have issue with travis-ci but my release is working at the moment.

I think it's compatible with v4 already (if modification are committed to master branch).

**Comment by Stiropor** [comment]
Aw such a shame this isn't going into v4 (not pushing anything tho, great work guys!), which looks amazing! We're looking for new backend for our projects and Backpack seems the best for now (also checking Twill). Looking forward to this :)

**Comment by bedoz** [comment]
I'm studying v4 to re-implements all changes to new version.
I need some time to understand how to do it.
I think the best way is with a new branch with all those breaking changes.
Keep in touch.

**Comment by tabacitu** [comment]
Thank you so much @bedoz . The only non-obvious change to how Backpack v4 works differently from v3 is [this one](https://github.com/Laravel-Backpack/CRUD/pull/1997#issuecomment-536255543). Otherwise, if you upgrade one project to Backpack v4 you'll pretty much understand how it's different - since you manually make the changes in the upgrade guide, you should understand how things are different in v4 vs v3. Let me know if that's not the case, and you don't understand something.

**Comment by tabacitu** [comment]
I've decided that, for now, adding `dimsav-translatable` support isn't a priority. Very few people have actually asked for it - looks like `spatie/laravel-translatable` is good enough for most people.

Since this PR is very very old, it can't be merged as-is. Adding dimsav support would require a different PR anyway, so I'm going to close this.

If anybody stumbles upon this and wants support for `dimsav/translatable`, please reply here - the conversation is open even if the PR is closed.

Cheers!

**Pull request closed without merging**
