### PR TITLE
[4.1] Fluent syntax for Fields, Columns, Filters

### PR DESCRIPTION
**Pull request by tabacitu**
This PR adds a new (optional) way to work with Columns, Fields.

Features this works on:
- [x] Fields
- [x] Columns
- [x] Filters in https://github.com/Laravel-Backpack/CRUD/pull/2572
- [x] Buttons in https://github.com/Laravel-Backpack/CRUD/pull/2636

Todo:
- [x] ```->after('title')```
- [x] ```->before('title')```
- [x] ```->makeFirst()```
- [x] ```->makeLast()```
- [x] ```->remove()``` - remove the field/column entirely;
- [x] ```->forget('label')``` - to forget the "label" attribute for that field/column; or maybe the more explicit ```->removeAttribute('label')``` / ```->forgetAttribute('label')``` would be better;

## How to use

On your ProductCrudController, ```use CrudColumn as Column;``` and then you can use that ```Column``` helper class, to add a column or modify an existing column. Each method you use on the ```Column``` helper class is assumed to be an attribute your want on that column.

So instead of doing this (the default):
```php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\MonsterRequest as StoreRequest;
// VALIDATION: change the requests to match your own file names if you need form validation
use Backpack\CRUD\app\Http\Controllers\CrudController;

class MonsterCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;

    public function setup()
    {
        $this->crud->setModel('App\Models\Monster');
        $this->crud->setRoute(config('backpack.base.route_prefix').'/monster');
        $this->crud->setEntityNameStrings('monster', 'monsters');
    }

    public function setupListOperation()
    {
        $this->crud->addColumns([
            'text',
            'textarea',
            [
                'name'  => 'image', // The db column name
                'label' => 'Image', // Table column heading
                'type'  => 'image',
            ],
            [
                'name'  => 'base64_image', // The db column name
                'label' => 'Base64 Image', // Table column heading
                'type'  => 'image',
            ],
            [
                'name'  => 'checkbox',
                'label' => 'Boolean',
                'type'  => 'boolean',
                // optionally override the Yes/No texts
                'options' => [0 => 'Yes', 1 => 'No'],
            ],
            [
                'name'  => 'checkbox', // The db column name
                'key'   => 'check',
                'label' => 'Agreed', // Table column heading
                'type'  => 'check',
            ],
            [
                'name'     => 'created_at',
                'label'    => 'Created At',
                'type'     => 'closure',
                'function' => function ($entry) {
                    return 'Created on '.$entry->created_at;
                },
            ],
            [
                'name'  => 'name', // The db column name
                'label' => 'Date', // Table column heading
                'type'  => 'date',
            ],
            [
                'name'  => 'name', // The db column name
                'label' => 'Datetime', // Table column heading
                'type'  => 'datetime',
            ],
            [
                'name'  => 'email', // The db column name
                'label' => 'Email Address', // Table column heading
                'type'  => 'email',
            ],
            [
                // show both text and email values in one column
                // this column is here to demo and test the custom searchLogic functionality
                'name'          => 'model_function',
                'label'         => 'Text and Email', // Table column heading
                'type'          => 'model_function',
                'function_name' => 'getTextAndEmailAttribute', // the method in your Model
                'searchLogic'   => function ($query, $column, $searchTerm) {
                    $query->orWhere('email', 'like', '%'.$searchTerm.'%');
                    $query->orWhere('text', 'like', '%'.$searchTerm.'%');
                },
            ],
            [
                'name'  => 'number', // The db column name
                'label' => 'Number', // Table column heading
                'type'  => 'number',
            ],
            [
                'name'        => 'radio',
                'label'       => 'Radio',
                'type'        => 'radio',
                'options'     => [0 => 'Draft', 1 => 'Published', 2 => 'Other'],
            ],
            [
                // 1-n relationship
                'label'     => 'Select', // Table column heading
                'type'      => 'select',
                'name'      => 'select', // the column that contains the ID of that connected entity;
                'entity'    => 'category', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model'     => "Backpack\NewsCRUD\app\Models\Category", // foreign key model
            ],
            [ // select_from_array
                'name'    => 'select_from_array',
                'label'   => 'Select_from_array',
                'type'    => 'select_from_array',
                'options' => ['one' => 'One', 'two' => 'Two', 'three' => 'Three'],
            ],
            [
                // select_multiple: n-n relationship (with pivot table)
                'label'     => 'Select_multiple', // Table column heading
                'type'      => 'select_multiple',
                'name'      => 'tags', // the method that defines the relationship in your Model
                'entity'    => 'tags', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model'     => "Backpack\NewsCRUD\app\Models\Tag", // foreign key model
            ],
            [
                'name'  => 'video', // The db column name
                'label' => 'Video', // Table column heading
                'type'  => 'video',
            ],
        ]);
    }
```

Developers can do this:
```php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\MonsterRequest as StoreRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Backpack\CRUD\app\Library\CrudPanel\CrudPanelFacade as CRUD;
use Backpack\CRUD\app\Library\CrudPanel\CrudColumn as Column;

class MonsterCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;

    public function setup()
    {
        $this->crud->setModel('App\Models\Monster');
        $this->crud->setRoute(config('backpack.base.route_prefix').'/monster');
        $this->crud->setEntityNameStrings('monster', 'monsters');
    }

    public function setupListOperation()
    {
        Column::name('text');
        Column::name('textarea');
        Column::name('image')->type('image');
        Column::name('base64_image')->type('base64_image');
        Column::name('checkbox')->type('boolean')->options([
            0 => 'Yes',
            1 => 'No',
        ]);
        Column::name('checkbox')->type('check')->key('check');
        Column::name('created_at')->type('closure')->function(function($entry) {
            return 'Created on '.$entry->created_at;
        });
        Column::name('date')->type('date');
        Column::name('datetime')->type('datetime');
        Column::name('email')->type('email');
        Column::name('model_function')->type('model_function')->label('Text and Email')
            ->function_name('getTextAndEmailAttribute')
            ->searchLogic(function($query, $column, $searchTerm) {
                $query->orWhere('email', 'like', '%'.$searchTerm.'%');
                $query->orWhere('text', 'like', '%'.$searchTerm.'%');
        });
        Column::name('number')->type('number');
        Column::name('radio')->type('radio')->options([ 0 => 'Draft', 1 => 'Published', 2 => 'Other' ]);
        Column::name('select')->type('select')->entity('category')->attribute('name');
        Column::name('select_from_array')->type('select_from_array')->options([ 'one' => 'One', 'two' => 'Two', 'three' => 'Three' ]);
        Column::name('tags')->type('select_multiple')->entity('tags')->attribute('name');
        Column::name('video')->type('video');
    }
```

I've only implemented the basics for Columns to see how it would look&feel and get feedback. But it works, and works well. So far, my thoughts:

PROs:
- non-breaking change;
- arguably more intuitive;
- syntax is a lot shorter when you need to define more than 1 attribute for a field/column;
- fixes an annoyance for people who enjoy writing fluent syntax rather than arrays;
- we've always planned for generated CRUDs to explicitly define each column and field, instead of using ```setFromDb()```; in this future where a generated ProductCrudController has each column explicitly mentioned, it's a lot easier to just add a new attribute; with the old syntax, you'd have to first change the argument from a string (```title```) to an array (```['name' => 'title']```) and _then_ add a ```type``` attribute; with the new one, just do ```->type('whatever')```;

CONs:
- since there's no real object for each column type (only the ```CrudColumn``` helper class), IDEs will _still_ not suggest the mandatory attributes people need to declare; so this does not (and will not) address that issue;
- one more syntax to maintain and support;
- documentation could get confusing with more than one syntax - which syntax do we recommend? why?! 

For comparison, all of the below will do the exact same thing:

### One attribute
```php
$this->crud->addColumn('title'); // the old shorthand
CRUD::addColumn('title'); // the new-ish Facade shorthand

$this->crud->addColumn(['name' => 'title']); // the old explicit
CRUD::addColumn(['name' => 'title']); // the new-ish Facade explicit

CRUD::column('title'); // the new fluent syntax (built-in)
Column::name('title'); // the new fluent syntax (after using the CrudColumn helper as Column)
```

### Two attributes
```php
# $this->crud->addColumn('price'); // the old shorthand does NOT work for multiple attributes
# CRUD::addColumn('price'); // the new-ish Facade shorthand does NOT work for multiple attributes

$this->crud->addColumn(['name' => 'price', 'type' => 'number']); // the old explicit
CRUD::addColumn(['name' => 'price', 'type' => 'number']); // the new-ish Facade explicit

CRUD::column('price')->type('number'); // the new fluent syntax (built-in)
Column::name('price')->type('number'); // the new fluent syntax (after using the CrudColumn helper as Column)
```

**Thoughts anyone? Likes/dislikes? Good/bad? Better/worse?**

### CODE REVIEW

**Comment by tabacitu** [comment]
Updated: just added the same thing for Fields. Just the basics. 

The old syntax:

```php
    protected function setupCreateOperation()
    {
        $this->crud->setValidation(StoreRequest::class);
        $this->crud->setOperationSetting('contentClass', 'col-md-12');

        $this->crud->addField([
            'name'  => 'text',
            'label' => 'Text',
            'type'  => 'text',
            'tab'   => 'Simple',
            'wrapperAttributes' => [
                'class' => 'form-group col-md-6',
            ],
        ]);

        $this->crud->addField([
            'name'  => 'email',
            'label' => 'Email',
            'type'  => 'email',
            'tab'   => 'Simple',
            'wrapperAttributes' => [
                'class' => 'form-group col-md-6',
            ],
        ]);

        $this->crud->addField([   // Textarea
            'name'  => 'textarea',
            'label' => 'Textarea',
            'type'  => 'textarea',
            'tab'   => 'Simple',
        ]);

        $this->crud->addField([   // Number
            'name'  => 'number',
            'label' => 'Number',
            'type'  => 'number',
            // optionals
            // 'attributes' => ["step" => "any"], // allow decimals
            // 'prefix' => "$",
            // 'suffix' => ".00",
            'tab' => 'Simple',
            'wrapperAttributes' => [ 'class' => 'form-group col-md-3' ],
        ]);

        $this->crud->addField([   // Number
            'name'  => 'float',
            'label' => 'Float',
            'type'  => 'number',
            // optionals
            'attributes' => ['step' => 'any'], // allow decimals
            // 'prefix' => "$",
            // 'suffix' => ".00",
            'tab' => 'Simple',
            'wrapperAttributes' => [ 'class' => 'form-group col-md-3' ],
        ]);

        $this->crud->addField([   // Number
            'name'  => 'number_with_prefix',
            'label' => 'Number with prefix',
            'type'  => 'number',
            // optionals
            // 'attributes' => ["step" => "any"], // allow decimals
            'prefix' => '$',
            // 'suffix' => ".00",
            'fake'     => true,
            'store_in' => 'extras',
            'tab'      => 'Simple',
            'wrapperAttributes' => [ 'class' => 'form-group col-md-3' ],
        ]);

        $this->crud->addField([   // Number
            'name'  => 'number_with_suffix',
            'label' => 'Number with suffix',
            'type'  => 'number',
            // optionals
            // 'attributes' => ["step" => "any"], // allow decimals
            // 'prefix' => "$",
            'suffix'   => '.00',
            'fake'     => true,
            'store_in' => 'extras',
            'tab'      => 'Simple',
            'wrapperAttributes' => [ 'class' => 'form-group col-md-3' ],
        ]);

        $this->crud->addField([   // Number
            'name'     => 'text_with_both_prefix_and_suffix',
            'label'    => 'Text with both prefix and suffix',
            'type'     => 'number',
            'prefix'   => '@',
            'suffix'   => "<i class='fa fa-home'></i>",
            'fake'     => true,
            'store_in' => 'extras',
            'tab'      => 'Simple',
            'wrapperAttributes' => [ 'class' => 'form-group col-md-6' ],
        ]);

        $this->crud->addField([   // Password
            'name'  => 'password',
            'label' => 'Password',
            'type'  => 'password',
            'tab'   => 'Simple',
            'wrapperAttributes' => [ 'class' => 'form-group col-md-6' ],
        ]);

        $this->crud->addField([
            'name'    => 'radio', // the name of the db column
            'label'   => 'Status (radio)', // the input label
            'type'    => 'radio',
            'options' => [ // the key will be stored in the db, the value will be shown as label;
                0 => 'Draft',
                1 => 'Published',
                2 => 'Other',
            ],
            // optional
            'inline' => true, // show the radios all on the same line?
            'tab'    => 'Simple',
        ]);

        $this->crud->addField([   // Checkbox
            'name'  => 'checkbox',
            'label' => 'I have not read the terms and conditions and I never will (checkbox)',
            'type'  => 'checkbox',
            'tab'   => 'Simple',
        ]);

        $this->crud->addField([   // Hidden
            'name'    => 'hidden',
            'type'    => 'hidden',
            'default' => 'hidden value',
            'tab'     => 'Simple',
        ]);
    }
```

can now be written like this:

```php

    protected function setupCreateOperation()
    {
        $this->crud->setValidation(StoreRequest::class);
        $this->crud->setOperationSetting('contentClass', 'col-md-12');

        Field::name('text')
            ->label('Text')
            ->type('text')
            ->tab('Simple')
            ->wrapperAttributes([ 'class' => 'form-group col-md-6' ]);

        Field::name('email')
            ->label('Email')
            ->type('email')
            ->tab('Simple')
            ->wrapperAttributes([ 'class' => 'form-group col-md-6' ]);

        Field::name('textarea')
            ->label('Textarea')
            ->type('textarea')
            ->tab('Simple');

        Field::name('number')
            ->label('Number')
            ->type('number')
            ->tab('Simple')
            ->wrapperAttributes([ 'class' => 'form-group col-md-3' ]);

        Field::name('float')
            ->label('Float')
            ->type('number')
            ->attributes(['step' => 'any'])
            ->tab('Simple')
            ->wrapperAttributes([ 'class' => 'form-group col-md-3' ]);

        Field::name('number_with_prefix')
            ->label('Number with prefix')
            ->type('number')
            ->prefix('$')
            ->tab('Simple')
            ->wrapperAttributes([ 'class' => 'form-group col-md-3' ])
            ->fake(true)->store_in('extras');

        Field::name('number_with_suffix')
            ->label('Number with suffix')
            ->type('number')
            ->suffix('.00')
            ->fake(true)->store_in('extras')
            ->tab('Simple')
            ->wrapperAttributes([ 'class' => 'form-group col-md-3' ]);

        Field::name('text_with_both_prefix_and_suffix')
            ->label('Text with both prefix and suffix')
            ->type('text')
            ->prefix('@')
            ->suffix('<i class="fa fa-home"></i>')
            ->fake(true)->store_in('extras')
            ->tab('Simple')
            ->wrapperAttributes([ 'class' => 'form-group col-md-6' ]);

        Field::name('password')
            ->type('password')
            ->tab('Simple')
            ->wrapperAttributes(['class' => 'form-group col-md-6']);

        Field::name('radio')
            ->label('Status (radio)')
            ->type('radio')
            ->options([ // the key will be stored in the db, the value will be shown as label;
                0 => 'Draft',
                1 => 'Published',
                2 => 'Other',
            ])
            ->inline(true)
            ->tab('Simple');

        Field::name('checkbox')
            ->label('I have not read the terms and conditions and I never will (checkbox)')
            ->type('checkbox')
            ->tab('Simple');

        Field::name('hidden')
            ->type('hidden')
            ->default('hidden value')
            ->tab('Simple');
    }
```

So it looks like there's not a lot of benefit in using this new syntax for super-complicated Create/Update operations. It's arguably a little cleaner and nicer, but not by much.

Obviously, it would still be better for normal, every-day Create/Update operations, where entities have 5-15 attributes, with not a lot of modifications to the fields.

Food for thought. Feedback welcome.

**Comment by pxpm** [comment]
I like the fluent syntax, I think the code looks cleaner that way but it works best for small columns/fields:

```php
Column::name('articles')->type('relationship')->inline_create(['entity' => 'article'])->ajax(true)->multiple(false)->wrapperAttributes(['one' => 'one', 'two' => 'two', 'three' => 'three'])
```
In this scenario I think is far way easier to see:

```php
Column::add([
'name' => 'articles',
'type' => 'relationship',
'inline_create' => ['entity' => 'article'],
'ajax' => true,
'multiple' => false,
'wrapperAttributes' => ['one' => 'one', 'two' => 'two', 'three' => 'three']
]);
```

But in general for people used to fluent syntax it should not make that much difference as it does for me that am used with array defining.

I think as it is, we could mention that it is possible to use, but keep the examples with arrays. 

If we ever make columns, fields IDE compatible, then I think fluent + IDE autocompletion is the way to go. 

Best,
Pedro

**Comment by tabacitu** [comment]
Yup, for complicated usage you maybe only save 2 lines per declaration (the first and last, where you open and close the array). In your example:

```php
CRUD::addColumn([
    'name' => 'articles',
    'type' => 'relationship',
    'inline_create' => ['entity' => 'article'],
    'ajax' => true,
    'multiple' => false,
    'wrapperAttributes' => ['one' => 'one', 'two' => 'two', 'three' => 'three']
]);

// vs

CRUD::column('articles')
	->type('relationship')
	->inline_create(['entity' => 'article'])
	->ajax(true)
	->multiple(false)
	->wrapperAttributes(['one' => 'one', 'two' => 'two', 'three' => 'three']);

// or

Column::name('articles')
	->type('relationship')
	->inline_create(['entity' => 'article'])
	->ajax(true)
	->multiple(false)
	->wrapperAttributes(['one' => 'one', 'two' => 'two', 'three' => 'three']);

```

**Comment by andrefigueira93** [comment]
Hi Tabacitu!

I don't know if you are already working on it, but what do you think about making linked relations?

Maybe we can do something like this:
```
{{-- single relationships (1-1, 1-n) --}}
<span>
    <a href="{{ env('APP_URL') }}/admin/{{ $column['entity'] }}/{{ $entry[$column['name'].'_id'] }}/show">
        <b>
        <?php
            $attributes = $crud->getModelAttributeFromRelation($entry, $column['entity'], $column['attribute']);
            if (count($attributes)) {
                echo e(str_limit(strip_tags(implode(', ', $attributes)), array_key_exists('limit', $column) ? $column['limit'] : 40, '[...]'));
            } else {
                echo '-';
            }
            ?>
        </b>
    </a>
</span>
```

And maybe this feature would be available through the ```->linked()``` attribute.

```
Column::name('articles')
	->type('relationship')
	->inline_create(['entity' => 'article'])
	->linked()
	->ajax(true)
	->multiple(false)
	->wrapperAttributes(['one' => 'one', 'two' => 'two', 'three' => 'three']);
```

It's a good time to implement it =)

Hope you think about it

**Comment by andrefigueira93** [comment]
Hi Tabacitu!

I don't know if you are already working on it, but what do you think about making linked relations?

Maybe we can do something like this:
```
{{-- single relationships (1-1, 1-n) --}}
<span>
    <a href="{{ env('APP_URL') }}/{{ config('backpack.base.route_prefix') }}/{{ $column['entity'] }}/{{ $entry[$column['name']] }}/show">
        <b>
        <?php
            $attributes = $crud->getModelAttributeFromRelation($entry, $column['entity'], $column['attribute']);
            if (count($attributes)) {
                echo e(str_limit(strip_tags(implode(', ', $attributes)), array_key_exists('limit', $column) ? $column['limit'] : 40, '[...]'));
            } else {
                echo '-';
            }
            ?>
        </b>
    </a>
</span>
```

And maybe this feature would be available through the ```->linked()``` attribute.

```
Column::name('setor_id')
	->type('relationship')
	->entity('setor')
	->attribute('nome')
	->linked();
```

to-tabacitu

It's a good time to implement it =)

Hope you think about it

**Comment by pxpm** [comment]
Hey Filipe. Have a look at PR that's called column anchor.

Best,
Pedro

A sábado, 7/03/2020, 21:20, Felipe Freitas <notifications@github.com>
escreveu:

**Comment by andrefigueira93** [comment]
Wow! You guys are doing a wonderful job over there.
Will be waiting for it on future releases =D

But will stay with my own solution for now xD

**Comment by tabacitu** [comment]
Todo - solve the following known issues:
- [ ] ```key``` doesn't work properly for Columns;
- [ ] ```visible_key``` on multidimensional_array Column didn't work;
- [ ]

**Comment by sergeyugai** [comment]
I'll jump in here again with my https://github.com/sergeyugai/backpack-fields-as-classes

With my package, you have a separate class for each type, allowing IDE to hint different methods for different field types / column types.
And they are all autogenerated from your docs (but I have not tested that with 4.1 yet).

And this is also non-breaking to any existing code.

**Comment by tabacitu** [comment]
@sergeyugai , I wrote a short novel to reply to your message 😄 So I've created another issue with it here - https://github.com/Laravel-Backpack/CRUD/issues/2604 

I think there's the potential for something very VERY exciting:
This PR + your package = ❤️  

I'm sorry that forgot all about your package. But maybe in 4.1.x we make it even easier for it to generate classes (accurately) and recommend people install it. Exciting times ahead! Details in https://github.com/Laravel-Backpack/CRUD/issues/2604.

**Comment by sergeyugai** [comment]
@tabacitu i am glad its been finally noticed :) i'll check out #2604 and let you know my thoughts on that

**Pull request merged**
