### PR TITLE
Do not register reset password routes if users do not have email

### PR DESCRIPTION
**Pull request by danilopolani**
Fixes https://github.com/Laravel-Backpack/CRUD/issues/3256

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @danilopolani 

I think now I got the big picture, I think I don't agree with the solution.

This way is just "hidding" the fact that we register the routes when they are not needed. 

I think the best way to fix this is `if login column is not email => do not register recover password routes`.

Let me know,
Pedro

**Comment by danilopolani** [comment]
> if login column is not email => do not register recover password routes

I thought about that solution too, but Idk if those routes are called somewhere else I'm not aware of. I'm gonna try to fix this later today directly on this PR and coming back to you!

**Comment by danilopolani** [comment]
Ehy @pxpm , just pushed the fix. Let me know if this works to you, I searched in the entire project for the routes and it seems they're used only in the `backpack_users_have_email()` context.

**Comment by tabacitu** [comment]
Awesome! Great collaboration here guys. 

@pxpm I'm gonna ask you to give the final review and thumbs up on this one, since you've been involved so far. You say the word, and I merge it in the next patch update, and it'll be available with a `composer update` most likely on Monday.

Cheers!

**Comment by danilopolani** [comment]
Ehy Pedro,
it does make sense to add a `setup_password_recovery_routes` option (default: true) to me. 

If @tabacitu agrees I'm gonna edit the PR to reflect this idea.

PS: in this PR I used the `backpack_users_have_email()` check in the routes because, although the check was in `login` and `register` blade templates too, it was still registering the routes breaking the `php artisan route:list`.

**Comment by tabacitu** [comment]
Now that I think of it - I also have a problem with this solution: **because `backpack_users_have_email()` makes a DB call to check if the `email` column exists in the DB, this will basically add a DB call to _every pageload_**. Which is A LOT, just to support a feature that hasn't come up in 6+ years of existence... Don't know why I didn't think about that, it's a good thing you guys had doubts about this - made me think about it from a different perspective too 🤣 🙄 

Yeah... it's probably best to go with a different config. And `setup_password_recovery_routes` sounds like a good name for it - it's consistent with the other configs for routes. 

Notes:
- We do need to mention about it that this is called INSIDE the `setup_auth_routes` block so if you disable that you also disable password recovery automatically. A good place for that would probably be the comment block above the default value, and the docs.
- We'll also need to check for this config wherever we use the routes and point to them (`login.blade.php` and `register.blade.php` afaik).

**Comment by tabacitu** [comment]
Awesome, thanks for the help!

**Comment by danilopolani** [comment]
Just pushed the edits, it kinda sucks to have `config('backpack.base.setup_password_recovery_routes', true)` everywhere but I think it's the only way to make it backward compatible

**Review by tabacitu — COMMENTED** [review]
This looks GREAT! Looks like a perfect PR, good job @danilopolani . Haven't tested this per-se, I'll let @pxpm test it thoroughly and give his review too. But from my point of view, if it's backwards-compatible this is ready to merge. Cheers!

**Review by pxpm — APPROVED** [review]
Hello guys.

From my tests this works as expected. 

Best,
Pedro

**Comment by tabacitu** [comment]
Awesome! Merged, will be available on Monday the latest, with a `composer update`.

**Pull request merged**
