### PR TITLE
Add back IE support (fix conflicting code)

### PR DESCRIPTION
**Pull request by pxpm**
So, this is `Dummy` create for me before this PR while browsing IE:

image

And some of them that don't pop-up!

After this:

image

I added some polyfills for some very usefull functions like `Object.entries` or `Object.keys` . One of the errors shown in this last screenshot could be fixed by this polyfill. I added them in `scripts`, but I guess `colorpicker` loads before we init the polyfill. 

** Maybe we should move the polyfills to the bundle ? **

List view were also not loading, was the `alerts` in the persistence table and `crud` was not defined if not added to `window` object. I fixed that, list view now displays, but I get a weird error:

image

All the 10 errors are the same, here is where the problem relies:

image

Incredible how an empty line throws 10 equal errors in the browser console hum? 🐻 ** but list displays ** !! 

Old good IE ... how much I don't miss you!

### CODE REVIEW

**Comment by tabacitu** [comment]
Ugh - this looks like it's been so frustrating to put together, thank you @pxpm ! I'll let @promatik test and review since he may have access to IE, I do not 😅

Since:
- Nobody complained about these issues for years and years 
- To most admins that use IE, you can just say "install a different browser"
- [Microsoft itself will stop supporting IE on 21st August 2021](https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge)
- the next version of Backpack will probably come a little after Aug 21st
- Backpack v12 will be using [Bootstrap 5, and they also dropped support for IE](https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/#internet-explorer)
 
I think we should approach this from a perspective of "_if it's easy to fix in IE, we'll do it, but that's about it_" and wait for PRs for any other stuff. To follow the 80/20 principle: rather than looking to fix _everything_ for the very VERY few IE users... we'll try to only do _a few_ things, that will fix most of the big stuff. Low effort, high reward. Your PR looks to do even more than that - super-grateful for it 🙏 What I'm saying is let's get the big stuff working, and if people complain about something in particular not working inside IE, we'll deal with it then. What you've already done here seems like more than enough 🙏

**Comment by promatik** [comment]
Hi @pxpm I tried to think on a nice way to say this, but there isn't, so, I'm 99% against merging this PR 😅

In this case, as @tabacitu said, IE will be deprecated this year, in just a few months, so bloating our `scripts.blade.php` with polyfills that all modern browsers support, and avoid a lot of (not so) new JS features like arrow functions, template strings, array/object destructuring, and so on, for me, doesn't seem like the proper way.

I would agree with small changes, but this seems like a huge step backwards for such a small gain.

Talking with @tabacitu, we thought about creating a separate branch (`internet-explorer-support`, or something like that) and keep it updated until 21th August, if anyone **really** needs it, they can `require backpack/crud:internet-explorer-support`.

Let me know what you think ✌

**Comment by DanielKimmich** [comment]
Seem right

**Comment by pxpm** [comment]
Totally agree.

I think this is way tooooooo bad! 

Having a branch with IE compatibility would also add lots of extra work for us, imagine the PR where I mentioned this one, you are adding an arrow function, then you need to code the same functionality for IE compatibility in this branch. 

My thoughts here is: 
- If IE is beeing deprecated in a few months, we could deprecate it ourselfs 2/3 months earlier and avoid all the extra work. 

BIG CON: what about legacy systems that cannot upgrade browser?

Also, the problem is not only in IE. Chrome <80 does not support it too: https://github.com/Laravel-Backpack/CRUD/pull/3640

We also have a problem in our side, that when some of those conditions are meet: chrome < 80, IE, or other browser that does not support new JS funcs, we don't deliver a clear error of why the admin panel is not working, it just fails with some console error, not very related to the error itself. 

Maybe, what we should do is add a config `show_unsupported_browser_error => true`, that we will check browser version and compare with versions in: https://caniuse.com/es6

Atleast the panel would fail, but a nice error `Update your browser please` will be shown to the user. 

I say this not as a user, but as a dev. I create and admin panel and sell it to client, I as a dev, have the most recent technology available so everything works smooth. Then after project delivery you start getting complains that X does not work, etc, you test everything and on your side is fine. "Change to chrome" you say to the client (still don't work, < 80). 

The error is not clear of what is failing. Also it does not show ALL the failures, it just show you the first one in file. You then correct that one and the next one pops up and the cicle goes on until no more errors.

Fine you say ... na ...! We have that problem in field files etc, so the error could happen in different places depending on what fields are used. 

What I say, is that if it has an error message poping up, you immediatly know the problem and the fix. Unless we are talking about those legacy systems ... 

This is tricky, I've wrapped my head around it for quite a bit. I think would be interesting to know how many projects developed using backpack CANNOT update their browser vs the simple solution of updating. 

Let me know,
Pedro

**Comment by lotarbo** [comment]
@pxpm some our clients using old browser version, and they cant update, becouse they using specific extension in browser for ther work. Some of them working with crypto extension to work with a digital signature and this extension doesnt update fast to work with latest browser or work only in IE. It's bad but it's the way it is

**Comment by promatik** [comment]
@lotarbo those clients use IE right? Can't they switch to an updated chrome to use your backpack software?
I'm just curious, because in this scenario by forcing them to switch it would even encourage them to use the modern browser for other stuff too (and they would be safer in the web), and leave IE for only the required.

@pxpm things like the null coalescing #3640, I'm open to revert it to a ternary, even that Chrome 80 has 1+ year, no support and has a 0.11% usage worldwide 😅

But yeah, we can do the warning 🤷‍♂️ _a normal warning_, instead of a complete disable of the page.

By the way, @tabacitu do you have the browser version in backpack usage stats? 🕵️

**Comment by tabacitu** [comment]
@promatik - no, Backpack doesn't collect any information about the user/browser - that would have dire privacy implications. We only collect [some general stats about the app & server](https://github.com/Laravel-Backpack/CRUD/blob/master/src/Stats.php#L53-L68), so we know when a developer is using Backpack without a license in production.

@pxpm in regards to adding a notification that it won't work in the current browser... I can't say I'm very excited about that. It would only show up once someone actually tests on that browser... which is already too late. It would turn a negative UX into a better UX (which you know is something I love), but you know what an even better UX would be? For it to _actually work_ 😅 And we even have a working PR for that (this one) 😅 so it'd be the easiest solution to implement. So between showing a notification bubble saying it won't work and making it _actually work_... I would choose the second 😀

This is a tricky one... a tricky one indeed. And no matter what we choose, someone won't be happy with it. 

So let's reframe the choice between:
- **(A) adding IE support in `master`** => we make a few of our users happy, but we add maintenance burden for us _a few months down the road_, when we have to rewrite this once again to remove IE support; so there's some work to be done in Sep to remove this;
- **(B) adding IE support in an `internet-explorer-support` branch** => we make a few of our users happy (but less happy than the above), and we add a small maintenance burden _for these next few months_, because every time we tag something we have to keep this new branch up-to-date;
- **(C) adding no IE support** => we make a few of our users unhappy, but keep the code cleaner and have no maintenance overhead;

If we frame it this way... I guess the _work_ doesn't make much of a difference... we do it for a few months or do a rewrite in September... whatever, we can do it. The only real difference is UX. **Do we want our developers and users to have the best UX now, for these few months? Or do we want to cripple/lessen the experience because we want the code to be clean?** And if you put it that way, I guess the rational decision would be to merge this PR to `master` and be done with it. Bootstrap & CoreUI provide IE support, so does Backpack, and that's that. In the next version Bootstrap 5 won't provide IE support anymore and we can remove all this bloat too.

What do you guys think about this way of thinking @promatik & @pxpm ? Sounds reasonable? Do you disagree?

**Comment by pxpm** [comment]
Hello @tabacitu 

I agree with your rationale. Also I would add that when we move to other stack (like BS5), for sure IE would not be supported, but our users would have the chance to stay on this branch with a working version if that is their requirement to use the software.

It's not beautiful, it's not the best of both worlds, but we can make it work I guess. 👍 

I will give this another review, please do the same, this is not only changing `=>` into `function()`, some parts like `alerts` and some `fields` also need some kind of re-work, let's not break them to have IE compatibility. 

Best,
Pedro

**Comment by promatik** [comment]
What a come back! 😅

> @pxpm; this is not only changing `=>` into `function()`, some parts like `alerts` and some `fields` also need some kind of re-work, let's not break them to have IE compatibility. 

This is what scares me the most, we need to make sure none of these changes break anything, not only on IE but on modern browsers too, and not only now, but when/if we re-refactor this back to ES6 style.

Let's review it carefully 🙌

**Comment by tabacitu** [comment]
> Let's review it carefully 🙌

Totally agree 😅💪

**Comment by tabacitu** [comment]
Bump @promatik 🙏

**Comment by promatik** [comment]
@pxpm I fixed 2 bugs, on `alerts.blade.php` the value argument was missing, and on `relationship_select.blade.php` I believe you copied similar code from other file, but the function behavior was slightly different, I tested both, but please give us your final approval. Everything else is good, you had a hell of a job here 👌

@tabacitu I reviewed line by line, and tested the changed code, I believe this one is ready 💥

Anyway, can we revert this PR on one 4.2? **PLEASE** 😅

**Review by promatik — APPROVED** [review]

**Comment by tabacitu** [comment]
Excellent, thank you!

> Anyway, can we revert this PR on one 4.2? PLEASE 😅

Yes, we'll definitely do that right away, in 4.2. Can't wait to drop IE support. Though by that time I don't think it'll be as easy as hitting the "Revert" button - I think we'll need to manually create a PR that undoes this.

**Pull request merged**
