### PR TITLE
[4.1-beta] fix fetch field  with custom model accessor

### PR DESCRIPTION
**Pull request by kritsot**

### CODE REVIEW

**Comment by tabacitu** [comment]
Thanks for pitching in @kritsot ! We really appreciate it.

@pxpm can you please double-check we need this, and let me know if I should merge it? `fetch` is your baby after all 😄

**Comment by pxpm** [comment]
I know i had it this way before, and then I changed. 

Let me try to find why I did it.

**Comment by pxpm** [comment]
Hey @kritsot 

Thanks for reporting in. 

Unfortunatelly I was  not able to reproduce your issue. 
I used a fetch field, with custom model acessor and it works fine.

I think this is a documentation issue, if you use an acessor in your field attribute you should add it to appends in model.

```php
    public $appends = [
        'composed'
    ];
```

If this is not the case please re-open. I might be wrong has i'v been lot of times. :)

Best,
Pedro

**Comment by pxpm** [comment]
@tabacitu please have a look in docs, make sure we state that cleary there. 

If people use a custom acessor they should add it to appends in model !

**Comment by kritsot** [comment]
@pxpm 
I don't think this solves the problem I mentioned.
Maybe I did not describe it properly.

As described in the [documentation](https://laravel.com/docs/7.x/eloquent-serialization#appending-values-to-json) 

**Once the attribute has been added to the appends list, it will be included in both the model's array and JSON representations.** 

The code below (taken from _relationship.fetch, relationship.relationship_select_) 
directly hits the database , we don't have an eloquent model yet. so **$appends** does not matter
```
$current_value = $connected_entity
    ->where($connected_entity_key_name, $current_value)
       ->pluck($field['attribute'], $connected_entity_key_name);
```
The ->where() method above is performed on the query builder, not the eloquent model.
Having a **categories** table, a **Category** model and using **nestedName** accessor,
when the code above is called, it will raise an exception
```
Undefined column: 7 ERROR: column "nestedName" does not exist LINE 1: select "nestedName", "id" from "categories" where "id" = $1 .
```

**Comment by pxpm** [comment]
Ok @kritsot let's try to debug this. 

What i did:

In model i created: 
```php
    public function getComposedAttribute() {
        return $this->name.'++';
    }

//and also
public $appends = ['composed'];
```

then I use this field:
```php
            [    // Relationship
                'label'     => 'does not matter',
                'type'      => 'relationship', //can be omitted
                'name'      => 'products',
                'entity'    => 'products', //can be omitted
                'attribute' => 'composed',
                'tab'       => 'Relationships',
                'ajax'      => true,
                'data_source'       => backpack_url('monster/fetch/product'),
            ],
```

Screenshot_7

Without adding to appends it does not work. 

Am i doing something different or this is not the use case ? 

Best to you and sorry for the trouble you are having. Hope we can solve this quickly!

**Comment by tabacitu** [comment]
Thank you for taking the time to get to the bottom of this @kritsot & @pxpm . I've confirmed with @pxpm that it's better with `get()`, and he'll submit a PR shortly to do the same inside `fetch_or_create`.

Thanks for the PR @kritsot ! You rule.

**Comment by kritsot** [comment]
@tabacitu @pxpm thanks guys!
Since you mentioned **fetch_or_create* 
you have to consider that the same thing has to be done for **relationship_select**

**Comment by DanielKimmich** [comment]
I also had trouble updating, what I did was add in the field in the $fillable variable of the model

**Pull request merged**
