### PR TITLE
[Enhancement] Adds the ability to define the templates from within your CrudController

### PR DESCRIPTION
**Pull request by OwenMelbz**
Publicises an API enabling the templates to be defined from within the CrudController setup using the below.

```php
$this->setShowView('your-view');
$this->setEditView('your-view');
$this->setCreateView('your-view');
$this->setListView('your-view');
$this->setReorderView('your-view');
$this->setRevisionsView('your-view');
$this->setDetailsRowView('your-view');
```

You can also call the getters for all the above if needed e.g

```php
$this->getShowView();
$this->getEditView();
$this->getCreateView();
$this->getListView();
$this->getReorderView();
$this->getRevisionsView();
$this->getDetailsRowView();
```

a more full example might look similar to 

```php
class RegionCrudController extends CrudController
{

    public function setUp()
    {
        $this->crud->setModel("App\Models\Region");
        $this->crud->setRoute("admin/regions");
        $this->crud->setEntityNameStrings('region', 'regions');

        $this->setCreateView('tabbed-form');
        $this->setEditView('tabbed-form');
    }
}
```

### CODE REVIEW

**Comment by tabacitu** [comment]
I LOVE THIS! :-) Great idea.

**Comment by OwenMelbz** [comment]
You haven't merged it though :P

Ha the one issue I've got is the lack of consistency, because its bound to the controller you apply it via `$this` rather than `$this->crud` 

However I'm not sure if it can be moved to the CrudPanel without breaking any conventions/recommended practice. I'm not sure if it should be attached to the controller, because you define the views in the controllers, so it should be attached to it. So I'm torn! ha but I think it could be moved easy enough

**Comment by tabacitu** [comment]
Yeah, sorry, I'm trying to first take care of the "low hanging fruit" PRs - those that take 30 minutes or less to test and merge. This one takes a little more time. Your PRs generally are big features, which is awesome (of course), but they also need proper testing before being merged, as one bug there would make a lot of people cry "help" :-)

Hmm... you bring up a good point. 

1) If it were a PanelTrait, you'd be able to change a view:
- from the CrudController (or anything that extends it);
- from the CrudPanel (or anything that extends it);

This should be more future-proof, if in time we decide to have CrudPanel methods that change views. 

2) Plus, I think it's more intuitive to have the syntax the same with all other methods (as you said above):
```diff
-$this->setShowView('your-view'); // will be fairly new, as we don't have any other methods on $this
+$this->crud->setShowView('your-view'); // would feel familiar, I think 
```

**Comment by tabacitu** [comment]
Going to merge this soon. Awesome feature for 3.2. Thinking out loud here:

(1) I like ```$this->crud->setShowView()``` better than ```$this->setShowView()```. Fits in nicely with the coming Facade, when it would be ```CRUD::setShowView()```;

(2) By now, we have a few _operations_ that the CRUD takes care of:
- C: create
- R: list, show, details_row, revisions
- U: edit, reorder
- D: delete

Each of them has a view (except delete). So for consistency, we could 
- create a syntax similar to ```$this->crud->allowAccess()``` and ```$this->crud->addButton()```, so basically ```$this->crud->setView('create', 'some_view')```; this does not necessarily exclude the detailed methods @OwenMelbz created, but:
   - I imagine it's easier to remember this one method instead of all of them;
   - I think it would make for cleaner code when you overwrite more than 2-3 views;
- make sure we have consistent names for each operation (**create** vs insert, **edit** vs update, **show** vs preview, **destroy** vs delete), across all traits (Access, Buttons, Views); or intelligent matching when the wrong operation name has been used;

**Comment by tabacitu** [comment]
Changed the following:
- moved the trait to CrudPanel instead of CrudController, for API syntax consistency;
- added alias for edit view (update);
- added alias for show view (preview);
- added revisions_timeline view getter and setter;
- did NOT adopt the ```$this->crud->setView('create', 'some_view')``` syntax;

Awesome PR again, @OwenMelbz , thanks a lot.

Merged into 3.2!

**Pull request merged**
