### PR TITLE
Show values label in select2 filter

### PR DESCRIPTION
**Pull request by iMokhles**
we can apply the same for other filters
it helps users to know exactly which filter applied

### CODE REVIEW

**Comment by tabacitu** [comment]
Hey @iMokhles - thanks for taking the time to submit the PR. Unfortunately, dumb old me doesn't quite understand what this does 😅 Could you please rephrase? Thanks!

**Comment by iMokhles** [comment]
@tabacitu dude you are the godfather of this community don't say that 🤪😜

When you apply filter it highlights only the filters without showing you which value exactly you have selected unless you open the filter to see which value you have selected

With this pull request i added the value next to the filter label to make it clear to know which value applied to this filter

**Comment by tabacitu** [comment]
Aaah I understand now, thanks!

This is an interesting UI choice, something I've been pondering for a while. 

On one hand, it's waaay better in terms of UX - you see immediately what's selected.

On the other hand, it increases the size of the filter itself. Which (as a developer) you might not want the user to do. For example, in a ListView with a lot of filters, like Monsters in our demo, if you choose a filter, it will immediately need two rows instead of one... which will make it look ugly.

----

So yeah, it's a tricky one, let me think about it please @iMokhles 

Nevertheless:
- if we do it for one filter we should do it for all filters;
- if we do it, it should be configurable (on/off);

So if we do decide to go this way... It should be in 4.2 the soonest.

Thanks again @iMokhles !

**Comment by tabacitu** [comment]
Hey @iMokhles ,

I've just given this another look, and careful consideration... and I don't think we should do this by default. Like I said above, if we do this for one field... we should do it for all of them (that's what's intuitive). And then as soon as you have 2-3 filters on page with stuff selected, it'd no longer fit in one row...

I think what we have now strikes a _decent_ balance between "know what's selected" and "fit everything in as little space as possible".

I think it's super-easy to have this inside your own projects, though, as a custom filter... something like `select2_with_labels`. Hell... it'd be pretty simple to [create an addon for it](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial-using-the-addon-skeleton) so not only you can use it, but others too. I don't think it would require any kind of maintenance once it's up.

Let me know if you decide to create an addon out of it - happy to put it on our website and promote it. But as far as including this in Backpack's core... I've decided it's better not to do it.

Let me know if you think I'm wrong - I often am 😀

Cheers!

**Pull request closed without merging**
