### PR TITLE
Fix invalid image url, add support for url prefix

### PR DESCRIPTION
**Pull request by lejubila**
Fix invalid image url on insert new record.
Add support for prefix on url image. Passing prefix from controller, es:

        $this->crud->addField([
            'name' => 'image',
            'label' => 'Image',
            'type' => 'image',
            'upload' => true,
            'crop' => true,
            'aspect_ratio' => 1,
            'url_prefix' => 'uploads/',
        ]);

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @lejubila ,

Thanks a lot for the PR! 

1) Could you please explain what problem you fixed for "_invalid image URL_" or how? Is it by removing the ```url()``` method? Would using the ```asset()``` method fix it too?
2) I'm not a big fan of having ```url_prefix```, to be honest. It might promote some bad programming behaviour. Yes, it makes writing the field faster, but if you're using this image in the admin, you're using it somewhere else, too. In the front-end of the app. Right? And you need to write your prefix there too. So now it's in two places, hardcoded. Now my conscience is saying "_bad developer_" :-) Since we have already have a layer that interacts with the DB and formats the information in a certain way (the Model), I think that's where it should sit. You can easily apply it using an [Accessor and Mutator](https://laravel.com/docs/5.4/eloquent-mutators#accessors-and-mutators). It takes a little more time, but it's the right way to do it. And when you need to change it or debug it, it's in one spot. I hope this makes sense...

Again, thank you for the PR, please keep them coming and sorry if this one doesn't get merged entirely.  Backpack has started being used by a lot of beginner developers and I really don't want to teach them bad habits.

Cheers!

**Comment by tabacitu** [comment]
Tidying up Github, so I'm going to close the issue. Please tell me about (1) above, very interested to have that solved.

Cheers!

**Comment by lejubila** [comment]
Hi @tabacitu,
for the second point, thanks for your suggestions. I removed the ugly code in the view and implemented in my model any changes to be performed in the url.
On the first point I'll try to explain better:
with the original code the url() function is also performed when the image field is empty. 
This way when you insert a new record and the image field is empty is generated url broken with only the domain name.
The url() function was inserted externally ternary operator. To solve the problem I moved the url() function internally ternary operator.
In the latter case of the ternary operator (when the image is empty field) have not entered the url() function so that it does not produce a broken url.

screenshot_url

If you want I can send a new PR with these modified.

Regards.

**Comment by MarcosBL** [comment]
Just my 2 cents on this. I tried a different approach, as the img preview is broken both if empty and if you use a custom disk/path to store them. In my example, image is called **Foto**

In my model **Tutores.php** I added a 

````php
class Tutores extends Model
{
  use CrudTrait;
  ...
  public $disk = 'uploads';
````

And a couple functions

````php
public static function boot()
{
  static::deleting(function($obj) {
    /* Takes care of deleting the file when deleting the Tutor */
    \Storage::disk($this->disk)->delete($obj->foto);
  });
}

public function setFotoAttribute($value)
{
  $attribute_name = "foto";
  $destination_path = "tutores/fotos";
  if ($value==null) {
    \Storage::disk($this->disk)->delete($this->foto);
    $this->attributes[$attribute_name] = null;
  }

  if (starts_with($value, 'data:image')) {
    /* Added this delete, otherwise each time you replace the old image */
    /* you end up with two on disk, because the old one is not deleted */
    /* Curious, upload field type does it @ uploadFileToDisk */
    \Storage::disk($this->disk)->delete($this->foto);
    $image = \Image::make($value);
    $filename = md5($value.time()).'.jpg';
    /* Please note the ('jpg', 80) parameters added to $image->stream */
    /* If you don't add them, you end with a png image saved as jpg */
    \Storage::disk($this->disk)->put($destination_path.'/'.$filename, $image->stream('jpg', 80));
    $this->attributes[$attribute_name] = $destination_path.'/'.$filename;
  }
}
````
That takes care of cleaning up, and the disk path.

Now, in the controller **TutoresCrudController.php** I had to specify the disk to pass it to the view:

````php
$this->crud->addField([
  'name' => 'foto',
  'label' => "Foto de Perfil del tutor",
  'type' => 'image',
  'upload' => true,
  'crop' => true,
  /* Specify disk here */
  'disk' => 'uploads'
], 'both');
````

And finally, had to copy the original view into **resources/views/vendor/backpack/crud/fields/image.blade.php** to be able to specify the disk. This is the worst part for me, as it invalidates future updates of the package. Then I fixed the original "broken image" view issue when creating new Model, or using your own disk configuration this way (no te both changes, disk specification and no src in image if no value):

````php
@if(isset($field['value']))
  <img id="mainImage" src="{{ url(old($field['name']) ? old($field['name']) : (isset($field['value']) ? \Storage::disk($field['disk'])->url($field['value']) : (isset($field['default']) ? $field['default'] : '') )) }}">
@else
  <img id="mainImage">
@endif
````

I'm not confident enought with Laravel to propose a PR, but those are my suggestions:

- Provide a way (mine is probably not the best) to specify the disk in the CRUD field, so the view could show the correct path to the images
- In the template, avoid the image **src** parameter in the case of and empty value, to avoid the 404
- Specify the additional parameters to "stream" in the docs, to avoid confusion, as the upload images are really png with jpg extensions

As said before, just my 2 cents on this

**Pull request closed without merging**
