### PR TITLE
[FEATURE] - Add the ability to remove ALL fields

### PR DESCRIPTION
**Pull request by pxpm**
Added a function to remove all fields from a CRUD on create/update or both forms. It helps if you have a form with 10+ fields.

I'v named it removeAllFields($form), as the others are removeField and removeFields.

now you can call $this->crud->removeAllFields() and have an empty crud to add the one or two fields you need on that form.

Nothing much to validate here, we call getCurrentFields() iterate over them, and delete.

Hope it helps someone too !

**_Haaaaaaa, before you ask, i'm using this because some fields are not yet initialized in crud so removing the ones defined i'm not going to write the code to add the same field again._**

### CODE REVIEW

**Comment by tabacitu** [comment]
I think it's a good idea. Thank you @pxpm - just merged it into ```master```. It'll be available with a ```composer update``` after I bundle it with a few more changes and tag it. Most likely in a few hours/days.

Thanks again. Cheers!

**Comment by ziming** [comment]
Wow. I was searching for how to fix remove fields issue in backpack 4.1 and encountered @pxpm first PR with @tabacitu !

Anyway the problem I had is this.

In Backpack 4. During update I always remove some readonly fields to prevent them from being updated like this:

```php
$fieldsToRemove = ['name', 'gender', 'height'];

foreach ($fieldsToRemove as $fieldToRemove) {
            $this->crud->request->request->remove($fieldToRemove);
        }

return $redirect_location = $this->traitUpdate();

return $redirect_location;
```

However in Backpack 4.1. This error is thrown

$this->crud->request has protected access.

In Backpack 4.1, what is the right way to remove fields from a request so that they don't get updated?

Thank you.

**Comment by tabacitu** [comment]
> I was searching for how to fix remove fields issue in backpack 4.1 and encountered @pxpm first merged PR with @tabacitu !

Haha that's a nice piece of trivia! ❤️ 

> In Backpack 4.1, what is the right way to remove fields from a request so that they don't get updated?

I've recently updated [this section in the docs](https://backpackforlaravel.com/docs/4.1/crud-operation-update#callbacks). Basically in 4.1 it's best to do:

```php

    use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation { update as traitUpdate; }

    // ...
    public function update()
    {
        // do something before validation, before save, before everything:
        $this->crud->removeField('name');
        // alternatively, you could do something like:
        // $this->crud->getRequest()->request->remove('name');
        // or 
        // request()->remove('name');

        $response = $this->traitUpdate();

        return $response;
    }
```

**Comment by ziming** [comment]
Thanks @tabacitu 

Will this work too or are they different from the example you provided?

$this->crud->removeFields($fieldsToRemove);

**Comment by tabacitu** [comment]
👍  Should work just fine!

**Comment by ziming** [comment]
Okay thanks shall just use $this->crud->removeFields($fieldsToRemove); then :)

**Pull request merged**
