### PR TITLE
Avoid space after commas

### PR DESCRIPTION
**Pull request by promatik**
Added a flex span containing text and comma to avoid space after commas.
Aligned everything.

### CODE REVIEW

**Comment by pxpm** [comment]
Hey @promatik 

I was discussing this with @tabacitu and I said to him: "Hum .. I already told @promatik that using the close and open tags seems too dirty, I will have a look at it asap, but in meanwhile I am sure @promatik will find a solution for it".

I am glad I was not wrong :) 

Thank you very much. 

:)

**Comment by tabacitu** [comment]
🥳 thank you so much @promatik ! @pxpm can you please test this thoroughly, and give your stamp of approval or review? Eager to merge this 😄

**Comment by pxpm** [comment]
Hello guys, and sorry for the time without response. 

I started looking at this PR last week 
**From my tests everything is ok with this PR so i will approve this**, but in meanwhile I found: #2839 and could not look away from it. 
I start working on a solution for that and let this one unanswered, i'm sorry. 

Still could not figure a solution for the other. But thanks for this @promatik

**Comment by promatik** [comment]
@pxpm I tested this myself, anyway it's better to have someone else to look at it further.
How's #2839 going? Do you want some help with it?

**Comment by pxpm** [comment]
@promatik thanks for the kindness! \o

I might need some help on that one, it's tricky to say the best. I will write on the issue our findings so you don't need to dive in the same waters as we did. 

I will aprove this one. 

Best,

**Pull request merged**
