### PR TITLE
Fix Reorder When Page is RTL

### PR DESCRIPTION
**Pull request by EGYWEB-Mohamed**
## WHY
Fix RTL Problem With Reorder Sort

### BEFORE - What was wrong? What was happening before this PR?

it was not working fine when the page was rtl 

### AFTER - What is happening after this PR?

work fine depending on the HTML tag dir

## HOW
so there's a method called RTL in nestedSortable() that allow RTL and it detects if dir is RTL from HTML dir attribute 

### How did you achieve that, in technical terms?

- check page dir via ``` $('html').attr('dir') == 'rtl') ```
- if it true it wilis l saved at ```isRtl```
- if isRtl is true will inject some CSS to fix some indentation issues
- add rtl to ``` nestedSortable() ``` with ```isRtl``` var

### Is it a breaking change?

no

### How can we test the before & after?

ice_video_20220918-073655

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @EGYWEB-Mohamed 

Thanks for the contribution. 🙏 

From what I see we are fixing two issues here:
1- `sortable` plugin has a `rtl: true/false` attribute that we don't allow developers to change and it's `false` by default.
2- added styles to make the rtl look similat to ltr.

Am I correct here ? 

Also, we have in `config/backpack/base.php` the following:
```php
// Direction, according to language
    // (left-to-right vs right-to-left)
    'html_direction' => 'ltr',
```

Can we use that setting instead of the html attribute? 

Cheers

**Comment by pxpm** [comment]
Thanks. 
Not saying that your approach is better or worst, I think for us, Backpack, would only make sense to merge it using a Backpack config otherwise we would have two different ways in the core system to handle RTL and that would add into maintenance costs and inconsequential bugs. 

I mainly agree with this PR, also is probably worth checking if `rtl:true` in the script initialization adds any rtl specific class or attribute that we can use to target with css, avoiding adding it with JavaScript. 

Thanks again for the contribution, if you happen to do the changes I mentioned I think this PR becomes very close to a merge. 

Cheers

**Comment by EGYWEB-Mohamed** [comment]
@pxpm So you think change it to use ```config/backpack/base.php``` ->  ```'html_direction' => 'ltr'``` 
am working on it and will update this PR soon

**Comment by EGYWEB-Mohamed** [comment]
@pxpm Done :)

**Review by pxpm — APPROVED** [review]
Thanks again @EGYWEB-Mohamed for the contribution.

I think we are good to go now 🙏

**Comment by EGYWEB-Mohamed** [comment]
Amazing :)

**Comment by tabacitu** [comment]
Thanks a lot for the PR @EGYWEB-Mohamed 🙏 We really appreciate it.

Hot tip: in the future, try not to include indentation changes in the same PR, it makes it much more difficult to review. We can always submit a PR later, just with indentation changes. That way, both of them get quickly merged. It's a little more work, but it does help review and merge things a lot faster, and the git history is clearer too 🏆

Thanks again 🙏

**Comment by EGYWEB-Mohamed** [comment]
@tabacitu Amazing thanks for this tip :) 
thank you guys for your efforts @pxpm

**Pull request merged**
