### PR TITLE
Create translate routes only when needed

### PR DESCRIPTION
**Pull request by martijnb92**
Prevents unnecessary routes creation by checking if the locales configuration variable contains more than one locale.

### CODE REVIEW

**Comment by tabacitu** [comment]
Totally agree that we shouldn't have the translate route if the entity is not translatable. This would clean up `php artisan route:list` quite a bit.

But while investigating this - I discovered something - **I think we can remove this route entirely**.  I've last worked on this a few years ago, so I don't remember exactly how it worked all the time, but it looks like this route is completely unused in Backpack v4. I see that:
- the URL is actually `admin/product/21/edit?locale=fr` when you translate an item;
- there's no reference to `translateItem` anywhere, other than when we set up this route;
- I couldn't find the `translateItem()` Controller method that this route points to;
- when manually accessing the URL you're greeted by a `Method does not exist` exception;
- removing this route results in the app still working as expected (because, again, it's not used anywhere);

It's totally possible that when I refactored to Operations I changed the URL, but forgot to remove the route. I make mistakes too, and this seems like quite an innocent one - so it's right up my alley. 

So I'm wondering - do you guys have any idea what this route does? Or what it did in the past? 😆 If not, and you guys also think this can be safely removed, I say let's do that - let's remove it entirely 😄 🥳 

Cheers! Thanks a lot for surfacing this @martijnb92

**Comment by pxpm** [comment]
Indeed, I could not find any reference to this function in main crud repository. 

Maybe is like you said, after the refactor this bit got lost.

**Comment by martijnb92** [comment]
Same here, can't find anything related to `translateItem`, route can be deleted.

**Comment by tabacitu** [comment]
Awesome. Thanks a lot for double-checking guys. Merged and tagged.

**Pull request merged**
