### PR TITLE
[4.1][Feature][Beta] Repeatable field type (aka matrix; aka group)

### PR DESCRIPTION
**Pull request by tabacitu**
As talked about in #131, #771 . I think now that v4 allows us to reinitialize fields with Javascript, it's finally its time to shine.

## Repeatable

Allows the developer to add _a group of Backpack fields_ (ex: 1 text field, 2 browse fields, 1 wysiwyg field). The user can fill in the fields, add another group with the same fields, or delete groups.

Screenshot:
64406749-451beb80-d08b-11e9-9b0a-c3a4c14edc04

Syntax:
```php
[
  'name' => 'repeatable',
  'label' => 'Entries',
  'type' => 'repeatable',
  'fields' => [
    [
      'name' => 'question',
      'label' => 'Question',
      'type' => 'textarea',
      'wrapperAttributes' => [
         'class' => 'form-group col-md-6'
       ],
    ],
    [
      'name' => 'answer',
      'label' => 'Answer',
      'type' => 'textarea',
      'wrapperAttributes' => [
         'class' => 'form-group col-md-6'
       ],
    ],
  ],
]
```

By default it compacts the fields and stores the group of fields as JSON. But the saving can be intercepted in the create/update operation, or using a mutator on the model, to make it store the values in a different way.

### CODE REVIEW

**Comment by tabacitu** [comment]
Since you can use ALL Backpack field types with this field, it needs _extensive_ testing before it's merged and launched. The testing list should include:

- [ ] all fields work as secondary fields in a repeatable group (test create (+), delete (x) and editing groups):
    - [ ] address_algolia
    - [ ] address_google
    - [ ] browse
    - [ ] browse_multiple
    - [ ] base64_image
    - [ ] checkbox
    - [ ] checklist
    - [ ] checklist_dependency
    - [ ] ckeditor
    - [ ] color
    - [ ] color_picker
    - [ ] custom_html
    - [ ] date
    - [ ] date_picker
    - [ ] date_range
    - [ ] datetime
    - [ ] datetime_picker
    - [ ] email
    - [ ] enum
    - [ ] hidden
    - [ ] icon_picker
    - [ ] image
    - [ ] month
    - [ ] number
    - [ ] page_or_link
    - [ ] password
    - [ ] radio
    - [ ] range
    - [ ] select (1-n relationship)
    - [ ] select_grouped
    - [ ] select2 (1-n relationship)
    - [ ] select_multiple (n-n relationship)
    - [ ] select2_multiple (n-n relationship)
    - [ ] select2_nested
    - [ ] select2_grouped
    - [ ] select_and_order
    - [ ] select_from_array
    - [ ] select2_from_array
    - [ ] select2_from_ajax
    - [ ] select2_from_ajax_multiple
    - [ ] simplemde
    - [ ] summernote
    - [ ] table
    - [ ] text
    - [ ] textarea
    - [ ] time
    - [ ] tinymce
    - [ ] upload
    - [ ] upload_multiple
    - [ ] url
    - [ ] video
    - [ ] view
    - [ ] week
    - [ ] wysiwyg
- [ ] default value
- [ ] hint
- [ ] wrapperAttributes to make the field smaller/bigger
- [ ] works as a fake field
- [ ] stores the information in the DB as a valid JSON
- [ ] edits the information in the DB as a valid JSON when deleting entries
- [ ] edits the information in the DB as a valid JSON when deleting and adding entries
- [ ] edits the information in the DB as a valid JSON when deleting all entries

The following advanced use cases should be tested and documented:
- [ ] intercept the field in the controller, and store the values in a different way (something other than JSON in the db)
- [ ] intercept the field in the model (using a mutator and accessor) and store the values in a different way (something other than JSON in the db)
- [ ] add validation for some secondary fields in a group

**Comment by OwenMelbz** [comment]
🙌🏼 Image uploaders I’ve found to be the hardest thing for these field types, have you sorted those all okay?

**Comment by annadnl** [comment]
how is the Select2_multiple (n-n relationship with pivot table) supposed to work in here?
should it
- return one record per group
- let user add one record per new group?

**Comment by diakosavvasn** [comment]
It will released also in the 3.6 version ? Or only 4.0 ?

**Comment by tabacitu** [comment]
@OwenMelbz indeed image uploaders are a bit tricky. I'm on it.

@annadnl I think each ```select2_multiple``` input should allow multiple choices per input; say:
- group 1 (text, number, select2_multiple) - select2_multiple has multiple values
- group 2 (text, number, select2_multiple) - select2_multiple has multiple values
- (add new)

Is this what you were asking? I think that's the intuitive way to see it. Don't know about the pivot table though - since most of the time the value of the input won't actually be stored as a column in the DB, but as an _attribute_ in a JSON column, that's the use case I think we should prioritise - storing the value as a JSON.

@diakosavvasn It'll only be available in v4. We've made considerable changes to ALL fields from v3 to v4, specifically to allow us to create a field like this one. In v3 it's "very very VERY" difficult to do. In v4 it's just "very" difficult 😄

**Comment by ziming** [comment]
Definitely looking forward to this field. Though I wonder if the fields can be vertically stacked instead of horizontal

**Comment by tabacitu** [comment]
@ziming Yes, they're vertically stacked by default - they work exactly the same as Backpack fields inside a create/update operation. You can make more fields fit into one line using ```wrapperAttributes``` - that's what I did in the screenshot above (```col-md-4```). 

But by default, with no ```wrapperAttributes```, a field group would look like this:

Screenshot 2019-12-03 at 13 27 54

**Comment by ziming** [comment]
I get that we can save the data in a different way, but can the data be fetched in a different way too if we don't save it directly to a json column?

**Comment by tabacitu** [comment]
@ziming sure. If you use [an Accessor and a Mutator](https://laravel.com/docs/6.x/eloquent-mutators#accessors-and-mutators). So on the model you can have:

```php
public function getRepeatableAttribute() {
     // fetch it any way you want
     // but it'll have to be a JSON or PHP array when you return it
}

public function setRepeatableAttribute($value) {
    // store it anywhere you want
}
```

**Comment by ziming** [comment]
Nice, I thought about using 'default' initially but yours was a better way.

Shall try this field in 1 of my apps and feedback here on how it goes

**Comment by ziming** [comment]
Just used it for a test run today with 3 number fields. All of them get saved as strings in the end. Wonder if there is an easy way to ensure if the type is number, it gets saved as a number in the json.

I could intercept it at update() but if the field auto cast it, that would be great

**Comment by tabacitu** [comment]
@ziming indeed that would be nice. I'm wondering if it's an optimization worth doing. Do you see any other fields apart from ```number``` that could use front-end casting? Off the top of my head, I can't think of any.

If the "number" field would be only one to use this, I don't think it's worth doing - it would overcomplicate the logic for all fields, when it's easy to fix on the developer side (just cast it in PHP before echoing or using).

**Comment by ziming** [comment]
Hmm only boolean and number so far.

date and datetime are fine as strings

**Comment by ziming** [comment]
Spotted some issues when using it in production

When using the table field in this repeatable, when I click the repeatable blue + (add) icon,

All the rows in the previous item table field gets duplicated as well.

Also when saving the table field data is escaped by \ slashes.

Here is an example:


```json
[ 
{ 
"name":"John",
"role":"student",
"iq":"123",
"toys":"[{\"name\":\"Jackson\",\"amount\":\"5999\"},{\"name\":\"Jackson\",\"amount\":\"5999\"}]"
},
{ 
"name":"Jane",
"role":"teacher",
"iq":"200",
"toys":"[{\"name\":\"Joanne\",\"amount\":\"3000\"},{\"year\":\"Joanne\",\"amount\":\"3000\"}]"
}
]
```

**Comment by ziming** [comment]
Just learnt today that one can do

json_encode($arrayOrObj, JSON_NUMERIC_CHECK);

And it will produce a json string with all the number strings (e.g. "1234" converted to real numbers (e.g. 1234)

**Comment by genesiscz** [comment]
Is this getting a completetion in, let's say, month?

**Comment by tabacitu** [comment]
@genesiscz yes. Hopefully sooner, like 1-2 weeks.

**Comment by tabacitu** [comment]
Added examples to the demo, in https://github.com/Laravel-Backpack/demo/pull/138

**Comment by ziming** [comment]
Wow!

**Comment by dilneiss** [comment]
found something i need in this moment:
i have multiple checkbox, in the repeatead item when i click on the label of the second item, it only check the first checkbox, not the clicked one

reorder the item is missing too, i want the second item to be the first for example, and it is missing

**Comment by movilas** [comment]
Sorting (sortable) would be nice to have feature.

**Comment by pxpm** [comment]
> Sorting (sortable) would be nice to have feature.

#2711 enjoy :)

Thanks for pitching in :+1:

**Comment by joaojoyce** [comment]
Hi @tabacitu.

This is such a great feature. 

I've noticed that images get into a base64 array. Does it work with image uploads as there's no place to set the [mutator](https://backpackforlaravel.com/docs/4.1/crud-fields#image)?

Thank you.

**Comment by iMokhles** [comment]
So it's an amazing fields but i had issue with image field as @joaojoyce 
but i i was able to make it works like that.

**Repeatable Field Mutator**
Capture d’écran 2020-06-30 à 19 06 49

**Image Setter same as [documentation](https://backpackforlaravel.com/docs/4.1/crud-fields#image) with some comments to serve my need**
Capture d’écran 2020-06-30 à 19 12 27

**Images saved in database like that**
Capture d’écran 2020-06-30 à 19 11 07

**And also uploaded and saved to my disk correctly**
Capture d’écran 2020-06-30 à 19 10 18

Hope it helps someone and hope it make sense for you @joaojoyce

**Comment by tabacitu** [comment]
Update - Pedro has just finished refactoring the `repeatable`, we now have nested array validation starting with Backpack 4.2 🎉  So we can do things like `'testimonial.*.name' => 'required|min:5|max:256'` 🎉🎉🎉  So much simpler!

[This refactor](https://github.com/Laravel-Backpack/CRUD/pull/3905) also opens up the possibility for us to _maybe_ make `image`, `upload` and `upload_multiple` work inside `repeatable` (still [working on that one](https://github.com/Laravel-Backpack/CRUD/pull/3951)) 😱  

I've decided to create one issue for all things `repeatable` - see https://github.com/Laravel-Backpack/CRUD/issues/3953

**Pull request merged**
