### PR TITLE
Fix mixed protocol block. Simple remove protocol from request url :)

### PR DESCRIPTION
**Pull request by peresmishnyk**
When backend work as http behind https proxy (as cloudflare example)

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @peresmishnyk 

I am not sure what this really solves by only changing this simple file, here it's the only place we use the request url ?

What would be the impact for non proxied requests ?

Best,

**Comment by tabacitu** [comment]
I also am a bit skeptical this needs a solution in code @peresmishnyk . Sounds more like a CloudFlare misconfiguration to me. What's your use case? The main site is under HTTP and the admin is under HTTPS? Or how's your setup that you need this?

I'm asking because I'm using the Reorder operation under Cloudflare's SSL just fine - it doesn't need this. All my routes are under HTTPS, always. 

Is your SSL set to full?
Screenshot 2020-04-20 at 09 37 51

You might also want to try "Always use HTTPS" option in Cloudflare, under SSL > Edge Certificates > Always use HTTPS

Hope it helps.
Cheers!

**Comment by peresmishnyk** [comment]
@pxpm request url used in two places. I am fixed both.
@tabacitu it would be more correct to use laravel  UrlGenerator to generate links than to use current request url? Then we can use forceSchema and forceRoot from UrlGenerator if necessary.

We have trouble If use flexible ssl and do NOT use ssl on backend server. The same problems will be when using laravel valet share https url because it forward request to non secure local url.

Use UrlGenerator solve this.

**Comment by tabacitu** [comment]
Hi @peresmishnyk ,

Thanks again for the PR. I think you're right, there's no harm in supporting that use case, even if most people will probably not stumble into it. I've had to create two different PRs for this, because in the meantime we've moved the Revise operation into its own package. So here they are:
- https://github.com/Laravel-Backpack/revise-operation/pull/10
- https://github.com/Laravel-Backpack/CRUD/pull/3270

One's already merged. The other will be merged soon. So starting Monday this will be ready to use with a `composer update`, in Backpack 4.1.

Thanks again.
Cheers!

**Comment by tabacitu** [comment]
PS. Even if you won't appear as the _author_ of this fix, you ARE. We know you are. You know you are :-)

**Pull request closed without merging**
