### PR TITLE
[4.1.0][Feature][Merged] Chart widget + ChartController

### LINKED ISSUE #2371: [4.1][Feature] New widget: chart
We should make it easier to add charts to the Dashboard / CRUDs. Especially since [Backstrap](https://backstrap.net/index.html) already provides beautiful charts using Chart.JS

The syntax should be pretty similar to the ChartJS syntax: https://www.chartjs.org/docs/latest/charts/line.html

Food for thought: should the chart load its data with AJAX? That would make for faster page loads. But it would require the developer to create a route and controller for that chart, which is... less than ideal.

### PR DESCRIPTION
**Pull request by tabacitu**
Fixes #2371
Alternative to https://github.com/Laravel-Backpack/CRUD/pull/2593

**Step 1.** ```composer require consoletvs/charts:"6.*"``` 

**Step 2.** ```php artisan make:controller {Admin/Charts/LatestUsersChartController}```
 - this will create a controller with that name inside ```app\Http\Controllers\Admin\Charts```

**Step 3.** Inside that controller, make sure to:
- extend ```Backpack\CRUD\app\Http\Controllers\ChartController```
- use ```ConsoleTVs\Charts\Classes\Chartjs\Chart``` (or the chart of a the library you want)
- configure your chart inside the ```setup()``` method
- (optional) define the results inside the ```data()``` method, if you want this ChartController to respond to AJAX requests

```php
<?php

namespace App\Http\Controllers\Admin\Charts;

use App\User;
use Backpack\CRUD\app\Http\Controllers\ChartController;
use ConsoleTVs\Charts\Classes\Chartjs\Chart;

class LatestUsersChartController extends ChartController
{
	public function setup()
	{
		$this->chart = new Chart;

		// MANDATORY. Set the labels for the dataset points
	  	$this->chart->labels(['6 days ago', '5 days ago', '4 days ago', '3 days ago', '2 days ago', 'Yesterday', 'Today']);

		// RECOMMENDED. Set URL that the ChartJS library should call, to get its data using AJAX.
		$this->chart->load(backpack_url('charts/users'));

		// OPTIONAL
		$this->chart->minimalist(false);
		$this->chart->displayLegend(true);
    }

    /**
     * Respond to AJAX calls with all the chart data points.
     * 
     * @return json
     */
    public function data()
    {
		$today_users = User::whereDate('created_at', today())->count();
		$yesterday_users = User::whereDate('created_at', today()->subDays(1))->count();
		$users_2_days_ago = User::whereDate('created_at', today()->subDays(2))->count();
		$users_3_days_ago = User::whereDate('created_at', today()->subDays(3))->count();
		$users_4_days_ago = User::whereDate('created_at', today()->subDays(4))->count();
		$users_5_days_ago = User::whereDate('created_at', today()->subDays(5))->count();
		$users_6_days_ago = User::whereDate('created_at', today()->subDays(6))->count();

		$this->chart->dataset('Users Created', 'bar', [
				$users_6_days_ago, 
				$users_5_days_ago, 
				$users_4_days_ago, 
				$users_3_days_ago, 
				$users_2_days_ago, 
				$yesterday_users, 
				$today_users,
			])->color('rgba(205, 32, 31, 1)')
			->backgroundColor('rgba(205, 32, 31, 0.4)');
    }
}
```

**Step 4.** Add a new route inside ```routes/backpack/custom.php```, to fetch the data for that chart using AJAX. The ```response()``` method that ChartController provides is perfect for this:

```php
    Route::get('charts/users', 'Charts\LatestUsersChart@response');
```

**Step 5.** Actually use that chart inside a widget:

```php
[ 
    'type' => 'chart',
    'controller' => \App\Http\Controllers\Admin\Charts\LatestUsersChartController::class,
    'content' => [
	'header' => 'New Users', // optional
	// 'body' => 'This chart should make it obvious how many new users have signed up in the past 7 days.<br><br>', // optional
    ],
    // 'class' => 'card mb-2', // optional
    'wrapperClass' => 'col-md-6', // optional
]
```

The end result of doing this inside the dashboard being:

Screenshot 2020-03-24 at 17 43 48

Screenshot 2020-03-24 at 17 43 58

### CODE REVIEW

**Comment by tabacitu** [comment]
This implementation has quite a few benefits over https://github.com/Laravel-Backpack/CRUD/pull/2593 :

**Numero 1.** It support all charting libraries, not just one. And the developer EASILY change the charting library they want, just by changing one line at the top of their ChartController:

```diff
-use ConsoleTVs\Charts\Classes\Chartjs\Chart;
+use ConsoleTVs\Charts\Classes\Echarts\Chart;
+use ConsoleTVs\Charts\Classes\Fusioncharts\Chart;
+use ConsoleTVs\Charts\Classes\Highcharts\Chart;
+use ConsoleTVs\Charts\Classes\C3\Chart;
+use ConsoleTVs\Charts\Classes\Frappe\Chart;
```

Now, sometimes it's just that easy. But not all charting libraries support the same syntax (ex: color, backgroundColor, fillColor) so _sometimes_ other tweaks are needed. The PHP errors will be clear enough in those cases.

**Numero 2.** Since LatestUsersChartController extends ChartController, not the actual Chart object, there are A LOT fewer methods that the developer can overwrite by mistake.

**Numero 3.** It's cleaner and easier to understand. Even for noobs, it shouldn't be scary at all all, it's just a controller that has to have 1/2 methods: ```setup()``` and optionally ```data()```.

I'm pretty happy with this implementation. It still has the same downsides as #2593 :
- for AJAX Charts, you have to define the labels inside setup(), and the datasets inside data(); it's a limitation of the laravel charts library; I don't see a nice way around it;
- it uses ChartJS from a CDN - but this doesn't bother me as much now, since:
    - developers can EASILY change the path to the file, if they want, by adding a ```protected $library = 'http://path/to/file';``` to their controller, or overwrite the method ```getLibraryFilePath()``` that does the same thing;
    - since we now support all JS libraries supported by [Laravel Charts](https://charts.erik.cat/), I don't think it would be a good idea to load and publish all their JS; i expect most projects to only be one (or none); so the other JS files will be just bloat;

- there are 5 freakin' steps to create a chart widget; again, creating our own ```php artisan backpack:chart {LatestUsers}``` can reduce this from 5 steps to 3;

**Comment by tabacitu** [comment]
I realise the example above might look a little intimidating. But I think that's just because its indentation is messed up. Here's a simpler example, that displays one of the pie charts above:

```php
<?php

namespace App\Http\Controllers\Admin\Charts\Pies;

use App\User;
use Backpack\CRUD\app\Http\Controllers\ChartController;
use ConsoleTVs\Charts\Classes\Echarts\Chart;

class EchartsPieController extends ChartController
{
	public function setup()
	{
		$this->chart = new Chart;

		$this->chart->dataset('Red', 'pie', [10, 20, 80, 30])
					->color([
						'rgb(70, 127, 208)', 
						'rgb(77, 189, 116)', 
						'rgb(96, 92, 168)', 
						'rgb(255, 193, 7)'
					]);

		// OPTIONAL
		$this->chart->displayAxes(false);
		$this->chart->displayLegend(true);

		// MANDATORY. Set the labels for the dataset points
		$this->chart->labels(['HTML', 'CSS', 'PHP', 'JS']);
    }
}

```

Pretty easy, right?

**Comment by tabacitu** [comment]
I've slept on it - I still like this implementation. 

I'll move it to "Review". If anybody cares about this feature, **please take a look and give your 2 cents**. I'm eager to merge this into 4.1 😁

**Comment by tabacitu** [comment]
Todo:
- [  ] add to docs
- [  ] add to upgrade guide

**Comment by azaricstefan** [comment]
This feature is awesome!

**Pull request merged**
