### PR TITLE
Update checklist.blade.php

### PR DESCRIPTION
**Pull request by PiahDoNeumann**
Add option to set attributes config

### CODE REVIEW

**Comment by tabacitu** [comment]
Sure thank you @PiahDoNeumann ! It's been merged into ```master```, and it'll be tagged shortly.

Cheers!

**Comment by ziming** [comment]
How does this work?

**Comment by tabacitu** [comment]
I didn't check, but all in almost all other fields you can define ```attributes``` to specify whatever you want: https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/fields/text.blade.php#L12

So if you want to add somethink like a ```style``` attribute, you can do that. This should work similarly. @PiahDoNeumann please correct me if I'm wrong. The reason it does not use that view we use in all other fields (I assumed) is because it shouldn't have the default class all other fields have.

**Comment by PiahDoNeumann** [comment]
I needed to show the checklist disabled, I checked in the checkbox field and had the code there, copied and it worked the way I wanted. This code "'attributes' => ['disabled' => 'disabled'],".

Thank @tabacitu for accepting the PR.

**Pull request merged**
