### PR TITLE
[MINOR] Add cachebusting to all backpack's assets

### PR DESCRIPTION
**Pull request by mahasadhu**
Add cachebusting to all backpack's assets
-------
Usually I overrode almost all of backpack's blade file just to add this cache buster, simply to force clear / reset client's cache.

Until I realized, when I do this I will not get any updates done to those overridden files...

### CODE REVIEW

**Comment by tabacitu** [comment]
Hmm... this... this sounds like a no-brainer... I'm actually surprised we weren't already doing this... Good work @mahasadhu !

@pxpm any idea _why_ we're not doing this already? Did we just forget to do this, or is there a possible problem I can't see right now?

**Review by promatik — APPROVED** [review]
These assets are published on developer project, and unless he publish it again, the assets wont get updated with backpack/crud updates, I believe that's why this cache busting was not present until now. Any way, it's nice to have since developer may republish the assets.

**Comment by pxpm** [comment]
This will have the downside of downloading new assets when they didn't change. You change 1 file and the cache busting string and all the files will be downloaded again. 

It's not that I don't like the idea, and in the meanwhile it could help ? But we might think in having a manifesto or something with all cache strings for files so we make sure only the updated files are changed. 

All in round, I like the idea of the caching bust string.

**Comment by tabacitu** [comment]
Since this is in line with what we're doing for general assets, defined in `config/backpack/base.php`, I think this is a good idea. It's unlikely that people will be getting any updates from them - since those particular files rarely (if ever) get updated by us Backpack maintainers, but... it's technically the way it should be.

So I'm going to merge this, thanks @mahasadhu ! It'll be available with a `composer update` starting next Monday, most likely.

Cheers!

**Pull request merged**
