### PR TITLE
Fix repeatable converting non-string values to string when adding prefix

### PR DESCRIPTION
**Pull request by pxpm**
refs: #3649 

Problem: if the value of the field is `null` in the database, as we are concatenating the prefix on it, it would become a string `"null"` (if not prefix, otherwise "prefix/null").

Solution: only apply prefix if the value is a string and it has some value. Checking if is a string will cover other use cases where we should not "convert" to string, like booleans.

### CODE REVIEW

**Review by promatik — APPROVED** [review]
@pxpm I noticed `values[$(this).data('repeatable-input-name')]` was being used a lot, so I turned it into a variable, I think it's more clean this way, hope you don't mind 😅

I tested and it's working, let me know what you think ✌

**Comment by pxpm** [comment]
I merged master here, but I found out another bug.

When the form submission fail validation (and we still have the base_64 encoded image), on page reload the prefix is added and breaks the image.

I still need to figure out the best way to distinguish between an "update" operation page load and a failed validation load!

**Comment by promatik** [comment]
@pxpm I was able to reproduce the issue you reported. I pushed a change to possibly fix that.
It just validates the current value is also not a base64, besides the previous validation of being a string with length.

When the image is base64 we never want the prefix right?

**Comment by pxpm** [comment]
@promatik I've just refactored the null coalescing operator into a conditional one as the first is not supported in IE. 

If you think the change is good please approve it, from my tests it seems ok.

Best,
Pedro

**Review by promatik — APPROVED** [review]
Perfect @pxpm 👌
I tend to forget about IE 🙃

**Pull request merged**
