### PR TITLE
Allow sending a default class attribute to field wrappers

### PR DESCRIPTION
**Pull request by njbarrett**
Works in the same way you can pass a default class to the fields themselves.

### CODE REVIEW

**Comment by OwenMelbz** [comment]
How would you go about using this feature? Like where would you define $default_class ?

**Comment by njbarrett** [comment]
I am using it because I have created a new field type in my project and I want to be able to define a default class for the wrapper.

**Comment by OwenMelbz** [comment]
Ah right I see.

Maybe instead of merging a small PR like this the feature could be bulked out more.

For example this method of doing it requires users to publish the view, and is pretty niche use case at the moment.

What I feel would be better is to make better use of the configs.

E.g within the config/backpack/crud.php we could do something like

'default_form_group_class' => 'class class class'
'default_form_class' => 'class'
'default_form_control_class' => 'class'

Then it could be globally defined, or overwritten in a controller.

Would mean users have bit more control and it's globally configurable and no need to publish the views to modify.

I feel if a feature like this was introduced we'd need to go the whole hog with config items like above

**Comment by tabacitu** [comment]
That's a great idea, @njbarrett and @OwenMelbz . A config and method to overwrite it in each controller sounds nice. Because you might want some cruds col-md-6, others col-md-12. Right?

**Comment by njbarrett** [comment]
Yeah I can understand why. I'll see what I can do

**Comment by njbarrett** [comment]
@OwenMelbz what if it is field specific? The default class for the wrapper of the field.
If I'm creating a new field and I know by default it should be `col-md-6`. But I don't want that to be the default for ALL fields.
Would the config file method work in this case?

**Comment by OwenMelbz** [comment]
By setting it in the config, you could overwrite the config in your controller

e.g

```php
Config::set('backpack.crud. default_form_group_class', 'my-classes-here');
```

or you just use the built in wrapper functionality

```php
$this->crud->addField([
    'name' => 'something',
    'wrapperAttributes' => ['class' => 'custom fields here']
]);
```

OR as its a custom field, you can just add it directly to your field, no need to edit the parent ones

**Comment by tabacitu** [comment]
Guys, I'm going to close this PR - it's been a while and is hasn't picked up much interest from others. I still think having the default wrapperAttribtues class in a config file is a good idea, but it's a "nice-to-have" and this PR doesn't treat that, so I'll close it.

@njbarrett , thanks a lot for the PR, but I don't see introducing ```$default_class``` like this to be a good long-term solution, as it doesn't conform to how we define things now for each field, and developers can already use:
```php
$this->crud->addField([
    'name' => 'something',
    'wrapperAttributes' => ['class' => 'custom fields here']
]);
```

Cheers!

**Pull request closed without merging**
