### PR TITLE
Added the required to email field

### PR DESCRIPTION
**Pull request by ricardovanlaarhoven**
The required property was not used in the email field, now it is!

### CODE REVIEW

**Comment by lloy0076** [comment]
My only comment is a business logic one; what if this changes expected behaviour? I know, people shouldn't be expecting an absent but required field to behave but...sillier things have been seen in life.

**Comment by ricardovanlaarhoven** [comment]
@iloy0076 i think it doesn't break, and if it breaks the only way it could is that a field becomes required that isn't required now but was meant to be required.

And if this kind of small changes don't pull through what changes will? So many people want to improve this project.. and it is needed.. let them.

**Comment by lloy0076** [comment]
I wasn't suggesting not to improve the project - I was wondering if this would cause entirely unexpected changes for someone :)

**Comment by tabacitu** [comment]
Hi @ricardovanlaarhoven , thanks for contributing to Backpack. First PR, I see. Let this be the first of many :-) 

I don't think I completely understand what this does, so I can merge it right away. Please help me out, will you? I'll explain what _I do_ understand below.

So, there are already 2 levels of validation that you can use on any Backpack/CRUD field:
- the [form request validation](https://laravel-backpack.readme.io/docs/crud-example#section-the-requests) (in PHP, which you MUST do to ensure the integrity of your db);
- the HTML5 input validation, which you COULD add to any field, for front-end validation; you just need to pass required as any other HTML attribute:
```diff
$this->crud->addField([
     // MANDATORY
    'name'  => 'address', // DB column name (will also be the name of the input)
    'label' => 'Street address', // the human-readable label for the input
    'type'  => 'text', // the field type (text, number, select, checkbox, etc)
    
     // OPTIONAL + example values
    'default'    => 'some value', // default value
    'hint'       => 'Some hint text', // helpful text, show up after input
    'attributes' => [
       'placeholder' => 'Some text when empty',
       'class' => 'form-control some-class',
+      'required' => 'required',
     ], // extra HTML attributes and values your input might need
     'wrapperAttributes' => [
       'class' => 'form-group col-md-12'
     ] // extra HTML attributes for the field wrapper - mostly for resizing fields using the bootstrap column classes
]);
``` 

The above work for all 44+ field types, including ```email```.

**The way I understand this PR, it adds a third layer for the ```email``` field, whereby if you specify ```"required"=>true``` it makes it required?** The reason I'm asking is because... I see you're calculating ```$isRequired``` and ```$dbdefault```, but I don't see the field using them anywhere... 

I could be wrong though. It's been known to happen :-)

**Comment by ricardovanlaarhoven** [comment]
Hi @tabacitu 

I just looked at the way you did it at the text field, so its the same code that you (used to)  use(d)
I think the way you're suggesting is also fine.

But i think it's also important to be consistent and use the same way in every field

**Comment by tabacitu** [comment]
@ricardovanlaarhoven  great to hear that. I'll close this PR then, but thanks for submitting it, and for finding a solution - most people don't bother. Cheers to you!

**Pull request closed without merging**
