### PR TITLE
[Feature Request] Allow delete button on edit page

### PR DESCRIPTION
**Pull request by maurohmartinez**
### BEFORE - What was wrong? What was happening before this PR?

Nothing, it is a feature requested [here](https://github.com/Laravel-Backpack/ideas/issues/208).

delete-button-on-edit

### AFTER - What is happening after this PR?

The new feature is added.

### How did you achieve that, in technical terms?

Only one file was changed. A button is added in `src/resources/views/crud/inc/form_save_buttons.blade.php`.

### Is it a breaking change?

No.

### How can we test the before & after?

Make sure that the buttons shows up when using `$this->crud->setOperationSetting('showDeleteButton', true);`.

**Important:** documentation also is being updated [here](https://github.com/Laravel-Backpack/docs/pull/395).

### CODE REVIEW

**Review by pxpm — CHANGES_REQUESTED** [review]
Hey @maurohmartinez thanks for the PR 🙏 

I am a bit concerned of doing this in a non-breaking way. I will write my reasoning below.

1) Until now, the only places where we displayed the Delete button was in `ListOperation` and in `ShowOperation`. 
So, if I as a developer do something like this in `setupListOperation`: 
```php
if (! backpack_user()->hasRole('admin')) {
    $this->crud->denyAccess('delete');
}
```
This would prevent the delete button to display on the List, but would now display on `UpdateOperation`, without me having the opportunity to disable it without following an update guide. 

This wouldn't be an issue if we use `opt-in` instead of `òpt-out`.

2) We need to make sure that the `DeleteOperation` is loaded, otherwise we wouldn't have the delete route available.

3) Another thing that I dislike is the fact that we are adding a method to the `CrudPanel` object that's very general `hideDeleteButton()`, but it actually only hides the delete button on the update operation.  

So my suggestion goes as following:
- making the Delete button on edit page an opt-in setting instead of opt-out. In next version we can make it on by default.
- remove the function from CrudPanel object, we can create an helper function in `UpdateOperation` if needed, or we can just document the usage of `$this->crud->setOperationSetting('deleteButton', true)` in `setupUpdateOperation()`. 
- add the docs for it 📖 

Cheers

**Comment by maurohmartinez** [comment]
@pxpm thank you for your review!

I made those changes and also created a [PR for docs](https://github.com/Laravel-Backpack/docs/pull/395).
Can you have a look again?

Thanks!

**Comment by pxpm** [comment]
Thanks @maurohmartinez 🙏 I like it ALOT now !

The docs really help to better understand what should/is happening in this PR, from there:

> `This will allow admins to remove entries right from the **Update Operation**, and it will redirect them back ot the **List Operation** afterwards.`

This raises the question for me: What if the current user doesn't have access to that `ListOperation` ? We will be giving him 404 whenever he deletes something from the `UpdateOperation`.

I think a simple and efetive way around is by accepting a `closure` as argument too. 
```php
$this->crud->setOperationSetting('deleteButton', function($entry) { return backpack_url('termination-notice/'.$entry->uuid.'/pdf'); }
```

So `deleteButton` would be either `absent`, `boolean` or `closure`. In case of `absent` or `false`, we don't show the button, case `true` or `closure` we either redirect to the `ListOperation` (when true), or run the closure that should return the url where user should be redirected. 

I think it's the last suggestion I have, what you think about it ? Maybe we need more parameters other than entry ?

**Comment by maurohmartinez** [comment]
@pxpm Thank you for your comments, very helpful.

I think instead of a closure, we can simply allow devs to pass a url of type `string` which we will use to redirect admins after deleting success.

This will redirect admins to the default url — List Operation path.
```
$this->crud->setOperationSetting('showDeleteButton', true);
```

Or this will use their string provided as url.
```
$this->crud->setOperationSetting('showDeleteButton', 'my_custom_url');
```

As you mentioned, if `showDeleteButton` is not set, or set to false, then we do not show the button.
I made the changes so can maybe have a quick test and see if you like the idea?

If yes, then I will update the docs PR.

Thanks!

**Comment by pxpm** [comment]
Hey @maurohmartinez sorry it took so much time to get back here. 

I am sorry but I don't agree with passing a string instead of a closure.

Using a string will make this function stale, and not fully entry dynamic. 

What I mean by "entry dynamic" is that with a closure, we receive the `$entry`  that is about to be deleted (or already deleted, whatever) as a function parameter in the closure.
Then we can do stuff like: `if($entry->type === 'book') { redirect('bookstore'); }` inside the closure. Additional to what I had already mentioned like `backpack_user()->hasRole()` that would produce the same result with or without closure. 

If you have an argument on why we should use the string parameter instead of a closure please go ahead, I may be missing something here. Otherwise let's please use the closure for full customizability 🙏 

Cheers

**Comment by maurohmartinez** [comment]
@pxpm Thank you for your comments!

I agree, a closure will definitely make it more flexible. However, the logic is within an ajax call, after the user confirms a message shown with `swal`. After removing the entry, I though expecting a string back from the ajax call with the url to redirect (using `window.location.href`) was the best way to deal with it. The downside, yes, it is not as flexible as using a closure, although not suitable for js.

Am I making sense? Maybe I am still missing something? Or you have a better idea?
Please let me know :)

Thanks again!

**Comment by pxpm** [comment]
Hey @maurohmartinez thanks for the follow-up. I agree with your reasoning, let's move on from that. 

I think I've found a the last small inconsistency regarding the delete button:

If I remove the `DeleteOperation` trait the button is not setup, that's great 🟢  

But if I deny delete access the button still show up 🔴 but then you get the permission denied 🟡🟢   

```php
public function setup()
{
    if(! backpack_user()->hasRole('admin') {
            $this->crud->denyAccess('delete');
        }
}
protected function setupUpdateOperation()
    {
        // this still display the button, but since user as no access the operation to delete will fail.
        $this->crud->setOperationSetting('showDeleteButton', true);
    }
```
My suggestion is that we also check for crud access to delete before the button setup, that way we will not display the button when user has no access to delete.

I think after you fix that, and give a little adjustment to the docs, mentioning the option of passing  `url string` and we are good to go here.

GJ @maurohmartinez 🙏

**Comment by maurohmartinez** [comment]
@pxpm How do you see it now?

Thanks for the suggestion, I think it improves the functionality quite a lot!

**Review by pxpm — APPROVED** [review]
Way to go! 👍

**Pull request merged**
