### PR TITLE
fix error display when using prefix in fields

### PR DESCRIPTION
**Pull request by pxpm**
### BEFORE - What was wrong? What was happening before this PR?

Reported in https://github.com/Laravel-Backpack/CRUD/issues/4835

When adding `prefix => 'some_prefix'` in the field configuration, the errors are not properly displayed.

This was due to the fact that when there is a `prefix` in a field it wraps the input in a new div `input-group` to display the inline prefix with the field. 

### AFTER - What is happening after this PR?

The prefixed fields get the same css as the non prefixed and display the errors accordingly. 

### How did you achieve that, in technical terms?

Replaced `.parent` with `.closest`, that way jQuery will search the parent and the parent parents until it finds the `form-group` element where the error classes should be added.
Also replaced `children` with `find`, because `children` will only search the direct childrens of the element and `find` will check deeper inside the childrens childrens. 

### Is it a breaking change?

I hope not, from my tests everything seems to be working fine after this PR.

### How can we test the before & after?

Add `prefix => '#'` in Monster `text` field (it's a required one). Trigger the validation error to see the errors display.

### CODE REVIEW

**Comment by jorgetwgroup** [comment]
Hi @pxpm great work here.

Here my test:

On main i get this problems, i try without prefix and work as expected:

screenshot-backpack test-2022 12 20-11_26_50

Then, with prefix not show any border on input (the same with avatar field, type browse):

screenshot-backpack test-2022 12 20-11_27_05

Suffix fail too:

screenshot-backpack test-2022 12 20-11_27_44

With this branch work as expected:

screenshot-backpack test-2022 12 20-11_28_35

Just a really small "but...", look at this:

Screenshot 2022-12-20 at 11 28 45

On browse type field i see this small problem with right border.

Cheers.

**Comment by pxpm** [comment]
Hey @jorgetwgroup so I've just submitted a fix to show the red border on the rigth side of browse field too. 

The border was hidden behind the button I bring it front with `z-index`. 

This required that I ran `npm run prod` to recompile crud assets, so to get the fix users would need to publish backpack assets after updating the app. `php artisan backpack:publish-assets`. 

@tabacitu from the updated packages I've given them a quick look everything seems to be working fine, but it's better to have a second pair of eyes here 🦅 

Cheers

**Comment by jorgetwgroup** [comment]
Hi @pxpm 

I confirm is working.

Before:
screenshot-backpack test-2022 12 26-16_07_49

After:
screenshot-backpack test-2022 12 26-16_14_04

Look ready to merge.

Cheers.

**Comment by tabacitu** [comment]
Thanks guys! I usually like the `npm rum prod` to be a separate PR in itself, but I'll let this one slide Pedro 😉 I've seen the commit history, so I understand the change this PR _actually_ does is small.

**Comment by tabacitu** [comment]
Of course, I meant `npm RUN prod` not `npm RUM prod` 😅 But maybe my subconscious is telling me something

johnny-depp-drinking-gif

**Pull request merged**
