### PR TITLE
Update HasRelationshipFields.php

### PR DESCRIPTION
**Pull request by mgralikowski**
Fix method (for now return only table name w/t prefix)

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @mgralikowski 

Why is this change needed ? The way it was before was not working ? 

Best,
Pedro

**Comment by mgralikowski** [comment]
As I wrote, this method in the previous version never returned a prefixed table, just a raw table name.

**Comment by mgralikowski** [comment]
It is because `$this->getConnectionName()` returns always null so I would avoid using it. Maybe this method is limited only to initiated instances of models.

**Comment by tabacitu** [comment]
Got it! Thank you @mgralikowski . 

@pxpm could you please double-check on a project that _actually uses db prefixes_? I see `getTableWithPrefix()` is used in only 3 places by Backpack code itself, one being inside the guessing functionality - it'd be good to know that it doesn't break those 3 places. 

@mgralikowski once @pxpm  gives his approval I will merge and tag this.
Cheers!

**Review by pxpm — APPROVED** [review]
Indeed `$this->getConnectionName()` return null.

From Laravel api: https://laravel.com/api/7.x/Illuminate/Database/Eloquent/Model.html#method_getConnectionName

The `getConnectionName()` only works if you define `protected $connection = 'connection'` in your model, otherwise we should build the connection with `getConnection(null)` that will setup the connection as the default in the config. 

https://github.com/laravel/framework/blob/0d1ac3282e019ed4608b715ac4f8c57a0a042b9b/src/Illuminate/Database/Eloquent/Model.php#L1308

I tested this change and it works as expected.

This should be merged with #3125

**Comment by tabacitu** [comment]
Merged into `master`. It'll be available later today as 4.1.18.
Thanks again @mgralikowski & @pxpm !

**Comment by mgralikowski** [comment]
Release, please 🙏

**Pull request merged**
