### PR TITLE
Add repeatable support to js library

### PR DESCRIPTION
**Pull request by pxpm**
This is a redo of #4376 with https://github.com/Laravel-Backpack/CRUD/pull/4376#discussion_r879689220 applied. 

```javascript
crud.field('wish').subfield('country').change(function(e,value, rowNumber) {
    crud.field('wish').subfield('body', rowNumber).disable();
 });
```

This needs https://github.com/DigitallyHappy/backpack-pro/pull/38

### CODE REVIEW

**Comment by tabacitu** [comment]
Thanks @pxpm ,

I've merged the corresponding PRO PR. But I see a possible problem here, when testing it. I've tried to add a new scenario, starting from your example above:

```javascript
// EXAMPLE 11
// SHOUD: when subfield changes, disable another subfield
crud.field('wish').subfield('country').change(function(e, value, rowNumber) {
    crud.field('wish').subfield('body', rowNumber).disable(value != '');
 });
```

Notice that what I'm trying to do is pass a parameter to the `disable()` function. Basically
- when a Country is selected, body input should be disabled
- when NO country is selected, body input should be active 
 
That's because `disable(false)` should actually do `enable()` after https://github.com/Laravel-Backpack/CRUD/pull/4379 was merged. While that worked before, after this PR is merged... that no longer works... Any idea why? Feel free to collaborate with Antonio on this one, 2 heads are better than one here.

**Comment by pxpm** [comment]
Hello @tabacitu 
I don't think you were used to do that, even in the PR you mentioned the `disable()` function does not accept any parameter. 

Not sure if there is a reason that @promatik is aware on why he didn't added the parameter to the `disable()` method other than thinking that it could be done from `enable()` ? 

I tried with: 

```javascript
        disable(value = true) {
            return this.enable(value ? false : true);
        }
```

It seems to work, but not sure if there are any implication that I am not aware at the moment. 

Cheers

**Comment by tabacitu** [comment]
Ahahahah. Ok, by bad then. Tested, merged.

**Comment by tabacitu** [comment]
Actually... I've edited the name of this PR, because in my opinion, this does NOT finish adding repeatable support, this just adds `subfield` support.

Just tested the methods on the repeatable field itself (not a subfield), and I see:
- 🟨  `change()` doesn't work
- ✅  `hide()` and `show()` work
- 🟨  `enable()` and `disable()` don't work
- ✅  `require()` and `unrequire()` work

But we can fix that in a separate PR.

**Comment by pxpm** [comment]
What we want from `change()` @tabacitu  ? new row added/deleted/reordered, or when some subfield change value the repeatable is considered to be "changed" ? What would be your "value" in the closure ? The whole repeatable values ? 

When you `disable()` you expect all subfields to be disabled plus delete buttons/add new row disabled too ?

**Pull request merged**
