### PR TITLE
[4.0][Feature] customize available save actions

### PR DESCRIPTION
**Pull request by mariavilaro**
This change makes possible to remove actions from the save options. It's used like this:

$this->crud->removeAction('save_and_new');

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @mariavilaro ,

I think this is an excellent addition, thank you. I've put it on the backlog to be included in Backpack 3.3.x (current version), so I'll be reviewing and merging it soon. I'll keep you posted.

Cheers!

**Comment by FrittenKeeZ** [comment]
This could be merged with #679

**Comment by yugen** [comment]
I'm wondering what the status is on this.  This feature would be helpful for one of my projects.  Thanks!

**Comment by tabacitu** [comment]
Thank you for working on this @mariavilaro - I'm sorry this did not get merged at the time. 

I think you'll be glad to know we've _finally_ decided to merge a solution for this. We're working on it in #2356 - please follow it there if you're interested. It will have ```add```, ```remove``` and ```replace``` functionality.

Thanks again for taking the time to submit the PR. Even if this one did not get merged, I'm very grateful for it. You were right to propose a solution to this, it _is_ something worth solving.

Thanks again.
Cheers!

**Pull request closed without merging**
