### PR TITLE
[4.1][Feature][Ready] Feature select2_many and select2_one

### PR DESCRIPTION
**Pull request by OliverZiegler**
This PR references #1442 and implements fields for the following "inverse" relation types as these are currently not present.

- hasMany: select2_many
- hasOne: select2_one

As this affects only private functions in the `PanelTrait\Create` this should be non-breaking as people being affected with this changes have excessively overwritten the CrudPanel and PanelTraits, I think.

### CODE REVIEW

**Comment by OliverZiegler** [comment]
## So after a bit of sleep I just have the following additional thoughts:

**Should hasMany been saved via the model update method?**
**Benefit**: There will be revisions (if enabled) for the change
**Drawback**: As this is a 1:n relation, this could lead to many DB requests. With the current implementation we need only two. One for add new relatives and one for removing the old. But this is plain sql without any model events fired...

**Do the changes for HasOne affect the select2_array functionality?**
I didn't find any situation for when the relation had been an instance of `HasOne` as there was currently no special field for this. But I wonder if anyone has a situation in which the old code had been executed. If so please share with me so I can test if the edited implementation will still work for this case.

**Comment by OliverZiegler** [comment]
@tabacitu feedback would be much appreciated :)

**Comment by tabacitu** [comment]
Excellent PR, as always, @OliverZiegler . Thoroughly impressed :-)

At first glance it looks great, but like you said, since this modifies a CORE part of Crud (the saving), we need to test this like crazy, in all possible use cases, to make sure we don't break people's apps.

**Comment by OliverZiegler** [comment]
@tabacitu just to remind you 

and what do you think?

> Should hasMany been saved via the model update method?

**Comment by jrbecart** [comment]
Is this feature still on the future support list ?

**Comment by OliverZiegler** [comment]
@jrbecart I hope so. Took me some time to implement 🙈 and seems like a good feature still missing...

@tabacitu any progress on testing? Does this still work with newest backpack features as this PRs is quite old 😅

**Comment by tabacitu** [comment]
Took us a few years, but I'm happy to say that this has been fixed in Backpack 4.2, in a more general way. The `relationship` field now supports the `hasMany` and `hasOne` relationships that this PR fixes. But it also supports adding `subfields` to edit the related entry on-the-fly, in a subform. [Check it out here](https://backpackforlaravel.com/docs/4.2-dev/release-notes#better-than-ever-relationship-field-now-with-subfields-too) (in the 4.2 release notes).

@OliverZiegler , again, sorry it took so long to implement this. Your code served as both a nudge and starting place for this, so it was very helpful, thank you 🙏 But with only 2 people interested in this... could not prioritize doing it until now.

Thanks again! Closing this as it's no longer needed in 4.2.

**Pull request closed without merging**
