### PR TITLE
[4.1] Fix for getting table name with prefix.

### PR DESCRIPTION
**Pull request by pxpm**
refs: #3119

### CODE REVIEW

**Comment by tabacitu** [comment]
Thank you! Waiting for your final thumbs up @pxpm & @mgralikowski !

**Comment by mgralikowski** [comment]
This PR is only partial solution. This and https://github.com/Laravel-Backpack/CRUD/pull/3126 must be accepted to final fix.

**Comment by pxpm** [comment]
Ready to merge with #3126

**Comment by tabacitu** [comment]
Awesome. Thanks for the help (and the patience) everyone. Merged into `master`. It'll be available later today as 4.1.18.

**Pull request merged**
