### PR TITLE
[4.2] Merge browse fields

### PR DESCRIPTION
**Pull request by jnoordsij**
Merge the `browse` and `browse_multiple` fields into a single field, so all features are shared.

Fixes https://github.com/Laravel-Backpack/CRUD/issues/2794

To Do:
- [x] Check if no functionality of the `browse` field is accidentaly removed now
- [x] Decide wether or not to call `.replace(/\\/g,"/")` on elFinder output
- [x] Update docs

### CODE REVIEW

**Comment by tabacitu** [comment]
So clean! Thanks a lot for taking the time to do this @jnoordsij ! The diff doesn't do it justice - I assume you've just copy-pasted the code from `browse_multiple` to `browse`, that's the _actual_ difference between the old `browse` and the new `browse`?

**Comment by tabacitu** [comment]
Love the fact that you added those leftover tasks. Could you please explain them a little bit?

> Check if no functionality of the browse field is accidentaly removed now

Totally agree.

> Decide wether or not to call .replace(/\\/g,"/") on elFinder output

Hmm why? Which one had it? What would that do?

> Update docs

I don't really feel this is needed - as far as the user is concerned, it's the same exact API. But... we _could_ add a notice inside the `browse_multiple` field type that it will be deprecated in the next version, and just use `browse` with multiple true`. So ok, maybe I do agree on this one too 😆

**Comment by jnoordsij** [comment]
> So clean! Thanks a lot for taking the time to do this @jnoordsij ! The diff doesn't do it justice - I assume you've just copy-pasted the code from `browse_multiple` to `browse`, that's the _actual_ difference between the old `browse` and the new `browse`?

Yes, I actually did it in 3 separate commits so that git would understand, but appearently the global diff still lists it as changes to the `browse` field. However the git history and blame on the 'new' `browse` field correctly shows all edits to the old `browse_multiple` field.



> Love the fact that you added those leftover tasks. Could you please explain them a little bit?
> 
> > Check if no functionality of the browse field is accidentaly removed now
> 
> Totally agree.
> 
> > Decide wether or not to call .replace(/\/g,"/") on elFinder output
> 
> Hmm why? Which one had it? What would that do?

It was in the old `browse` field and was actually quite convenient, as elFinder by default uses the php constant `DIRECTORY_SEPARATOR`. On Windows installations this would mismatch with the forward slash that Laravel uses for file paths, so I needed this as well in my local development environment. I think it is a convenience feature that breaks little things (as I doubt many people actually relied on Windows directory separators), but I can make it into an optional parameter. 

> 
> > Update docs
> 
> I don't really feel this is needed - as far as the user is concerned, it's the same exact API. But... we _could_ add a notice inside the `browse_multiple` field type that it will be deprecated in the next version, and just use `browse` with multiple true`. So ok, maybe I do agree on this one too 😆

Yeah, I'd say it is easier to only document the `browse` field, so that if you would ever add more features, it spares you the effort of documenting it at both places or else have users missing out on it because the picked the wrong field ;)

**Comment by pxpm** [comment]
Hello @jnoordsij 

Thanks for submiting a PR. Indeed this is something we should do, there is no sense in having both fields with a simple flag that differentiates them. 

I just spotted some aesthetical changes.

Before you had: 

Screenshot_9

now it's:

Screenshot_8

Also in `browse single`, we are allowing people to select more than one file, and then just grab the first in the list. **I am ok with that**. 

Apart from that in my tests it's working as before. 

@tabacitu is this aesthetical change something to tackle or nvm ?

**Comment by jnoordsij** [comment]
Thanks for the testing! I saw that the old `browse` field allowed overriding of the readonly attribute, so I copied that. So everything should be functioning in the same way now.

**Comment by tabacitu** [comment]
> Yes, I actually did it in 3 separate commits so that git would understand, but appearently the global diff still lists it as changes to the browse field. However the git history and blame on the 'new' browse field correctly shows all edits to the old browse_multiple field.

Awesome @jnoordsij - I see it now, perfect!

> Also in browse single, we are allowing people to select more than one file, and then just grab the first in the list. I am ok with that.

@pxpm yeah... that's what `browse` did before this PR too. I'm ok with it too 👍 

> is this aesthetical change something to tackle or nvm ?

I think one line is much better for `single` browse, from a UI perspective. Paths are rarely very long - so it makes little sense to use two lines when one will do. If you only have one `browse` field in a form, it doesn't make much of a difference. But when you have 5 of them, it's 5 lines that you could have gotten rid of. You get a much shorter form without them. That's especially important when used in `repeatable`.

Another pain point would be when used with `size()` or `wrapper['class']`, to make it half the size or something. If the new single `browse` spans across two lines, it won't look good alongside a simple `text` field - one would take up one line, the other would take up two lines. So I guess we shouldn't really push this as a non-breaking change to people, unless it show the same as before - on a single line for `single` browse, on multiple lines for `multiple`. Otherwise we might make their forms a little uglier.

On the other hand, to achieve this better UI for single `browse`, we have to bloat up the blade file quite a bit with an `if` statement... But if it doesn't get too bloated, I think it's worth it.

Thanks for spotting this @pxpm , it's indeed something that's important.

**Comment by tabacitu** [comment]
I just had another look at this, and still like it A LOT, but I still think we should provide a one-line solution for single browse... 😞 

**@jnoordsij are you available to work on this a little bit more**? To make the single-file-picker one-line like it was in `browse`? Or should @pxpm or I do this ourselves?

Thanks again for all the work you've put into this - much appreciated.
Cheers!

**Comment by jnoordsij** [comment]
I'll try to squeeze it in somewhere later this week. Will keep you posted!

**Comment by jnoordsij** [comment]
@tabacitu this seems to work for me, let me know your findings!

**Comment by tabacitu** [comment]
Awesome! Thanks a lot @jnoordsij ! 

@pxpm double-check please?

**Comment by jnoordsij** [comment]
Closing in favor of #3952 which contains this branch with merge conflicts resolved. Thanks @pxpm !

**Pull request closed without merging**
