### PR TITLE
select2 add i18n for other locale

### PR DESCRIPTION
**Pull request by shiroamada**
for select2 blade file, I added
```
@if (app()->getLocale() !== 'en')
    @php
        $currentLocale = str_replace('_', '-', app()->getLocale());
    @endphp
    language: "{{ $currentLocale }}",
@endif
```
Added for language support

### CODE REVIEW

**Comment by promatik** [comment]
Hi @shiroamada!
Thank you for contributing to backpack 🙌

I have a question about this, I usually use backpack in my mother language, portuguese, and it's working due to this bit of code;
```php
@if (app()->getLocale() !== 'en')
    <script src="{{ asset('packages/select2/dist/js/i18n/' . app()->getLocale() . '.js') }}"></script>
@endif
```

Doesn't this works for you?
Is it possible that it doesn't work because in this case we don't replace `'_'` with `'-'`?

Please let me know, thank you.

**Comment by shiroamada** [comment]
@promatik, 
My use case because I am using **zh_CH**, so I notice I can't use it without **str_replace**
If you look into public/packages/select2/dist/js/i18n
image

pt-BR.js
sr-Cyrl.js
zh-CN.js
zh-TW.js
These 4 files are using "-",

However, Laravel app()->getLocale() for these 4 languages are using "_"
According to Laravel:-
https://laravel.com/docs/8.x/localization
> For languages that differ by territory, you should name the language directories according to the ISO 15897. For example, "en_GB" should be used for British English rather than "en-gb".

That's the reason I added the php code, I know it look ugly :)
`$currentLocale = str_replace('_', '-', app()->getLocale());`

The solution is open as long as better support for i18n.

**Comment by promatik** [comment]
```php
@if (app()->getLocale() !== 'en')
    <script src="{{ asset('packages/select2/dist/js/i18n/' . str_replace('_', '-', app()->getLocale()) . '.js') }}"></script>
@endif
```

@shiroamada do you think that, adding the string replace on the language load would be enough?

**Comment by shiroamada** [comment]
Yes! Brilliant idea. I forgot can't do inline. So I resubmit the pull request?

**Comment by promatik** [comment]
@shiroamada yes, we really appreciate if you have the time to submit a new PR 🙌
And you'll have the credit for it 👌

**Comment by shiroamada** [comment]
Sure. I am glad I can contribute for it. 👍

**Comment by shiroamada** [comment]
create another pull request at #3598

**Comment by promatik** [comment]
Thank you so much @shiroamada 🙌

**Pull request closed without merging**
