### PR TITLE
Array/Matrix field type

### PR DESCRIPTION
**Pull request by OwenMelbz**
**summary**
Enables users to add an array of items, with multiple columns if they need, with re-ordering and deleting.

**preview**
item array - edited

**usage**

database column type should be either json or text

```php

$this->crud->addField([
            'name' => 'products',
            'label' => 'Product',
            'type' => 'array',
            'properties' => [
                'name' => 'Item Name',
                'desc' => 'Description',
                'price' => 'Price'
            ],
            'max' => 5,
            'min' => 0
        ]);

$this->crud->setColumnDetails('products', [
            'type' => 'array',
            'display_field' => 'name',
            'label' => 'Products',
            'list' => true
        ]);

```

### CODE REVIEW

**Comment by tabacitu** [comment]
This is very very nice. Ok, now I understand what you're saying... this IS the array field type, no point rewriting it in jQuery now...

I'll take a closer look at it soon and merge it. Really nice work!

**Comment by OwenMelbz** [comment]
@tabacitu I would say before merging it, there are are a couple of considerations to make

- [ ] I really liked your idea if defining the input type e.g number/email/etc so it could be nice to implement that
- [ ] currently I bundle jqueryUI, angularjs and angular-sortable into the field - I think it's worth integrating this properly, for example I don't check for jQueryUIs existence which could cause issues

**Comment by tabacitu** [comment]
@OwenMelbz ,

I've made a few changes to this field. Please tell me if this is not ok with you:

1) I've made the UI a little simpler (table with borders, stripes, action columns next to each other, add button below, buttons without colors), so that this input won't stand out next to the others (it usually won't be more important, so it shouldn't stand be in the forefront)
screen shot 2016-09-25 at 08 39 46

2) I was thinking of naming it "table" instead of "array". Wouldn't that be more intuitive? When I think of an array, my first thought is of a single-dimension array, whereas "table" would better express having multiple columns. That would also make the field definition a little clearer:
```php
$this->crud->addField([
            'name' => 'products',
            'label' => 'Product',
            'type' => 'table',
            'columns' => [
                'name' => 'Item Name',
                'desc' => 'Description',
                'price' => 'Price'
            ],
            'max' => 5,
            'min' => 0
        ]);
```

What do you think?

**Comment by tabacitu** [comment]
Also, I had to rename the "array" column to "multidimensional_array" because people might be already using the old "array" definition and we should keep backwards-compatibility.

So:
```php
$this->crud->setColumnDetails('products', [
            'type' => 'multidimensional_array',
            'display_field' => 'name',
            'label' => 'Products',
            'list' => true
        ]);
```

**Comment by tabacitu** [comment]
Ok with you to merge this way? Anything I missed...?

**Comment by OwenMelbz** [comment]
@tabacitu my only concern is with the way the javascript is included - for example we're including jQuery UI and angualrjs regardless of if its already loaded.

If somebody was to use 2 different components that require jquery ui - the second jquery ui script tag, would unbind all the previous setup code.

Its almost like we need to pass the items into a helper function which includes the javascript, similar to how wordpress does [wp_enque_scripts](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) to prevent overloading

**Comment by tabacitu** [comment]
Hmm... I think that's a non-issue right now, since 
- that's the way all field scripts are loaded (select2, cropper, etc);
- developers will definitely find that during their testing;

We might think about that in version 4. So, in order to better find focus for this version of the software, I've created a [Project in Github for version 4](https://github.com/Laravel-Backpack/CRUD/projects/3). When ideas come up in the comments for new features and we decide they're worth taking into consideration and talking about, but not urgent enough to be included now, we place them there. Then, when we finish the core functionality, we can go through them. Some will probably get included in 3.2, 3.3, 3.4, not 4.0, but it's just a "basket" we can take features from. Sounds good?

**Comment by OwenMelbz** [comment]
Yup, so lets merge it up! :)

**Comment by tabacitu** [comment]
One more thing :-) The button adds one line, so it should say "add product" not "add products". Do you have a better name for that than "_entity_singular_"?

```php
        $this->crud->addField([
            'name' => 'options',
            'label' => 'Options',
            'type' => 'table',
            'entity_singular' => 'option', // used on the "Add X" button
            'columns' => [
                'name' => 'Option Name',
                'desc' => 'Description',
                'price' => 'Price'
            ],
            'max' => 5,
            'min' => 0
        ]);
```

**Comment by OwenMelbz** [comment]
I guess you could call it "button_label" if it isnt to get used elsewhere, however I've just used it in a PNotify prompt, so I'm happy with enitity_singular, Its optional anyway i guess!

**Comment by tabacitu** [comment]
That's weird. Now it stores the values in the database, but it no longer shows them on EDIT.

**Comment by tabacitu** [comment]
Note: I've separated the features into traits, like we talked about. And merged master into this branch to make sure there are no conflicts.

**Comment by OwenMelbz** [comment]
@tabacitu my bad. I know why they're not showing :) will push a fix in a moment

**Comment by OwenMelbz** [comment]
@tabacitu fix pushed, accidently left in a change where was using `json_encode` instead of `json_decode`

**Comment by tabacitu** [comment]
Awesome. 

**1) table field**
One more mention and we're done. On this field type I think we should force everyone to use [attribute casting](https://mattstauffer.co/blog/laravel-5.0-eloquent-attribute-casting). I've already made the modifications to support both ```array``` and ```object``` casting, will push them shortly, but needed to run it by you. Allowing access to it as pure JSON would force you to have json_decode() in many places inside your app, and that's not needed.

**2) multidimensional_array**
I think it would make more sense to split this into 2 column types:
- multidimensional_array
- array_count

No point in having two functionalities in 1 column type, right? Just say the word, I'll do it myself.

**Comment by tabacitu** [comment]
So my modifications above allow:
- no attribute casting
- casting as object
- casting as array

If it's ok by you, I'll merge it.

Cheers!

**Comment by OwenMelbz** [comment]
Yup thats fine with me :)

Quick question - just to save hassle in the future, I noticed you swapped the blade `@php` tags for native php tags, wondering what the main reason for this was? and if theres any benefits for doing this or the other?

Thanks :)

**Comment by tabacitu** [comment]
Oh, no benefits. My editor does't color code @php so I had to do it to work on the code :-)

I thinks it's fine either way.

**Comment by guillermohaad** [comment]
Hi friend @tabacitu , 
implement this new functionality but does not allow me to write in the text boxes and not allow me to add products ??

image

**Comment by tabacitu** [comment]
Hi @guillermohaad ,

It definitely should work. That's why we pushed it :-) Can you see any javascript errors in your Developer Console?

Cheers!

**Comment by guillermohaad** [comment]
@tabacitu  I have no problem with javascript, but on the console throws me this message when I try to write in the text boxes: (Unexpeted EOF)

image

**Comment by OwenMelbz** [comment]
@guillermohaad would you be able to view the page source, and upload a [gist](https://gist.github.com/) of it? - remove any sensitive information first of course?

**Comment by guillermohaad** [comment]
Hi friend  @OwenMelbz , I will upload
Thank you

**Comment by guillermohaad** [comment]
public gist : https://gist.github.com/guillermohaad/f54c1263eab671be7fa38168e174f271

**Comment by OwenMelbz** [comment]
Hi @guillermohaad Sorry I meant the HTML source code outputted by your browser

**Comment by guillermohaad** [comment]
ok , no problem... 

HTML source code outputted

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <meta name="csrf-token" content="8F0LQwMNyqCgCYRx4hPVnTpZKuTv79JGEAdGn61i" />

    <title>
      Añadir product :: Backpack Admin
    </title>

    
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/dist/css/skins/_all-skins.min.css">

    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/plugins/iCheck/flat/blue.css">
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/plugins/morris/morris.css">
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/plugins/datepicker/datepicker3.css">
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/plugins/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <link rel="stylesheet" href="http://localhost:8000/vendor/adminlte/plugins/pace/pace.min.css">
    <link rel="stylesheet" href="http://localhost:8000/vendor/backpack/pnotify/pnotify.custom.min.css">

    <!-- BackPack Base CSS -->
    <link rel="stylesheet" href="http://localhost:8000/vendor/backpack/backpack.base.css">

    	<!-- CRUD FORM CONTENT - crud_fields_styles stack -->
	    
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-purple sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="http://localhost:8000" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>B</b>p</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Back</b>pack</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Activar/desactivar la navegación</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <div class="navbar-custom-menu pull-left">
    <ul class="nav navbar-nav">
        <!-- =================================================== -->
        <!-- ========== Top menu items (ordered left) ========== -->
        <!-- =================================================== -->

        <!-- <li><a href="http://localhost:8000"><i class="fa fa-home"></i> <span>Home</span></a></li> -->

        <!-- ========== End of top menu left items ========== -->
    </ul>
</div>


<div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- ========================================================= -->
      <!-- ========== Top menu right items (ordered left) ========== -->
      <!-- ========================================================= -->

      <!-- <li><a href="http://localhost:8000"><i class="fa fa-home"></i> <span>Home</span></a></li> -->

                    <li><a href="http://localhost:8000/admin/logout"><i class="fa fa-btn fa-sign-out"></i> Salir</a></li>
        
       <!-- ========== End of top menu right items ========== -->
    </ul>
</div>
        </nav>
      </header>

      <!-- =============================================== -->

      <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
      <!-- sidebar: style can be found in sidebar.less -->
      <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
          <div class="pull-left image">
            <img src="http://placehold.it/160x160/00a65a/ffffff/&text=G" class="img-circle" alt="User Image">
          </div>
          <div class="pull-left info">
            <p>Guillermo Haad</p>
            <a href="#"><i class="fa fa-circle text-success"></i>En linea</a>
          </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
          <li class="header">ADMINISTRACIÓN</li>
          <!-- ================================================ -->
          <!-- ==== Recommended place for admin menu items ==== -->
          <!-- ================================================ -->
          <li><a href="http://localhost:8000/admin/dashboard"><i class="fa fa-dashboard"></i> <span>Panel</span></a></li>


          <!-- ======================================= -->
          <li class="header">USUARIO</li>
          <li><a href="http://localhost:8000/admin/logout"><i class="fa fa-sign-out"></i> <span>Salir</span></a></li>
		  <!-- GHAAD -->
		  <li><a href="http://localhost:8000/admin/elfinder"><i class="fa fa-files-o"></i> <span>File manager</span></a></li>
		  <li><a href="http://localhost:8000/admin/setting"><i class="fa fa-cog"></i> <span>Configuracion</span></a></li>
		  
		  <!--<li><a href="http://localhost:8000/admin/page"><i class="fa fa-file-o"></i> <span>Paginas</span></a></li> -->
		  <!-- ================================================ -->
			<!-- ==== Recommended place for admin menu items ==== -->
			<!-- ================================================ -->
		  
		  
		  <li class="treeview">
				<a href="#"><i class="fa fa-newspaper-o"></i> <span>Maestros</span> <i class="fa fa-angle-left pull-right"></i></a>
				<ul class="treeview-menu">
					<li><a href="http://localhost:8000/admin/tag"><i class="fa fa-tag"></i> <span>Etiqueta</span></a></li>
					<li><a href="http://localhost:8000/admin/vehiculos"><i class="fa fa-tag"></i> <span>Vehiculo</span></a></li>
					<li><a href="http://localhost:8000/admin/novedad"><i class="fa fa-tag"></i> <span>Novedades</span></a></li>
					<li><a href="http://localhost:8000/admin/article"><i class="fa fa-newspaper-o"></i> <span>Articulo</span></a></li>
					<li><a href="http://localhost:8000/admin/category"><i class="fa fa-list"></i> <span>Categoria</span></a></li>
					<li><a href="http://localhost:8000/admin/tag"><i class="fa fa-tag"></i> <span>Tags</span></a></li>
					<li><a href="http://localhost:8000/admin/products"><i class="fa fa-newspaper-o"></i> <span>Productos</span></a></li>
		  
				</ul>
		  </li>
			
		  
		  <!--<li><a href="http://localhost:8000/admin/menu-item"><i class="fa fa-list"></i> <span>Menu</span></a></li> -->
		  
		  
		  <!-- Users, Roles Permissions -->
			<li class="treeview">
				<a href="#"><i class="fa fa-group"></i> <span>Seguridad</span> <i class="fa fa-angle-left pull-right"></i></a>
				<ul class="treeview-menu">
					<li><a href="http://localhost:8000/admin/user"><i class="fa fa-user"></i> <span>Usuarios</span></a></li>
					<li><a href="http://localhost:8000/admin/role"><i class="fa fa-group"></i> <span>Roles</span></a></li>
					<li><a href="http://localhost:8000/admin/permission"><i class="fa fa-key"></i> <span>Permisos</span></a></li>
				</ul>
			</li>
			
			
		<!--		
		  <li class="treeview">
            <a href="#"><i class="fa fa-globe"></i> <span>Traduccion</span> <i class="fa fa-angle-left pull-right"></i></a>
            <ul class="treeview-menu">
              <li><a href="http://localhost:8000/admin/language"><i class="fa fa-flag-checkered"></i> Idiomas</a></li>
              <li><a href="http://localhost:8000/admin/language/texts"><i class="fa fa-language"></i> Traduccion</a></li>
            </ul>
          </li> 
		  -->
		           
		  <li class="treeview">
            <a href="#"><i class="fa fa-globe"></i> <span>Administracion</span> <i class="fa fa-angle-left pull-right"></i></a>
            <ul class="treeview-menu">
             <li><a href="http://localhost:8000/admin/backup"><i class="fa fa-hdd-o"></i> <span>Backups</span></a></li>
		     <li><a href="http://localhost:8000/admin/log"><i class="fa fa-terminal"></i> <span>Logs</span></a></li>
		  </ul>
          </li>
		  
        </ul>
      </section>
      <!-- /.sidebar -->
    </aside>

      <!-- =============================================== -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
         	<section class="content-header">
	  <h1>
	    Añadir <span class="text-lowercase">product</span>
	  </h1>
	  <ol class="breadcrumb">
	    <li><a href="http://localhost:8000/admin/dashboard">Admin</a></li>
	    <li><a href="http://localhost:8000/admin/products" class="text-capitalize">products</a></li>
	    <li class="active">Añadir</li>
	  </ol>
	</section>

        <!-- Main content -->
        <section class="content">

          <div class="row">
	<div class="col-md-8 col-md-offset-2">
		<!-- Default box -->
					<a href="http://localhost:8000/admin/products"><i class="fa fa-angle-double-left"></i> Volver al listado  <span class="text-lowercase">products</span></a><br><br>
		
		  <form method="POST" action="http://localhost:8000/admin/products" accept-charset="UTF-8"><input name="_token" type="hidden" value="8F0LQwMNyqCgCYRx4hPVnTpZKuTv79JGEAdGn61i">
		  <div class="box">

		    <div class="box-header with-border">
		      <h3 class="box-title">Añadir nuevo  product</h3>
		    </div>
		    <div class="box-body row">
		      <!-- load the view from the application if it exists, otherwise load the one in the package -->
		      		      	<form role="form">
  
  
  
      <!-- load the view from the application if it exists, otherwise load the one in the package -->
			<!-- array input -->

<div ng-app="backpackTable" ng-controller="tableController" class="form-group col-md-12"
 >

    <label>Product</label>

    <input class="array-json" type="hidden" id="products" name="products">

    <div class="array-container form-group">

        <table class="table table-bordered table-striped m-b-0" ng-init="field = '#products'; items = &quot;[]&quot;; max = 5; min = 0; maxErrorTitle = 'backpack::crud.table_cant_add'; maxErrorMessage = 'backpack::crud.table_max_reached'">

            <thead>
                <tr>

                                        <th style="font-weight: 600!important;">
                        Item Name
                    </th>
                                        <th style="font-weight: 600!important;">
                        Description
                    </th>
                                        <th style="font-weight: 600!important;">
                        Price
                    </th>
                                        <th class="text-center">  </th>
                    <th class="text-center">  </th>
                </tr>
            </thead>

            <tbody ui-sortable="sortableOptions" ng-model="items" class="table-striped">

                <tr ng-repeat="item in items" class="array-row">

                                        <td>
                        <input class="form-control input-sm" type="text" ng-model="item.name">
                    </td>
                                        <td>
                        <input class="form-control input-sm" type="text" ng-model="item.desc">
                    </td>
                                        <td>
                        <input class="form-control input-sm" type="text" ng-model="item.price">
                    </td>
                                        <td>
                        <span class="btn btn-sm btn-default sort-handle"><span class="sr-only">sort item</span><i class="fa fa-sort" role="presentation" aria-hidden="true"></i></span>
                    </td>
                    <td>
                        <button ng-hide="min > -1 && $index < min" class="btn btn-sm btn-default" type="button" ng-click="removeItem(item);"><span class="sr-only">delete item</span><i class="fa fa-trash" role="presentation" aria-hidden="true"></i></button>
                    </td>
                </tr>

            </tbody>

        </table>

        <div class="array-controls btn-group">
            <button class="btn btn-sm btn-default" type="button" ng-click="addItem()"><i class="fa fa-plus"></i> Add product</button>
        </div>

    </div>

    
    </div>





    
    
    
    

	  </form>




		      		    </div><!-- /.box-body -->
		    <div class="box-footer">
		    	<div class="form-group">
		    	  <span>Después de guardar:</span>
		          <div class="radio">
		            <label>
		              <input type="radio" name="redirect_after_save" value="admin/products" checked="">
		              ir al listado
		            </label>
		          </div>
		          <div class="radio">
		            <label>
		              <input type="radio" name="redirect_after_save" value="admin/products/create">
		              añadir otro item
		            </label>
		          </div>
		          <div class="radio">
		            <label>
		              <input type="radio" name="redirect_after_save" value="current_item_edit">
		              editar este item
		            </label>
		          </div>
		        </div>

			  <button type="submit" class="btn btn-success ladda-button" data-style="zoom-in"><span class="ladda-label"><i class="fa fa-save"></i> Añadir</span></button>
		      <a href="http://localhost:8000/admin/products" class="btn btn-default ladda-button" data-style="zoom-in"><span class="ladda-label">Cancelar</span></a>
		    </div><!-- /.box-footer-->

		  </div><!-- /.box -->
		  </form>
	</div>
</div>


        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <footer class="main-footer">
                    <div class="pull-right hidden-xs">
              Creado con <a target="_blank" href="http://laravelbackpack.com">Checkin</a>
            </div>
                Realizado por <a target="_blank" href="http://tabacitu.ro">Cristian Tabacitu</a>.
      </footer>
    </div>
    <!-- ./wrapper -->


    
    <!-- jQuery 2.2.0 -->
    <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script>window.jQuery || document.write('<script src="http://localhost:8000/vendor/adminlte/plugins/jQuery/jQuery-2.2.0.min.js"><\/script>')</script>
    <!-- Bootstrap 3.3.5 -->
    <script src="http://localhost:8000/vendor/adminlte/bootstrap/js/bootstrap.min.js"></script>
    <script src="http://localhost:8000/vendor/adminlte/plugins/pace/pace.min.js"></script>
    <script src="http://localhost:8000/vendor/adminlte/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="http://localhost:8000/vendor/adminlte/plugins/fastclick/fastclick.js"></script>
    <script src="http://localhost:8000/vendor/adminlte/dist/js/app.min.js"></script>

    <!-- page script -->
    <script type="text/javascript">
        // To make Pace works on Ajax calls
        $(document).ajaxStart(function() { Pace.restart(); });

        // Ajax calls should always have the CSRF token attached to them, otherwise they won't work
        $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

        // Set active state on menu element
        var current_url = "http://localhost:8000/admin/products/create";
        $("ul.sidebar-menu li a").each(function() {
          if ($(this).attr('href').startsWith(current_url) || current_url.startsWith($(this).attr('href')))
          {
            $(this).parents('li').addClass('active');
          }
        });
    </script>

    <script src="http://localhost:8000/vendor/backpack/pnotify/pnotify.custom.min.js"></script>


<script type="text/javascript">
  jQuery(document).ready(function($) {

    PNotify.prototype.options.styling = "bootstrap3";
    PNotify.prototype.options.styling = "fontawesome";

      });
</script>
    	<!-- CRUD FORM CONTENT - crud_fields_scripts stack -->
	        
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-sortable/0.14.3/sortable.min.js"></script>
        <script>
            angular.module('backpackTable', ['ui.sortable'], function($interpolateProvider){
                $interpolateProvider.startSymbol('<%');
                $interpolateProvider.endSymbol('%>');
            })
            .controller('tableController', function($scope){

                $scope.sortableOptions = {
                    handle: '.sort-handle'
                };

                $scope.addItem = function(){

                    if( $scope.max > -1 ){
                        if( $scope.items.length < $scope.max ){
                            var item = {};
                            $scope.items.push(item);
                        } else {
                            new PNotify({
                                title: $scope.maxErrorTitle,
                                text: $scope.maxErrorMessage,
                                type: 'error'
                            });
                        }
                    }
                    else {
                        var item = {};
                        $scope.items.push(item);
                    }
                }

                $scope.removeItem = function(item){
                    var index = $scope.items.indexOf(item);
                    $scope.items.splice(index, 1);
                }

                $scope.$watch('items', function(a, b){

                    if( $scope.min > -1 ){
                        while($scope.items.length < $scope.min){
                            $scope.addItem();
                        }
                    }

                    if( typeof $scope.items != 'undefined' && $scope.items.length ){

                        if( typeof $scope.field != 'undefined'){
                            if( typeof $scope.field == 'string' ){
                                $scope.field = $($scope.field);
                            }
                            $scope.field.val( angular.toJson($scope.items) );
                        }
                    }
                }, true);

                if( $scope.min > -1 ){
                    for(var i = 0; i < $scope.min; i++){
                        $scope.addItem();
                    }
                }
            });
        </script>

    
	<script>
		// Ctrl+S and Cmd+S trigger Save button click
		$(document).keydown(function(e) {
		    if ((e.which == '115' || e.which == '83' ) && (e.ctrlKey || e.metaKey))
		    {
		        e.preventDefault();
		        // alert("Ctrl-s pressed");
		        $("button[type=submit]").trigger('click');
		        return false;
		    }
		    return true;
		});
	</script>

    <!-- JavaScripts -->
    
</body>
</html>

**Comment by OwenMelbz** [comment]
GitHub has messed with the formatting so we can't actually see the full code, could you please add it to a gist like the rest you done

Thanks

**Comment by OwenMelbz** [comment]
@guillermohaad can you update your cud package to at least version `3.1.25` please, running a `composer update` should do it

**Comment by guillermohaad** [comment]
Hi friend @OwenMelbz 

update and works well the front-end, but when I go to save shows this error:

image

**Comment by OwenMelbz** [comment]
Hi, it seems to be because your database schema is set up to expect a value in the name field.

As your crud controller does not have a name field it is erroring, 

You can fix it by either setting a default value on your database field, or by changing the scheme to allow null values, or even actually submit a name for your entity and make sure it's in the fillable array within the model!

**Comment by guillermohaad** [comment]
Friend @OwenMelbz I want to insert in these fields defined in the product table and in my model I fillable array. Something I doing wrong? Deputy evidence

image

**Comment by tabacitu** [comment]
@guillermohaad the "table" field stores all values (the entire table) inside ONE database column, as a JSON. So for your case, a "product" column would probably make sense, which you also need to place in the $fillable array. It's also recommended that you $cast that column to array, using [Laravel attribute casting](https://mattstauffer.co/blog/laravel-5.0-eloquent-attribute-casting).

@OwenMelbz - I think I just discovered an issue. **I can't seem to add two ```table``` fields inside the same form** - the second one doesn't work (not working: default values, add button, delete, reorder). **Could you please take a look when you have the time?** I guess one way around it would be to give the ng-app a custom name for each field and remove the ```@if ($crud->checkIfFieldIsFirstOfItsType($field, $fields))```. But then we'd have the same javascript twice on the same page, that basically does the same thing. Right? Is there any way in Angular to avoid this?

Cheers!

**Comment by OwenMelbz** [comment]
@tabacitu theres a fix for it -> https://github.com/Laravel-Backpack/CRUD/pull/150 however is not ideal, need a proper asset/javascript flow for actual files to optimise it as much as possible, but this is the most simple way

**Comment by guillermohaad** [comment]
Hi friend @OwenMelbz , 

update the latest version of CRUD but when added product does not save me ??

see:

image

**Comment by OwenMelbz** [comment]
@guillermohaad can you please paste your Model, Your Crud Controller and Your database Schema for the table please?

**Comment by OwenMelbz** [comment]
make it £5, the exchange rate is better :P

**Comment by guillermohaad** [comment]
Hi @tabacitu @OwenMelbz 

I excuse me friends but perhaps do not understand the language which means $ 5 ??
however attached model

model 
------------------------

<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;

class products extends Model
{
	use CrudTrait;

     /*
	|--------------------------------------------------------------------------
	| GLOBAL VARIABLES
	|--------------------------------------------------------------------------
	*/

	protected $table = 'products';
	protected $primaryKey = 'id';
	// public $timestamps = false;
	// protected $guarded = ['id'];
	// protected $fillable = [];
	
	
	protected $fillable = ['name','desc','price'];
	public $timestamps = true;
	// protected $hidden = [];
    // protected $dates = [];

**Comment by OwenMelbz** [comment]
@guillermohaad 

I think you might be using the wrong field type.

# Option 1
If you have 1 database column, which you want to store multiple items in, then you must have something like

```php
//model
$casts = ['field_name' => 'array'];
$fillable = ['field_name'];
```

```php
//controller
$this->crud->addField([
            'name' => 'field_name',
            'label' => 'Your Field',
            'type' => 'table',
            'entity_singular' => 'Your Field', // used on the "Add X" button
            'columns' => [
                'field_1' => 'Fake Column 1',
                'field_2' => 'Fake Column 2',
                'field_3' => 'Fake Column 3'
            ]
        ]);
```

This will create a JSON array containing `field_1, field_2, field_3` and insert it into `field_name`

# Option 2

If your database has got 3 columns, and you need to populate each field, then you need to do something like

```php
//model
$fillable = ['field_1', 'field_2', 'field_3'];
```

```php
//controller
$this->crud->addField([
    'name' => 'field_1',
    'label' => 'Field 1',
    'type' => 'text'
]);
$this->crud->addField([
    'name' => 'field_2',
    'label' => 'Field 2',
    'type' => 'text'
]);
$this->crud->addField([
    'name' => 'field_3',
    'label' => 'Field 3',
    'type' => 'text'
]);
```

This will create 3 text boxes, which will save to each database column

**Comment by guillermohaad** [comment]
thank friend @OwenMelbz , 
Use option 1 and was successful.
I have the following question? in which case the option 2 is used?

Thank you for your time

**Comment by tabacitu** [comment]
@guillermohaad You can use option 1 when you have a complicated entity that needs to have a "subentity", but it's not important for that subentity to be searchable/stored as a separate database column.

For lack of a better example, let's say you have a "Page" model. And your page has
- 1 headline
- 1 description
- 3-5 team members (each with name, bio and email)
- 1 call_to_action_headline

It would then be pretty simple for you to create an admin panel for that Page entity. You would use:
- headline - "text" field type
- description - "textarea" field type
- team_members - "table" field type (with the columns name, bio and email)
- call_to_action_headline - "text" field type

That would be stored in this database table as:
pages
  - id INT
  - headline VARCHAR
  - description TEXT
  - team_members TEXT (will be a JSON array)
  - call_to_action_headline TEXT

...not sure I've explained it clear enough, hope I did.

Cheers!

P.S. Damn it! Ok, @OwenMelbz ... you win. I owe you £5 :-)

**Comment by guillermohaad** [comment]
Understood Thank you. Very Example :-), I feel your loss of $ 5

**Comment by JeanHules** [comment]
I know this is closed, but is it possible to have one of the table options be an icon option? Basically merging the icon_picker field type and the table field type. 

Thanks

**Pull request merged**
