### PR TITLE
Added checks for data-can-be-visible-in-table

### PR DESCRIPTION
**Pull request by dnwjn**
Possible fix for #3252.

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @dnwjn 

Thanks for the report and for the fix. 

I think it's enough to change only `export_buttons.blade.php` because we will not show a `exportOnlyField` by default in table, and if users don't get the option to activate it in column filtering, that column would never endup in the table anyway. 

Let me know you what you think.

Best to you,
Pedro

**Comment by dnwjn** [comment]
> Hello @dnwjn
> 
> Thanks for the report and for the fix.
> 
> I think it's enough to change only `export_buttons.blade.php` because we will not show a `exportOnlyField` by default in table, and if users don't get the option to activate it in column filtering, that column would never endup in the table anyway.
> 
> Let me know you what you think.
> 
> Best to you,
> Pedro

Hi Pedro!

I think you're right! I wasn't sure if it would be enough to just add it to the buttons, so I also added it to the table logic in case.

Would you like me to remove the change from the datatables logic?

**Comment by pxpm** [comment]
Yes please. I tested with only the change in export_buttons and it works as expected. 

Best,
Pedro

**Comment by dnwjn** [comment]
Alright, this should do it!

**Review by pxpm — APPROVED** [review]

**Comment by tabacitu** [comment]
Excellent! Thank you @dnwjn & @pxpm - great collaboration and PR here. Sorry for the bug - I believe very few people use this feature in particular, and we have no feature tests for it yet, so it must have slipped through the cracks.

Merged, it'll be available in the next patch update, with a `composer update`, on Monday the latest.

Cheers!

**Pull request merged**
