### PR TITLE
[4.0][Feature] uncdn

### PR DESCRIPTION
**Pull request by alashow**
Added/Downloaded frontend dependencies to `public` folder.

Advantages: consistency?, offline support, some cdn's are blocked in some countries.

### CODE REVIEW

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/CRUD/issues/736 got closed btw.

**Comment by alashow** [comment]
> @alashow - why not use one of the build tools?

https://github.com/Laravel-Backpack/CRUD/pull/148#issuecomment-307687112

**Comment by lloy0076** [comment]
@alashow Still I don't think my comment in #148 was totally against using a build tool - just not one for absolutely everything; I am concerned that Laravel Mix has had a history of simply just breaking and/or using unstable build systems (and just changing names because it _can_).

**Comment by alashow** [comment]
@lloy0076 I didn't mean you were against. Just reminding possible reasons for not using build tools.

BTW, it was discussed in #863 too.

**Comment by Sobak** [comment]
@lloy0076 @tabacitu what's the statement on using e.g. `gulp` to handle such dependencies? I'd be willing to prepare PR for that but I don't know if complicating the set up process is fine.  But maybe eliminating usage of CDNs would be nice addition to 3.3 release?

**Comment by alashow** [comment]
@Sobak A very nice addition in fact.

**Comment by lloy0076** [comment]
@Sobak - Laravel seems to have chosen `webpack` over `gulp` ... and if we were to choose one, I'd pick `webpack` (for that reason, mostly).

That said, the moment something broken and pre-beta turns up that is shiny and new, Laravel Mix will move to use it or some such silliness.

I am getting old and cynical 😢

**Comment by alashow** [comment]
@Sobak any updates on that PR?

**Comment by tabacitu** [comment]
Hi guys,

Sorry for answering so late. I was hoped to see this in a different light, or figure out a solution, but so far nothing. This is a huge PR @alashow , so thanks a lot for taking the time to do it. But it's also a controversial change. The way I see it:

PROs: 
- this will allow developers to Backpack on intranets; and it's the only way I see that will do this;

CONs:
- this is a breaking change - people will need to republish their assets for it to work;
- this forces us to maintain specific versions of assets; 
- we'll only be able to update assets 2 times a year, when we launch breaking changes ourselves; 
- when we update versions, if developers modified anything in those assets, their modifications are overwritten or ignored; 
- if/when we use a ```js``` or ```css``` dependency with a major bug, the only way to fix it would be to force a breaking change in Backpack, ahead of schedule, and ask everybody to update;

As you can see, right now if ```feels``` like there are more CONs than PROs. But I don't know, I don't think I'm ready to close this yet, because this is a real issue and a real use case. I wish we had a better solution...

**Comment by alashow** [comment]
> this forces us to maintain specific versions of assets;

We are already using specific versions of libraries (I counted 7 out of 10), i.e specifying a version in CDN url instead of using `latest` (which is not very safe).

> when we update versions, if developers modified anything in those assets, their modifications are overwritten or ignored;

I think this is already a case because we already have assets in [`public`](https://github.com/Laravel-Backpack/CRUD/tree/master/src/public).


> this is a breaking change - people will need to republish their assets for it to work;
> we'll only be able to update assets 2 times a year, when we launch breaking changes ourselves;
> if/when we use a js or css dependency with a major bug, the only way to fix it would be to force a breaking change in Backpack, ahead of schedule, and ask everybody to update;

Yes, the main problem will be introducing a breaking change. But I think it's worth the change until we setup webpack (and/or option to switch cdn assets from publishable assets or webpack).

**Comment by tabacitu** [comment]
@alashow - there's no better way to say this: **You were right, I was wrong.** I now (finally) agree with your - it might be a good idea to load the assets locally, not using CDNs. Yes, it's more difficult to maintain. And the package will be a lot bigger, and slower to install. BUT. A few months ago the datatables CDN was down, so all Backpack interfaces were down - for a few hours, I think. Yes, some people might have had the assets cached in their browsers, and CDNs are rarely brought down, but it was the last drop in the bucket that made me decide to move away from CDNs. I think we should make Backpack packages work on their own. Bonus - they'd also work on intranets. Late to the party, I know.

I've just take your PR further for v4. Thanks a lot for the PR - but I'm going to close it now since that one is based on this, and has no merge conflicts with v4. Please check it out here - https://github.com/Laravel-Backpack/CRUD/pull/1977 . The actual assets are installed using NPM here https://github.com/Laravel-Backpack/Base/pull/402 . 

It was a monstrous task - which makes me appreciate your the effort you've put in even more. Thanks again @alashow ! Of course, also thank you @Sobak & @lloy0076 for the ideas and feedback.

Let's do this. Let's un-cdn Backpack v4 :-) [well it's already done, but you know what I mean]
Cheers!

**Pull request closed without merging**
